### ISSUE TITLE
Don't try and read/write all ingesters in a set; only do it if one fails/times out

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#100]
We should only write to the minimum required.

This should improve tail latencies & reduce load on the system.

**Comment by jml** [comment]
@tomwilkie Is this still relevant?

**Comment by tomwilkie** [comment]
Yes - we still write to all three; we should only try and write to two, as per Tiered Requests in http://www.cs.duke.edu/courses/cps296.4/fall13/838-CloudPapers/dean_longtail.pdf

**Comment by bboreham** [comment]
If we write to two ingesters (when configured for 3x replication), and one of them dies, now we have three potential replicas with only one of them holding the data.  A subsequent read can accept the response from the two that don't have the data.  This is also noted at #731

**Comment by csmarchbanks** [comment]
I agree that as the ingester stands we need to write to all 3 all the time. The read path could be changed to only do 2 queries, then send the third out later if one of the first two is slow/fails. Perhaps this issue should be changed to only the read path?

**Comment by gouthamve** [comment]
Closing this as Tom thinks that with Bryan's chunk alignment change this is redundant and maybe even make this use more space. /cc @bboreham
