### ISSUE TITLE
RFC: caches shouldn't return errors, should just log them and return hits & misses.

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1003]
Because if there is an error, we still want to use what ever hits we did get.

Theres been some confusion over this, so I suggest we remove err from the return values, and force caches to consume the errors (and log them).

WDYT?

**Comment by khaines** [comment]
I would agree with this. 

There's no reason to handle the error from a cache read, in the consuming logic. We should treat it as missed data and proceed to query/read the backing store
