### ISSUE TITLE
New logo for CNCF sandbox move

### ISSUE THREAD

**Issue by svoegeli** [cortexproject/cortex#1004]
![cortex-logo](https://user-images.githubusercontent.com/7969051/45535372-7ab13000-b7bb-11e8-8208-f4af67788753.png)

Hi all, I'm proposing this updated logo for the move to the CNCF sandbox and the press release on 9/20. This image shows the white logo mark and wordmark for use on dark backgrounds. We will need to select colors for use on light backgrounds as well. I'm the designer at FreshTracks.io and have availability to work on Cortex branding this week and throughout the CNCF transition.

**Design for the proposed logo**

The nodes going into the central core represent multiple tenants and data sources. The larger pipeline coming back out (which also creates the C shape) shows that the data can be queried and accessed out of storage.

The surrounding hex shape is a reference to support for containers and microservices, and the break in the outer hex that creates the C is a reference to open source with a nod to the design patterns for several other CNCF project logos.

**Goals for the logo**

* Represent the letter C in an interesting way that stands alone as a mark
* Reflect what the product does in a way that is abstract enough to be visually simple but still convey meaning
* Fit in to the CNCF landscape
* Give a nod to open source (e.g. the opening in the outer shape of the Open Metrics and Open Tracing logos)
* Balance the shapes in the mark with the font characteristics and vice versa
* Gracefully transition from Weaveworks branding to a standalone project
* Design a mark that works for horizontal, vertical, and square logo variations and can be inverted to white on a dark background
* The logo should scale well and remain recognizable and impactful at small sizes
* The mark should be easy to remember and draw (a good test for both recognition and simplicity)

**Topics for discussion**

* Logo fit for Cortex and CNCF
* Logo colors
* Timing to update brand assets prior to the press release

If we can come to a decision, I will submit a PR for the updated logo. It would be great to have a plan and decision prior to the press release next week to present the project with standalone branding for the transition.

**Comment by davkal** [comment]
Great! Nicely balanced logo and excellent representation of the its inner workings.

My main worry with logos is, how does it look on a sticker.
For this one, I think the lines to the nodes could be too thin and the nodes too small resulting in smudge. So if you checked for that, all good. Otherwise I recommend a) reducing nodes to 4 and have them pointed differently, e.g., at the edges; and/or b) make them bigger, while pulling them a bit in as the node to outside barrier could be a bit thin too.

Minor OCD nit: the inside corners of the C opening look a bit too sharp.
Bike shedding to be ignored: I'd widen the letter spacing for more impact.

Could we see a black on white?

**Comment by bboreham** [comment]
When we chose a logo for the CNI project (which also ended up as a "big C"), I liked the way there were three variations each time and we could say which one we preferred.  My brain doesn't seem to work in a way where I can look at a visual design and just come up with ways to make it better.

https://github.com/containernetworking/cni/issues/426

**Comment by bulletfactory** [comment]
I quite like the word mark, but wonder if the icon feels a bit too familiar. I understand how it conveys the inner workings, but it immediately made me think of 2 other logos in the space -

Collectd: https://www.google.com/search?ei=G8CbW7rcI9Hp_QaG-Y2QBw&q=collectd+logo&oq=collectd+logo&gs_l=psy-ab.3..0.11085.12793..13304...0.0..0.85.951.13......0....1..gws-wiz.......0i71j0i67j0i131j0i131i67.pPuf8ApjRXo 

Kafka: https://www.google.com/search?ei=5sCbW8WXJoGQ_Qb73af4CQ&q=kafka+logo&oq=kafka+logo&gs_l=psy-ab.3..0i67l2j0l2j0i7i30l5j0i30.8931.9675..9844...0.0..0.82.387.5......0....1..gws-wiz.......0i71.0p787xtbc0M

This isn't to say it should be changed, but only an additional datapoint for discussion, and avoid any potential confusion.

**Comment by cboggs** [comment]
I like it! I think the "sticker factor" is interesting, but I've seen smaller details work fine so I'm not concerned. On the side of it being too similar, it's sufficiently different from any other CNCF project logo. Even if that weren't the case, I'd venture that similarity is not sufficient for a downvote, short of it being nigh identical. :-)

The side-by-side comparison is great for situations where the designer has multiple equally viable designs to share. When Sarah provides one design, it's safe to assume that she's invalidated the alternate designs for good reason. Unless there is a specific glaring issue, I don't think there's any need for comparison pieces against to which to measure this one.

All that said, +1, it has my vote for acceptance into the repo. :-)

**Comment by tomwilkie** [comment]
I'm going to close this as we didn't really get anywhere, and the current logo is fine.
