### ISSUE TITLE
cmd/lite panics at startup with `flag redefined: distributor.ingestion-rate-limit`

### ISSUE THREAD

**Issue by ellisda** [cortexproject/cortex#1009]
Attempting to run `cmd/lite` panics for a flag that is registered twice.

    `panic: ./cortexLite flag redefined: distributor.ingestion-rate-limit`

The `Limits` config struct is shared by both the ingestor and the distributor configs; the `cmd/lite/main.go` program tries to register flags for both ingestor and distributor configs which causes a panic.

I'm not sure how widespread the use of `lite` is, but I've been using it to experiment with some local dev and I had to workaround this panic. I'l link a tentative PR with the solution I copied from `SetClientConfig` (in 'cortex/pkg/ingester/ingester.go').

REPRO STEPS:
 1. `make cmd/lite/.uptodate`
 1. `go build -o cortexLite ./cmd/lite && ./cortexLite`

**Comment by csmarchbanks** [comment]
Fixed in #1032
