### ISSUE TITLE
Update Go import paths to use `cortexproject/cortex` ?

### ISSUE THREAD

**Issue by mbrukman** [cortexproject/cortex#1026]
There are a lot of Go import paths that read:

```go
import "github.com/weaveworks/cortex/..."
```

Since this repo was migrated from `weaveworks/cortex` to `cortexproject/cortex`, the redirection works just fine, but perhaps might be confusing for newer folks who are reading the code, as this repo appears to depend a lot on an external repository, when in fact, it's all in the local code base.

Should all these paths be rewritten accordingly to match the current source code location?

**Comment by bboreham** [comment]
Yes
