### ISSUE TITLE
Bigger chunks

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1045]
I'd like to build a new chunk format that results in reliably bigger chunks.  Effectively I want to build a "meta chunk" which itself is a series of chunks.  These chunks won't be fixed to 1kb in size, but instead to 12hrs in length.

Any thoughts on this?  Going to experiment today.

If this works I suspect it will solve:
- #300 Grow chunks in memory 
- #448 We're flushing virtually empty chunks in prod
- #766 Use Prom2 chunk code (I'm going to investigate using this for the new code)

**Comment by bboreham** [comment]
I have spoken (in Slack and/or the community meeting) about "multi-chunks", which can cover a number of cases.

For example putting all buckets of a histogram in one block in the storage, for efficiency.
This needs other changes to indexing on ingest and query; just noting it here for now.

Also possibly doing a mass rewrite of an entire day to put all data for the same series/bucket in one multi-chunk.  This collapses the v9 schema to about the same as v6; removes the need to do N(series) queries.

**Comment by bboreham** [comment]
One of the reasons I added the "event sampling" code was to gather data on why I was getting short chunks.  Recommend you turn it on and do some counts, e.g. reason=idle vs reason=chunk full.

**Comment by bboreham** [comment]
> IFAICT there are a few reasons 

https://github.com/cortexproject/cortex/blob/master/pkg/ingester/flush.go#L105-L108
