### ISSUE TITLE
Distributor RPC errors for ingester healthcheck

### ISSUE THREAD

**Issue by leth** [cortexproject/cortex#1049]
While running `quay.io/cortexproject/distributor:master-ee74728f` we observed a very high rate of errors with the ingester healthcheck: `msg="removing ingester failing healtcheck" reason="rpc error: code = Unimplemented desc = unknown service grpc.health.v1.Health"`

**Comment by tomwilkie** [comment]
I thought I'd fixed that, let me check...

**Comment by tomwilkie** [comment]
Yeah the server is correctly registered: https://github.com/cortexproject/cortex/blob/master/cmd/ingester/main.go#L99

Are you running `quay.io/cortexproject/ingester:master-ee74728f`?  Not that is should matter.

**Comment by leth** [comment]
Rolling back the distributor to `quay.io/weaveworks/cortex-distributor:master-0165a29a` fixed things for us.

Our ingesters are running `quay.io/weaveworks/cortex-ingester:labelpairs-optimisation2-dc7e78a2` which @bboreham looks to have built from dc7e78a2.

**Comment by tomwilkie** [comment]
Thats probably it - I guess it does matter.  We previously relied on go's duck typing to implement health, but now actually implement Health properly.  This was all triggered by them removing the proto for health from the repo.

**Comment by bboreham** [comment]
Note for future readers: this feature is turned off by default, so we can escape the problem during the period when client and server are mismatched by not setting `-distributor.health-check-ingesters=true`

**Comment by leth** [comment]
Closing this issue since it's not an ongoing problem
