### ISSUE TITLE
Bigtable: Use SampleRowKeys to parallelise read requests by tablet.

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1066]
See https://godoc.org/cloud.google.com/go/bigtable#Table.SampleRowKeys

**Comment by tomwilkie** [comment]
Idea here it to parallelise queries in the same way the underlying data is shared, hopefully resulting in faster queries.

**Comment by gouthamve** [comment]
Can you explain this a little bit?

**Comment by gouthamve** [comment]
Lot of time passed, but from my recollection, we tried this but didn't make any difference hence scrapped this.
