### ISSUE TITLE
"query must contain metric name" when using __name__=~"foo|bar"

### ISSUE THREAD

**Issue by poblahblahblah** [cortexproject/cortex#1079]
Hello,

When querying Cortex and using the syntax __name__=~"foo|bar" we are getting an error response back from Cortex of "query must contain metric name". This is a valid Prometheus query, so Cortex should be able to handle this type of query. See attached screenshot.

![screen_shot_2018-10-16_at_8 16 52_am](https://user-images.githubusercontent.com/51938/47101339-a1b1b600-d1ee-11e8-979f-133fb5aff677.png)

**Comment by csmarchbanks** [comment]
Hi @poblahblahblah, this is a known limitation of Cortex right now, tracked by #416.

I am going to close this as a duplicate.
