### ISSUE TITLE
cortex about multitenant 

### ISSUE THREAD

**Issue by zhangjianweibj** [cortexproject/cortex#1081]
hello,i am a prometheus user.recently,i find cortex has multitenant feature.so i look up documents and video in the cncf and promcon conference.but find nothing about multitenant feature.evneryone can tell me that feature or givie me some detail document about multitenant,verty thanks

**Comment by gouthamve** [comment]
See: https://github.com/cortexproject/cortex/blob/master/docs/auth.md
