### ISSUE TITLE
Send 'flushed' status in ingester-to-ingester chunk transfer

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1084]
Now we retain chunks after flush, we do want to transfer them but we don't want to flush them again.

As noted at https://github.com/cortexproject/cortex/pull/1077#issuecomment-431029682

**Comment by gouthamve** [comment]
This is not a big issue if you're running the WAL (statefulset)

**Comment by alanprot** [comment]
Chunks storage was removed.
