### ISSUE TITLE
Investigate ways of reducing distributor to ingester latency

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1094]
As you grow the number of ingesters, the distributors have to do more work, as on average each batch to the distributor will touch each ingester.

We could consider combining batches of distributor -> ingester writes across batches to the distributor, essentially serialising writes from the distributor -> ingester through a single go routine and "collecting" samples from multiple batches.  This would bound the load, and while it might introduce artificial latency needed to build the batches, it might also reduce load enough to reduce latency.

WDYT?

**Comment by bboreham** [comment]
As an extension to this idea I've been thinking about reducing GC by only sending label name and value strings once; this could be done by opening a streaming connection from distributor to ingester so we know what we've sent on that stream and we know when the stream is broken so we have to send them again.
