### ISSUE TITLE
how to run cortex for testing purpose

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [cortexproject/cortex#1102]
Hello guys. 
I try to run cortex with latest docker image master-1cdc9a7c using kubernetes manifests in this repo with small changes (use s3 and dynamo db in aws), but unfortunately it does not  start properly, database is created, but looks like need some additional configuration in local consul agent all components write errors like this
```
level=error ts=2018-10-31T16:57:40.88749648Z caller=pool.go:170 msg="error removing stale clients" err="empty ring"
level=error ts=2018-10-31T16:57:43.090852645Z caller=consul_client.go:230 msg="error getting path" key=collectors/ring err=null
level=error ts=2018-10-31T16:57:45.821262268Z caller=consul_client.go:230 msg="error getting path" key=collectors/ring err=null
level=error ts=2018-10-31T16:57:55.877989162Z caller=pool.go:170 msg="error removing stale clients" err="empty ring"
```

i checked and there is no key colelctors/ in consul kv store, i try to create it on my own but no luck i still getting this error, can you help me to configure it properly, or point me when i can read about it?

ingester component just restart without any error just all output in logs just this 
```
level=info ts=2018-10-31T16:57:48.792840763Z caller=override.go:33 msg="per-tenant overides disabled"
```

**Comment by bboreham** [comment]
We’re kinda light on information here. Details of the changes you made, and full logs, would fill in the gaps. 

Absent that information, the “ring” data should be written to Consul by ingesters.

**Comment by tomwilkie** [comment]
Also add the flags you started the various components with to that list.  The `k8s/` directory can be used for inspiration, although they are pretty out of date too.

**Comment by bboreham** [comment]
@tomwilkie I think OP said they started from that directory.
Also I think they posted full logs of the ingester, so why that did nothing is the mystery.
Could run with `-log.level=debug`; that might add something.

**Comment by PriyaSivaraj1987** [comment]
Any update on this issue.. I am receiving the same error when I try to use cortex

**Comment by gouthamve** [comment]
See: https://github.com/cortexproject/cortex/blob/master/docs/getting_started.md
