### ISSUE TITLE
Auto-scale DynamoDB read capacity

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1108]
Currently table-manager will auto-scale writes but not reads.
Outline proposal:
 - keep historic tables provisioned quite low, e.g. 10
 - monitor usage closely, e.g. poll Prometheus every 15 seconds
 - if you spot someone using an old table, scale it up
 - if no usage on a scaled-up table for a while, scale it down again

The trick is, DynamoDB lets you consume under-utilisation for the last 5 minutes, so if you've been using zero you will get to use 10x5x60=3,000 units of capacity until it starts to throttle.  And scale-up within the limits you have previously scaled to is quite fast, around 5-10 seconds.

**Comment by khaines** [comment]
What would we base the scale up on in this case? with writes there's a flush queue to measure against, but for reads it may be more difficult. Especially in the case where we start with a very low number (ex: 10) for read units. Perhaps in the initial scaling there is a fixed size increase to "jump start" the capacity, after which we can use a percentage scaling to fine tune the units if the initial scaling wasn't sufficient to meet demand.

**Comment by bboreham** [comment]
The current implementation for writes looks at both queue size and rate of provision-exceeded errors.
For reads we have no queue but (a) any usage at all is enough to raise it from the floor, for historic tables and (b) throttling is still a guide you might want more.

There is already a kind of "jump start" for writes in that the minimum increment is 10% of the range - i.e. if you set a range from 10 to 10,000 then the first increment will be from 10 to 1,010.

**Comment by khaines** [comment]
Ah, good point about the existing scale action on writes for a minimum step. I agree with your criteria A and B for read scaling.

**Comment by khaines** [comment]
I've got some code written for this now and its unit tests are passing. Due the US holiday this week, getting some practical testing in our integration environment is going to have to wait until Monday.

**Comment by bboreham** [comment]
AWS have on-demand pricing for DynamoDB, so that may obviate the need.

**Comment by khaines** [comment]
Certainly sounds like a good option for historical tables. 

However for current/active tables were we want to manage the write capacity more closely, there may be still a desire to  scale provisioned reads with metrics.

**Comment by bboreham** [comment]
Closed by #1140
