### ISSUE TITLE
Automatic removal of old tables

### ISSUE THREAD

**Issue by rsteneteg** [cortexproject/cortex#1132]
In our use case we have a specific retention period for our users data, to avoid the need to manually remove tables that is older than the retention (for cost savings), it would be nice to be able to have the older tables removed automatically

**Comment by rsteneteg** [comment]
Here is a PR for this suggested feature
https://github.com/cortexproject/cortex/pull/1133

**Comment by gouthamve** [comment]
Fixed in #1133
