### ISSUE TITLE
RFC: single binary cortex / make cortex easier to get started with

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1136]
- I'd like to put Cortex back to a single binary; see #151 for the split into multiple binaries.
- You'd still be able to run as a ingester, distributor etc; that would be a flag.
- I want to introduce reading flags from yaml (see #1127); this would allow us to leave the flag defaults as is for backwards compat, whilst shipping a couple of yamls in the repo for getting started.
- I want to unify the dependancies of the various "components" into a single place, and programatically initialise them in the right order.  This should reduce the duplication in the various mains.
- it will ensure the lite version never breaks due to flag (although we have a test now, so maybe not an issue)

I've got a WIP prototype of this based on the code in #1127, which I'm trying to publish in time for kubecon.  WDYT?

**Comment by bboreham** [comment]
Would this apply to the query front-end too?  It seems a different style to the ingester, querier, etc.

I see some other pros:
 * faster build time
and some cons:
 * all the flags will come out when it prints usage

**Comment by tomwilkie** [comment]
> Would this apply to the query front-end too? It seems a different style to the ingester, querier, etc.

I'd like it to.  Its more like the ruler in that its a singleton; in this mode we'd need some was of doing master-election to pick which lite instance would be a query-frontend.  Not insurmountable though.

> all the flags will come out when it prints usage

True; I suspect when we get closer to v1 and we're more comfortable with the config files, we could consider not exposing some of them as flags?
