### ISSUE TITLE
API descrepency: result is null in cortex, [] in Prom

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#1142]
If we query for `up{dont="exist"}` in Cortex now, 
```
{"status":"success","data":{"resultType":"","result":null}}
``` 
is returned, but if we query Prometheus, 
```
{"status":"success","data":{"resultType":"matrix","result":[]}}
``` 
is returned.

Both should match up and Cortex should return `[]`. This is using a query that hits the query-frontend.

**Comment by pracucci** [comment]
I've just tested the version in `master` and looks working as expected:
`{"status":"success","data":{"resultType":"matrix","result":[]}}`

_I'm going to close it. Feel free to reopen it if you're still experiencing it._
