### ISSUE TITLE
etcd support

### ISSUE THREAD

**Issue by kfox1111** [cortexproject/cortex#1144]
Many Kubernetes admins already know how to deal with etcd. It would be good if you could switch out consul for etcd to reduce the cognitive load on admins.

**Comment by bboreham** [comment]
Another suggestion at #157

**Comment by tomwilkie** [comment]
Yes! I want Etcd too.  I was playing with the API on the flight back from KubeCon...

Theres an abstraction layer here that should be pretty easy to implement for etcd: https://github.com/cortexproject/cortex/blob/master/pkg/ring/kvstore.go#L18

**Comment by bboreham** [comment]
Currently the usage is not too light - every ingester rewrites the ring every 3 seconds. 
But as discussed at #157 we could move the heartbeat side elsewhere (we now have grpc health checks) then the ring is only updated when ingesters join and leave.
