### ISSUE TITLE
Replace fake S3 with minio

### ISSUE THREAD

**Issue by kfox1111** [cortexproject/cortex#1145]
Was digging through some code and hit this deployment:
cortex/k8s/s3-dep.yaml

looking through the container it says its containerizing:
https://github.com/jubos/fake-s3

Which mentions needing to go get a license. This doesn't seem good.

Can this be switched out for some other s3 compatible service such as minio?

**Comment by bboreham** [comment]
Sure; that’s just to show how it can work, not intended for real deployment.

**Comment by ashikjm** [comment]
Hello @gouthamve, I have submitted a PR for this #2671 . Please review.
