### ISSUE TITLE
Use a Retryer instead of retry loops for DynamoDB

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1152]
The DynamoDB client [disables retries](https://github.com/cortexproject/cortex/blob/5699ca2d3bc0d8d841679d07758fcc2fcde3b7bb/pkg/chunk/aws/storage_client.go#L822) and then [wraps everything in a loop](https://github.com/cortexproject/cortex/blob/5d187b904c5806d7aa50b7d8fb8ed2806de34fed/pkg/chunk/aws/dynamodb_table_client.go#L79) to do retries.  
Disabling retries came in #153; the backoff loop has gone through many iterations since #119.

The stated reason is that we want to monitor retries.

From my experiences using the DynamoDB API elsewhere, I think it would be far cleaner to implement a [`Retryer`](https://github.com/aws/aws-sdk-go/blob/8234000fff968de811646c75b200b0c713f800ec/aws/request/retryer.go#L13) which adds the required monitoring, let the AWS SDK do retries, and take out the explicit loops.

Noted at https://github.com/cortexproject/cortex/issues/792#issuecomment-425464568.

**Comment by rlisagor** [comment]
There's a chance I can take this on, depending on our priorities. It seems like the logic in the DefaultRetryer from the AWS SDK should work, if wrapped with monitoring code. Would that be sufficient? Or do you envision some custom retry logic?

**Comment by csmarchbanks** [comment]
I believe the intention is to just wrap with monitoring code and stop trying to do any custom retry logic.

**Comment by pracucci** [comment]
@bboreham In the PR #2452 you mentioned it partially fixes this issue. What's left out?

**Comment by bboreham** [comment]
I believe all of `pkg/chunk/aws/dynamodb_table_client.go` could be changed from the loop in `backoffAndRetry()` to the `retryer` added in #2452.

`BatchWrite()` and `getDynamoDBChunks()` also implement their own retry loops, but these have complicated interactions with throttling so I suspect will have to stay.

**Comment by alanprot** [comment]
Chunks storage was removed.
