### ISSUE TITLE
Slow "distributor" queries

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1158]
Most of our slowest queries now seem to be "critical-pathed" on fetching chunks from the ingesters.  

- This seems to happen most often on high-cardinality queries.
- We also observe this seems to perhaps happen when there is high concurrent query load.

Things to consider:
- Perhaps the sequential nature of sending the chunks is the problem?  Could try "sharding" the individual queries - do multiple, parallel gRPC requests to the same ingester to fetch a subset of the chunks.
- Perhaps its locking in the ingester?  When we iterate through the series we take the fingerprint lock.
- We hold this lock which sending on the network, which probably isn't right.
- Make sure we don't do more work than needed (see #1149)

**Comment by gouthamve** [comment]
Closing this as we removed CPU limits in k8s and this problem went away.
