### ISSUE TITLE
Move to non-framed Snappy when encoding chunks

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1161]
The Snappy framing format is useful when you don't know how many blocks of data you will be compressing.  We know this, so it isn't useful.

The framing adds a few extra bytes to each chunk, and the decoder has a buffer over 64K, which needs to be garbage-collected.  #633 addressed this in part by re-using decoders, but now we are running more fetches in parallel that doesn't work so well.

Will need to either retain the existing code for old chunks or apply inside knowledge to skip the framing and pull the one block out.

**Comment by alanprot** [comment]
Chunks storage was removed.
