### ISSUE TITLE
-store.fullsize-chunks=false breaks ingester hand-overs

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1163]
The feature implemented in #1044 results in handed-over chunks lacking the "footer" to add more values.

A simple way to work round the problem would be to reset the global flag before beginning a hand-over.

Maybe cleaner to add a "closed" flag to each chunk so it knows whether further writing is expected?

**Comment by gouthamve** [comment]
Closing this as we now use BigChunk as the default and it isn't a problem here anymore.

**Comment by bboreham** [comment]
The problem remains as stated.  A reasonable step would be to remove this feature entirely.
