### ISSUE TITLE
Store partial results into index cache

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1167]
Consider a large query, say 100,000 individual lookups to the series store. If we get 50,000 done before the call is cancelled, we throw all of them away and start again when the client retries.

So I believe `cachingStorageClient.QueryPages()` should store whatever valid results it does have into the cache before giving up.

Edit: likely have to change the `QueryPages()` api to tell us when all pages of one query have arrived.

**Comment by yeya24** [comment]
Since we deprecated chunks store already, I will close this issue.
