### ISSUE TITLE
Replace hacky tests in query frontend with better tests

### ISSUE THREAD

**Issue by codesome** [cortexproject/cortex#1168]
Example: In `TestSplitByDay`, the query and the merged response doesn't match well, as the `http.HandlerFunc` is wrapped to return the same result all the time. Also test doesn't look comprehensive.

In the title I have mentioned `query frontend` so that if any more tests can be improved, it can be tracked in this issue.

**Comment by pracucci** [comment]
@codesome @owen-d Is this still valid? If not, may you close it, please?

**Comment by codesome** [comment]
Frontend tests seem to be changed and there is no longer `TestSplitByDay`. I am closing this for now and if there are tests to be improved we can open another specific issue for that.
