### ISSUE TITLE
Using go1.11 breaks memcache DNS lookups

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#1200]
The net library in `go1.11+` cannot read SRV responses from kube-dns `v1.14.10` or below. This is because kube-dns prior to `1.14.11` used to send compressed SRV responses which is against the spec. See: https://github.com/golang/go/issues/27546 for more details.

We use it here: https://github.com/cortexproject/cortex/blob/master/pkg/chunk/cache/memcached_client.go#L103

This means that we are right now stuck to go1.10. Upgrading cortex to `go1.11+` would break memcache lookups among others. The fix for this would be to use https://github.com/miekg/dns like Prometheus does.

/cc @codesome

**Comment by codesome** [comment]
Found another place where it is used https://github.com/cortexproject/cortex/blob/a888416ea1cc069e09c1e690f378769cd7dcc0f9/pkg/alertmanager/peers.go#L65

**Comment by codesome** [comment]
Looks like I need to update in 1 more place. Thanks @bboreham!

**Comment by codesome** [comment]
I don't know about this part of Golang, but would this make this file to be compiled only with go1.8?
https://github.com/cortexproject/cortex/blob/a888416ea1cc069e09c1e690f378769cd7dcc0f9/vendor/google.golang.org/grpc/naming/go18.go#L1

**Comment by bboreham** [comment]
It means 1.8 and above. See https://golang.org/pkg/go/build/

**Comment by codesome** [comment]
Yes you are right. I should have searched before asking :)

**Comment by gouthamve** [comment]
This is only a problem when running kubernetes `v1.11` or below and compiling Cortex with go v1.11 and above.

**Comment by gouthamve** [comment]
Having said that bumping up `kube-dns` is straight forward and will fix this. We're on k8s 1.11 but with kube-dns at `1.14.13`

**Comment by bboreham** [comment]
So there is a more specific problem description involving kube-dns ?

**Comment by bwplotka** [comment]
That's funny, we found similar issue on Thanos as well: https://github.com/improbable-eng/thanos/issues/1015 obviously same thing with go 1.12

We consider moving to https://github.com/miekg/dns as it allows much much more flexibility. Have you considered this?

**Comment by bboreham** [comment]
@bwplotka see #1206 - in the end we decided that upgrading kube-dns would be a better route than changing the software.

**Comment by bwplotka** [comment]
Awesome, thanks for this link, super useful.

**Comment by bwplotka** [comment]
FYI: We added (basic) miekg's option to Thanos: https://github.com/improbable-eng/thanos/pull/1016

**Comment by tomwilkie** [comment]
We decided not to fix this, as we're all on k8s >1.14.
