### ISSUE TITLE
When querying data from query frontend using curl GET request, The query fails after 5 retries

### ISSUE THREAD

**Issue by dhruvbehl** [cortexproject/cortex#1209]
I'm trying to setup cortex and facing the following issue while querying the data freom the query frontend.

### PROBLEM:
When querying data from query frontend using curl GET request, The query fails after 5 retries
1) The data can be seen stored in the S3 bucket
2) `curl -X GET -H 'X-Scope-OrgID:5000' http://127.0.0.1:8089/api/prom/api/v1/query?query=up` returns Query failed after 5 retries.
3) There are 3 ingesters, 1 distributoe, 1 querier and 1 query frontend
4) The -s3.url is passed as AccessID:SecretKEY@s3URL
5) Querier throws error in logs: at least 2 live ingesters required, could only find 1 whereas im running 3 instances of querier

### SETUP:

Prometheus is pointed to reverse proxy via remote write
The reverse proxy is using proxy pass to distributor and adding a tenant id using the HTTP header X-Scope_OrgID

**Consul:**
`consul agent -dev -node machine01 -bind 127.0.0.1`

**Distributor:**
` ./distributor -log.level=debug -server.http-listen-port=8080 -consul.hostname=http://127.0.0.1:8500 -distributor.replication-factor=1 -server.grpc-listen-port=8081 -server.http-listen-port=8080`

**Ingester 1:**
`./ingester -s3.url=s3://AccessID:SecretKey@s3.url/bucket -dynamodb.original-table-name=cortex -dynamodb.url=inmemory:///DynamoCortex -consul.hostname=http://127.0.0.1:8500 -server.http-listen-port=8087 -server.grpc-listen-port=8088`

**Ingester 2:**
`./ingester -s3.url=s3://AccessID:SecretKey@s3.url/bucket -dynamodb.original-table-name=cortex -dynamodb.url=inmemory:///DynamoCortex -consul.hostname=http://127.0.0.1:8500 -server.http-listen-port=8082 -server.grpc-listen-port=8083`

**Ingester 3:**
`./ingester -s3.url=s3://AccessID:SecretKey@s3.url/bucket -dynamodb.original-table-name=cortex -dynamodb.url=inmemory:///DynamoCortex -consul.hostname=http://127.0.0.1:8500 -server.http-listen-port=8070 -server.grpc-listen-port=8071`

**Querier:**
`./querier -consul.hostname=http://127.0.0.1:8500 -s3.url=s3://AccessID:SecretKey@s3.url/bucket -server.http-listen-port=8084 -dynamodb.original-table-name=cortex -dynamodb.url=inmemory:///DynamoCortex  -server.grpc-listen-port=8085 -querier.frontend-address=localhost:8090`

**Query Frontend:**
`./query-frontend -log.level=debug -server.http-listen-port=8089 -server.grpc-listen-port=8090`

### ERROR MESSAGES:

**Querier:**
`level=warn ts=2019-01-29T09:37:17.003484161Z caller=gokit.go:43 traceID=2d114009ce84d08f msg="GET /api/prom/api/v1/query?query=up (500) 369.921µs Response: \"{\\\"status\\\":\\\"error\\\",\\\"errorType\\\":\\\"internal\\\",\\\"error\\\":\\\"at least 2 live ingesters required, could only find 1\\\"}\" ws: false; Accept: */*; User-Agent: curl/7.29.0; X-Scope-Orgid: 5000; uber-trace-id: 2d114009ce84d08f:2d114009ce84d08f:0:0; "
level=error ts=2019-01-29T09:37:17.003683635Z caller=chunk_store.go:391 org_id=5000 trace_id=2d114009ce84d08f msg="error querying storage" err="QueryPage error: context canceled for table cortex_2560, last error <nil>"`

**Query Frontend:**
`level=error ts=2019-01-29T09:37:16.998881282Z caller=frontend.go:229 msg="error processing request" try=0 resp="&HTTPResponse{Code:500,Headers:[&Header{Key:Access-Control-Allow-Methods,Values:[GET, OPTIONS],} &Header{Key:Access-Control-Allow-Origin,Values:[*],} &Header{Key:Access-Control-Expose-Headers,Values:[Date],} &Header{Key:Content-Type,Values:[application/json],} &Header{Key:Access-Control-Allow-Headers,Values:[Accept, Authorization, Content-Type, Origin],}],Body:[123 34 115 116 97 116 117 115 34 58 34 101 114 114 111 114 34 44 34 101 114 114 111 114 84 121 112 101 34 58 34 105 110 116 101 114 110 97 108 34 44 34 101 114 114 111 114 34 58 34 97 116 32 108 101 97 115 116 32 50 32 108 105 118 101 32 105 110 103 101 115 116 101 114 115 32 114 101 113 117 105 114 101 100 44 32 99 111 117 108 100 32 111 110 108 121 32 102 105 110 100 32 49 34 125],}"
level=error ts=2019-01-29T09:37:17.000425225Z caller=frontend.go:229 msg="error processing request" try=1 resp="&HTTPResponse{Code:500,Headers:[&Header{Key:Access-Control-Allow-Headers,Values:[Accept, Authorization, Content-Type, Origin],} &Header{Key:Access-Control-Allow-Methods,Values:[GET, OPTIONS],} &Header{Key:Access-Control-Allow-Origin,Values:[*],} &Header{Key:Access-Control-Expose-Headers,Values:[Date],} &Header{Key:Content-Type,Values:[application/json],}],Body:[123 34 115 116 97 116 117 115 34 58 34 101 114 114 111 114 34 44 34 101 114 114 111 114 84 121 112 101 34 58 34 105 110 116 101 114 110 97 108 34 44 34 101 114 114 111 114 34 58 34 97 116 32 108 101 97 115 116 32 50 32 108 105 118 101 32 105 110 103 101 115 116 101 114 115 32 114 101 113 117 105 114 101 100 44 32 99 111 117 108 100 32 111 110 108 121 32 102 105 110 100 32 49 34 125],}"
level=error ts=2019-01-29T09:37:17.001489326Z caller=frontend.go:229 msg="error processing request" try=2 resp="&HTTPResponse{Code:500,Headers:[&Header{Key:Access-Control-Allow-Headers,Values:[Accept, Authorization, Content-Type, Origin],} &Header{Key:Access-Control-Allow-Methods,Values:[GET, OPTIONS],} &Header{Key:Access-Control-Allow-Origin,Values:[*],} &Header{Key:Access-Control-Expose-Headers,Values:[Date],} &Header{Key:Content-Type,Values:[application/json],}],Body:[123 34 115 116 97 116 117 115 34 58 34 101 114 114 111 114 34 44 34 101 114 114 111 114 84 121 112 101 34 58 34 105 110 116 101 114 110 97 108 34 44 34 101 114 114 111 114 34 58 34 97 116 32 108 101 97 115 116 32 50 32 108 105 118 101 32 105 110 103 101 115 116 101 114 115 32 114 101 113 117 105 114 101 100 44 32 99 111 117 108 100 32 111 110 108 121 32 102 105 110 100 32 49 34 125],}"
level=error ts=2019-01-29T09:37:17.002712852Z caller=frontend.go:229 msg="error processing request" try=3 resp="&HTTPResponse{Code:500,Headers:[&Header{Key:Access-Control-Allow-Headers,Values:[Accept, Authorization, Content-Type, Origin],} &Header{Key:Access-Control-Allow-Methods,Values:[GET, OPTIONS],} &Header{Key:Access-Control-Allow-Origin,Values:[*],} &Header{Key:Access-Control-Expose-Headers,Values:[Date],} &Header{Key:Content-Type,Values:[application/json],}],Body:[123 34 115 116 97 116 117 115 34 58 34 101 114 114 111 114 34 44 34 101 114 114 111 114 84 121 112 101 34 58 34 105 110 116 101 114 110 97 108 34 44 34 101 114 114 111 114 34 58 34 97 116 32 108 101 97 115 116 32 50 32 108 105 118 101 32 105 110 103 101 115 116 101 114 115 32 114 101 113 117 105 114 101 100 44 32 99 111 117 108 100 32 111 110 108 121 32 102 105 110 100 32 49 34 125],}"
level=error ts=2019-01-29T09:37:17.003863727Z caller=frontend.go:229 msg="error processing request" try=4 resp="&HTTPResponse{Code:500,Headers:[&Header{Key:Access-Control-Expose-Headers,Values:[Date],} &Header{Key:Content-Type,Values:[application/json],} &Header{Key:Access-Control-Allow-Headers,Values:[Accept, Authorization, Content-Type, Origin],} &Header{Key:Access-Control-Allow-Methods,Values:[GET, OPTIONS],} &Header{Key:Access-Control-Allow-Origin,Values:[*],}],Body:[123 34 115 116 97 116 117 115 34 58 34 101 114 114 111 114 34 44 34 101 114 114 111 114 84 121 112 101 34 58 34 105 110 116 101 114 110 97 108 34 44 34 101 114 114 111 114 34 58 34 97 116 32 108 101 97 115 116 32 50 32 108 105 118 101 32 105 110 103 101 115 116 101 114 115 32 114 101 113 117 105 114 101 100 44 32 99 111 117 108 100 32 111 110 108 121 32 102 105 110 100 32 49 34 125],}"
level=warn ts=2019-01-29T09:37:17.004370667Z caller=gokit.go:43 traceID=2d114009ce84d08f msg="GET /api/prom/api/v1/query?query=up (500) 8.951725ms Response: \"Query failed after 5 retries.\" ws: false; Accept: */*; User-Agent: curl/7.29.0; X-Scope-Orgid: 5000; "`

**Comment by bboreham** [comment]
This seems to be the most important part:
 > Querier throws error in logs: at least 2 live ingesters required, could only find 1 whereas im running 3 instances of querier

The message is telling you about ingesters - check you have at least two running, and that they each own part of the "ring".  If you hit `http://ring` on a distributor from a browser you should see the current status.
