### ISSUE TITLE
how prometheus remote write carry OrgID

### ISSUE THREAD

**Issue by lm123** [cortexproject/cortex#1212]
prometheus remote write does not set OrgID in its http request header. proxy shall be put between prometheus and cortex to make OrgID be set in http request?

**Comment by nrjpoddar** [comment]
Yes that is correct. If you look at the https://github.com/cortexproject/cortex/blob/master/k8s/nginx-config.yaml file it has an example of how to use Nginx for adding the org ID header.

Depending upon your environment you might be able to use Nginx or write a small custom proxy to do the mapping and insert the correct headers before forwarding the request to the distributor or querier.
