### ISSUE TITLE
Support Google Cloud Firestore as storage

### ISSUE THREAD

**Issue by tamalsaha** [cortexproject/cortex#1229]
I am exploring whether it will be possible to use [Google Cloud FireStore](https://firebase.google.com/docs/firestore/) (FS) as IndexClient for Cortex. Here are my questions:

- Has anyone else tried this or looked into this?

- FS has a limit of 1M for a document (row in RDBMS terms). What are the size limits of `hashKey`, `rnagekey`, `value` []byte ?

- [FS does not support `Prefix` query](https://stackoverflow.com/questions/46642641/sql-like-operator-in-cloud-firestore). It can do >= queries. Is there a way to work around this in Cortex? Is there any structure to `rangekey` []byte (potentially store as separate fields).

- What does the TableClient do? In FS, the first time data is written to a collection it gets created. So, seems like a nop to me.

Thanks.

**Comment by bboreham** [comment]
Hi @tamalsaha , an interesting question but I don't know anything about FireStore.

To cover some of your other points:

> What are the size limits of `hashKey`, `rnagekey`, `value` []byte ?

Those are generally a few tens of bytes for index entries, but the entire _row_ can be quite large as you can have hundreds of thousands of series indexed against the same label value.  See #1242 which aims to shard index rows.

> * Is there any structure to `rangekey` []byte

All the index entries (for the latest schema) are constructed [here](https://github.com/cortexproject/cortex/blob/5d4b7661fb948db3e49643e249eab81900e08584/pkg/chunk/schema.go#L550-L586) . The design for this schema was sketched at https://github.com/cortexproject/cortex/issues/433

> What does the TableClient do?

Whatever it needs to do to set the DB up for reading and writing.  In DynamoDB this includes the table schema, provisioning IOPs, applying tags.  If your DB doesn't need any of that, no problem!

**Comment by tamalsaha** [comment]
Thanks @bboreham ! We are not looking to use Cloud Firestore.
