### ISSUE TITLE
Turning off -ingester.normalise-tokens resulted in ingesters with zero tokens

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1252]
In view of #1251, and #1203 being a failure, I decided to turn off `-ingester.normalise-tokens`.  As the rolling update proceeded, new ingesters appeared to have zero tokens, in metrics and on the `/ring` page.

Relevant: #1112

**Comment by bboreham** [comment]
Having studied the implementation a bit more, there was never any code to make this work.
I would be ok with documenting this instead of calling it a bug.

**Comment by gouthamve** [comment]
This has now been fixed in #1727
