### ISSUE TITLE
"unexpected error: runtime error: integer divide by zero" doing subquery 

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1265]
```
quantile_over_time(0.99, sum(rate(cortex_gw_request_duration_seconds_count{job=~"(.+)/cortex-gw", route="cortex-read"}[5m]))[24h:])
```

NB this doesn't happen with prometheus 2.8rc0.  Either we need to update vendor or we're missing some config.

**Comment by tomwilkie** [comment]
Hoping #1274 fixes this, but haven't had a chance to test yet.

**Comment by gouthamve** [comment]
That did not fix it, looking into it now.
