### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by vtolstov** [cortexproject/cortex#1269]
```
# github.com/cortexproject/cortex/pkg/ring
../../../.cache/go-path/pkg/mod/github.com/cortexproject/cortex@v0.0.0-20190305174137-a4ed288f585b/pkg/ring/batch.go:16:15: undefined: IngesterDesc
```

**Comment by bboreham** [comment]
The latest CI build worked fine: https://circleci.com/gh/cortexproject/cortex/4978

If you're going to post an issue like this, you have to show exactly what you did to get there.
I note that `mod` appears in your error message, and the PR to move to Go Modules is as yet un-merged: #1232

**Comment by vtolstov** [comment]
Ah i see, error present in godoc too. You repo does not have some definition. Theck https://godoc.org/github.com/cortexproject/cortex/pkg/ring#ReplicationSet for example. Can you push in git protoc generated structs too?
Firstly - because go get not works, second - understanding via godoc what struct returned or needed is very hard.

**Comment by vtolstov** [comment]
My problem because i'm try to go get grafana/loki but it fails, becuase for example ring package does not have some definition, that as i understand created via protoc

**Comment by tomwilkie** [comment]
@vtolstov the vendored Cortex in Loki includes the protoc files.  You should use the vendor, and not go mod for now.  Use the makefile to build.

We have a separate issue to track committing generated files: #1224.

**Comment by vtolstov** [comment]
thanks!

**Comment by bboreham** [comment]
#1224 is not the issue you are looking for.

**Comment by vtolstov** [comment]
can you create pr/issue to track including generated files in git repo?
