### ISSUE TITLE
Duplicate datapoints when using query-frontend

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#1273]
We noticed one case when using the query-frontend that duplicate datapoints are returned. This is only for latest datapoints and it goes away when the cache is cleared.

The following is the result returned:
![cortex-dupes](https://user-images.githubusercontent.com/7354143/54120428-aab15700-441d-11e9-8c52-a07a33c5bb78.png)

Further, deleting the caches is only a temporary fix and the duplicates return after a couple of queries. And the more queries you do, the more duplicates there are. This looks like a cache alignment issue tbh.

**Comment by DanCech** [comment]
Saw this again last night

**Comment by woodsaj** [comment]
I am seeing this also. 
![image](https://user-images.githubusercontent.com/8415072/55633995-18b82680-57f0-11e9-8092-b39226005b57.png)

I am explicitly setting the step in the query to '1d',  if i change the step, the problem goes away.
Whether i query for "start=now-7d,end=now" or "start=now-30d,end=now" i still get the problem.  But if i query for "start=now-8d,end=now-1d" i get correct data.

**Comment by woodsaj** [comment]
Actually, even with the updated query time range i am still getting duplicate datapoints, but the point being duplicated changed.

**Comment by gouthamve** [comment]
This is fixed in: https://github.com/cortexproject/cortex/pull/1434
