### ISSUE TITLE
/metrics calls on ingesters taking multiple seconds

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1281]
According to Jaeger traces about half are <20ms and half are 2-10 seconds.
According to Prometheus the mean is 1.5 seconds.
Traces have no detail, haven't really looked into it.

Similar: #283

**Comment by bboreham** [comment]
I added some tracing and this lead to a `ReadMemStats` call in `prometheus/client_golang`.

So I believe the root cause is (a) my ingester has a 30GB Go heap which can take more than 10 seconds to run a GC cycle and (b) `ReadMemStats()` is blocked for that cycle - https://github.com/golang/go/issues/19812

**Comment by bboreham** [comment]
This should be fixed by https://github.com/prometheus/client_golang/pull/568, when Cortex updates to that version.

**Comment by gouthamve** [comment]
This should be fixed now
