### ISSUE TITLE
*_over_time incorrect with subquery

### ISSUE THREAD

**Issue by DanCech** [cortexproject/cortex#1284]
When using `quantile_over_time` with a subquery, the results don't match those from prometheus.

Given a series like:
![image](https://user-images.githubusercontent.com/1443603/54381066-39fb7c00-4663-11e9-8bb5-2d4811b6b4da.png)

Using a standard query we see that the 7-day 95th percentile figure stays at the correct level after the source series drops off:
![image](https://user-images.githubusercontent.com/1443603/54380922-edb03c00-4662-11e9-8960-3b8a2b9c8b67.png)

Changing it to a subquery by adding `:10m` the quantile line drops ~8hrs after the raw series.
![image](https://user-images.githubusercontent.com/1443603/54380945-facd2b00-4662-11e9-96a7-6779eda855b9.png)

The plot thickens when using `count_over_time`:
![image](https://user-images.githubusercontent.com/1443603/54381480-4af8bd00-4664-11e9-8a3d-8f5f3624314d.png)

And prometheus:
![image](https://user-images.githubusercontent.com/1443603/54381909-42ed4d00-4665-11e9-989c-74d22e4c1759.png)

With subquery:
![image](https://user-images.githubusercontent.com/1443603/54381580-898e7780-4664-11e9-9259-517745e1c75f.png)

vs Prometheus:
![image](https://user-images.githubusercontent.com/1443603/54381974-67492980-4665-11e9-91d6-cdc43feb3a97.png)

**Comment by jtlisi** [comment]
@codesome Could you take a look at this?

**Comment by codesome** [comment]
I won't be able to have a look till the end of coming week. I will try though.

**Comment by tomwilkie** [comment]
I think we assume bound on seek in our iterators, and I think subqueries break these assumptions.  Will look for a link.
