### ISSUE TITLE
DynamoDB writes are 'lumpy'

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#129]
DynamoDB is statically provisioned, so this probably isn't a good idea:

![screen shot 2016-11-10 at 16 00 17](https://cloud.githubusercontent.com/assets/444037/20199371/e0763ddc-a75e-11e6-9432-216c55b4f576.png)

We should decrease the GC loop period to scan more often, and perhaps optimise it to a priority queue of something.

**Comment by tomwilkie** [comment]
#127 might help too.

**Comment by gouthamve** [comment]
I think with Bryan's chunk alignment this can be closed. /cc @bboreham
