### ISSUE TITLE
Metrics and recovering from not being able to flush chunks

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#1294]
When debugging #1293, we had no way for hotfixing alerting on not being able to flush chunks. Some ideas on tackling that:
- Keep a per-chunk counter of number of flush attempts, and alert when it gets too high, to catch this case of chunks failing to flush forever.
- Have a hook to slurp all the chunks out of an ingester so we have a way of recovering this.

_Originally posted by @tomwilkie in https://github.com/cortexproject/cortex/pull/1293#issuecomment-474971776_

**Comment by bboreham** [comment]
See #773 and #852 for similar problem and metric (sadly not named very conveniently to re-use for this situation)
