### ISSUE TITLE
Support Redis beside Memcached

### ISSUE THREAD

**Issue by weeco** [cortexproject/cortex#1333]
As devops who has:

1. Much more experience in operating Redis instead of Memcached
2. Can use managed redis services like Google's memory store

I wish cortex would support Redis beside/instead of memcached too, so that I don't need to gain experience in operating Memcached clusters and/or can even use existing redis clusters for Cortex.

**Comment by krystianity** [comment]
+1

**Comment by tomwilkie** [comment]
I'd be happy to merge support for this; you just need to implement the Cache interface here: https://github.com/cortexproject/cortex/blob/master/pkg/chunk/cache/cache.go#L10

**Comment by dmitsh** [comment]
@weeco @tomwilkie please take a look at #1612 and share your feedback. Thanks!

**Comment by bboreham** [comment]
Closed by #1612
