### ISSUE TITLE
Cortex does not compile for Windows

### ISSUE THREAD

**Issue by daixiang0** [cortexproject/cortex#1336]
refer [issue](https://github.com/grafana/loki/issues/193)

**Comment by bboreham** [comment]
I think the problem in https://github.com/grafana/loki/issues/193 is that compilation for Windows was attempted, and the code has not been ported to Windows.

If someone would like to confirm that, I change the issue title.

**Comment by daixiang0** [comment]
refer the [comment](https://github.com/grafana/loki/issues/193#issuecomment-450779604),  the `diskcache.go` use some func which not port to Windows.

**Comment by wagdav** [comment]
@bboreham we'd like to contribute to make Loki's `promtail` work on Windows and this ticket is the blocker for that.  You tagged this ticket "help wanted", do you have something in mind for the implementation?

**Comment by bboreham** [comment]
Hi, thanks for the offer!

Roughly: find all the parts which don't compile on Windows, then either reimplement or stub out, and add [build constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints) and/or the file naming convention to build the right file on the right platform.

Extend CI to cross-compile, at least as a check to see everything compiles.

**Comment by sh0rez** [comment]
Trying to resolve this one!
