### ISSUE TITLE
Ingester: missing region error

### ISSUE THREAD

**Issue by PriyaSivaraj1987** [cortexproject/cortex#1351]
msg="failed to flush user" err="MissingRegion: could not find region configuration"

I have used the following endpoint for dynamodb in ingester.yaml
dynamodb.url=dynamo://dynamodb.us-east-1.amazonaws.com

In the code https://github.com/weaveworks/common/blob/master/aws/config.go 
--> strings.Contains(awsURL.Host, ".") results in "dummy" region 
--> withRegion defaults to "" empty url.. 
How to make sure it selects the amazon endpoint for dynamodb  instead of an empty or default url?

 It might be helpful to show the structure of the dynamodb url for an amazon endpoint (in addition to the kubernetes service endpoint) you’ve used in your example :)

**Comment by nrjpoddar** [comment]
Hi @PriyaSivaraj1987 take a look at the comments [here](https://github.com/cortexproject/cortex/issues/1358#issuecomment-488034341), it might help you in configuring your DynamoDB endpoint correctly.

**Comment by gouthamve** [comment]
Closing as I don't think this is a bug. Please re-open if you feel necessary.
