### ISSUE TITLE
Consistent width for chunk external keys

### ISSUE THREAD

**Issue by candlerb** [cortexproject/cortex#1352]
(Migrated from https://github.com/grafana/loki/issues/454)

**Describe the bug**
Not really a bug, just something that could be neater.

Chunk external keys have variable length, because the fingerprint is normally 16 hex characters but sometimes less (when there would be leading zeros).

I think the issue is [here](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/chunk.go#L179):

```
return fmt.Sprintf("%s/%x:%x:%x:%x", c.UserID, uint64(c.Fingerprint), int64(c.From), int64(c.Through), c.Checksum)
```

My suggestion is to change `%x` to `%016x`, at least for the fingerprint - although it would probably be sensible for the other fields to be fixed width too.

**To Reproduce**
I discovered this issue using loki, which uses cortex as backend.
1. Started loki (c9948233)
2. Started promtail (c9948233) to tail '/var/logs/*.log' (default config)
3. Wait around
4. `ls /tmp/loki/chunks`

**Behavior**

```
# ls /tmp/loki/chunks/
 ZmFrZS83YTI1N2M5ZWI2YTYyMDkwOjE2OWYzMTZiODE2OjE2OWYzMTZiODYyOjdkNzMyNGQy
 ZmFrZS83YTI1N2M5ZWI2YTYyMDkwOjE2OWYzMzk2ZWExOjE2OWYzMzk2ZWExOjE1MGVkZDA2
 ZmFrZS83YTI1N2M5ZWI2YTYyMDkwOjE2OWYzNzA1Y2YzOjE2OWYzNzA1Y2YzOmY3YzNhNjk3
 ZmFrZS83ZTAyYmFmNDA1NmYyN2Q0OjE2OWYzMTZiODE5OjE2OWYzMWE2MjU0OjE0ZDliNGE4
 ZmFrZS83ZTAyYmFmNDA1NmYyN2Q0OjE2OWYzMjExYmEyOjE2OWYzMjI5ZmU0OjNkMzM2M2I3
 ZmFrZS84ZTk0MDgzMzdiZDZlYzA0OjE2OWYzMTZiODFhOjE2OWYzMTZiODJmOjIyYmFhYWI2
'ZmFrZS85N2RiMjQ0MDM5ZWFiOGY6MTY5ZjM3MDVjZjM6MTY5ZjM3MDVjZjM6OGNiNmIwMjY='
'ZmFrZS85N2RiMjQ0MDM5ZWFiOGY6MTY5ZjMxNmI4MTc6MTY5ZjMxNmI4MjI6YWM3NWFkZmI='
'ZmFrZS85N2RiMjQ0MDM5ZWFiOGY6MTY5ZjMzOTZlYTE6MTY5ZjMzOTZlYTE6YTc3MjQ0MDA='
 ZmFrZS85NDY0MWIwNjQ0MGRkNGE0OjE2OWYzMTZiODFiOjE2OWYzMTZiOGVmOjI0ODBjYWVh
 ZmFrZS85ZjY0NjJiM2YxZmM5ZmZlOjE2OWYzMTZiODE5OjE2OWYzMTZiODFmOjE3NjA0ODFk
```

Notice how some of the filenames are quoted, because they end with "=".  This implies a different length in the underlying data which was base64-encoded.

Decoding these, I can see that most of them start with 16 hex digits after the tenant ID: e.g.

```
# echo 'ZmFrZS83YTI1N2M5ZWI2YTYyMDkwOjE2OWYzMTZiODE2OjE2OWYzMTZiODYyOjdkNzMyNGQy' | base64 -d; echo
fake/7a257c9eb6a62090:169f316b816:169f316b862:7d7324d2
# echo 'print(len("7a257c9eb6a62090"))' | python3
16
```

But a quoted one has 15 hex digits at that point:

```
# echo 'ZmFrZS85N2RiMjQ0MDM5ZWFiOGY6MTY5ZjM3MDVjZjM6MTY5ZjM3MDVjZjM6OGNiNmIwMjY=' | base64 -d; echo
fake/97db244039eab8f:169f3705cf3:169f3705cf3:8cb6b026
# echo 'print(len("97db244039eab8f"))' | python3
15
```

This is a very minor issue, but it might be a bit less surprising if the filenames were better aligned.

**Comment by bboreham** [comment]
Some of us pay by the byte for storage.
Besides the aesthetic look of the data, is there any other reason to change?

**Comment by bboreham** [comment]
Since the code has to be backwards-compatible, this would end up being an option and/or a new schema type.

At that point, if I'm moaning about byte wastage, we could move to a different encoding than hex.

**Comment by candlerb** [comment]
> Some of us pay by the byte for storage.

Including filenames? I guess it's a small consideration.  As you say, these could be shrunk further (loki already base64-encodes the whole chunk key).

Aesthetics: well, it does mean that filenames don't sort properly - but sorting by fingerprint is probably not very important.  Once in a blue moon though, you're going to see a file with a filename noticeably shorter than the others, and I would worry that something was accidentally truncated.  (I am old enough to remember non-error-correcting modems which dropped characters :-)

In general, I just found it surprising that different chunks had different filename lengths, and wasted some time trying to figure out why it was the case.  Documenting this behaviour clearly would help.

**Comment by bboreham** [comment]
These "filenames" go in the index.  Also my instance of Cortex stores data in DynamoDB.
I imagine the file storage base64-encodes the string because characters like `:` and `/` are illegal in filenames on one or more OS platforms.

**Comment by candlerb** [comment]
> These "filenames" go in the index

Sure - but with Loki they are actual filenames on your disk (if using local storage); if using S3 backend I expect they are filenames inside the bucket too.
