### ISSUE TITLE
Dynamodb URL issue for AWS endpoint 

### ISSUE THREAD

**Issue by nirajhshah** [cortexproject/cortex#1358]
I am getting below while trying to connect DynamoDB with my cortex.

msg="failed to flush user" err="MissingRegion: could not find region configuration"

I am using below DynamoDB in ingester.yaml with url clearly defined as:
dynamodb.url=dynamo://dynamodb.us-east-1.amazonaws.com

Looking at the code I see that (https://github.com/weaveworks/common/blob/master/aws/config.go)
--> strings.Contains(awsURL.Host, ".") results in "dummy" region
--> withRegion defaults to "" empty url..

So looks like it is setting it up as "dummy" url, do you know how can I make sure to have it select correct supplied DynamoDB url?

**Comment by nrjpoddar** [comment]
You might need to set the following option:
`-dynamodb.url=dynamodb://<AWS_ACCESS_KEY_ID>:<AWS_SECRET_ACCESS_KEY>@<AWS_REGION>`

where <AWS_REGION> is `us-west-2` or whatever region you want to use.

**Comment by fizzamahdi** [comment]
Similar issue here.  My ingester deployment is given an IAM role, so the credentials management and access to AWS resources for the pods are handled by that.  Since I am not planning on passing credentials as part of the URL I thought I could just pass in the region (dynamodb.url=dynamo://@us-east-1) as the hostname as suggeested by this snippet in aws common:

	// Let AWS generate default endpoint based on region passed as a host in URL.
	return config.WithRegion(awsURL.Host), nil

but it is still resulting in the missing region error.  Do you know of a dynamodburl that works properly in generating an aws endpoint for non-emulated services, given just the region?

**Comment by nirajhshah** [comment]
thanks @nrjpoddar , I have the similar usecase like @fizzamahdi mentioned above to use IAM role. we are using IAM for credentials management and we are not going to hardcode the keys.  

Any further suggestions you can provide to resolve the issue?

**Comment by nrjpoddar** [comment]
@fizzamahdi & @nirajhshah we also use kube2iam and pass the appropriate IAM role. Here's the config that works for us:

`-dynamodb.url=dynamodb://us-west-2`

Can you give that a try?

**Comment by fizzamahdi** [comment]
@nrjpoddar thank you!  Got rid of the '@' and got a single message saying that a chunk was successfully flushed, but a minute later the err="MissingRegion: could not find region configuration" proceeded to flood the logs.  Could I bother you to share the format of the S3 url you've provided, to make sure the error isn't coming from that?  I removed the '@' from there as well and now have `-s3.url=us-east-1/<bucket>`

**Comment by fizzamahdi** [comment]
@nrjpoddar it was the s3 url. I accidentally removed the "s3://", but this works: -s3.url=s3://us-east-1/<bucket>

Thank you for your help!

**Comment by nirajhshah** [comment]
@nrjpoddar Thanks for the help, above solution worked. Really appreciate your quick response.
