### ISSUE TITLE
Alertmanager: Email notifier

### ISSUE THREAD

**Issue by Bekt** [cortexproject/cortex#1359]
https://github.com/cortexproject/cortex/blob/d166217273aa54496ff4b079d5fa8349c5c9e0f5/pkg/configs/api/api.go#L175

I didn't see an issue for this but it would be great to have email notifier in Cortex since it has existed in Alertmanager itself for a long time.

**Comment by jaybatra26** [comment]
Hi, I am a gsoc aspirant. Can I take this up?

**Comment by bboreham** [comment]
This is now configurable with the `-configs.notifications.disable-email` flag.
I think it was a security feature, to avoid letting users configure arbitrary smtp endpoints in a multi-tenant system.
