### ISSUE TITLE
tablemanager unknown value type \"\"

### ISSUE THREAD

**Issue by mattparkes** [cortexproject/cortex#1360]
I had Table Manager Autoscaling working, but I've noticed that it stopped working recently and gives the following error every time it polls:

```
level=debug ts=2019-05-01T06:16:09.258445284Z caller=schema_config.go:378 msg="Expected Table" tableName=cortex_weekly_2569 provisionedRead=300 provisionedWrite=1 useOnDemandMode=false
level=debug ts=2019-05-01T06:16:09.25850215Z caller=schema_config.go:378 msg="Expected Table" tableName=cortex_weekly_2570 provisionedRead=300 provisionedWrite=1 useOnDemandMode=false
level=debug ts=2019-05-01T06:16:09.258513214Z caller=schema_config.go:378 msg="Expected Table" tableName=cortex_weekly_2571 provisionedRead=300 provisionedWrite=1 useOnDemandMode=false
level=debug ts=2019-05-01T06:16:09.258524722Z caller=schema_config.go:378 msg="Expected Table" tableName=cortex_weekly_2572 provisionedRead=300 provisionedWrite=1 useOnDemandMode=false
level=debug ts=2019-05-01T06:16:09.258534871Z caller=schema_config.go:378 msg="Expected Table" tableName=cortex_weekly_2573 provisionedRead=300 provisionedWrite=1 useOnDemandMode=false
level=debug ts=2019-05-01T06:16:09.258545773Z caller=schema_config.go:399 msg="Table is Active" tableName=cortex_weekly_2573 provisionedRead=300 provisionedWrite=100 useOnDemandMode=false useWriteAutoScale=true useReadAutoScale=false
level=info ts=2019-05-01T06:16:09.258561427Z caller=table_manager.go:218 msg="synching tables" num_expected_tables=6 expected_tables=6
level=debug ts=2019-05-01T06:16:09.296262473Z caller=table_manager.go:388 msg="checking provisioned throughput on table" table=cortex_weekly_2571
level=error ts=2019-05-01T06:16:10.279615926Z caller=table_manager.go:206 msg="error syncing tables" err="unknown value type \"\""
```

I also sometimes see this error:
```
level=error ts=2019-05-01T06:27:03.859303114Z caller=table_manager.go:197 msg="error syncing tables" err="expected three values: 4"
```

This happens with `table-manager:master-79bba2f9` _(Today)_ and `table-manager:master-f18cc59b` _(2nd March 2019 which was an arbitrary tag older than some recent changes to table_manager.go)_, with the following arguments:
```
-log.level=debug
-server.http-listen-port=80
-dynamodb.url=dynamodb://***************:*********************************@ap-southeast-2
-dynamodb.v9-schema-from=2019-04-01
-dynamodb.use-periodic-tables
-dynamodb.periodic-table.period=168h
-dynamodb.periodic-table.prefix=cortex_weekly_
-dynamodb.periodic-table.from=2019-04-01
-dynamodb.periodic-table.write-throughput=100
-dynamodb.periodic-table.write-throughput.scale.enabled=true
-dynamodb.periodic-table.write-throughput.scale.target-value=80
-dynamodb.periodic-table.write-throughput.scale.min-capacity=10
-dynamodb.periodic-table.write-throughput.scale.max-capacity=1000
-dynamodb.periodic-table.write-throughput.scale.in-cooldown=3600
-dynamodb.periodic-table.write-throughput.scale.out-cooldown=3600
-dynamodb.periodic-table.write-throughput.scale.role-arn="arn:aws:iam::****************:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable"
-metrics.url=http://cortex-nginx/api/prom/
-metrics.queue-length-query=sum(avg_over_time(cortex_ingester_flush_queue_length{job="cortex/cortex-ingester"}[2m]))
```

**Comment by bboreham** [comment]
`"unknown value type"` comes from the logger; it's a bit weird because any error type should be able to convert itself into a string.  So really we have two problems: whatever is really failing, and the inability to print it out.

`"expected three values"` comes from `pkg/chunk/aws/metrics_autoscaling.go`; it says the Prometheus query returned more values than we expected.  Again, I think we need more data on what went in and what came out.

Are you up for modifying the code to add more debugging info?

**Comment by mattparkes** [comment]
Thanks for the reply. I'm more of an ops guy, so I'm not really able to do much with the code unfortunately.

I'll drop the raw result of my `-metrics.queue-length-query` in this Issue tomorrow to assist with debugging that. It's just the default query wit the Job label tweaked slightly to match my Prometheus  collector's labels, but there must be something subtly different with the data being returned.

**Comment by mattparkes** [comment]
I fixed the issue with the `"expected three values: 4"` by tweaking my `-metrics-queue-length-query` slightly, but that didn't actually fix the issue with Tablemanager not autoscaling.

My `-metrics-queue-length-query` now correctly returns results like:
```
{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1557442985.872,"366"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1557443255.488,"156.5"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1557443285.691,"0"]}]}}
```


I've dug into the code a little bit, and the `"unknown value type"` error is coming from [`vendor/github.com/prometheus/common/model/value.go:279`](https://github.com/prometheus/common/blob/master/model/value.go#L279)

I changed that line to: 
```
    return fmt.Errorf("unknown prometheus value type %T: %#v", s, s)
```

and am now getting:
```
unknown prometheus value type string: \"\""
```

I'm not really savvy enough with go to take this much further, so if anyone has any pointers that would be greatly appreciated.

**Comment by bboreham** [comment]
Looks like this is inadequate error handling inside the metrics-based autoscaler code; it fires some queries and if it gets back a result it wasn't expecting it prints this cryptic message.
