### ISSUE TITLE
Consider jingo for frontend JSON encoding.

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1373]
Blog post claims its faster than JSON iterator, which we currently use:  https://bet365techblog.com/open-sourcing-jingo-a-faster-json-encoder-for-go

**Comment by VineethReddy02** [comment]
Hi!
I would like to take this up. So do I need to replace``` json.marshal``` & ```json.unmarshal``` where ever it's being used?

**Comment by pracucci** [comment]
> So do I need to replace json.marshal where ever it's being used?

Not trying to make it too complicated, but I would suggest to take an informed decision on this change. I would suggest to:

1. Run an independent benchmark first (ideally based on Cortex use case), share data upon which we can decide it's worth the effort
2. Propose a list of places where switching it may bring a significative performance benefit and gather some feedback from the Cortex community
3. Act upon feedback received

**Comment by pstibrany** [comment]
Also make sure that Cortex is not affected by any of the drawbacks: https://github.com/bet365/jingo#drawbacks

**Comment by bboreham** [comment]
Closing as stale.  If anyone is interested to resurrect, please post benchmark stats demonstrating the value.
