### ISSUE TITLE
Update/enhance architecture documentation

### ISSUE THREAD

**Issue by weeco** [cortexproject/cortex#1375]
The architecture documentation helped me understanding how Cortex works. However while working on the deployment of Cortex I noticed there may be some parts which have not been documented yet or left out (for a reason?).

**1. Configs Deployment**

I am not sure what this deployment is supposed to do or how it interacts with the other microservices. Apparently it has another dependency on a Database (Postgres only?). 

**2. Table Manager**

Same here, what is this microservice responsible for? Do I need it when I want to use Cassandra/BigTable instead of DynamoDB?

**3. Ruler**

Is the Ruler dependency required to run Cortex? In case I do not want to use any of the alert manager features.

**Comment by pracucci** [comment]
Closed by #1421 and #1945.
