### ISSUE TITLE
remove AWS auto-scaler code 

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1379]
Currently we have two ways to auto-scale DynamoDB - using AWS' facility and using Cortex "metrics-based" code.
As described at #735 the AWS version never worked satisfactorily for Weaveworks.

This issue is to gather feedback for removing support for AWS autoscaling, thus simplifying the codebase. Most of the implementation is in [one file](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/aws/aws_autoscaling.go).

Not much would change for end-users who are not using the feature.  Most of the flags were re-used for metrics-based scaling.

**Comment by tomwilkie** [comment]
+1 we don't use it, so I'd say go for it.

**Comment by csmarchbanks** [comment]
I agree to get rid of it. I just spun up my first AWS cortex deployment, and figuring out autoscaling took the most amount of time. Having just one way to do it would be much appreciated.

**Comment by khaines** [comment]
+1 for removal. Once we switched to the metrics based autoscaling, I've never looked back.

The AWS based one is really good at scaling your bill up though :)
