### ISSUE TITLE
TTL for object stores(S3, GCS)

### ISSUE THREAD

**Issue by sandlis** [cortexproject/cortex#1381]
As of now, Table Manager does the retention, which is the only component that knows about retention policy and it only handles the retention of index tables.

Retention in object stores like S3 and GCS can be done by setting a TTL.
Should this be done manually by someone before configuring object store into Cortex or should Table Manager get object store clients to set the TTL?

**Comment by gouthamve** [comment]
My opinion is that we let the operator handle it and not table-manager. This is because we have a single bucket and even that bucket is created by the operator and not via table-manager.

**Comment by gouthamve** [comment]
Closing this as I see this as the purview of the operator and not the table-manager.
