### ISSUE TITLE
Retention with multiple store configs

### ISSUE THREAD

**Issue by sandeepsukhani** [cortexproject/cortex#1382]
As of now, Table Manager creates Table Client only for newest config as seen here:
https://github.com/cortexproject/cortex/blob/master/cmd/table-manager/main.go#L47-L62
Retention code calls deleteTable only on this table client for newest config.
If someone would use different config for different time span then Table Manager would not delete expired index tables from previous configs.
Should this be fixed or its never going to be a case where people would have multiple configs?

**Comment by bboreham** [comment]
It should be fixed.
It should even support cases like "started on DynamoDB, moved to Bigtable".
Not just retention, but all the provisioning stuff too.

**Comment by friedrichg** [comment]
Not valid anymore, Chunks was deprecated and removed
