### ISSUE TITLE
Spans in promql don't anchor properly.

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#1391]
This is on commit: prometheus/prometheus@3cc5f9d8806 and no relevant changes have been made to master of prometheus after this.

Before `promqlPrepare` used to end and then `promqlInnerEval` used to start.

![image](https://user-images.githubusercontent.com/7354143/57779888-b0405b80-7744-11e9-9233-c884534976da.png)

But right now promqlPrepare ends in less than millisecond and innerEval is starting waaay earlier. Not sure if the bug is in cortex or upstream.

**Comment by codesome** [comment]
Adding more info: Though `promqlPrepare` seems to take very less time, when expanded, the nested functions seem to take a longer time.

![Screenshot from 2019-06-05 16-23-33](https://user-images.githubusercontent.com/15064823/58951294-5e707b80-87ae-11e9-8204-a4b784640fbe.png)

`promqlPrepare` looks normal on a local Prometheus though

![Screenshot from 2019-06-05 16-26-15](https://user-images.githubusercontent.com/15064823/58951418-b5765080-87ae-11e9-9e04-8a65a01d412a.png)

**Comment by codesome** [comment]
I guess I found that is happening. It is the `lazyQuerier`.
https://github.com/cortexproject/cortex/blob/a491c4a38009d7d04cf3ea7f559cbdeb7256096b/pkg/querier/lazy_querier.go#L17-L18

And it doesn't get expanded in `populateSeries` (the function instrumented for `promqlPrepare`)
https://github.com/prometheus/prometheus/blob/9ba2f13c5ebea1775561551988910de04d922cf4/promql/engine.go#L579
https://github.com/prometheus/prometheus/blob/9ba2f13c5ebea1775561551988910de04d922cf4/promql/engine.go#L598

So `promqlPrepare` is not capturing the background task as expected. Does it make sense?

**Comment by gouthamve** [comment]
Hmm, it makes sense and it's kinda not possible to make it look at the background tasks given the prepare function exits. So this is a feature then, sigh.
