### ISSUE TITLE
RFC: Release cadence, process and ideas

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#1402]
We've decided to do a cortex release soon, but after the first release, I think we should have some process and cadence for future releases. I made a Google docs with initial suggestions here: https://docs.google.com/document/d/1Ma5upv_lPG0KaJySqm8AY20ZjicNrB2qZS5WIlDqbNw/edit#

This is largely inspired by the Prometheus release cadence and process.

**Comment by avicshw** [comment]
@gouthamve Is there any progress?

**Comment by gouthamve** [comment]
Closing as this is done in #1470
