### ISSUE TITLE
SQL index store for cortex

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#1419]
I think we should support an SQL backend for the index store. This could be a generic SQL backend that supports both MySQL and Postgres and other MySQL/Postgres compatible stores like cockroachdb and TiDB (alternatively TiKV).

**Comment by chancez** [comment]
@gouthamve Just to be clear, #1681 isn't a pre-req for new index stores right? It's always possible to extract built-in options to external plugins later right, so I assume that doesn't block work on this.
