### ISSUE TITLE
Rolling update on ingester causes duplicate value for timestamps

### ISSUE THREAD

**Issue by weeco** [cortexproject/cortex#1438]
**The problem**

Every time I perform a rolling update on ingesters I can see lots of discarded samples (~1% of all ingested samples) due to "new-value-for-timestamp". With each updated ingester the number of discarded samples seems to increase. After all ingesters had been updated it takes something like 30-45minutes until the discarded samples slowly decreases towards 0 again:

![Cortex Dashboard](https://i.imgur.com/gKosOMG.png)

This issue is 100% reproducible across several Cortex versions. I checked the logs and they all have in common that they say, the previous value for that timestamp seems to be 0 (which I suspect to be wrong).

If I can provide any further information to figure out the problem, please let me know.

**Comment by bboreham** [comment]
I think this is because `memorySeries.setChunks()`, called from `TransferChunks()`, sets `lastTime` but not `lastSampleValue`.
