### ISSUE TITLE
RFC: Tombstones based deletes in Cortex

### ISSUE THREAD

**Issue by sandeepsukhani** [cortexproject/cortex#1449]
As of now, there is no way of deleting unwanted or sensitive data from Cortex. [Here](https://docs.google.com/document/d/10YZitDkEpX1G-aifPGqeMBACYteCMgVgGe3x0e3yTyA/edit?usp=sharing) is the design doc for implementing deletes in Cortex using Tombstones. It would be great if someone can review it and help it align with the expectations of the users.

**Comment by aengusrooneygrafana** [comment]
Updating with the latest design doc (reference above is out of date - the doc now marked as 'old') - the Cortex team are working on the latest design doc [here](https://docs.google.com/document/d/1PeKwP3aGo3xVrR-2qJdoFdzTJxT8FcAbLm2ew_6UQyQ/edit#heading=h.7tz1d625ev0c)

**Comment by bboreham** [comment]
Implemented in #2103 and subsequent PRs.
Docs https://cortexmetrics.io/docs/guides/deleting-series/
