### ISSUE TITLE
Queries that hit size limits are retried

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#1450]
We are seeing a lot of the following errors in our queriers:
```
level=error ts=2019-06-06T17:42:31.656508688Z caller=worker.go:176 msg="error processing requests" err="rpc error: code = ResourceExhausted desc = trying to send message larger than max (398218677 vs. 104857600)"
```

Now this same query is being retried 5 times, as the front-end sees a 500 error. We should have a limit on the number of samples being returned and then return a 4xx for it.

**Comment by bboreham** [comment]
Related: #1178
