### ISSUE TITLE
Dynamodb on-demand  support

### ISSUE THREAD

**Issue by rverma-nikiai** [cortexproject/cortex#1452]
Support for provisioning type as on-demand can really contribute to huge savings, especially for the weekly chunks and the main table as well. I saw that it gets provisioned by default as 300RC and 3000WC, which is too large when we start investigating in the cortex in dev env.
Some docs on customizing these would be awesome too :)

**Comment by rverma-nikiai** [comment]
found -dynamodb.chunk-table.enable-ondemand-throughput-mode in code. Thanks

**Comment by stvnwrgs** [comment]
@rverma-nikiai can you tell what the problem is besides the wrong naming of the config variable?
