### ISSUE TITLE
Table-manager as a batch-job

### ISSUE THREAD

**Issue by rverma-nikiai** [cortexproject/cortex#1453]
Wondering whether we require to run table-manager as a pod or can we switch it to jobs+cronJobs (https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) to schedule on init creation and weekly creation of tables.

I believe this is the only role currently which table-manager does. If we need to trigger a resource build on some condition we can use k8 APIs to execute a job as well.

**Comment by bboreham** [comment]
I agree this would be better in some cases, however to add to your last paragraph table-manager may also be configured to adjust the capacity of DynamoDB every few minutes, which is valuable if your load is uncertain.

**Comment by gouthamve** [comment]
You can do it right now, run it as a batch job. But you lose out on some advantages as Bryan mentioned.

Closing this as there is nothing to do here.
