### ISSUE TITLE
Allow custom authenticator for cassandra clusters

### ISSUE THREAD

**Issue by CH-JosephBironas** [cortexproject/cortex#1454]
We're doing audit logging using the ecAudit cassandra module and getting this error from table-manager:
level=error ts=2019-06-09T16:34:17.500073012Z caller=log.go:141 msg="error initializing cortex" err="gocql: unable to create session: unable to discover protocol version: unexpected authenticator \"com.ericsson.bss.cassandra.ecaudit.auth.AuditPasswordAuthenticator\"\n

Looking at this gocql issue for reference, it looks like it's possible to create a new authProvider object that allows override of gocql's default list.
https://github.com/gocql/gocql/issues/1109#issuecomment-439044906

**Comment by gouthamve** [comment]
Closing as it's fixed by https://github.com/gocql/gocql/pull/1321
