### ISSUE TITLE
Can't run cmd/Dockerfile image. Error: standard_initi_linux.go:207. 

### ISSUE THREAD

**Issue by DandyDeveloper** [cortexproject/cortex#1462]
I'm building the image, the entrypoint is a locally build cortex (nothing changed in the application) and `docker run` is throwing the following:

`standard_init_linux.go:207: exec user process caused "no such file or directory"`

This normally happens in alpine when an entrypoint is using bash rather then sh. I've never seen this with Go based applications before. 

I've tried variations of docker run:

- `docker run cortex:latest`
- `docker run -it cortex:latest /bin/sh`

I'm building in Linux Mint, both the cmd app and the image were built in this distro.

**Comment by bboreham** [comment]
Generally this means that some shared library is missing - run `ldd cortex` outside and inside the container and see if that sheds any light.

**Comment by DandyDeveloper** [comment]
@bboreham Looks like the container is missing `linux-vdso.so.1`. I'll swap to a different distro for images for the time being.

Is this something worth keeping open to investigate?

**Comment by bboreham** [comment]
The bit in the Makefile which says `-ldflags "-extldflags \"-static\" -s -w"` is supposed to statically link the binary to avoid this kind of problem.  Can you confirm you are getting that as part of your build?

**Comment by DandyDeveloper** [comment]
@bboreham That explain things, I was running go build directly, without using the Makefile. 

So fair warning to everyone, the short of it is run this: 

`CGO_ENABLED=0 go build -ldflags "-extldflags \"-static\" -s -w" -tags netgo -o cmd/cortex/cortex ./cmd/cortex`

Alternatively, just run `make` and it'll do it for you. Closing. 

Thank you @bboreham
