### ISSUE TITLE
Idea: constant-value chunks

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1468]
In a typical Kubernetes cluster there are many series where the value is zero for all samples, and a significant number where the value is continuously 1.  Examples: `kube_pod_container_status_waiting_reason` and `kube_pod_container_status_ready`.

My idea is, before saving a chunk, we check to see whether (a) the values are all the same and (b) the timestamps are very regular, say within 1% of the same interval each time.  If so, replace the chunk with one which just has the value, interval and repeat count.

The benefits are reduced storage and faster queries.  The downside is effort expended to check the values - chunks which are non-constant should be detected quite quickly so this effort will be focused on the ones where we benefit.

Instead of checking a whole chunk on flush, we could check each sample as it is appended and switch out the in-memory storage when a chunk is found to be non-constant. My instinct is that this would be more expensive.

Prometheus v1 `varbit` chunks did this internally, but v2 chunks do not.

(This idea is similar to the discussion at #1034)

**Comment by bboreham** [comment]
Some discussion upstream https://github.com/prometheus/prometheus/issues/5865

**Comment by gouthamve** [comment]
The problem is that even if we have minute variances in the scrape interval, by ignoring the variance we would be storing and return technically wrong data and would fail PromQL compliance tests. I would suggest we just implement this upstream as discussed in https://github.com/prometheus/prometheus/issues/5865

**Comment by alanprot** [comment]
Chunks storage was removed.
