### ISSUE TITLE
Elastic as a storage backend

### ISSUE THREAD

**Issue by roopakparikh** [cortexproject/cortex#1477]
Elastic is probably the most popular opensource document storage out there.  I would like to add Elastic as backend storage for cortex. I would also like to hear any opinions out there on that subject.

**Comment by csmarchbanks** [comment]
I am fine with someone adding elastic as a backend (and offering to support it). Would it make sense to add a pluggable storage instead though? Similar to the approach Jaeger is taking.

**Comment by friedrichg** [comment]
Elastic made sense when cortex needed a KV DB for the indexes (Cassandra or Dynamodb ) in chunks.
With chunks deprecated and removed in v1.14.0. This is no longer possible/needed.
