### ISSUE TITLE
build without aws s3 storage only with local

### ISSUE THREAD

**Issue by vtolstov** [cortexproject/cortex#1490]
how can i avoid building with github.com/cortexproject/cortex/pkg/chunk/aws? (it depends on github.com/aws/aws-sdk-go/service/s3) that i don't need.

**Comment by bboreham** [comment]
Only by editing the source and removing references to that package. 
There’s probably only four or five.

**Comment by vtolstov** [comment]
But why not do that stuff pluggable?

**Comment by bboreham** [comment]
We would welcome PRs in that direction.
