### ISSUE TITLE
S3 as long term storage point only

### ISSUE THREAD

**Issue by KaoSiTo** [cortexproject/cortex#1494]
Hi,

I'm new with cortex and I'd like to know if it's possible to use it with S3 only as long term storage without using DynamoDB and how should I configure it.
I haven't seen anywhere how to do it or a list of options to configure the yaml file properly.

Thanks.

**Comment by csmarchbanks** [comment]
Hello,

It is not possible to just use an object store with Cortex. You need to use something like DynamoDB in order to store the index created by Cortex.

**Comment by KaoSiTo** [comment]
How can I configure it on the yaml file instead of passing it as a parameter?

Thanks.
