### ISSUE TITLE
Can't statically (w/o SRV lookup) set memcached servers

### ISSUE THREAD

**Issue by pablokbs** [cortexproject/cortex#1505]
Hello, sorry for all the issues I'm creating today :D

I have the ingesters working but not being able to push to memcached (in aws) I tried pushing an item with another pod in the same network and namespace and I was able to do it:

```
root@ubuntu-649f64d646-482db:/# telnet test-cortex.xxxx.cfg.use1.cache.amazonaws.com 11211
Trying 10.80.17.123...
Connected to test-cortex.xxxx.cfg.use1.cache.amazonaws.com.
Escape character is '^]'.
get greeting
END
set greeting 1 0 11
Hello world
STORED
get greeting
VALUE greeting 1 11
Hello world
END
```

But ingester is complaining:

```
ingester-84c4b85c4d-sfdsm ingester level=error ts=2019-07-10T16:49:07.529243532Z caller=memcached.go:230 msg="failed to put to memcached" name= err="memcache: no servers configured or available"
ingester-84c4b85c4d-sfdsm ingester level=error ts=2019-07-10T16:49:07.535683451Z caller=memcached.go:230 msg="failed to put to memcached" name= err="memcache: no servers configured or available"
ingester-84c4b85c4d-sfdsm ingester level=error ts=2019-07-10T16:49:07.539257288Z caller=memcached.go:230 msg="failed to put to memcached" name= err="memcache: no servers configured or available"
ingester-84c4b85c4d-sfdsm ingester level=error ts=2019-07-10T16:49:07.541753931Z caller=memcached.go:230 msg="failed to put to memcached" name= err="memcache: no servers configured or available"
```

The relevant part in the config:

```
      -memcached.hostname=test-cortex.xxxxx.cfg.use1.cache.amazonaws.com:11211
      -memcached.timeout=100ms
      -memcached.service=memcached
```

I wonder if it's related to https://github.com/cortexproject/cortex/issues/1501

**Comment by gouthamve** [comment]
Hrm, we expect the memcached servers to be running in kubernetes and look them up using SRV records. We should be able to statically configure a single instance of memcached like in the example above and not depend on SRV records.

Easiest way I see is to just use the `hostname` when `service` is unset.

**Comment by chancez** [comment]
From what I can tell the code will revert to the default for the flag if you explicitly set it to `""`, so either a new flag is needed to disable this behavior or the default needs to be removed and the logic can be updated to handle `""` as "don't use SRV discovery". 

Is there a preference?

**Comment by chancez** [comment]
Correction, you can set the `service` option to `null` in the configuration file, but it seems to fail still:
```

**Comment by pracucci** [comment]
_FYI, I'm incidentally working on this while adding adding memcached support to Thanos and we may want to wait mine PR into Thanos to see if we can reuse it (it supports statically configured memcached servers too)._

**Comment by chancez** [comment]
@pracucci that sounds good. I think even if not, the code for fixing this (disabling SRV discovery) is pretty simple so the effort is pretty minimal, even if it ends up being replaced with what you've done.

**Comment by pracucci** [comment]
Sure @chancez. Feel free to move on. I just wanted to warn you, in case it was a large work (I didn't check).

**Comment by lyc0221** [comment]
sorry, I don't still known how to solve this question! How ?

**Comment by hmfritz** [comment]
I'm having a similar problem. Any word on this? I'm getting .a no such host error from memcached_client and consul_client

**Comment by chris-ng-scmp** [comment]
Me too, I have the same issue, any fix?

**Comment by hmfritz** [comment]
@chris-ng-scmp The thing that fixed it for me was changing the resolver in nginx-config.yaml to kube-dns.kube-system. I'm using the helm chart.

**Comment by ericescalante** [comment]
Same here, not using kubenertes at the moment and need to enable memcache (since redis is failing [as well](https://github.com/cortexproject/cortex/issues/2133))

**Comment by mrmassis** [comment]
Some resolution?

**Comment by mrmassis** [comment]
I have the same problem.

**Comment by pracucci** [comment]
The memcached server endpoint config option now supports the DNS service discovery mode as well ([see doc here](https://cortexmetrics.io/docs/configuration/arguments/#dns-service-discovery)) so you can set the memcached static endpoints as something like `dns+memcached.local:11211`

**Comment by darioef** [comment]
As I read in Loki's Slack channel I solved it using "addresses" instead "host" with the address of my memcached. It worked.

PS: "addresses" option isn't documented in the official documentation.
