### ISSUE TITLE
Embed metrics into structs and optional initialization

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#1512]
The single binary version of cortex ends up reporting metrics for each component in cortex regardless of whether the module is enabled or not. At this point it would make sense to start embedding metrics into structs so that the initialization of those metrics is actually dependent on whether that module is deployed or not.

This can be done piecemeal one module or package at a time.

**Comment by bboreham** [comment]
I support this idea; came here to add that we have some other metrics that come in via `promauto` from vendor'd code that never gets called.  Example `prometheus_remote_storage_highest_timestamp_in_seconds`

**Comment by jtlisi** [comment]
Relevant Design Document: https://docs.google.com/document/d/100HSvgvaswVR96Bmz2BWIL3d9ds6wqNTVI7_vESgOtE/edit?usp=sharing

**Comment by pracucci** [comment]
I think the solution we've already started adopting is to pass `prometheus.Registerer` to services and register metrics on that, avoiding `promauto`.

**Comment by bboreham** [comment]
This issue says not to use `promauto`, while #2204 says to use `promauto`.

This one got closed as stale; does that mean `promauto` won?

**Comment by pracucci** [comment]
> This one got closed as stale; does that mean `promauto` won?

I think we can close this issue. The pattern we're currently using (and looks working fine with downstream projects) is to take the `prometheus.Registerer` in input (eg. `NewSomething(reg prometheus.Registerer)` and then registering metrics via `promauto.With(reg)`.

**Comment by bboreham** [comment]
Agreed: if we create the metrics in `NewSomething()` that achieves the aim of this issue.

Nitpick: the key is we are _creating_ metrics via `promauto.With()`, hence not needing to think about whether they need registering.
