### ISSUE TITLE
Connecting Cortex to Cassandra Cluster

### ISSUE THREAD

**Issue by cobalt293** [cortexproject/cortex#1515]
Hi I am currently looking to connect a Kubernetes Cortex cluster to a Cassandra cluster.  I did a good amount of looking but couldn't find much documentation.  I believe I would need to modify the Ingester and the Querier but not 100% sure.  Has this been done before?  I would be willing to contribute to the project if you need help.

**Comment by ambujjain** [comment]
Hi Did you get any update on it ? I am also looking cassandra as backend storage.

**Comment by techy16** [comment]
Hi Did you guys get some directions or help to move further as i am also looking Cassandra as storage option.
