### ISSUE TITLE
Multi-tenancy documentation

### ISSUE THREAD

**Issue by pspiller** [cortexproject/cortex#1517]
I'm interested in using Cortex to add multi-tenancy to Prometheus. I wasn't able to find much information on how to set this up in the docs, though. There was a mention of setting the `X-Scope-OrgID` header on samples written to Cortex, but not much more. Is there an example of a multi-tenant setup anywhere that I could look at?

Related to this: how easy would it be to only use the multi-tenancy feature of Cortex? I don't currently need the other features (long-term storage, HA, etc), but I do need to prevent multiple users from seeing each other's data.

Thanks in advance for any help.

**Comment by weeco** [comment]
Pass this header along to set the tenant ID - for querying and writing. This way you can encapsulate data between tenants. You may want to build your own gateway in front of it. I put a little documentation about it on here: https://github.com/cloudworkz/cortex-ops

More documentation will follow

**Comment by weeco** [comment]
Will be resolved by https://github.com/cortexproject/cortex/pull/1553

**Comment by gouthamve** [comment]
Closed by https://github.com/cortexproject/cortex/pull/1553
