### ISSUE TITLE
Who does Cortex deals with Prometheus side defined alerts and AlertManager

### ISSUE THREAD

**Issue by thosil** [cortexproject/cortex#1518]
Hi,

if I define alerting rules in Prometheus config, how do Cortex deal with them?
Are they sent to the Cortex's AlertManagers or do I have to configure each Prometheis to send alerts to them?

Thanks

**Comment by bboreham** [comment]
Cortex embeds the AlertManager code, adapted for multi-tenant use. Per-tenant config is read from a database. 

`cortex -target=alertmanager`

**Comment by thosil** [comment]
thanks :-)
