### ISSUE TITLE
Grafana graphs getting an error when choosing the time picker bigger than the retention of metrics

### ISSUE THREAD

**Issue by fcastello** [cortexproject/cortex#1523]
I have my test cluster with a retention of 1 week and when I change the time picker to be greater than 7 days I get errors in the graphs. I know it's complaining that is trying to fetch data from a table that doesn't exist which probably was cleaned by tablemanager. So when using prometheus even if there are metrics before one week have a time picket more than the retention only brings the metrics it has.

I am running quay.io/cortexproject/cortex:master-479e64c8 on the queriers and query frontend and index store and chunk store is Cassandra

**Comment by fcastello** [comment]
![Screenshot 2019-07-19 12 57 35](https://user-images.githubusercontent.com/7442541/61534413-71ba6c00-aa27-11e9-924c-a659cf64a38e.png)

**Comment by fcastello** [comment]
Sorry I forgot to attach grafana error on the original post

**Comment by jtlisi** [comment]
@fcastello What does your schema config look like?

**Comment by fcastello** [comment]
That is my schema.yml
`configs:
- from: 2019-03-25
  schema: v10
  store: cassandra
  index:
    prefix: index_
    period: 24h
  object_store: cassandra
  chunks:
    prefix: chunk_
    period: 24h`

**Comment by gouthamve** [comment]
Hi @fcastello Please limit the lookback period in the querier by passing: `-store.max-look-back-period=<retention-period>`. That'll fix your issue.
