### ISSUE TITLE
Come up with a way of migrating from consul to etcd.

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1525]
We probably want to be able to mirror the ring into etcd, and then have a way of switching over to it.

Will be tricky to get right, so some though required.

**Comment by tomwilkie** [comment]
I've asked @pstibrany to look into this.

**Comment by pstibrany** [comment]
Sent PR #1749 to support such migration. Details in PR.

**Comment by pstibrany** [comment]
#1749 is now in Cortex 0.6.0, so this issue can be closed.
