### ISSUE TITLE
Add jitter to HA deduping heartbeats

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#1534]
Right now there is a thundering herd every `15s` (updateTimeout) where all distributors will be CASing the ring. With 25+ distributors, I think this puts undue load on etcd. I think we can do better by adding jitter to the heartbeats.

**Comment by adnxn** [comment]
@gouthamve will take a look at this one

**Comment by gouthamve** [comment]
Closed this in #1748
