### ISSUE TITLE
Please move assert.sh to /vendor

### ISSUE THREAD

**Issue by dankohn** [cortexproject/cortex#1537]
Despite https://github.com/cortexproject/cortex/pull/1531 GitHub is appropriately not applying an Apache 2.0 license label to cortex because of the existence of https://github.com/cortexproject/cortex/blob/master/COPYING.LGPL-3.

Could you please move https://github.com/cortexproject/cortex/blob/master/tools/integration/assert.sh to the /vendor directory (and mention in https://github.com/cortexproject/cortex/blob/master/VENDORED_CODE.md) and then delete https://github.com/cortexproject/cortex/blob/master/COPYING.LGPL-3.

Then GitHub will identify cortex as Apache 2.0 licensed, and the CNCF Landscape will pick it up the next day.

Also note that an LGPL-3 dependency will require an explicit vote of the CNCF governing board to approve. It's certainly likely in this case given how trivial the code is, but it would be great if upstream would agree to dual-license it or if you could replace with similar functionality using a whitelisted license. https://github.com/cncf/foundation/blob/master/whitelist-policy.md#approved-licenses-for-whitelist

**Comment by bboreham** [comment]
Note that the `tools` subdirectory is a `git subtree` "vendor" from https://github.com/weaveworks/build-tools; `assert.sh` is not used by Cortex.

(We have somewhat broken the subtree relationship already; just noting all the complications I could think of)

Historically we couldn't put arbitrary files under `vendor` because the tool `dep` would delete them.  I'm not sure if `go mod` is any softer.

**Comment by csmarchbanks** [comment]
How do we feel about giving up on the subtree and just removing `assert.sh` (as well as other unused tools)?

**Comment by bboreham** [comment]
I would feel better if it was done completely, rather than changing a file here and a file there as to date. 

Note there are some improvements upstream, eg the call to `go vet` was fixed. But we can always bring them in piecemeal.
