### ISSUE TITLE
Rule group metrics are always zero in Cortex

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1557]
#1548 prompted me to look at these metrics.  Most of what I looked at was zero:

`prometheus_rule_group_duration_seconds` (this one is also zero in our Prometheus)
`prometheus_rule_group_duration_seconds_count` 
`prometheus_rule_group_duration_seconds_sum`
`prometheus_rule_group_last_duration_seconds`
`prometheus_rule_group_last_evaluation_timestamp_seconds`

In fact the only one which isn't all zeros in Cortex is `prometheus_rule_group_rules`

**Comment by jtlisi** [comment]
The metrics that should work with the way we utilize the rule group struct are
```
prometheus_rule_evaluation_duration_seconds
prometheus_rule_evaluation_failures_total
prometheus_rule_group_rules
```

I think the ones you listed could be added relatively easily with some upstream work

**Comment by bboreham** [comment]
Emitting a bunch of metrics which are all zero strikes me as wasteful, though this is by no means the only place that Cortex does it.

**Comment by jtlisi** [comment]
Ever since #1571, all of the rule group metrics in cortex have been populated. I think this issue can be closed. I agree there is room for improvement on null metrics generally.

**Comment by bboreham** [comment]
Nit-picking, the exact metrics named are no longer exported at all by Cortex, but prefixed ones like `cortex_prometheus_rule_group_duration_seconds` are now exported per-user.  Thanks!
