### ISSUE TITLE
Example of deploying Cortex in Kubernetes

### ISSUE THREAD

**Issue by emillg** [cortexproject/cortex#1565]
Is there any example of how to deploy Cortex in Kubernetes?

Thanks!

**Comment by weeco** [comment]
https://github.com/cortexproject/cortex/tree/master/k8s
https://github.com/cortexproject/cortex/pull/1410
https://github.com/cortexproject/cortex/pull/1397
For GKE/BigTable: https://github.com/cloudworkz/cortex-ops

**Comment by emillg** [comment]
@weeco Thanks!
