### ISSUE TITLE
Runtime Component sharing with Grafana Loki

### ISSUE THREAD

**Issue by rverma-nikiai** [cortexproject/cortex#1568]
Sincere thanks to maintainers for the two wonderful open source project cortex and Loki. 

Wondering since they do share some common components, it might make sense to pass a global argument like ManagedService = 'Cortex,Loki' which allows to run shared components to manage stuff for both cortex and Loki.

For eg. 
A single instance of `TableManager` can manage DynamoDB tables for both `Cortex` and `Loki`. 

I believe one of the bigger roadblock is that if we do this it will increase the cohesion/interdependecy of these two projects. But In longer run I can see these tool suites being combined as a single solution. 

Opening this to list down the components which can be shared. 
```
- table-manager
- consul [possible as of now]
- memcached [possible as of now]
- memcached-index-queries
- memcached-index-writes
- ingester
- gateway
```
And the one which can't
```
- distributor
- querier
```

Feel free to correct the list as its my initial guess. I have used only Loki as of now but looking forward to use cortex as well very soon.

**Comment by gouthamve** [comment]
I don't think this is something we want to pursue within in cortex. Both cortex and loki are large enough beasts that they best require their own resources.
