### ISSUE TITLE
Come up with a better scheme for dealing with consul outages

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#157]
We should be able to operate if consul goes away.  This probably means heartbeating the ingesters ourselves, or something like that.

**Comment by bboreham** [comment]
I was thinking about this - in a Kubernetes install we could just store the ring as an object in the api-server, and forget Consul.

**Comment by bboreham** [comment]
I imagine the benefit of Consul (or equivalent) is that all callers have a consistent view of the world.  If callers have an inconsistent view then queries can go to ingesters that don't have all the samples.

So what does "heartbeating the ingesters ourselves" mean? "Use a last-known-consistent copy of the ring, and check heartbeats from ingesters are still consistent with that" ?

**Comment by bboreham** [comment]
OK, so "Use a last-known-consistent copy of the ring, make heartbeat calls directly to ingesters in that ring"?

**Comment by rverma-nikiai** [comment]
+1 for kubernetes crd

**Comment by gouthamve** [comment]
One solution: We have healthcheck / heartbeats in the distributors to the ingesters. if consul is down, use the healthcheck info to coast until it is back up.

**Comment by friedrichg** [comment]
With memberlist and dynamodb we can close this as done. No longer needed to run single consul.
