### ISSUE TITLE
Running out of disk space on cassandra because of snapshots being kept

### ISSUE THREAD

**Issue by fcastello** [cortexproject/cortex#1588]
I am running cortex with a cassandra index and chunkstore I almost blew up on disk space because while tablemanager is deleting the tables the data is still there. 
I know this is not directly related to cortex and more related to cassandra administration, but can there be a way to have that cleaned up from cortex, even if there is not implemented yet I might give a shot to do it right from cortex if that is something that would be useful.

Cassandra by default has `auto_snapshot: true` which in case of destructive queries like DROP or TRUNCATE it creates a snapshot of the data. It is not recommended to disable this on cassandra administration.
However, it would be nice to have some flag to pass to table manager to automatically clean up snapshots when the retention period has passed for those tables. So far I have searched and couldn't find how to do this over CQL. There is a cassandra tool that can do it but not over CQL. The cassandra tool is by running `nodetool clearsnapshots cortex` however if it's not possible to do it from cql I might end up have some kind of cron job to clean up cassandra.

**Comment by gouthamve** [comment]
I would say this is out of scope for cortex and is more about how cassandra works and is operated. Don't also see a clean way of doing it via cortex. Closing.

**Comment by loguido** [comment]
I also think this shoul be managed in someway from cortex to avoid custom manual activities in backend

**Comment by pracucci** [comment]
I personally believe this is out of the scope of Cortex and should belong to Cassandra administration.

**Comment by jtlisi** [comment]
I'm also of the opinion this is out of scope for Cortex
