### ISSUE TITLE
Ruler Notifier and Alertmanager use different API versions

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#1604]
The alertmanager and ruler notifiers are currently using two separate API versions. 

Between https://github.com/cortexproject/cortex/blob/f69327c1c1f062b803727ac14f74c0a2c71bf75c/pkg/alertmanager/alertmanager.go#L134
and
https://github.com/cortexproject/cortex/blob/f69327c1c1f062b803727ac14f74c0a2c71bf75c/pkg/ruler/notifier.go#L120

We need to align these two configs if the ruler/alertmanager are going to work correctly. I'm not sure if this is related to #1592, the alertmanager will still work with the ruler, if the ruler is running a pre #1510 image.

#1597 Will fix this issue if the change I requested is added.

**Comment by bboreham** [comment]
Yes, this is the cause of the "no alerts" part of #1592 .

However just changing the API from v1 to v2 is likely to cause disruption as people upgrade.  It's difficult to synchronise the upgrades of ruler and alertmanager.

**Comment by jtlisi** [comment]
I think the ruler should have the option to send to either. We can put V1 behind a flag

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
