### ISSUE TITLE
Tablemanager sleep at startup could confuse new adopters

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1618]
The sleep at startup added in #1587 will mean that people who download Cortex, fire it up on default settings and do a query within the first two minutes could get an error message that the table doesn't exist.

I guess this is a bit of a rare scenario, but it might be better to do an initial sync then sleep to space out subsequent cycles.

**Comment by tcl00taco** [comment]
Anyone working on this one? If not, I can have a go with this one!

**Comment by bboreham** [comment]
I don’t think anyone has started - feel free!

**Comment by tcl00taco** [comment]
@bboreham Great! I am on to it.
