### ISSUE TITLE
query frontend doesn't stop cache on exit

### ISSUE THREAD

**Issue by dmitsh** [cortexproject/cortex#1629]
When the query frontend exits, it does not invoke `Stop` method of `Cache` interface.

**Comment by bboreham** [comment]
What are the bad consequences of this?

**Comment by dmitsh** [comment]
> What are the bad consequences of this?
In case of memcached, we will have `updateLoop` go-routine running indefinitely.
In case of Redis (#1612) we won't properly clean up and close connection pool.

**Comment by bboreham** [comment]
You’re saying the updateLoop continues running past the process’ decision to exit?

**Comment by dmitsh** [comment]
> You’re saying the updateLoop continues running past the process’ decision to exit?

No, when a process exits, obviously all running go-routines belonging to that process are terminated.
What I'm saying is that `Stop` method `Cache` interface is never called, despite being declared.
We might meed to gracefully stop the cache before exiting.

**Comment by bboreham** [comment]
Ok, I like to be precise. 
So the issue is that there are no bad consequences but there might be, under some different circumstances in future?

**Comment by dmitsh** [comment]
You are correct. There are no immediate consequences. There is a bug in `memcached_client.go`, which I submitted PR #1610 for, but since `Stop` is never called, this bug hasn't been exposed.

I've been working on adding Redis cache support (PR #1612), and for that case calling `Stop` would be desirable, as it would properly dispose connection pool.

**Comment by bboreham** [comment]
>  it would properly dispose connection pool

What is the value of this when the program is exiting?

**Comment by jtlisi** [comment]
If the `Stop` function in the cache interface is never called and there are currently no consequences, that sounds s like a good reason to remove the `Stop` function from the interface.
