### ISSUE TITLE
Cassandra issue unconfigured table cortex_weekly_2591

### ISSUE THREAD

**Issue by modogo2000** [cortexproject/cortex#1646]
Hello,

I'm using Cassandra for storage I can't make any grafana dasboard because of this error : 
Cassandra issue unconfigured table cortex_weekly_2591

This is my dealaration on my table-manager : 

- -cassandra.addresses=cassandra.cortex.svc.cluster.local
        - -cassandra.keyspace=cortex
        - -cassandra.timeout=1000ms
        - -cassandra.replication-factor=2
        - -chunk.storage-client=cassandra
        - -dynamodb.chunk-table.period=168h0m0s
        - -dynamodb.chunk-table.prefix=cortex_chunks_
        - -dynamodb.periodic-table.prefix=cortex_weekly_
        - -dynamodb.periodic-table.from=2017-01-06
        - -dynamodb.daily-buckets-from=2017-01-10
        - -dynamodb.base64-buckets-from=2017-01-17
        - -dynamodb.v4-schema-from=2017-02-05
        - -dynamodb.v5-schema-from=2017-02-22
        - -dynamodb.v6-schema-from=2017-03-19
        - -dynamodb.chunk-table.from=2017-04-17

I don't find  what's wrong

**Comment by shancang** [comment]
table-manager running ？

**Comment by modogo2000** [comment]
Yes table-manager is running the issue is fixed

**Comment by gouthamve** [comment]
Closing as issue is fixed
