### ISSUE TITLE
Static File Backend for Alertmanager and Ruler

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#1647]
Ideally both the alertmanager& ruler could utilize static files for user configurations. This would allow new cortex users to start using the project without coupling postgres as a dependency. All that would be required is a filesystem where configs can be stored. All that would need to be provided would be a path to a directory where user configs would exist

Tenants can be separated with a unique naming scheme. Either each tenants configs exists in a directory named after their user id or a prefix naming scheme could be devised.

**Comment by csmarchbanks** [comment]
To be similar with the other storage options for Cortex, would it make more sense to be able to store user configurations in s3/GCS? Perhaps that would be in addition to static files?

**Comment by jtlisi** [comment]
Yes in addition. We have a branch currently running using GCS.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bboreham** [comment]
To clarify, you would have no API in front of this, just leave it up to the admin to modify the files?

**Comment by jtlisi** [comment]
Yes, read only

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pracucci** [comment]
@jtlisi Has #2125 fixed this, or this issue should be kept open?

**Comment by jtlisi** [comment]
#2125 fixed this
