### ISSUE TITLE
enable ha-tracker,ERR

### ISSUE THREAD

**Issue by shancang** [cortexproject/cortex#1652]
my configure
```
        - -consul.hostname=consul:8500
        - -distributor.replication-factor=3
        - -distributor.ha-tracker.enable=true
        - -distributor.ha-tracker.enable-for-all-users=true
        - -distributor.ha-tracker.consul.hostname=consul:8500
        - -distributor.ha-tracker.prefix=ha/
        - -distributor.ha-tracker.store=consul
        - -distributor.ha-tracker.cluster="prometheus"
        - -distributor.ha-tracker.replica="prometheus_replica"
```
distributor log err:
caller=client.go:226 msg="error getting path" prefix=ha/ err=null

use cortex:v0.2.0-rc.0

**Comment by csmarchbanks** [comment]
cc: @cstyan It seems like ha-tracker is not creating the necessary path in consul? I can reproduce with 0.1.0 by changing the ha-tracker.prefix to something that does not exist.

**Comment by cstyan** [comment]
Hmmm, I feel like it did create the path for us. I'll have to check the client library I guess.

**Comment by gouthamve** [comment]
Hrm, interesting. This shouldn't be an error. Just that when we try to watch the path we get an error, but it doesn't break anything and will fix itself once a HA pair sample is seen. That'll create the path.

**Comment by weeco** [comment]
@shancang and @yokiworks maybe you fell for the same: https://github.com/cortexproject/cortex/pull/1687
