### ISSUE TITLE
s3 ceph/radosgw not receiving data chunks

### ISSUE THREAD

**Issue by dgttm** [cortexproject/cortex#1663]
I'm having cortex running in a test installation on k8s, the remote prometheus is sending data via remote_write and I can connect to cortex via grafana, so far so good.

I configured a on-premise ceph/radosgw s3 for the data chunks.
I created a bucket and with s3cmd I am able to access my bucket.

I replaced the s3 line with the following pattern

I configured the s3-urls (ingester, querier, ruler) with the syntax s3://<ACCESSKEY>:</SECRETKEY>@<BUCKETNAME>.<S3URL>  (so as example s3://1234:1234@cortexbucket-1234.s3.mytorage.example/s3

but somehow, there is no data received. I tested the s3 with s3cmd and its working. Any hints how to debug ?

the ingester logs don't show any flush error..

e.g. 

`
level=info ts=2019-09-10T13:31:04.793827958Z caller=cortex.go:198 msg=initialising module=overrides
level=info ts=2019-09-10T13:31:04.793879191Z caller=override.go:53 msg="per-tenant overrides disabled"
level=info ts=2019-09-10T13:31:04.793902009Z caller=cortex.go:198 msg=initialising module=store
level=info ts=2019-09-10T13:31:04.818382251Z caller=cortex.go:198 msg=initialising module=server
level=info ts=2019-09-10T13:31:04.818598607Z caller=server.go:117 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-09-10T13:31:04.81870922Z caller=cortex.go:198 msg=initialising module=ingester
level=info ts=2019-09-10T13:31:04.818982874Z caller=main.go:68 msg="Starting Cortex" version="(version=, branch=, revision=)"
level=info ts=2019-09-10T13:31:04.828712211Z caller=lifecycler.go:387 msg="entry not found in ring, adding with no tokens"
level=info ts=2019-09-10T13:31:34.834698507Z caller=lifecycler.go:317 msg="auto-joining cluster after timeout"
`

any hints how to debug?

thanks in advance.

**Comment by paulcostinean** [comment]
You probably figured out a solution by now, but what worked for me in a similar setup was `s3://<access_key>:<secret_access_key>@your-service.namespace/<bucket-name>` with `-s3.force-path-style=true` set.

**Comment by gouthamve** [comment]
Closing this as I think it should be fixed by now. Please re-open if it's not. Also, note tht flushing won't happen immediately and might take upto 12hrs.
