### ISSUE TITLE
errors in querier: []promql.Point: unsupported value: NaN

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1668]
```
level=error ts=2019-09-16T12:39:17.30841883Z caller=api.go:1110 msg="error marshaling json response" err="v1.response.Data: v1.queryData.Result: promql.Matrix: promql.Series.Points: []promql.Point: unsupported value: NaN"
```

Not sure what causes it but myself and a user on Slack have both encountered this message.

**Comment by bboreham** [comment]
The [Slack message](https://cloud-native.slack.com/archives/CCYDASBLP/p1568321798248300) led to https://github.com/prometheus/client_golang/pull/570, where code was added to `marshalPointJSON()` to allow NaN, but no similar code was added to prometheus/prometheus/web/api/v1/api.go .  

When jsoniter is updated to a version that de-supports NaN, as was done in #1597, we get this error.

**Comment by gouthamve** [comment]
Fixed in https://github.com/prometheus/prometheus/pull/6030 Will vendor in after that is merged.
