### ISSUE TITLE
gauge metric with suffix _total

### ISSUE THREAD

**Issue by yeya24** [cortexproject/cortex#1683]
I am looking through some cortex metrics. I found that some gauge metrics with suffix _total like 
``` Go
	totalConfigs = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: "cortex",
		Name:      "scheduler_configs_total",
		Help:      "How many configs the scheduler knows about.",
	})
	totalRuleGroups = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: "cortex",
		Name:      "scheduler_groups_total",
		Help:      "How many rule groups the scheduler is currently evaluating",
	})
```
Does this break the convention https://prometheus.io/docs/practices/naming/ ? Is it better to change the suffix from _total to _count ?

**Comment by bboreham** [comment]
Yes. It’s generally a pain to rename metrics because it breaks historical reporting but in this case I don’t feel too bad.

**Comment by yeya24** [comment]
If we want to rename them I' d like to open a PR

**Comment by bboreham** [comment]
Please do.
