### ISSUE TITLE
Startup message can have blank version

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1709]
I see this at the top of my logs:

`caller=main.go:68 msg="Starting Cortex" version="(version=, branch=, revision=)"`

I guess something is supposed to put a value into those strings?
Maybe we would consider this approach, new with Go Modules: https://github.com/dlespiau/go-main-module-version

This is running image `cortexproject/cortex:master-de231804` from Dockerhub.

**Comment by ariefrahmansyah** [comment]
Hi, I would like to pick this up. I have two solutions in mind:

### Proposed solution 1: We still use the current approach and fix missing value.

From my understanding, the current code is using Prometheus' common [version](https://github.com/prometheus/common/blob/master/version/info.go) package and we can use `-ldflags` to set these build information value. We can put it on `Makefile` and it will be something like this:

```
VERSION=$(shell cat VERSION)
GIT_REVISION=$(shell git rev-parse HEAD)
GIT_BRANCH=$(shell git rev-parse --abbrev-ref HEAD)

GO_BUILD_FLAGS := -X github.com/cortexproject/cortex/vendor/github.com/prometheus/common/version.Version=${VERSION} \
        -X github.com/cortexproject/cortex/vendor/github.com/prometheus/common/version.Revision=${GIT_REVISION} \
        -X github.com/cortexproject/cortex/vendor/github.com/prometheus/common/version.Branch=${GIT_BRANCH}

GO_FLAGS := -ldflags "${GO_BUILD_FLAGS} -extldflags \"-static\" -s -w" -tags netgo

$(EXES):
	CGO_ENABLED=0 go build $(GO_FLAGS) -o $@ ./$(@D)
	$(NETGO_CHECK)
```

### Proposed solution 2: Read Build Information from inside the code.

We can use your proposed approach here by using:
1. [`ReadBuildInfo`](https://tip.golang.org/pkg/runtime/debug/#ReadBuildInfo) as we can see on https://github.com/dlespiau/go-main-module-version
2. Execute `git` command using `exec.Command()` as we can see on https://github.com/prometheus/promu/blob/master/pkg/repository/info.go

---

Personally, I prefer to use **solution 1**. Even though Prometheus' common package is made to be shared across Prometheus components and libraries, the `version` package itself is generic enough to be used by other projects. Another benefit is we don't need to modify any Cortex Golang code.

**Comment by bboreham** [comment]
Please go ahead, @ariefrahmansyah 

We have a script https://github.com/cortexproject/cortex/blob/master/tools/image-tag which adds a `-WIP` suffix when there are local modifications to the git tree - that can be useful.

Separately, I think the raw `VERSION` file is worse than nothing, since it is wrong on every commit but one per release.

**Comment by bboreham** [comment]
Also it would be good to add the version to metric `cortex_build_info`
