### ISSUE TITLE
Debugger crash on macOS/dlv

### ISSUE THREAD

**Issue by cyriltovena** [cortexproject/cortex#1712]
This line : 

https://github.com/cortexproject/cortex/blob/bf9aa2e8b9d2b5425cc09b4dc51d7af7bd518881/pkg/chunk/series_store.go#L305

Creates a panic which seems to be recovered when running without debugging.

The panic happen when the matcher (*labels.Matcher) is nil. Opentracing is trying to call the stringer on it.

Which leads to here:

https://github.com/prometheus/prometheus/blob/53ea6d63901b96a13bb79ff598c96af4a979adce/pkg/labels/matcher.go#L71-L73

Obviously the pointer is nil so this raises a panic.

While this is working fine because the fmt package catch the panic:

https://github.com/golang/go/blob/64785bf96c5942e5e2a3d326b48eae4e7b189e03/src/fmt/print.go#L629-L630

On my machine I can't debug it.

How could we approach this issue ? There is multiple place where we could add a fix, in prometheus Stringer we could take care of nil value. In the series store we could have a if nil and swap the value with an empty string.

**Comment by bboreham** [comment]
In what sense is this a "crash"?  It sounds like your main problem is your debugger is over-sensitive.  And perhaps a performance issue.

I would fix it in OpenTracing.

**Comment by cyriltovena** [comment]
The debugger exit as soon as this code is reached

**Comment by cyriltovena** [comment]
related to https://github.com/go-delve/delve/issues/852 . Unfortunately there is no fix.

**Comment by cyriltovena** [comment]
I just need to update open tracing now.
