### ISSUE TITLE
Use gossiping to distribute ring information

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#1721]
Instead of using Consul or Etcd, use gossiping to distribute ring information between all the members. This has some benefits (eg. availability) but also introduces new problems.

Document describing my implementation is available at: https://docs.google.com/document/d/1UfGZDYSuk-p0_W3Yl4NA2vKfah88r5u2v_ECvUJj9Ng/edit?usp=sharing

Implementation lives in  https://github.com/pstibrany/cortex/tree/gossip-ring2, and small change to Loki is at https://github.com/pstibrany/loki/tree/gossip-ring2. I try to keep the document up-to-date wrt implementation.

Implementation is working and covers edge cases I was able to find during my testing. At this moment, it is still missing metrics, and there is no clear upgrade path yet.

**Comment by gouthamve** [comment]
This is now closed in #1727
