### ISSUE TITLE
Ruler doesn't take account of delays in incoming data

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1723]
With the move to WAL-watching, it became possible for a sending Prometheus to get several minutes behind then catch up.  However ruler always runs its queries as-of "now" so you get a gap and/or corrupted results until the sender catches up.

Conceptually, Ruler should fire each time a set of samples is available, as-of that time.  However I believe Prometheus remote write code doesn't attempt to send breadth-first so that won't be easy.

**Comment by jtlisi** [comment]
This will be a difficult problem to solve since it involves differentiating when a gap is temporary or completely shutdown. The upstream prometheus implementation has support for restoring state for alerts, but nothing of the sort exists for recording rules.

**Comment by gouthamve** [comment]
I think the simplest fix for this is to delay the execution by an interval (a minute or two). If your data is delayed more than that, there is nothing we can do.
