### ISSUE TITLE
Add ability to drop cluster label after dedupe

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1724]
A couple of users have asked for this; as we need a cluster label for deduping in the distributors, some people don't have this and adding it will break their graphs.

By "break their graphs", they will cause things like discontinuations in things like recording rules, which for LTS systems is undesirable.

@cstyan is this something we can make an option?

**Comment by bboreham** [comment]
> we need a cluster label for deduping in the distributors

why is this?

**Comment by cstyan** [comment]
The `cluster` label is used to differentiate between HA Prometheus "pairs", the `__replica__` label identifies each replica in the pair.

**Comment by nbellowe** [comment]
This is a similar ask to https://github.com/cortexproject/cortex/issues/1736

Any status updates?

**Comment by cstyan** [comment]
There's a PR open: https://github.com/cortexproject/cortex/pull/1726
