### ISSUE TITLE
Ingester not leaving Ring properly with replication_factor=1

### ISSUE THREAD

**Issue by mizeng** [cortexproject/cortex#1732]
In kubernetes world, if I delete one Ingester pod, the new one will join the Cortex ring, however the old one still exists in the ring with status "unhealthy". This will cause 500 error in Distributor for unhealthy ingester.

Details can be found in https://github.com/grafana/loki/issues/1159

Is it as expected that when replication_factor=1, user have to manually click "forget" in Cortex Ring UI?

**Comment by bboreham** [comment]
This document describes what is supposed to happen: https://github.com/cortexproject/cortex/blob/master/docs/ingester-handover.md

Maybe the new one was not ready in time, or you did not allow enough time for hand-over?

**Comment by mizeng** [comment]
The new one is ready in seconds by my observation. I just think the logic of removeStaleClient is not proper for replication_factor=1. Say I have 6 ingesters, if I replace 1, there'll be always 7 ingesters at first with 1 unhealthy which is reasonable. Then Cortex try to delete the unhealthy one to keep the number go down to 6, but the check in ring.GetAll will always fail in this scenario.

**Comment by jtlisi** [comment]
@mizeng Currently the ruler runs using the ring with a replication factor of 1. I have not observed this issue. Generally if an ingester is exiting but not clearing the ring it's because it terminated incorrectly.

Looks like the issue was resolved [here](https://github.com/grafana/loki/issues/1159#issuecomment-543137516).

**Comment by mizeng** [comment]
@jtlisi  Ye, thanks. Just find my issue is due to some lack of config settings which is not well-documented for production use-case.

**Comment by mizeng** [comment]
Seems solved this issue, and updated in the linked Loki Issue. Close this one for now.

**Comment by bboreham** [comment]
I remember thinking that the default of 0s is wrong, but can’t find an issue about it. 

The documentation is indeed a bit oblique.

**Comment by drequena** [comment]
@mizeng , I'm facing the exactly same error. What parameter did you configure in order to stop that problem? :) 
Best Regards.
