### ISSUE TITLE
HA dedupe should not require a "cluster" label

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1736]
I'm told the purpose of the cluster label is to allow differentiatiation between multiple Prometheus HA pairs in a tenant. Its name is set via `-distributor.ha-tracker.cluster`.

Cortex should support the scenario where there is only one HA pair in a tenant, by making the cluster label optional.

**Comment by cstyan** [comment]
@bboreham can you clarify the meaning of tenant here? Is it for a given user ID, or for one of those user ID's environments in their own networks. Such as a given k8s cluster or cloud region. 

From how I'm reading it, the cluster label is still a requirement to differentiate between different HA pairs.

If you mean only a single HA pair for a user ID then I'd argue that we shouldn't support not requiring a cluster label as it's likely they will at some point have multiple HA pairs and if they didn't then remember to add a cluster label deduping would then stop working.

**Comment by bboreham** [comment]
Yes, what the code calls “user”, but sometimes “org”. Cortex is “multi-tenant”. 

I’d argue that a significant percentage of users will never use multi-HA, and it’s no great problem to add the label for those that evolve in the way you describe.

**Comment by weeco** [comment]
I agree with Bryan, if you make it optional and set the default to let's say "unnamed" you could still add additional pairs. 

We have ~20 tenants and we only use one HA pair in each of these. It's not a big deal to set it to something static though.

**Comment by cstyan** [comment]
Sorry I’m not sure I understand. You have one HA pair total, or one per
cluster?

**Comment by weeco** [comment]
We have one HA Pair (prometheus-1, prometheus-2) in each (kubernetes) cluster.

**Comment by cstyan** [comment]
Right okay, that's the exact situation where the `cluster` label is required...

**Comment by weeco** [comment]
Right now yes, that's the issue all about I think. Just as Bryan said, there will be users like me who have exactly one Prometheus pair for each x-scope-orgid. We do set the cluster label to the same label for all pairs which is fine because there is always just one pair in each tenant.

**Comment by pracucci** [comment]
> Cortex should support the scenario where there is only one HA pair in a tenant, by making the cluster label optional.

I do understand the use case but, given the minimum extra effort to also set the `cluster` label, I'm wondering if it's worth making it optional.

I'm thinking about cases where a tenant just have 1 HA pair (and thus technically wouldn't need the `cluster` label), then after some time setup another HA pair (I bet copy-pasting the config already in use) and forget that now the `cluster` label is required on both HA pairs.


_I'm following up this conversation to understand what we should do with https://github.com/cortexproject/cortex/pull/1737 (either reiterate on it or close it)_

**Comment by cstyan** [comment]
> I'm thinking about cases where a tenant just have 1 HA pair (and thus technically wouldn't need the `cluster` label), then after some time setup another HA pair (I bet copy-pasting the config already in use) and forget that now the `cluster` label is required on both HA pairs, spending extra time debugging it.

This was my point against making the cluster label optional as well.

**Comment by jtlisi** [comment]
Would a middle ground be adding a default cluster label for anything that does not include one?

**Comment by pracucci** [comment]
> Would a good middle ground be adding a default cluster label for anything that does not include one?

Isn't risky? If the user has multiple HA pairs and erroneously forget to set the cluster label, it would take time to find the mistake because the deduplication will work but not in the expected way.
