### ISSUE TITLE
Rate limit Chunk & Index writes to Bigtable

### ISSUE THREAD

**Issue by weeco** [cortexproject/cortex#1739]
As far as I know there's currently no way to rate limit the write requests from Cortex -> BigTable.

We currently use a single dev node which can run handle up to 25k writes / sec. After a rolling update the ingesters try to flush lots of serieses to BigTable. In my case this takes approx 1 hour. The ingesters do that without any rate limits, which quickly results in a very busy Cortex. During that time my read requests mostly fail because BigTable is so saturated. Even with bigger clusters I can see this happening for some time.

Therefore I propose an option to rate limit the writes, to ensure BigTable is not overstrained handling the read requests at the same time.

_For reference, here's Bryan's comment from Slack:_

```
Bryan Boreham 8:26 PM
I don't think that's in the code at the moment.  The DynamoDB client has a rate-limiter, based on throttling responses that come back from DynamoDB.
I think it would be quite simple to put a golang.org/x/time/rate.Limiter on the write calls.
```

**Comment by tcl00taco** [comment]
@weeco If anyone is not working on this one, I will tackle this.

**Comment by weeco** [comment]
@tcl00taco I am not aware of anyone working on this, feel free to go ahead with this.

**Comment by VineethReddy02** [comment]
I can work on this. If no one else is already on this.

**Comment by weeco** [comment]
I think there already is a PR: https://github.com/cortexproject/cortex/pull/1914

**Comment by pracucci** [comment]
_There's still a PR #1914 open but the PR looks stale too.
