### ISSUE TITLE
Trying to pull the images 

### ISSUE THREAD

**Issue by gunjan-DP** [cortexproject/cortex#1741]
Getting an error while pulling an image from " image: quay.io/cortexproject/cortex " in Kubernetes. I am using the same k8s to launch the pods and deployment.

**Comment by bboreham** [comment]
See https://github.com/cortexproject/cortex/pull/1674#issuecomment-532584306

**Comment by gouthamve** [comment]
Dupe of https://github.com/cortexproject/cortex/issues/1805
