### ISSUE TITLE
Standardise cache/memcache metrics

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#1745]
Right now, our [`instrumentedCache`](https://github.com/cortexproject/cortex/blob/5f3904892bc37ac682ac0fb323de89ea4d31678f/pkg/chunk/cache/instrumented.go) has some deficiencies:

1. ~The `cortex_cache_request_duration_seconds` histogram doesn't have the `name` label attached making it effectively useless.~
2. It cannot track errors as we decided not to return them. This means we'll need each cache to export its own metrics about the error lookups. 

And then we have the case where the memcache client exports its own metrics, https://github.com/cortexproject/cortex/blob/master/pkg/chunk/cache/memcached.go#L22-L28

I think we should be consistent across all caches, and fix the issues with the instrumented cache. And remove the memcache specific metric.

**Comment by adnxn** [comment]
id like to pick this up

**Comment by gouthamve** [comment]
Also add metrics about the size of the cached objects, see https://github.com/cortexproject/cortex/issues/1058

**Comment by pstibrany** [comment]
Still an issue, any takers? (Good first issue)

**Comment by adnxn** [comment]
ill take a look

**Comment by aknuds1** [comment]
I might look into this, in order to learn a bit about Cortex :)

**Comment by aknuds1** [comment]
@gouthamve could you help me get started on this one, f.ex. tomorrow? :)

**Comment by gouthamve** [comment]
> The `cortex_cache_request_duration_seconds` histogram doesn't have the name label attached making it effectively useless
This is no longer true. We added a `name` label later.

> It cannot track errors as we decided not to return them. This means we'll need each cache to export its own metrics about the error lookups.

memcache does this: https://github.com/cortexproject/cortex/blob/master/pkg/chunk/cache/memcached.go#L149-L166

We need to copy it over to Redis here: https://github.com/cortexproject/cortex/blob/3fedc1108a49e88274c4b7a7c5b18b573fe51553/pkg/chunk/cache/redis_cache.go#L35

**Comment by aknuds1** [comment]
Thanks @gouthamve, will try!

**Comment by gouthamve** [comment]
Given we have this an instrumenting wrapper now: https://github.com/cortexproject/cortex/blob/fdb1106d951d7b85c3a6cb9db7824b55d47fcc27/pkg/chunk/cache/instrumented.go#L14

I think we can close this issue after #3976
