### ISSUE TITLE
Enable querier.ingester-streaming by default

### ISSUE THREAD

**Issue by paulcostinean** [cortexproject/cortex#1753]
From my (limited) experience with cortex, it looks like queries with large enough results will fail to return with an error from the grpc client, unless streaming rpc is enabled.
```
 grpc: trying to send message larger than max
```
The maximum grpc message size is ~4MB.

**Comment by bboreham** [comment]
Do note #1195 should be investigated / fixed before we do this.

**Comment by bboreham** [comment]
Closed by #2344 (though #1195 is still a big efficiency hit)
