### ISSUE TITLE
Exclude specific metric serieses from limits

### ISSUE THREAD

**Issue by weeco** [cortexproject/cortex#1758]
**The problem**

The per-metric-serieses limit is great to identify metrics with high cardinality labels. Most services  which return more than 10k metric serieses of a single metric are indeed problematic because they put full HTTP URLs, IDs or similiar highly dynamic values into their labels.

However in our case (and I believe that's common for others too) there are prometheus exporters (e. g. the node exporter) which report stuff like `container_cpu_usage_seconds`. Depending on the number of containers you run in a cluster, this can quickly become a metric with thousands of metric-serieses. I had to bump the `per-metric-serieses-limit` to 70k for all metrics coming from that tenant, even though only 2 metrics actually exceed this limit. Because of this we'll probably miss many of the other microservices which expose too many metric-serieses.

**My idea to solve this**

1) We could either add an override for specific metrics (similiar as we do offer overrides per tenant), so that we can set a different per-metric-serieses limit for one or more metrics.

2) (this could also be part of solution 1) Optionally I could also imagine offering a possibility to completely exclude metrics from this validation.

**Comment by pstibrany** [comment]
Ideally we would like to be able to specify metric -> limit mapping in the overrides file. Goutham claims it's easy to implement (when using the blocks engine). May be a good first issue.

**Comment by friedrichg** [comment]
Fixed by https://github.com/cortexproject/cortex/pull/4302
