### ISSUE TITLE
Metric cortex_ingester_chunks_stored_total ignores chunk write deduping

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1781]
Metric `cortex_ingester_chunks_stored_total`, which counts chunks stored per user, is [incremented for every chunk sent to the store](https://github.com/cortexproject/cortex/blob/3c6875dd433a34faaed604cca6b73ac5b63faea8/pkg/ingester/flush.go#L402), regardless of whether it was already stored by another ingester and hence [skipped](https://github.com/cortexproject/cortex/blob/3c6875dd433a34faaed604cca6b73ac5b63faea8/pkg/chunk/series_store.go#L464).

This means we are not getting a true readout of the impact of each user on resource utilisation.

Similarly `cortex_ingester_chunk_stored_bytes_total`

**Comment by pstibrany** [comment]
Fixed by #2463.
