### ISSUE TITLE
Create administrator account failed

### ISSUE THREAD

**Issue by Tukali** [cortexproject/cortex#1785]
![image](https://user-images.githubusercontent.com/45891208/68181690-355d4c80-ffd3-11e9-93d3-5c90aba46877.png)
like it 

When i first install it ,after I enter the required account password,clicking the Create button below does not respond, and the page does not jump

**Comment by Tukali** [comment]
> ![image](https://user-images.githubusercontent.com/45891208/68181690-355d4c80-ffd3-11e9-93d3-5c90aba46877.png)
> like it
> 
> When i first install it ,after I enter the required account password,clicking the Create button below does not respond, and the page does not jump

**Comment by CSchathuranga** [comment]
this also happens to me.
How to solve this?
