### ISSUE TITLE
Add support for iam roles for service accounts in AWS 

### ISSUE THREAD

**Issue by adamjohnson01** [cortexproject/cortex#1797]
Due to this [issue](https://github.com/aws/aws-sdk-go/issues/2828) in the aws sdk, it is not possible to authenticate using iam roles for service accounts in AWS EKS.

This is because session.New is being used.

https://github.com/cortexproject/cortex/blob/4a7f5b05f9cfd819d22522cfbc749dbe9bb6d9cf/pkg/chunk/aws/s3_storage_client.go#L54

session.New is deprecated and requires the AWS_SDK_LOAD_CONFIG environment variable to be set in order to automatically call AssumeRoleWithWebIdentity.

I propose updating to use session.NewSession instead. I am happy to contribute this change.

**Comment by bboreham** [comment]
Thanks for pointing this out.  Please go ahead and make a PR if you are able. 
Do we need to change this too?

https://github.com/cortexproject/cortex/blob/4a7f5b05f9cfd819d22522cfbc749dbe9bb6d9cf/pkg/chunk/aws/dynamodb_storage_client.go#L847

**Comment by adamjohnson01** [comment]
Yes, that need to change as well.
