### ISSUE TITLE
Dedicated Twitter account

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#1804]
Have you ever considered opening a dedicated Twitter account for the Cortex project, managed by maintainers, used to publish news about Cortex?

**Comment by bboreham** [comment]
Good idea!
I see ‘cortexproject’ is taken, but with 0 followers they might give it to us. 
Other names we might use? 
‘cortexmetrics’ is open.

**Comment by pracucci** [comment]
May be difficult to reach out to `@cortexproject` owner: the linked website is not even available and last tweet is years ago.

`@cortexmetrics` (or `@CortexMetrics` like Thanks) may be a good alternative.

**Comment by codesome** [comment]
If we plan to have a dedicated website too, then we can keep the twitter handle and the website domain name in sync.

**Comment by pracucci** [comment]
Good point @codesome! I do agree that even if we don't plan to build a website immediately, we should secure the domain anyway. Following the "cortex metrics" idea, `cortexmetrics dot io` would be available.

**Comment by tomwilkie** [comment]
Discussed on call and @cortexmetrics and cortexmetrics.io registered.

@cyriltovena wanna setup a github pages site?

**Comment by pracucci** [comment]
> @cyriltovena wanna setup a github pages site?

@cyriltovena Since there are several cross-contributors between Cortex and Loki, may be a wise decision to use the same tooling both for the Cortex website and the Loki one.

**Comment by cyriltovena** [comment]
Just read this, do you want to to add https://github.com/cortexproject/cortex/pull/1851 to github pages ? if yes under which repository ? To setup automatic deployment on master, I might need some credentials for this new repository.
