### ISSUE TITLE
Kuberenetes Deployment fails with image not found ( Latest tag missing on registry)

### ISSUE THREAD

**Issue by anoopl** [cortexproject/cortex#1805]
I am trying to install Cortex with Kubernetes manifest files from the k8s directory in the Github repo. Most of the component fails with Error: ImagePullBackOff. Error:

``` 
Failed to pull image "quay.io/cortexproject/cortex": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/cortexproject/cortex:latest not found

```

Checked the Image repo https://quay.io/repository/cortexproject/cortex?tag=latest&tab=tags
I could not find the tag "latest"

**Comment by pracucci** [comment]
Thanks @anoopl for the report. Should be resolved once the PR https://github.com/cortexproject/cortex/pull/1674 would get finalized and merged.

Until then, I would suggest you to edit the manifests and use the `v0.3.0` tag (ie. `quay.io/cortexproject/cortex:v0.3.0`).

**Comment by pstibrany** [comment]
Example config was fixed to use release versions.
