### ISSUE TITLE
client.FromLabelAdaptersToLabels breaks contract of `labels.Labels`

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#1813]
https://github.com/cortexproject/cortex/blob/fab5ced5e3c071a930966781b6eb786d8d34cc83/pkg/ingester/client/compat.go#L193

`labels.Labels` is supposed to be sorted set of labels. Conversion from `[]LabelAdapter` is unsafe unless order is checked first.

**Comment by bboreham** [comment]
There's various other ways to resolve this - could comment that it doesn't check that contact, or comment that it must only be called with sorted `LabelAdapter`.

Could you say a bit about where this caused a problem?

**Comment by pstibrany** [comment]
Yes, documenting break of contract or required preconditions is one way of fixing it.

I'm not sure if it is a problem in Cortex (on quick check, it doesn't seem to be), but I've found several unsafe usages in Loki.

**Comment by pstibrany** [comment]
Same problem in https://github.com/cortexproject/cortex/blob/5bd771feec6d0e775001c3a6dac101811fa192fe/pkg/storage/tsdb/labels.go#L14 (with slightly different types) (@pracucci)

**Comment by pracucci** [comment]
> Same problem in
> https://github.com/cortexproject/cortex/blob/5bd771feec6d0e775001c3a6dac101811fa192fe/pkg/storage/tsdb/labels.go#L14
> 
> (with slightly different types) (@pracucci)

@pstibrany May you elaborate a bit more on the issue, please? `labels.Labels` is `[]Label` and the `tsdb.FromLabelAdaptersToLabels()` iterates over the input list of `LabelAdapter` keeping the same ordering in the output list of `Labels` so, as far as the input is correctly sorted, the output is as well. What am I missing?

**Comment by pstibrany** [comment]
> as far as the input is correctly sorted, the output is as well.

This is exactly the problem. `labels.Labels` is documented as: "Labels is a sorted set of labels.", and there may be code relying on this property. However, `FromLabelAdaptersToLabels` doesn't check for it, and will happily generate unsorted `labels.Labels` instance, thus breaking its contract.

**Comment by pstibrany** [comment]
There is now a comment on the function warning about this behavior.
