### ISSUE TITLE
Same series may end up in chunks using different fingerprint names

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#1820]
Chunk IDs [contain fingerprint](https://github.com/cortexproject/cortex/blob/ccefdef404a76f54e9856dbdc2707ea3f68f854b/pkg/chunk/chunk.go#L171) of the series. However, due to fingerprint remapping that happens because of fingerprint collisions, same series written by different ingesters may end up in chunks with different fingerprint in the IDs. Spotted by @sandlis, in Loki we fix this in https://github.com/grafana/loki/pull/1247. I can fix it in Cortex too, if we think it's a problem worth fixing.

**Comment by bboreham** [comment]
This is kind-of opposite to #717 

Cortex already dedupes individual metrics, and the series index is based off the sha of the labels, so can you say a bit more about what more needs to be done (without me having to read a 1600-line PR)?

**Comment by pstibrany** [comment]
If Cortex doesn't use fingerprints from Chunk IDs, then this fix isn't necessary. (That would be `Fingerprint` field in `chunk.Chunk` struct)

That linked Loki PR primarily fixes problem with hash collisions, which Loki didn't deal with before (unlike Cortex). Once we started using remapped fingerprints to handle collisions, we also started to write those remapped fingerprints into Chunk IDs. I was told that Loki uses fingerprints from Chunk IDs, so we now make sure to use original (not remapped) fingerprint into Chunk ID.

From #717 (which I actually have on my TODO list to look at and possibly fix):

> The chunk store fetch code assumes that fingerprints uniquely identify a timeseries; this is fairly likely when they are looking at a single metric, but we still could get clashes.

This assumption is wrong. (But this issue is about opposite implication: different fingerprints => different series, which is also wrong.)

**Comment by pstibrany** [comment]
> If Cortex doesn't use fingerprints from Chunk IDs, then this fix isn't necessary. (That would be `Fingerprint` field in `chunk.Chunk` struct)

I can see one such usage at https://github.com/cortexproject/cortex/blob/77a09cc7c953ce5bc4938f042ccb588503ce8eb5/pkg/chunk/series_store.go#L239, where fingerprints are used to detect duplicate chunks.

**Comment by bboreham** [comment]
Is the problem that you can make a query like `up` and receive a matrix with two rows for the same series (name + labels)?
It would be good to create a unit test, or even an integration test, that showed the problem.

**Comment by pstibrany** [comment]
Thinking about it bit more, using the fix from Loki, we may actually drop valid data, as we already know that we have different series using the same fingerprint, so we don't want to deduplicate based on fingerprint only.

Fixing #717 would probably avoid this concern completely.

**Comment by sandlis** [comment]
I didn't know Cortex already handled fingerprint remapping. The problem that I imagine can happen with remapping fingerprint is when series are being replicated, different ingesters could refer same series with different fingerprints(since its not necessary all ingesters would see same fingerprint collisions) and in turn flush chunks with different IDs with same data.

Also the way collisions are handled in Cortex can make different series share the same fingerprint since colliding fingerprints are remapped to have a fingerprint from reserved range i.e 1 to 1<<20.
This makes fingerprints unreliable and I can't imagine what use-case they would have.

Should we consider dropping fingerprints and using seriesID(which is sha256 of labels) everywhere for sake of uniquely identifying series?

**Comment by sandlis** [comment]
Looking at the usages of chunk.Fingerprint, I see a problem only in https://github.com/cortexproject/cortex/blob/a3eaf067f449e96f2590709a834cc175504b7198/pkg/chunk/chunk_store_utils.go#L63-L65 which is used in [store.LabelNamesForMetricName](https://github.com/cortexproject/cortex/blob/a3eaf067f449e96f2590709a834cc175504b7198/pkg/chunk/series_store.go#L235)
Someone could do the same not knowing how reliable `chunk.Fingerprint` is.
