### ISSUE TITLE
TSDB support for limits

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1823]
We need to be able to limit number of active series etc.

**Comment by thorfour** [comment]
Current design proposal. https://docs.google.com/document/d/18WJgjhBWhHqTmRPGmdG0IMfuD5qah0UAe9955gsTHwY/edit?usp=sharing

Kind of stuck on invalidating the head block limits

**Comment by codesome** [comment]
^ still relevant. @pracucci: can we add `keepalive` to this?

**Comment by pracucci** [comment]
Closed by https://github.com/cortexproject/cortex/pull/2676.
