### ISSUE TITLE
Migrate storage from chunks to TSDB

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#1827]
Having introduced TSDB support to Cortex (still experimental), we should design and build a migration path from chunks to TSDB.

**Comment by shelby-moore** [comment]
Hey! I'm curious when you think this work will be tackled? Will it be once the TSDB support has been moved out of the experimental phase?

**Comment by pracucci** [comment]
> Will it be once the TSDB support has been moved out of the experimental phase?

Not necessarily. We've started brainstorming on it, but no real work has been done yet. The migration path from chunks to blocks storage involve two distinct tasks:
1. Add queriers the capability to read from the chunks long term storage before a specific timestamp and blocks storage after that
2. A (standalone) migration tool to create and upload blocks with series read from the chunks storage

If you're interested into working on this, I may offer some guidance and we may work together on a design document to start.

**Comment by bboreham** [comment]
@pracucci I believe you said at the community meeting this is now under test; could you update here?

**Comment by pracucci** [comment]
The proposal described at https://cortexmetrics.io/docs/proposals/ingesters-migration/ has been implemented and @pstibrany is testing it. We'll come up with a documentation update once done.

**Comment by pstibrany** [comment]
Guide for migration of live cluster is at https://cortexmetrics.io/docs/blocks-storage/migrate-cortex-cluster-from-chunks-to-blocks/

**Comment by pstibrany** [comment]
Blocks convert set of tools (with no documentation yet): https://github.com/cortexproject/cortex/pull/3092

**Comment by pracucci** [comment]
I think we can consider this done. We've both provided a documentation to migrate a live cluster and a tool to convert the storage from chunks to blocks (it currently supports only BigTable but it can be used as a reference to add support to other chunks index storage backends too).
