### ISSUE TITLE
Ingester flushing should not block on cache issues

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1833]
Ingesters can make two cache calls before each chunk flush - one for index write dedupe and one for chunk write dedupe.

By default these will time out at 100ms, but if the cache is having trouble we don't even want to wait that long - the only penalty of skipping the cache lookup is extra IO, whereas slowing the flush rate to 10/sec will cause a backlog in flushing, eventually OOM of ingesters.
Also every timeout generates a log line, which across 50 goroutines is 5,000 logs/sec with default settings and with default Docker logging that also puts the system under stress.

If we drop the timeout a lot I suspect this will exacerbate the problem seen at #1821.

Also I wonder if this behaviour is related to what #1666 was trying to fix.

Here's the bones of an idea: decouple the two things, so a different set of goroutines attempts to talk to memcached.  The flush code will wait at most 1ms for a response; the memcached side stops even attempting to talk if it sees issues and waits 5-10 seconds to reconnect before resuming.

**Comment by bboreham** [comment]
Interesting to see what difference the circuit-breaker makes. It should stop waiting, but also log even faster.

**Comment by alanprot** [comment]
Chunks storage was removed.
