### ISSUE TITLE
JAEGER_ENDPOINT not supported

### ISSUE THREAD

**Issue by kvaidas** [cortexproject/cortex#1843]
It appears that due to the current way that the dependency (https://github.com/weaveworks/common/blob/master/tracing/tracing.go) works, it's not possible to deliver traces to a Jaeger collector due to the configuration failing if only JAEGER_ENDPOINT is configured.

Maybe it would be useful to just implement the functionality that you get from weaveworks/common instead of depending on it (since that's what is currently breaking this)?

**Comment by bboreham** [comment]
It certainly is possible to deliver traces to a Jaeger collector, since my system does it.
We set `JAEGER_AGENT_HOST`. 

`JAEGER_ENDPOINT` was added after the code was written.  Happy to accept a PR to add this either upstream or in Cortex.

**Comment by kvaidas** [comment]
Did you mean deliver traces to a collector or an agent? Because if you set JAEGER_AGENT_HOST I assume you're sending the trace data to an agent while I was trying to send it to a collector.

**Comment by bboreham** [comment]
You're right, my traces get to the collector via an agent.

**Comment by ethervoid** [comment]
One question, does [this PR](https://github.com/cortexproject/cortex/pull/3682) fix this issue?

**Comment by pracucci** [comment]
> One question, does [this PR](https://github.com/cortexproject/cortex/pull/3682) fix this issue?

I think so. @bboreham could you confirm, please?

**Comment by bboreham** [comment]
I haven't tried it but that was the intention.
Closed by https://github.com/weaveworks/common/pull/204 brought in by #3682
