### ISSUE TITLE
Distributors using too much memory

### ISSUE THREAD

**Issue by ankit1ank** [cortexproject/cortex#1846]
Distributors released in Cortex version 0.3.0 are using too much memory. We have noticed that memory usage just keeps on increasing till the distributor hits the limit and is OOMKilled.

**Comment by pracucci** [comment]
Do you have more details to share, please? Few questions:
1. Which metric are you using to monitor distributor memory usage? RSS (ie. `container_memory_usage_bytes`) or memory used reported by Go (ie. `go_memstats_alloc_bytes`)?
2. Has the distributors memory usage changed to you compared to `0.2.0`, assuming a comparable traffic? Do you have any chart to share it with us, to better understand it?
3. What's the current memory limit of your distributors? Are you using `-mem-ballast-size-bytes` as well?

**Comment by ankit1ank** [comment]
We are using the metric `container_memory_working_set_bytes`. The memory usage in v0.2.0 was very low compared to the memory usage reported in v0.3.0. The following screenshots will show the same.

**Comment by pracucci** [comment]
May you also show us a graph of `go_memstats_alloc_bytes` for the distributor, please?

**Comment by ankit1ank** [comment]
The graph showing `go_memstats_alloc_bytes` for all distributors. This also shows how distributors before and after the v0.3.0 using less memory.
![Screenshot from 2019-11-26 19-11-33](https://user-images.githubusercontent.com/4493180/69638452-ba8ecb00-1080-11ea-962b-561ae0ee92d1.png)
