### ISSUE TITLE
Get an https redirect for cortexmetrics.io

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1850]
So it doesn't say "unsecure" in the browser

**Comment by rfratto** [comment]
https://cortexmetrics.io/ works for me and seems to have a valid certificate, but there doesn't seem to be an HTTPS redirect set up.

**Comment by pstibrany** [comment]
> HTTPS redirect set up.

HTTPS redirects are not safe ;-)

In addition to HTTPS redirect, page should also use Strict-Transport-Security header (HSTS). If we really wanted to fix first-usage problem, we could also register https://cortexmetrics.io to https://hstspreload.org, once HSTS header is fixed.

**Comment by bboreham** [comment]
Thanks!

**Comment by pstibrany** [comment]
Wait, I didn't fix anything. Just quoted Robert's comment.

**Comment by pracucci** [comment]
> HTTPS redirects are not safe

I think you're making it too complicated for an OSS doc website. Anyway, redirect works now, so someone has set it up:

```
$ curl -v http://cortexmetrics.io

< HTTP/1.1 301 Moved Permanently
< Location: https://cortexmetrics.io/
```
