### ISSUE TITLE
Queriers use too much memory

### ISSUE THREAD

**Issue by canghai118** [cortexproject/cortex#1868]
I run querier in kubernetes pod. 
After a few query from grafana dashboard, the querier consume some gigabytes memory, sometimes more than 3GB,  and reach the memory limit.
Is querier caching something that consumes a lot memory or it is a bug ?

**Comment by cyriltovena** [comment]
Possibly if you are using index/result/chunk cache, we can check you config.

However that could be related to fast allocations, what is your type of deployment ?

**Comment by canghai118** [comment]
> Possibly if you are using index/result/chunk cache, we can check you config.
> 
> However that could be related to fast allocations, what is your type of deployment ?

I am pretty sure, I'm not using index/result/chunk cache.

After some investigate, I think it's about golang scavenging.  below is part of the gc log

```bash
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
scvg: 0 MB released
scvg: inuse: 29, idle: 3040, sys: 3070, released: 3017, consumed: 53 (MB)
```
the scavenging is running,  but still have much idle memory that not return to OS.  I seems it never return to OS, even if there is no query any more

**Comment by canghai118** [comment]
according to https://golang.org/pkg/runtime/
> madvdontneed: setting madvdontneed=1 will use MADV_DONTNEED
instead of MADV_FREE on Linux when returning memory to the
kernel. This is less efficient, but causes RSS numbers to drop
more quickly.

set `GODEBUG=madvdontneed=1` environment solve my problem.
