### ISSUE TITLE
Distributor ingestion rate limit exceed

### ISSUE THREAD

**Issue by ksriteja95** [cortexproject/cortex#1870]
I am getting the following error in distributor pod:
level=error ts=2019-12-02T18:31:35.81174598Z caller=http_server.go:45 org_id=0 trace_id=7487fbc67d8ea745 msg="push error" err="rpc error: code = Code(429) desc = ingestion rate limit (25000) exceeded while adding 100 samples

**Comment by canghai118** [comment]
You can set `-distributor.ingestion-rate-limit` higher
https://github.com/cortexproject/cortex/blob/master/docs/arguments.md#ingester-distributor--querier-limits

**Comment by ksriteja95** [comment]
Worked. Thank you
