### ISSUE TITLE
Inconsistent behaviour of `Desc.AddIngester`

### ISSUE THREAD

**Issue by codesome** [cortexproject/cortex#1877]
Before the introduction of normalized tokens, `Desc.AddIngester` used to append tokens to the existing ones. But currently, it works as `append` when it's not normalized tokens and `replace` when it's normalized tokens.

https://github.com/cortexproject/cortex/blob/08ddf88e082352a89a6daa08fad6c7064d7a731a/pkg/ring/model.go#L38-L63

Looking at places where `Desc.AddIngester` is used, `append` seems to be the desired behaviour. Discovered in #1750 and @pstibrany plans to fix it in #1809

**Comment by pstibrany** [comment]
> Looking at places where `Desc.AddIngester` is used, `append` seems to be the desired behaviour.

`append` was desired behaviour only when not doing normalization. Since we're removing that option, AddIngester will now always `replace` the tokens. That requires small change in `autoJoin` method, but all other places are unaffected. This is how I implemented it in #1809

**Comment by codesome** [comment]
Oh okay. Yes, autoJoin was the only place it could cause a problem. Didn't notice that change in the PR (I didn't have a look tbh :) )
