### ISSUE TITLE
Expose HTTP endpoint to export live config in yaml format

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#1886]
Given the intention to deprecate CLI flags, I'm wondering if it's useful / required to give users a way to convert CLI flags to yaml. An option - for users already running Cortex clusters - may be introduce an HTTP endpoint to export the live config (which is the result of yaml + CLI flags + defaults) as yaml.

_I'm not super sure this is useful, so I would like to gather some feedback and real use cases first._

**Comment by jaybatra26** [comment]
Hi, I am a GSOC aspirant and could work on this as my project. Please let me know where I can start from?

**Comment by pracucci** [comment]
Thanks @jaybatra26 for your interest! This specific issue has been addressed in the PR #2165 but I would suggest you to look at other issues. Feel free to ping me on the CNCF Slack (I'm "Marco Pracucci") if you need guidance across PRs easy to start.

**Comment by jaybatra26** [comment]
Thanks @pracucci. I have pinged you on slack.
