### ISSUE TITLE
-http.prefix with empty string causes 404

### ISSUE THREAD

**Issue by JosephSalisbury** [cortexproject/cortex#1927]
With a Prometheus server running on localhost:
```
$ curl localhost:9090
<a href="/graph">Found</a>.
```

And setting up the cortex query-frontend to use it:
```
$ ./cortex \
   -target=query-frontend \
   -frontend.downstream-url=http://localhost:9090 \
   -server.http-listen-port=9091 \
   -auth.enabled=false \
   -http.prefix=
level=info ts=2019-12-19T14:48:56.894668Z caller=cortex.go:232 msg=initialising module=server
level=info ts=2019-12-19T14:48:56.894919Z caller=server.go:117 http=[::]:9091 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-12-19T14:48:56.895159Z caller=cortex.go:232 msg=initialising module=overrides
level=info ts=2019-12-19T14:48:56.895184Z caller=override.go:53 msg="per-tenant overrides disabled"
level=info ts=2019-12-19T14:48:56.895201Z caller=cortex.go:232 msg=initialising module=query-frontend
level=info ts=2019-12-19T14:48:56.89525Z caller=main.go:76 msg="Starting Cortex" version="(version=, branch=, revision=)"
```

everything is cushty:
```
$ curl localhost:9091
<a href="/graph">Found</a>.
```

However, if the empty string is used for the `-http.prefix`, as in:
```
$ ./cortex \
   -target=query-frontend \
   -frontend.downstream-url=http://localhost:9090 \
   -server.http-listen-port=9091 \
   -auth.enabled=false \
    -http.prefix='""'
level=info ts=2019-12-19T14:49:40.485835Z caller=cortex.go:232 msg=initialising module=server
level=info ts=2019-12-19T14:49:40.48618Z caller=server.go:117 http=[::]:9091 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-12-19T14:49:40.486473Z caller=cortex.go:232 msg=initialising module=overrides
level=info ts=2019-12-19T14:49:40.486507Z caller=override.go:53 msg="per-tenant overrides disabled"
level=info ts=2019-12-19T14:49:40.486531Z caller=cortex.go:232 msg=initialising module=query-frontend
level=info ts=2019-12-19T14:49:40.486706Z caller=main.go:76 msg="Starting Cortex" version="(version=, branch=, revision=)"
```

then you only get 404s and everything is sad:
```
$ curl localhost:9091
404 page not found
```

This isn't really an issue on the command line (who the fuck writes `'""`), but in a Kuberentes deployment, it's pretty easy to do it by accident (i know, because I just did it :D), e.g:
```
      - args:
        - -http.prefix=""
```
and then it is pretty much impossible to debug this.

Ideally, `-http.prefix=` and `-http.prefix=""` should be the same, or at least post an error message that `-http.prefix=""` is gonna make you sad

**Comment by JosephSalisbury** [comment]
cc @gouthamve, as discussed on twitter <3

**Comment by pstibrany** [comment]
It seems weird to me to add workarounds to Cortex for YAML syntax quirks. I understand it can be difficult to debug, but that's just life when using YAML. You can use JSON or Jsonnet or  to generate your YAML files.

**Comment by pracucci** [comment]
I see @pstibrany perspective, but I believe we should do whatever reasonable to improve the UX. 

We recently added config validation support, so an easy option could be return a config validation error when the prefix is `""`. It should just be a matter of adding a check to `Config.Validate()` in `pkg/cortex/cortex.go`.

**Comment by pstibrany** [comment]
> We recently added config validation support, so an easy option could be return a config validation error when the prefix is `""`. It should just be a matter of adding a check to `Config.Validate()` in `pkg/cortex/cortex.go`.

I was just about to add such check, but then realized that there are many other combinations we may want to check for (eg. `''`, or even strings with double or single quotes with them).

Instead of doing checks like that, I think it may be more useful to actually log HTTP prefix value on startup, to make it easier to users to spot the problem.

**Comment by pracucci** [comment]
> I was just about to add such check, but then realized that there are many other combinations we may want to check for (eg. '', or even strings with double or single quotes with them).

May be realistic enforcing the prefix to start with `/`?

**Comment by pstibrany** [comment]
> May be realistic enforcing the prefix to start with `/`?

Yes, that looks like simple and good check to me.

**Comment by pracucci** [comment]
> May be realistic enforcing the prefix to start with /?

Errata corrige: to be empty or start with `/`.

**Comment by ethervoid** [comment]
Hi!

I've tried to reproduce this bug and looks like is not happening anymore.

Cortex logs:

```
$ ./cortex \  
   -target=query-frontend \
   -frontend.downstream-url=http://localhost:9090 \
   -server.http-listen-port=9091 \
   -auth.enabled=false \
    -http.prefix='""' 
level=info ts=2021-01-23T19:03:46.307706097Z caller=main.go:187 msg="Starting Cortex" version="(version=, branch=, revision=)"
level=info ts=2021-01-23T19:03:46.307814694Z caller=server.go:229 http=[::]:9091 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-01-23T19:03:46.308401077Z caller=module_service.go:58 msg=initialising module=server
level=info ts=2021-01-23T19:03:46.308528473Z caller=module_service.go:58 msg=initialising module=query-frontend-tripperware
level=info ts=2021-01-23T19:03:46.308580167Z caller=cortex.go:389 msg="Cortex started"
```

Curl to prometheus:

```
$ curl localhost:9090
<a href="/graph">Found</a>.
```

Curl to Cortex:

```
$ curl localhost:9091

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Cortex</title>
	</head>
	<body>
		<h1>Cortex</h1>
		
		<p>Admin Endpoints:</p>
		<ul>
			
				<li><a href="/config">Current Config (including the default values)</a></li>
			
				<li><a href="/config?mode=diff">Current Config (show only values that differ from the defaults)</a></li>
			
				<li><a href="/services">Service Status</a></li>
			
		</ul>
		
	</body>
</html>% 
```

**Comment by pracucci** [comment]
> I've tried to reproduce this bug and looks like is not happening anymore.

There have been several changes to API endpoints registration since when this issue has been opened. The `/` endpoint is no more registered prefixing it with `-http.prefix` and `-http.prefix` has been marked "soft" deprecated (we'll not remove it soon, but its usage is discouraged - see [HTTP API doc](https://cortexmetrics.io/docs/api/)).

You can check in `pkg/api/api.go` which are the endpoints still using `LegacyHTTPPrefix`. For example, one is `/user_stats` in the querier.

**Comment by ethervoid** [comment]
I'll take a look and try to fix this bug. Thx!
