### ISSUE TITLE
Ingester write performance degrades due to read volume

### ISSUE THREAD

**Issue by owen-d** [cortexproject/cortex#1928]
Currently the ingesters are susceptible to write performance degradation when exposed to high read volume. This is because both write and read paths [use the same grpc server resources](https://github.com/cortexproject/cortex/blob/master/pkg/cortex/modules.go#L253-L258). 

Reads should probably defer to writes here/have some way to acknowledge back-pressure.

**Comment by bboreham** [comment]
The read and write paths are also locking the same in-memory data structures.
Agreed we should try to prioritise writes.
