### ISSUE TITLE
error decoding list of values for prefix:key

### ISSUE THREAD

**Issue by lyc0221** [cortexproject/cortex#1936]
#docker-compose.yml 

> services:
  cortex:
    image: cortexproject/cortex:v0.4.0
    restart: always
    hostname: prometheus-db-1
    container_name: cortex
    ports:
      - "9009:9009"
      - "9095:9095"
    volumes:
      - "/opt/data/cortex/data:/data"
      - "./config/single-process-config.yaml:/etc/single-process-config.yaml"
    command:
      - "-config.file=/etc/single-process-config.yaml"
      - "-ring.store=consul"
      - "-consul.hostname=consul-cluster:8500"
      - "-distributor.replication-factor=3"
      - "-distributor.ha-tracker.enable"
      - "-distributor.ha-tracker.enable-for-all-users"
      - "-distributor.ha-tracker.cluster=cluster"
      - "-distributor.ha-tracker.replica=replica"
      - "-distributor.ha-tracker.consul.hostname=consul-cluster:8500"

#./config/single-process-config.yaml as like [https://github.com/kanuahs/cortex-demo/blob/master/docker-demo/cortex-configs/single-process-config.yaml](url)

**why does it reports the following error?**

`level=error ts=2019-12-26T10:03:54.746577132Z caller=client.go:275 msg="error decoding list of values for prefix:key" prefix=collectors/ key=collectors/ring err="proto: wrong wireType = 2 for field ReceivedAt"`

**Comment by pracucci** [comment]
I think the problem is that it's reusing the same consul used for the ring, and the `WatchKey()` done by the HA tracker clashes with the `collectors/ring` key.

A quick solution should be using a different prefix for the HA tracker, for example `-distributor.ha-tracker.prefix=ha-tracker/`.
