### ISSUE TITLE
how to run “globally aggregated” queries across all data in a single place ?

### ISSUE THREAD

**Issue by lyc0221** [cortexproject/cortex#1939]
I can run a scale out Cortex cluster using Docker. but how to run “globally aggregated” queries across all data in a single place ? for example? I can't find the way.

**Comment by pracucci** [comment]
Could you elaborate more on what you would like to achieve, please?

**Comment by lyc0221** [comment]
[https://github.com/cortexproject/cortex/blob/master/docs/getting_started.md
](url)

I configured `Horizontally scale out`, but can't query to all data, I only query the single instance's data, can you provide methods?

**Comment by lyc0221** [comment]
> Could you elaborate more on what you would like to achieve, please?

[https://github.com/cortexproject/cortex/blob/master/docs/getting_started.md](url)

I configured Horizontally scale out, but can't query to all data, I only query the single instance's data, can you provide methods?

**Comment by pracucci** [comment]
I'm missing a bit of context on your setup. Let me share some general guidelines.

The querier fetches time series both from ingesters and the storage. The ingesters contain the in-memory series not flushed to the storage yet, while the storage contains the stored one.

That being said:

- Ensure there are no errors in logs
- Which index and chunks store are you using? (ie. AWS DynamoDB / S3, Google GCS / BigTable, Cassandra). Remember that in cluster mode the local filesystem storage is not a viable solution (unless you use a shared filesystem like ceph, with which I personally have no experience)
- Ensure the ingester ring is correctly setup (all ingesters talk to the same consul/etcd backend cluster)

**Comment by lyc0221** [comment]
> I'm missing a bit of context on your setup. Let me share some general guidelines.
> 
> The querier fetches time series both from ingesters and the storage. The ingesters contain the in-memory series not flushed to the storage yet, while the storage contains the stored one.
> 
> That being said:
> 
> * Ensure there are no errors in logs
> * Which index and chunks store are you using? (ie. AWS DynamoDB / S3, Google GCS / BigTable, Cassandra). Remember that in cluster mode the local filesystem storage is not a viable solution (unless you use a shared filesystem like ceph, with which I personally have no experience)
> * Ensure the ingester ring is correctly setup (all ingesters talk to the same consul/etcd backend cluster)

sorry, I use the local filesystem storage, not like ceph, and the data saves in each instance. So, if I don't use AWS DynamoDB / S3, Google GCS / BigTable or Cassandra, I must use a shared filesystem like ceph?

**Comment by pracucci** [comment]
>  if I don't use AWS DynamoDB / S3, Google GCS / BigTable or Cassandra, I must use a shared filesystem like ceph?

If you're not running in the cloud (AWS / Google) and you're running Cortex in microservices mode (multiple nodes), then you should setup Cassandra at least for the index store (required) and then you have two options for the chunks: either Cassandra or a shared filesystem (but to my knowledge no proper production-grade testing has been done on setups with a shared filesystem so I would discourage it).

**Comment by derekssmith** [comment]
I found this issue because I feel like I am missing something.  I was expecting to provide an Org ID when writing metrics in from remote clusters, but not when querying cortex.  The documentation states you can run "globally aggregated" queries across all data, however if I have to provide an Org ID when querying how is that possible?  If the read and write have to be scoped by Org ID, how can I create a query that crosses org's?

My ultimate goal is to create Grafana charts that help monitor different prometheus instances (i.e. multiple org ids).  Am I maybe using the Org Id incorrectly?

**Comment by pracucci** [comment]
> The documentation states you can run "globally aggregated" queries across all data, however if I have to provide an Org ID when querying how is that possible? If the read and write have to be scoped by Org ID, how can I create a query that crosses org's?

Cortex currently doesn't allow to run cross-tenants (tenant = user = org) queries. Each tenant is fully isolated from the other one.

When the documentation mention "globally aggregated queries" what we mean is that, given 1 tenant, you can have multiple Prometheus servers (ie. a server in each region where you operate), all remote writing to the same Cortex with the same tenant ID, and then you can run globally aggregated queries across them.

**Comment by derekssmith** [comment]
Ah okay that makes sense.  I was mis-understanding the Org Id.

**Comment by bboreham** [comment]
Just to link the existing issue for cross-tenant queries #923

**Comment by gouthamve** [comment]
Closing this in favour of #923
