### ISSUE TITLE
Docs: Update the Architecture Section about the Ring

### ISSUE THREAD

**Issue by gotjosh** [cortexproject/cortex#1949]
The ring is one of the most complex pieces within Cortex. While the current documentation seems adequate, we could do with a more in-depth breakdown of the ring and its uses. In addition to that, a Diagram could help illustrate how it behaves in different scenarios. 

In the past, I've had to refer to external sources (videos, articles) to get a better understanding of it - the intention is to have it all in one place through reference and an expanded explanation.

The plan is to build on top of #1945 to expand a bit more on this section of the documentation. I think this could help new contributors/adopters understand how Cortex works a bit better.

**Comment by pracucci** [comment]
> While the current documentation seems adequate, we could do with a more in-depth breakdown of the ring and its uses.

May we write down a list of points we would like to cover?

**Comment by pracucci** [comment]
@gotjosh Are you willing to pick up this issue?

**Comment by gotjosh** [comment]
Yes @pracucci, assign it to me.

**Comment by pracucci** [comment]
Thanks @gotjosh !

**Comment by pracucci** [comment]
We should also mention:
- You can throw away the KV store data and lifecyclers will reconstruct it
- Failure modes
- Ingesters replication set (actually the replication set of any service using the ring for sharding). Differences between ingesters, store-gateways, compactors, rulers, distributors (for limits)

**Comment by pracucci** [comment]
_Still valid_

**Comment by jtlisi** [comment]
_still valid_

**Comment by pracucci** [comment]
_Still valid, help wanted_ 🤗
