### ISSUE TITLE
error: WebIdentityErr: failed to retrieve credentials

### ISSUE THREAD

**Issue by Eraac** [cortexproject/cortex#1950]
I use cortex throw [loki](https://github.com/grafana/loki). Running into EKS with eks-iam role 

That works pretty well, but actually logs are spammed with many errors, like this one and I've no idea because is actually work. 
```
level=error ts=2020-01-04T15:09:41.245349804Z caller=table_manager.go:188 msg="error syncing tables" err="WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidAction: Could not find operation AssumeRoleWithWebIdentity for version 2011-06-15\n\tstatus code: 400, request id: 3b7947a4-2f04-11ea-bbec-d7e945586644"
```

I get this error each 5 minutes, matching with `table_manager.dynamodb_poll_interval` and `storage_config.indexcachevalidity`

My config is pretty simple, S3 for chunk and DynamoDB for index

**Comment by Eraac** [comment]
The issue is still here

**Comment by tanujd11** [comment]
@Eraac Did you get the solution to this issue? Having the same issue I guess. DynamoDB is working but s3 is not with oidc web identity provider

**Comment by Eraac** [comment]
@tanujd11 No, but we've migrate to GCP so we don't have the problem anymore
