### ISSUE TITLE
Enhancement Request: Index on Cassandra, Chunks on S3?

### ISSUE THREAD

**Issue by sdwire** [cortexproject/cortex#1984]
Our on-prem datacenter has an S3-compatible object store for cheap long-term storage, but - being an on-prem environment - we don't have AWS's DynamoDB available for indexes.

We'd like to use Cassandra for the indexes and S3 (compatible) Object Cache for chunks.  This combination would make Cortex the perfect HA solution for our Prometheus metrics, but the current documentation suggests this isn't currently an option. Am I misreading?

**Comment by gouthamve** [comment]
It is possible. Please follow this https://cortexmetrics.io/docs/guides/cassandra/ and specify, `object_store` as `s3`.

You'll need supply the S3 URL in the CLI:
```
  -s3.url value
    	S3 endpoint URL with escaped Key and Secret encoded. If only region is specified as a host, proper endpoint will be deduced. Use inmemory:///<bucket-name> to use a mock in-memory implementation.
```

**Comment by sdwire** [comment]
Good to know.  Thanks, gouthamve!
