### ISSUE TITLE
Cassandra: Failing host verification without IP SANs

### ISSUE THREAD

**Issue by joshmue** [cortexproject/cortex#2007]
Hi!

I am trying to connect Cortex to Azure CosmosDB via the Cassandra API.
Using cortex 0.4.0 (target querier; `cassandra.ssl=true`) without `-cassandra.host-verification=false` yields:

```
level=error ts=2020-01-20T10:08:59.800666696Z caller=log.go:141 msg="error initializing cortex" err="gocql: unable to create session: unable to discover protocol version: x509: cannot validate certificate for <AZUREIP> because it doesn't contain any IP SANs <...>
```

This is apparently the same issue as https://github.com/gocql/gocql/issues/1232 in the used gocql library. The fix for this problem (https://github.com/gocql/gocql/pull/1310) was already merged into the gocql-master, but did not make it into the vendored dependencies of cortex yet.

Would you mind updating this dependency (or accepting a PR for it)?

**Comment by pracucci** [comment]
@VineethReddy02 Are you willing to take a look at this?
