### ISSUE TITLE
Cassandra data provider has no retry policy options via config

### ISSUE THREAD

**Issue by khaines** [cortexproject/cortex#2010]
Currently the Cassandra data package immediately fails on any error from the storage layer, even retry-able/recoverable errors such as rate throttling or network flaps.

**Comment by khaines** [comment]
I'm testing a solution to this on my AKS cortex cluster and should have a PR out soon.

**Comment by thojkooi** [comment]
We are running into similar issues. I'm happy to try out your solution once you have a PR out.
