### ISSUE TITLE
Injectable Prometheus Registry w/ Per User Functionality

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#2014]
When reusing structs from various projects in the Prometheus ecosystem (Alertmanager, Prometheus, Thanos, etc...), it is common to come across a case where a Prometheus Registry must be injected. For structs that are instantiated on a per-user basis this can be tricky to resolve. If a struct is instantiated multiple times, passing the default registry will lead to an error. Currently, the two options in this situation are:

1. Pass a nil registry -- Passing a nil registry none of the metrics will be reported from the struct
2. Pass the default registry wrapped with a userID label --  Passing a userID wrapped label can lead to an explosion of unwanted metrics/cardinality

I propose a custom registry that aims to solve this problem by allowing the following:

1. Handle duplicate registration on a per-user basis and automatically consolidate metrics w/o a userID
2. Config options to allow for named metrics to be reported with a userID label

**Comment by pracucci** [comment]
We had the same problem while building the experimental blocks storage and @pstibrany came up with a solution which should be generic enough to be reused. Please look at the [`metrics_helper.go`](https://github.com/cortexproject/cortex/blob/master/pkg/util/metrics_helper.go) and its usage across the code to see examples.

**Comment by jtlisi** [comment]
This looks great for this use case. Closing the issue
