### ISSUE TITLE
Fix deprecated gRPC naming.Watcher

### ISSUE THREAD

**Issue by zendern** [cortexproject/cortex#2015]
Found as part of #1912 where we fixed most of the linting issues. The only outstanding item is as follows and has been ignored for now by adding a `//nolint:staticcheck`

```
pkg/querier/frontend/worker.go:60:10: SA1019: naming.Watcher is deprecated: please use package resolver.  (staticcheck)
	watcher naming.Watcher
```

https://github.com/cortexproject/cortex/blob/6774c628af69a54570e33f6a6d875c90f61f6d54/pkg/querier/frontend/worker.go#L60

This will have ripple effects that will go up into where we define the resolver 

https://github.com/cortexproject/cortex/blob/6774c628af69a54570e33f6a6d875c90f61f6d54/pkg/querier/frontend/worker.go#L76-L96

There is no direct Watcher class that exists in the resolver package referenced. So the migration is likely a little more in depth than just using resolver.Watcher or something similar. 

Reference to that Watcher class
https://godoc.org/google.golang.org/grpc/naming#Watcher

**Comment by pracucci** [comment]
_This is still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
This will be required once we'll upgrade gRPC (1.30.0 or above), but we're currently blocked by etcd not supporting it yet. See this issue for more details: https://github.com/etcd-io/etcd/issues/12124.

**Comment by pracucci** [comment]
_Still valid_
