### ISSUE TITLE
Azure Blob - Invalid Chunk Checksum

### ISSUE THREAD

**Issue by JohnCMcDonough** [cortexproject/cortex#2024]
I'm running Cortex: `quay.io/cortexproject/cortex:v0.5.0-rc1` in Kubernetes.
[cortex-yaml-redacted.txt](https://github.com/cortexproject/cortex/files/4098145/kube-yaml-redacted.txt)
[cassandra-statefulset-redacted.txt](https://github.com/cortexproject/cortex/files/4098147/cassandra-statefulset-redacted.txt)

I've been testing out a variety of backends. I managed to get chunk and index storage running against Azure's CosmosDB. Tuns out, CosmosDB costs a fortune as it charges per Keystore per Cassandra table a min of 400 RUs.

I switched the index store to use a (temporarily) in memory Cassandra Cluster and the chunk store to use Azure Blob.

I also began running with multiple instances, and started seeing `invalid chunk checksum `. The first time was my fault, as I didn't correctly have the ingesters running against consul and was still using memory.

I shut everything down, wiped the dbs, restarted everything, force deleted a pod, and ran into #1521. After wiping the consul and verifying that everything was working, around 5 minutes into collecting metrics, I started getting "Invalid Chunk Checksum" in my Grafana Queries again.

I scaled everything down, wiped it the DB and blob, and started it all over again. It worked fine for another few minutes or so, and then I started seeing more `invalid chunk checksum`. 

Is there any information about what causes this issue? Is anyone else running into this? Is there some way of ignoring just the sections of bad data? If I change the queries to use a smaller time window, I can still pull some of the data, but if I increase the window to a section that includes bad data, the entire query fails.

I'll try to collect logs next time I run into this, and attach them to this issue.

**Comment by JohnCMcDonough** [comment]
It's worth noting that I did a graceful rollout and all the cortex instances successfully migrated data to another ingester, and I still ran into #1521. I'm not sure if this is related to this issue.

**Comment by pstibrany** [comment]
To avoid problems with ingesters that don't unregister themselves from the ring, you may want to increase `terminationGracePeriodSeconds` for your pod. It defaults to 30 seconds. It should be long enough to 1) give ingester chance to perform handover of data. This can be disabled by `-ingester.max-transfer-retries=0`, 2) flush data from memory to storage (this can take minutes with lot of data), 3) do final sleep [=30 seconds in your config].

Ingester unregisters itself from the ring on correct shutdown. It seems that your ingesters don't have enough time to flush data, which may then also lead to invalid chunk checksum errors – these happen when cortex reads chunks from storage, but such chunks are corrupted (eg. not complete).

**Comment by JohnCMcDonough** [comment]
That might have been part of it! My current manifests are kinda janky. I just threw them together quickly so I could move on from testing in docker to k8s. That grace period would especially be an issue since I don’t think I added any readiness probes. 

I’ll be sure to test the changes when I get back to the office on Monday. I was pretty sure I was seeing corruption even without pods restarting, but I’ll give it another shot just to see what I can see. I found a really nice metric that counts the number of corrupted chunks so I can see that easily. 

In the mean time, I switched everything (chunk and index) to Cassandra and haven’t had any issues! 

Also, this isn’t related to the current issue, but if I go to switch back to Azure Blob, is there some config that lets me migrate chunks and/or dual write?

**Comment by JohnCMcDonough** [comment]
I did more testing around this, scaling back to a single instance. I'm still running into these issues even after updating my deployment manifest with all the recommended things such as pod-affinity, termination grace period, readiness probe, max-surge and max-unavailable, etc.

After encountering issues, I started scraping Cortex metrics from a prometheus instance so I could see what was going on. I'm seeing an increase in the  `cortex_ingester_ingested_samples_failures_total` metric that corresponds with chunk corruption.

I've also noticed some TLS handshake timeouts on the cluster when pulling docker images (ugh firewalls). I wonder if it's exceeding the number of retries to write to blob, and just marking that as a failed and never writing it. I'm not sure if that's what's causing the chunk corruption, as I did see a few issues even prior to me restarting with azure blob. I've attached an image below.

![image](https://user-images.githubusercontent.com/18016200/73380966-ee5dbb00-4292-11ea-8bbc-18da35dd60f7.png)

**Comment by JohnCMcDonough** [comment]
I think the dropped samples are a red herring. I think we had bad relabel config in our source prometheus, and our relabels created duplicated metrics.I think that's what the `cortex_ingester_ingested_samples_failures_total` was from. We're still noticing constant `invalid chunk checksum` though. I tried setting
```yaml
azure:
     ...
     max_retries: 15
     min_retry_delay: 10ms
     max_retry_delay: 5s
     ...
```
to see if that would help, but it didn't. @pstibrany, if you maybe have a reference config that I can use and try out that for sure works, that might help. 

Maybe it's the v10 storage schema?

Here's my updated OpenShift manifest:

[cortex-blob-cassandra-redacted.txt](https://github.com/cortexproject/cortex/files/4134845/cortex-blob-cassandra-redacted.txt)

**Comment by khaines** [comment]
I've duplicated the error, but the investigation into the root cause is still underway.

**Comment by khaines** [comment]
Found the cause. A buffer was passed by value vs by reference, so the result read by the checksum validator was always 0. PR to correct this is imminent.
