### ISSUE TITLE
Metrics labels make it hard to join

### ISSUE THREAD

**Issue by sylr** [cortexproject/cortex#2025]
Hi,

There is a difference of labels between `cortex_cache_hits` (name) & `cortex_cache_request_duration_seconds_count` (method and status_code) which make it hard to calculate the hit ratio.

`method` label of `cortex_cache_request_duration_seconds_count` is a combination of `name` + a method suffix so I believe it would make more sense to keep a name label and add a method label instead of concatenating both in a single label.

Regards.

**Comment by pracucci** [comment]
The total number of keys requested to the cache is counted by `cortex_cache_fetched_keys`, so you can calculate the hit ratio with:

```
rate(cortex_cache_hits[1m]) / rate(cortex_cache_fetched_keys[1m])
```

**Comment by sylr** [comment]
I came up with

```
sum(xdelta(cortex_cache_hits[10m])) without (name)
/ 
sum(xdelta(cortex_cache_request_duration_seconds_count[10m])) without (method, status_code)
```

**Comment by bboreham** [comment]
The `method` and `status_code` labels on `cortex_cache_request_duration_seconds` come from library code that does metrics, tracing, etc., so a little tricky to change. This is probably why it's  stuffing two labels into `method`.

I agree this is poor for Prometheus, although it works quite well in Jaeger.

While we're on the subject, `cortex_memcache_request_duration_seconds` is almost completely overlapping with `cortex_cache_request_duration_seconds`, right?
