### ISSUE TITLE
Can't add alertmanager config

### ISSUE THREAD

**Issue by flbla** [cortexproject/cortex#2029]
Hello,

When I'm trying to add a new alertmanager config following: https://github.com/cortexproject/cortex/blob/master/docs/apis.md
I'm getting a 204 after POST the configuration.
But it doesn't work and in Alertmanager I can see the following log :
```level=debug ts=2020-01-23T16:04:28.897670862Z caller=multitenant.go:288 msg="adding configurations" num_configs=1
level=warn ts=2020-01-23T16:04:28.897726629Z caller=multitenant.go:296 msg="MultitenantAlertmanager: error applying config" err="blank Alertmanager configuration for 0"
```
When I do a get on api/prom/configs/alertmanager:
```
{"id":92,"config":{"rules_files":null,"rule_format_version":"1","template_files":null,"alertmanager_config":""},"deleted_at":"0001-01-01T00:00:00Z"}
```

There is no logs in configs Api.

my python code to post config
```python
headers = {'Content-Type': 'application/json', 'X-Scope-OrgID': '10'}
config = { 'global': { 'resolve_timeout': '10s' }, 'route': { 'receiver': 'webhook' }, 'receivers': [ { 'name': 'webhook', 'webhook_configs': [{ 'url': 'https://example.com' }] }] }
payload = { 'id': 99, 'rule_format_version': '1', 'config': { 'alertmanager_config': config } }
r = requests.post("http://192.168.1.1/api/prom/configs/alertmanager", headers=headers, json=payload)
```

We are using: quay.io/cortexproject/cortex:v0.4.0 image
And deployed on k8s.

Thank you.

**Comment by flbla** [comment]
I tried to validate my config with the api/prom/configs/alertmanager/validate endpoint
I got a : `200 {"status":"success"}`

**Comment by pstibrany** [comment]
`alertmanager_config` field is supposed to contain a string with YAML configuration, not JSON object. (Given that JSON is a valid YAML, you should be able to encode `config` field into JSON and put that string into `alertmanager_config`)

**Comment by flbla** [comment]
I converted my payload like this :
```python
payload = { 'rule_format_version': '1', 'alertmanager_config': 'global:\n  resolve_timeout: 10s\nroute: \n  receiver: webhook\nreceivers:\n  - name: webhook', 'rules_files': { 'test.yaml': 'test=aaaa' }, 'template_files': { 'test': 'test'} }
```
It seems alertmanager_config, rules_files and template_files have to be defined not in config.

**Comment by pstibrany** [comment]
Does it work for you now or are you still running into a problem?

**Comment by flbla** [comment]
I can add alertmanager config, so yes
but I think the doc is not up to date: https://github.com/cortexproject/cortex/blob/master/docs/apis.md

I defined my POST to /api/prom/configs/alertmanager like this :
```
{
    "rule_format_version": "2",
     "alertmanager_config": "<standard alertmanager.yaml config>",
     "rules_files": {
        "rules.yaml": "<standard rules.yaml config>",
        "rules2.yaml": "<standard rules.yaml config>"
     },
     "template_files": {
        "templates.tmpl": "<standard template file>",
        "templates2.tmpl": "<standard template file>"
     }
}
```

**Comment by flbla** [comment]
#2039
