### ISSUE TITLE
Configs Alertmanager webhooks urls can be abused

### ISSUE THREAD

**Issue by friedrich-at-adobe** [cortexproject/cortex#2036]
Alertmanager config defines webhooks urls
https://prometheus.io/docs/alerting/configuration/

Those urls are free form so a tenant could use cortex as an attack vector to any url endpoint reachable by alertmanager (local or in the Internet)

First idea: a way to whitelist the urls.

**Comment by pracucci** [comment]
Ideas:
- Introduce a allowlist and blocklist
- Resolve hostnames and block private IPs (eg. to avoid hitting internal network services)
- Run webhooks through a proxy which runs on isolated network (the alertmanager [`http_config`](https://www.prometheus.io/docs/alerting/latest/configuration/#http_config) already allows to configure a proxy)
