### ISSUE TITLE
Don't forget about lack of MaxConcurreny in PromQL the next Prometheus dep update

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#2045]
This PR prometheus/prometheus#6701 introduced a kind of hidden change in behavior of PromQL: `MaxConcurrency` option is Noop if you don't use active tracker, which we don't.

When we'll update the Prometheus dep, we'll have to handle it. Configure `ActiveQueryTracker` may be the simplest solution.

Reported by @bwplotka in https://github.com/thanos-io/thanos/issues/2064.

**Comment by pstibrany** [comment]
Handled in PR #2088. Fortunately Prometheus devs also decided to actually remove `MaxConcurrency` field, so it was hard to miss.

**Comment by bwplotka** [comment]
Awesome. We will upgrade Prometheus deps, probably after this being done: https://github.com/prometheus/prometheus/pull/

Cheers! :beers:

**Comment by bwplotka** [comment]
We won't forget - it creates build errro I think.

Stil we are waiting for chunk iter to be merged to update Prom deps on Thanos. Also there tons of memory leaks and issues - so kind of good update is delayed ;p

**Comment by pracucci** [comment]
Fixed in #2088.
