### ISSUE TITLE
Log to stdout in unit tests

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#2048]
I've noticed that the Ingester WAL test has introduced an override to log to stdout. Given it's done in a `init()` function, this applies to any `pkg/ingester` test:

https://github.com/cortexproject/cortex/blob/032f3a83f5f057b913a2ac0c4fdfe01e5aceea57/pkg/ingester/wal_test.go#L14-L16

I personally find it both useful and noisy. While developing and running unit tests, I frequently find myself commenting these lines because add too much noise to the tests result output, while sometimes they're useful.

I'm wondering if we're OK keeping such logs always enabled by default or being able to conditionally enable them would be better.

/cc @codesome @jtlisi

**Comment by bboreham** [comment]
I'm a 'no'.  I agree it's occasionally useful; we could add a command-line flag to turn logs on in every package's tests.

**Comment by pstibrany** [comment]
I also only add these during development. I wouldn't mind using `testing.Verbose()` as a flag whether we want this or not.

**Comment by jtlisi** [comment]
I have not preference either way. It's something I can work around.

**Comment by codesome** [comment]
Whoops. I only wanted to initialize the logger in the tests as they were panicking without that and did not think much about the effect of stdout.
