### ISSUE TITLE
Docs: Getting Started

### ISSUE THREAD

**Issue by oddlittlebird** [cortexproject/cortex#2050]
A Getting Started topic helps a brand new user get started with software. It should be like "Hello, world!" in programming. The current Getting Started topic is way too advanced.

Introduction: Either in this topic or another, you need to explain what Cortex is and what a person might use it for. This can be brief and link to other pages, but it needs to be there, because thanks to Google, every page of the help can be page 1.

Prerequisites: What do I need in order to get started? Minimum hardware requirements? Software already installed? Prometheus?

Step-by-step instructions: This will be 100% more understandable if you add step-by-step instructions. For example:

1. Install Cortex. (Include a command or link for that).
2. Hook up Prometheus (explain how)
3. Enter this command to start the system.
And whatever else they need to do for the bare minimum to get a result.

**Comment by vishnubraj** [comment]
Yes, I am still confused if i can use cortex without Docker or not, and if yes how do i do that and where can i find the binary for the same.

**Comment by pracucci** [comment]
> Yes, I am still confused if i can use cortex without Docker or not

Yes, you can run Cortex without Docker / Kubernetes, even if probably most of users run Cortex services in containers.

> where can i find the binary for the same.

In the [releases page](https://github.com/cortexproject/cortex/releases) you can scroll down to the "Assets" section of each recent release to find the binaries.

**Comment by vishnubraj** [comment]
Thanks @pracucci  if i have to run separate ingester, distributor, querier etc in linux.
do i have to download the linux package and run it only with that specific service config? or i have to build from source ?

**Comment by pracucci** [comment]
> if i have to run separate ingester, distributor, querier etc in linux.
do i have to download the linux package and run it only with that specific service config?

@vishnubraj Cortex always compiles as a single binary, so there's no need to build it from source. To run Cortex in microservices mode (where a single instance runs only a specific service) you've just to pass the CLI flag `-target=NAME` where `NAME` is the service name (ie. `distributor`). Alternatively, you can specify the target in the YAML config file ([see config file reference](https://cortexmetrics.io/docs/configuration/configuration-file/#supported-contents-and-default-values-of-the-config-file)).

**Comment by vishnubraj** [comment]
Thanks @pracucci
