### ISSUE TITLE
distributor use too much more memory after upgrade to v0.6.0

### ISSUE THREAD

**Issue by Wing924** [cortexproject/cortex#2053]
The distributor use much more memory and get OOM after upgrade from v0.4.0 to v0.6.0.

<img width="1292" alt="スクリーンショット 2020-01-30 15 54 12" src="https://user-images.githubusercontent.com/8895721/73426904-e1b39280-4378-11ea-90f0-4d4cc30fdf47.png">
red line is the time I upgrade the cortex.

**Comment by Wing924** [comment]
`go_memstats_heap_inuse_bytes` metrics
<img width="638" alt="スクリーンショット 2020-01-30 16 51 09" src="https://user-images.githubusercontent.com/8895721/73430390-4a9f0880-4381-11ea-80ea-a8318c5ee959.png">

**Comment by Wing924** [comment]
workaround:
* change prometheus batch size from 10k to 2k
* chnage GOGC from 100 to 30
* add nginx as frontend and set `limit_req`

**Comment by weeco** [comment]
I observed the same behaviour. The memory usage is way higher after upgrading the distributors from v0.4.0 to v0.6.1. I've also seen a couple OOM kills after upgrading the distributors.

![Screenshot 2020-03-02 at 13 16 46](https://user-images.githubusercontent.com/23424570/75675820-3738d300-5c88-11ea-81b0-35603c178ebb.png)

You can divide this graph into 3 sections:

1. Distributor v0.4.0 using max memballast of 1Gb
2. Distributor v0.6.1 using the same memballast
3. Distributor v0.4.0 without max memballast

**Comment by weeco** [comment]
Don't mark as stale, still a present issue and reproducible. In the cortex slack there was a third user reporting the same issue.

**Comment by Wing924** [comment]
still not fixed (confirmed on v1.2.0)

**Comment by jtlisi** [comment]
@Wing924 it would help if you could upload a profile of the memory usage of your distributors. It would give us a sense of where the extra memory usage is coming from.

**Comment by amckinley** [comment]
I'm seeing something very similar: #3188

**Comment by amckinley** [comment]
Here's a pprof of a distributor pod (original SVG available on request):
![Screen Shot 2020-09-15 at 4 45 13 PM](https://user-images.githubusercontent.com/54160/93275843-ddef4780-f772-11ea-9a83-e5a06565421a.png)

**Comment by pracucci** [comment]
Closing this issue to continue the discussion on https://github.com/cortexproject/cortex/issues/3188.
