### ISSUE TITLE
Separate config file flags

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#2062]
`-runtime-config.file` and `-config.file` seem like they could be interchangeable to me. I think there is a case to be made the most of the time you want to use a single config file for Cortex and not one for initialization and another for reloads.

**Comment by pracucci** [comment]
> I think there is a case to be made the most of the time you want to use a single config file for Cortex and not one for initialization and another for reloads.

Agree. The only downside I see of merging into live reloading the `-config.file` is that for the final user it's difficult to understand which config options support live reloading and which not. Having a separate file for the live reloading makes it obvious.

**Comment by pracucci** [comment]
_If I'm not mistaken, @pstibrany worked on this and may have opinions._

**Comment by jtlisi** [comment]
If the `runtime-config.file` is not set, we could default to the `config.file`

**Comment by pstibrany** [comment]
> If the `runtime-config.file` is not set, we could default to the `config.file`

That wouldn’t work currently, as those two files have different content.

**Comment by jtlisi** [comment]
> That wouldn’t work currently, as those two files have different content.

I see, I guess that won't work. I think long term we should have hot reloads on a single config file. But in the meantime there is not much we can do.
