### ISSUE TITLE
Selectively disable indexing of labels

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#2068]
**This issue is intended as a Google Summer of Code project.**

The idea is that Cortex should have config saying "do not index any label `kubernetes_io_arch`", then ingester skips indexing it and querier knows if it does appear in a query to fall back to scanning each chunk.

Rationale: some labels are not very selective, or very rarely come up in queries. Not indexing them reduces IO and storage cost.

More examples:
* The `id` label on every cAdvisor series, which has a value like `/kubepods/burstable/podc6b74f34-0fec-11ea-898b-5254009d7039/dd55c1bddcc13c442f38ed3e9980b801ffac53b6ae2e3a0e76e3d55e7a36d016`.
* Standard Prometheus pod Service Discovery will give an `instance` label which is the dynamically allocated pod IP, like `10.24.10.73:9404`, which is meaningless.
* Almost any high-cardinality field like the Kubernetes api-server `client` label or a `url` field which you might want to summarise on but quite unlikely to select on.

Most likely the unit of configuration will be a tuple: (tenant,metric,label); perhaps over date ranges. Perhaps tenant and metric can be wild-carded.

Sub-tasks:
 - Create a testing framework for the finished work.
 - Create some way to measure selectivity of labels in existing data.
 - Create some way to measure frequency of use of labels in queries.
 - Design a way to store and access metadata on indexing.
 - Design a way to measure the effectiveness of the finished project.
 - Implement selective indexing in the write path.
 - Implement selective indexing in the read path (ie checking metadata and falling back to full scan)

If time allows:
 - Implement back-filling of missing indexes.
 - Implement back-removal of existing indexes.
 - Stretch goal: extend the metadata to say how selective a label is, then use this info to skip some index fetches.

**Comment by pracucci** [comment]
> Rationale: some labels are not very selective, or very rarely come up in queries. Not indexing them reduces IO and storage cost.

Do you have any estimation on the IO/storage reduction with this optimization? Would be interesting to understand the benefits of such effort.

**Comment by bboreham** [comment]
On our system using AWS DynamoDB, indexes are about 70% of IO cost and 37% of storage cost.
The number of labels varies widely, but suppose we could stop indexing 20% of them, that would give a 14% reduction in IO and 7% in storage.

**Comment by Syn3rman** [comment]
Hey,
I'm a junior year cs undergrad interested in working under cortex for GSoC this year.
I've gone over the cortex intro and deep dive videos and also the architecture overview, so how should I proceed?
Thanks!

**Comment by bboreham** [comment]
Hi @Syn3rman, sorry we missed your message here.
If you're still interested the best way is to start with one or two small issues in the Cortex repo, and come on the Cortex channel in the CNCF Slack.

**Comment by Syn3rman** [comment]
Hey @bboreham,
Can I pm you on slack?

**Comment by bboreham** [comment]
If you like, however GSoC is all about Open Source and doing things in the open, so let's try to use the public channel where possible.

**Comment by friedrichg** [comment]
This reduction of indexes made more sense in the context of chunks because indexes were very expensive to store.
With chunks deprecated and the move to tsdb format, we still have high cardinality that needs to be tackled, but now we have indexes coupled with chunks in the new format. The new format is also less expensive to store, there is less need to make this kind of optimizations to not store something.
