### ISSUE TITLE
cannot set -ingester.chunk-encoding by config file

### ISSUE THREAD

**Issue by Wing924** [cortexproject/cortex#2077]
The `-ingester.chunk-encoding` can only set by flag and it can't be set by config file.

https://github.com/cortexproject/cortex/blob/4e2dd12de6ca921f4f329a6aa037ed19be7bb605/pkg/chunk/encoding/factory.go#L16-L28

**Comment by pracucci** [comment]
True. I believe it's not a trivial change to do because `DefaultEncoding` is a global variable and not bind to a config struct. If you have a good idea to add YAML config in a safe and clean way, I would love to review that PR.

**Comment by tomwilkie** [comment]
Would love to be able to do this from the config file - any ideas?

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid, but we need some help_

**Comment by friedrichg** [comment]
chunks was deprecated and removed in v1.14.0, thus this flag was removed
