### ISSUE TITLE
Automatic repair for the WAL in ingester

### ISSUE THREAD

**Issue by codesome** [cortexproject/cortex#2084]
Currently, we don't have any repair mechanism for the WAL. If the WAL gets corrupt due to any reason, ingester will fail to start. Also during an ingester crash (like for OOM), it is very likely that the last WAL segment which was being appended to gets corrupt (this was reported on the slack).

I plan to have the repair mechanism similar to Prometheus: Delete all the WAL segments from the point where the corruption was found.

**Comment by pracucci** [comment]
@codesome This has been done, right? Or am I missing something?

**Comment by codesome** [comment]
Fixed in https://github.com/cortexproject/cortex/pull/2105
