### ISSUE TITLE
Support multiple regions with disjoint ingesters and DB replication

### ISSUE THREAD

**Issue by ThePants999** [cortexproject/cortex#2090]
Raising at @gouthamve request after discussion in Slack - thanks again Goutham!

We need to monitor a highly distributed application that's split across multiple geographic regions. We'd like to be able to do this using a single Cortex cluster, but to avoid unnecessary inter-region network traffic, we'd like the write path to be zone-aware so that distributors prefer to select an ingester that's local to them, even though all ingesters are in the same ring so that queriers can find them all. Something like this:

![image](https://user-images.githubusercontent.com/2923823/74031554-c0225e80-49a9-11ea-8fbe-b0cec522a793.png)

**Comment by weeco** [comment]
Duplicate of https://github.com/cortexproject/cortex/issues/612

**Comment by ThePants999** [comment]
Agree there's some overlap, but not duplicates. #612 is saying, "if I have two ingesters in the same availability zone, avoid distributing the same data to both of them". This one is saying, "prefer ingesters in the same region as the distributor".

**Comment by ThePants999** [comment]
Not stale
