### ISSUE TITLE
Config validation for cortex

### ISSUE THREAD

**Issue by vaisakhb** [cortexproject/cortex#2098]
I am not able to see any data in my long term store(minio). Below is the ingester configuration which I am using. Can we validate the config during the startup? ingester came up  even when I used incorrect credentials. 

> - -target=ingester
>         - -ingester.join-after=30s
>         - -ingester.claim-on-rollout=true
>         - -consul.hostname=consul.consul.svc.cluster.local:8500
>         - -consul.acltoken=xxxx-xxxx-xxx-xxxx-xxxxxxxxx
>         - -ingester.max-chunk-age=5m
>         - -s3.url=s3://KIA4DXXXPHWKAYXXX2:aNcJHGJJ8XtgIyuSrT6%2Fgx%2Fr@cortex.example.net:9000
>         - -dynamodb.original-table-name=cortex
>         - -dynamodb.url=dynamodb://user:pass@dynamodb.platform-cortex.svc.cluster.local:8000
>         - -dynamodb.periodic-table.prefix=cortex_weekly_
>         - -dynamodb.periodic-table.from=2020-02-01
>         - -dynamodb.daily-buckets-from=2020-02-01
>         - -dynamodb.base64-buckets-from=2020-02-01
>         - -dynamodb.v4-schema-from=2020-02-01
>         - -dynamodb.v5-schema-from=2020-02-01
>         - -dynamodb.v6-schema-from=2020-02-01
>         - -dynamodb.chunk-table.from=2020-02-01
>         - -dynamodb.v9-schema-from=2020-02-01
>         - -memcached.hostname=memcached.platform-cortex.svc.cluster.local
>         - -memcached.timeout=100ms
>         - -memcached.service=memcached

Even the ingester logs doesnt show anything 

> level=info ts=2020-02-10T09:34:11.160268747Z caller=cortex.go:240 msg=initialising module=server
> level=info ts=2020-02-10T09:34:11.160614843Z caller=server.go:117 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
> level=info ts=2020-02-10T09:34:11.160842386Z caller=cortex.go:240 msg=initialising module=runtime-config
> level=info ts=2020-02-10T09:34:11.160870177Z caller=manager.go:63 msg="runtime config disabled: file not specified"
> level=info ts=2020-02-10T09:34:11.16089707Z caller=cortex.go:240 msg=initialising module=overrides
> level=info ts=2020-02-10T09:34:11.160913331Z caller=cortex.go:240 msg=initialising module=store
> level=info ts=2020-02-10T09:34:11.173246736Z caller=cortex.go:240 msg=initialising module=ingester
> level=info ts=2020-02-10T09:34:11.174385467Z caller=lifecycler.go:476 msg="not loading tokens from file, tokens file path is empty"
> level=info ts=2020-02-10T09:34:11.175195066Z caller=main.go:100 msg="Starting Cortex" version="(version=, branch=, revision=)"
> level=info ts=2020-02-10T09:34:11.181413547Z caller=lifecycler.go:500 msg="instance not found in ring, adding with no tokens" ring=ingester
> level=info ts=2020-02-10T09:34:11.989318834Z caller=lifecycler.go:679 msg="changing instance state from" old_state=PENDING new_state=JOINING ring=ingester
> level=info ts=2020-02-10T09:34:12.025798989Z caller=transfer.go:87 msg="processing TransferChunks request" from_ingester=ingester-786c675b79-cqm2q
> level=info ts=2020-02-10T09:34:12.144545331Z caller=lifecycler.go:679 msg="changing instance state from" old_state=JOINING new_state=ACTIVE ring=ingester
> level=info ts=2020-02-10T09:34:12.190238185Z caller=transfer.go:149 msg="Successfully transferred chunks" from_ingester=ingester-786c675b79-cqm2q series_received=1476
> 
> 

Is there anything wrong with the configuration ?

**Comment by jtlisi** [comment]
Did try querying cortex for data or just inspect dynamo? It will take some time for the ingesters to flush data to the backend.
