### ISSUE TITLE
Cannot run integration tests on macOS X with Docker Desktop version 2.2.0.3

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#2149]
After removing `CORTEX_INTEGRATION_DIR` env variable and upgrading Docker Desktop to version 2.2.0.3, I can no longer run integration tests on macOS X.

I was advised to add `/var/folders` to the "File Sharing" directories, but I'm unable to do so, since Docker always resolves it to `/private/var/folders` instead, and I cannot edit this afterwards.

<img width="1152" alt="Screenshot 2020-02-18 at 08 15 41" src="https://user-images.githubusercontent.com/895919/74712615-ff14a780-5226-11ea-87b5-0e31a3d2cbe5.png">

**Comment by pracucci** [comment]
Fixed in #2143.
