### ISSUE TITLE
I don't know what the problem is mainly。So i need help

### ISSUE THREAD

**Issue by sun-iot** [cortexproject/cortex#2151]
This is the case. I configured the address of my own server on Prometheus, and the server can obtain Prometheus monitoring data normally.But when the server forwards the data to Cortex, it has this problem.

Here is the screenshot。
![error](http://www.source.sun-iot.xyz/image/cortex/error.png)

**Comment by pracucci** [comment]
What version of Prometheus are you running and can you show the remote write configuration (make sure to remove any sensitive data)?
