### ISSUE TITLE
DynamoDB: Make min usage for scaledown configurable

### ISSUE THREAD

**Issue by dcherman** [cortexproject/cortex#2183]
Hi,

Right now, the minimum usage to trigger scaledown in DynamoDB is hard-coded to 100 units/sec

https://github.com/cortexproject/cortex/blob/5f7340c1fc487e455476fdc5ab65ef07894e823c/pkg/chunk/aws/metrics_autoscaling.go#L26

Can we consider making that configurable?  My use case is that I have multiple clusters that use this, some of them via Loki.  Especially for dev/ephemeral clusters, we don't even come *close* to using 100 units/sec of capacity, meaning that downscaling never occurs for us, requiring manual intervention.

**Comment by dcherman** [comment]
Any thoughts here?  Happy to make the contribution, just want to make sure it's something that'd be accepted/considered.

**Comment by dcherman** [comment]
Still would be useful :)

**Comment by dcherman** [comment]
Can this be reopened?  Not sure why it was closed since I had commented on this previously.

**Comment by pracucci** [comment]
> Any thoughts here? Happy to make the contribution, just want to make sure it's something that'd be accepted/considered.

I don't know how 100 was picked, but I'm 💯  open to make it configurable.
