### ISSUE TITLE
Allow 3rd party projects to customise the metrics namespace

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#2217]
Loki is vendoring Cortex for some components and Cortex metrics are registered with the `cortex_` namespace. We should allow such external projects to customise the metrics namespace.

The idea to define `var util.MetricNamespace` set to `cortex` and replace `Namespace: "cortex"` with `Namespace: util.MetricNamespace` everywhere in the Cortex codebase. Then Loki (or other projects) can use linker flags to change the `util.MetricNamespace` value.

**Comment by pstibrany** [comment]
Also split `Name: "cortex_..."` metrics names to use `Namespace`.

**Comment by pracucci** [comment]
_Closing for now. We can reopen it anytime if will still be necessary to do._
