### ISSUE TITLE
Running Cortex with Cassandra

### ISSUE THREAD

**Issue by ybnelson** [cortexproject/cortex#2237]
Trying to start the cortex process with cassandra only as documented here:
https://cortexmetrics.io/docs/guides/cassandra/

results in following errors output from docker logs <id> -f
level=error ts=2020-03-09T20:12:31.75034073Z caller=table_manager.go:188 msg="error syncing tables" err="Undefined Column. Column doesn't exist\n\n\t\tSELECT\n\t\t\tfunction_name,\n\t\t\targument_types,\n\t\t\targument_names,\n               ^^^\n\t\t\tbody,\n^^^^\n\t\t\tcalled_on_null_input,\n\t\t\tlanguage,\n\t\t\treturn_type\n\t\tFROM system_schema.functions\n\t\tWHERE keyspace_name = ?\n (ql error -203)"

Is there an example of the schema in CQL that I could pass independently to my cassandra instance?

**Comment by VineethReddy02** [comment]
Hi @ybnelson Can you share configuration i.e ```--config.file```?

**Comment by ybnelson** [comment]
Config file is here: [https://github.com/yugabyte/cortex/blob/master/yb-demo/single-process-config.yaml](https://github.com/yugabyte/cortex/blob/master/yb-demo/single-process-config.yaml)
