### ISSUE TITLE
Document compatibility guarantees for v1

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#2247]
- Config files fields
- Flags
- Whats experimental & whats not.

**Comment by tomwilkie** [comment]
Proposal (brain dump for now, could have missed things):

# Flags, Config and minor version upgrades.

Upgrading cortex from one minor to the next should "just work"; that being said, we don't want to bump the major version every time we remove a flag, so we will will keep deprecated flags around for 2 minor release.  There is a metric you can alert on to find out if you're using a deprecated  flag.

Similarly to flags, minor version upgrades using config files should "just work".  If we do need to change config, we will keep the old way working for two minor version.  There will be a metric you can alert on for this too.

# Reading old data

The Cortex maintainers commit to ensuring future version of Cortex can read data written by versions up to two years old.  In practice we expect to be able to read more, but this is our guarantee.

# API Compatibility

Cortex strives to be 100% API compatible with Prometheus; any deviation from this is considered a bug, except:
- Requiring the `__name__` label on queries.
- Additional API endpoints for creating, removing and modifying alerts and recording rules.
- Additional API endpoints for management of Cortex itself, such as the ring.  These APIs are not part of the any compatibility guarantees.

# Experimental features

Cortex is an actively developed project and we want to encourage the introduction of new features and capability.  As such, not everything in each release of Cortex is considered "production-ready".

Examples of features considered experiemental:
- TSDB block storage.
- Ingester chunk WAL.

**Comment by pracucci** [comment]
> Cortex strives to be 100% API compatible with Prometheus; any deviation from this is considered a bug, except:

As of today, the labels API endpoints are not 100% compatible, considering Cortex only queries data in the ingesters.

> Experimental features

Other experimental features we have:

- Gossip memberlist
- User subring
- Ruler API
- Memcached client DNS-based service discovery (https://cortexmetrics.io/docs/configuration/arguments/#dns-service-discovery)
- Delete series
- FIFO and Redis cache (according to https://cortexmetrics.io/docs/guides/caching/)
