### ISSUE TITLE
Migrate object storage clients to use thanos objstore.Bucket implementations

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#2262]
Currently we have generic `ObjectClient` interface defined here: 
https://github.com/cortexproject/cortex/blob/58c081a8eab77b70ce4d9f425fd2400d1155eee8/pkg/chunk/storage_client.go#L64-L71

This interface is used by the `pkg/chunk/objectclient` to store chunks. It will also be used by @sandeepsukhani works on delete. I also utilize this interface for my rules/alerts branches. These clients are pretty generic and I think we might be able to utilize some off the shelf libraries instead of rolling our own object client. I found two potential libraries that might work:

1. Go Cloud Development Kit

https://github.com/google/go-cloud

Keeps things very generic and easy for reuse.

2. Reuse Thanos
The Thanos libary is pretty full featured and would be able to do most of what we want. It would also be nice for unifying the two ecosystems.
https://github.com/thanos-io/thanos/blob/master/pkg/objstore/objstore.go

**Comment by pracucci** [comment]
> Reuse Thanos

Unless we have a good argument to not use the Thanos objstore I would use it. We're already using it for the blocks storage anyway, so it's already vendored.

**Comment by jtlisi** [comment]
@pracucci  I agree. I added some tags to signal to anyone who wants to take up this issue.

**Comment by jaybatra26** [comment]
@jtlisi and @pracucci Can I take this up as my next work item?

**Comment by jtlisi** [comment]
Go for it!

**Comment by jaybatra26** [comment]
Thanks @jtlisi . I am assuming that I would have to write something like this [code snippet](https://github.com/cortexproject/cortex/blob/82eae45bc7f71e89c8fcf5a4551683b842b3e6bb/pkg/storage/tsdb/backend/gcs/bucket_client.go#L13-L17) for each of the object store i.e(s3/gcs/azure etc). 
Also, looks like local file system is in testing mode.
![image](https://user-images.githubusercontent.com/24604293/76728544-03c47100-677d-11ea-81b9-f7054757eedd.png)

Is that correct?

**Comment by jtlisi** [comment]
@jaybatra26 In this case you should be able to reuse that snippet and update the `pkg/chunk/objectclient` code to utilize the `objstore.Bucket` interface. You will also have to update anything that utilizes the `chunk.ObjectClient` interface to use the `objstore.Bucket` interface instead. This includes the code in `pkg/chunk/purger` and probably the `pkg/ruler/rules/objectclient` implementation if #2269 is merged.

It may make sense to move the packages in `pkg/storage/tsdb/backend` to the more general `storage/backend` path. @pracucci does that sound good to you?

**Comment by pracucci** [comment]
> It may make sense to move the packages in pkg/storage/tsdb/backend to the more general storage/backend path. @pracucci does that sound good to you?

It makes sense to me. However, I would advocate for incremental PRs. A first PR may be which package move, then we may have a PR for the object store client interface refactoring and then a PR for each object store client replacement?

**Comment by jaybatra26** [comment]
Thanks @jtlisi and @pracucci. As @pracucci suggested, I will create incremental PR's.

**Comment by jaybatra26** [comment]
@pracucci, by refactoring object store client interface, you mean deleting it, right? We would no longer require this piece of code, right?
>  A first PR may be which package move, then we may have a PR for the object store client interface refactoring and then a PR for each object store client replacement?

**Comment by jtlisi** [comment]
@jaybatra26 Yes

**Comment by pracucci** [comment]
I'm exploring the idea to change the ruler and alertmanager object store client to the client we use in the blocks storage. There's no easy way to make it a non-breaking change, and realistically it would end up to introduce breaking changes in the config and objstore client metrics. As per our 1.x guarantees, we can't introduce breaking changes in the config, so looks a deal breaker.

_I'm wondering how many people actually uses the s3, gcs, azure or swift storage for the ruler or alertmanager._

**Comment by jtlisi** [comment]
I think this would make a good 2.0 candidate. @pracucci WDYT?

**Comment by pracucci** [comment]
_Still valid_

**Comment by jaybatra26** [comment]
Hi! Can I take this up as a part of the community bridge program for 2021 Q1?

**Comment by jtlisi** [comment]
_still valid_

**Comment by pracucci** [comment]
Done for ruler and alertmanager. However, the old clients are still supported (will be deprecated soon), so I'm keeping this issue open.

**Comment by pracucci** [comment]
> Done for ruler and alertmanager. However, the old clients are still supported (will be deprecated soon), so I'm keeping this issue open.

This is still true. Old clients have been deprecated in Cortex 1.9.0 so I'm going to close this issue. They will be removed 2 releases after 1.9.0, so 1.11.0.
