### ISSUE TITLE
Query frontend closes connections after 30s

### ISSUE THREAD

**Issue by brancz** [cortexproject/cortex#2283]
I may very well be misconfiguring something, but I haven't found that config if so.

I run cortex with these flags:

```bash
$ cortex -log.level=debug -config.file=config.yaml -querier.max-retries-per-request=0 -frontend.downstream-url=http://localhost:8080
```

And this config:

```yaml
auth_enabled: false
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
http_prefix: ""
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        size: 2048
        validity: 6h
    max_freshness: 1m
  split_queries_by_interval: 24h
server:
  http_listen_port: 9090
target: query-frontend
```

Then I have a go server:

```go
package main

import (
	"net/http"
	"time"
)

func main() {
	http.ListenAndServe(":8080", http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		time.Sleep(33 * time.Second)
		w.Write([]byte(`{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1584469480.016,"1"]}]}}`))
	}))
}
```

Then curl upstream directly:

```bash
$ curl -vvvv localhost:8080/api/v1/query
*   Trying ::1:8080...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 17 Mar 2020 19:21:43 GMT
< Content-Length: 105
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1584469480.016,"1"]}]}}
```

And curl the cortex query frontend:

```bash
$ curl -vvvv localhost:9090/api/v1/query
*   Trying ::1:9090...
* TCP_NODELAY set
* Connected to localhost (::1) port 9090 (#0)
> GET /api/v1/query HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

Interestingly, since I have debug logs on this is still printed:

```
level=info ts=2020-03-17T19:22:31.047473406Z caller=server.go:147 http=[::]:9090 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2020-03-17T19:22:31.047670604Z caller=main.go:109 msg="Starting Cortex" version="(version=, branch=, revision=)"
level=debug ts=2020-03-17T19:22:31.047740481Z caller=module_service.go:48 msg="module waiting for initialization" module=query-frontend waiting_for=server
level=info ts=2020-03-17T19:22:31.047789902Z caller=module_service.go:58 msg=initialising module=query-frontend
level=info ts=2020-03-17T19:22:31.04787027Z caller=module_service.go:58 msg=initialising module=runtime-config
level=info ts=2020-03-17T19:22:31.047901303Z caller=manager.go:109 msg="runtime config disabled: file not specified"
level=info ts=2020-03-17T19:22:31.048238016Z caller=cortex.go:319 msg="Cortex started"
level=info ts=2020-03-17T19:23:17.941294158Z caller=frontend.go:166 msg="slow query" org_id=fake url=http://localhost:9090/api/v1/query time_taken=33.001989337s
level=debug ts=2020-03-17T19:23:17.941630644Z caller=logging.go:44 traceID=27eb33fe232a6759 msg="GET /api/v1/query (200) 33.002394934s"
```

Presumably that 200 is the what the upstream responded, as it's not what curl ended up seeing.

Thoughts why this might be happening?

@pracucci @gouthamve

**Comment by brancz** [comment]
My suspicion is the use of the `http.DefaultTransport`, here: https://github.com/cortexproject/cortex/blob/4913017a67fb54c34102c6b75d58f77b842cff94/pkg/querier/frontend/frontend.go#L114.

**Comment by brancz** [comment]
I tried creating a new `http.RoundTripper` with higher timeouts, but that doesn't seem to have solved it.

**Comment by brancz** [comment]
Side note, all `cortex_cache_request_duration_seconds` metrics also only report `200`s.

**Comment by brancz** [comment]
Just got note that @owen-d might know what's happening.

**Comment by brancz** [comment]
It appears that the `-server.http-write-timeout` flag actually solved this. This doesn't seem right. Is this maybe because the instant query endpoint is just proxied through to the upstream and we can't know whether it's a read or write request?

**Comment by brancz** [comment]
Nevermind it makes sense now. It's the timeout until when writing of the response must be finished. Sorry for the noise.

**Comment by owen-d** [comment]
Oh man, I was curious why I was tagged here, didn't see anything weird in the issue and eventually looked up that `server.http-write-timeout` defaults to 30s... then I noticed that there was a 33s sleep :D

**Comment by brancz** [comment]
I get why the responses returned 200s now because essentially the idea is that that's not a valid user request, but I think that should rather return some 4xx code, and or should have separate metrics to be tracked no? From what I can tell there are no metrics about these timeouts, but I might have missed them.

**Comment by brancz** [comment]
Should I open another issue for that or should we reopen this one to track that?

**Comment by gouthamve** [comment]
Lets open an new one? Or edit the title and description of this one? Either
works.

**Comment by brancz** [comment]
done https://github.com/cortexproject/cortex/issues/2297
