### ISSUE TITLE
Zookeeper for Ring KV Store?

### ISSUE THREAD

**Issue by mizeng** [cortexproject/cortex#2286]
I'm wondering if anyone tried use zookeepr for Ring KV Store? Is there any thing forbid to do this way?

**Comment by bboreham** [comment]
I wouldn't say it is forbidden but we don't really want to have every KV, NoSQL and SQL database as dependencies of the project, and the cross-product of all of them as a testing matrix.

If you have a really good rationale that might make a difference.
