### ISSUE TITLE
Feature: 'top K series over time'

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#2288]
This is something which has been requested upstream https://github.com/prometheus/prometheus/issues/586, https://github.com/prometheus/prometheus/issues/5656, but will likely never be implemented there.

The Cortex query frontend is well-placed to do it; it should be done after reassembly of sharded queries.

What I'd really like is a way to return the top N plus one more series "other" that aggregates everything else: this helps to know whether your visualisation is skewed by a lot of smaller values.

I haven't spent a lot of time thinking about how to express this in a query: it may be possible to subvert `topk()` (which you should never call in `query_range` today as it's so slow), or we could add a new function, or a parameter in the http.  The latter requires collusion from UI makers.

**Comment by bboreham** [comment]
Now being discussed again upstream: https://github.com/prometheus/prometheus/issues/7903

**Comment by pracucci** [comment]
> Now being discussed again upstream: [prometheus/prometheus#7903](https://github.com/prometheus/prometheus/issues/7903)

I think we can close it here, being eventually implemented in Prometheus.
