### ISSUE TITLE
[Feature Request]Add support of tls in etcd backended

### ISSUE THREAD

**Issue by cmsxbc** [cortexproject/cortex#2294]
It would be good to add a config options to make etcd client use tls...

**Comment by jtlisi** [comment]
@annanay25 Can this be closed?

**Comment by pracucci** [comment]
@annanay25 What's the status of this?

**Comment by annanay25** [comment]
etcd client does not have TLS support yet. TLS config options need to be added to the etcd config - https://github.com/cortexproject/cortex/blob/566dc15736256e7b60710b7f3eac40058a27a6b5/pkg/ring/kv/etcd/etcd.go#L18-L22

**Comment by jtlisi** [comment]
Fixed in https://github.com/cortexproject/cortex/pull/3102

**Comment by cmsxbc** [comment]
> Fixed in #3102

thank you~
