### ISSUE TITLE
Series API impl + index support

### ISSUE THREAD

**Issue by owen-d** [cortexproject/cortex#2313]
## What

This issue describes the current problems facing an efficient implementation of the Prometheus Series API and a possible path towards mitigating them.

/cc @gouthamve @cyriltovena 

## Background

Currently Prometheus supports a [Series API](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers) which basically has the type `Matchers -> [LabelsSet]`.

Cortex has a special case for this -- [it only queries ingesters](https://github.com/cortexproject/cortex/blob/master/pkg/querier/querier.go#L207-L214) because the `start/end` times are not included in the `Querier.Select` call. This behavior makes sense; it's infeasible to query _all_ series across _all_ time ranges in Cortex.

## Possible implementation path

1) The `Queryable` interface already has support for bounding the time range. We should be able to use this.
2) We can then ignore the fact that `*SelectParams` are not passed to the `Querier.Select` call as these boundaries are already encoded via the `Queryable.Querier` invocation.

This approach also raises some new problems: Internally, we resolve a `SeriesSet` by resolving _all_ chunks for those matchers/time range. This makes sense when we're looking for the timeseries data _inside_ chunks, but is wasteful if we're only concerned with the _series_ themselves.

Starting in the [v9 schema](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/schema.go#L693), `SeriesID`s are encoded in the index. There are even unexported functions [lookupSeriesByMetricNameMatchers](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/series_store.go#L257) and [lookupChunksBySeries](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/series_store.go#L384) to support this lookup. Therefore, we can extend the [`chunk.Store`](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/composite_store.go#L21) interface by exporting these. Then, we'd only need to pull _one_ chunk per series instead of every chunk in the time range in order to check the labels.

The combination of time bounding `/series` lookups and only needing to pull _one_ chunk per series to check labels should make Series API parity attainable.

## Context

Most of this comes from (naively) implementing the Series API in Loki: https://github.com/grafana/loki/pull/1419

**Comment by pracucci** [comment]
> Cortex has a special case for this -- it only queries distributors

I guess you mean "it only queries ingesters". We query the series in the ingesters memory. The fact we're going through the distributors (running within the queriers) is a tech debt we have since the past and we should get rid of (that code should be moved to queriers and queriers should not run distributors internally).

**Comment by pracucci** [comment]
> There are even unexported functions lookupSeriesByMetricNameMatchers and lookupChunksBySeries to support this lookup. Therefore, we can extend the chunk.Store interface by exporting these. 

I'm not sure about exporting these functions, instead of adding a single higher level function to `chunk.Store` like `GetSeries(ctx context.Context, userID string, from, through model.Time, matchers ...*labels.Matcher)`. Then it's the underlying implementation that can use ` lookupSeriesByMetricNameMatchers` and `lookupChunksBySeries` if required. In this scenario, `Get()` could be renamed to `GetChunks()` for clarity.

**Comment by owen-d** [comment]
> Cortex has a special case for this -- it only queries distributors
Eh yeah, that's a bit embarrassing. I meant ingesters 😱

**Comment by pracucci** [comment]
This issue so far is covering the chunks storage. I'm very interested into extending the discussion to the blocks storage too, where we could contribute with the implementation.

**Comment by pracucci** [comment]
How does this proposal play with the interval splitting done by the `query-frontend`? I guess no interval splitting will be done and the query will be executed by 1 single querier. Is it correct?

**Comment by owen-d** [comment]
I don't think it should be aversely affected by splitting in the `query-frontend`. We could split it in the query frontend and recombine them or distribute it to one querier. It may be easier to start on one querier and then refactor to fan-out if needed.

**Comment by owen-d** [comment]
Note, we were able to improve the implementation in loki by using the chunk fingerprints to partition `(series,chunks)` groupings in https://github.com/grafana/loki/pull/1914. This is likely a reusable approach for cortex.
