### ISSUE TITLE
FIFO cache is limited by the number of entries, but not by their total size

### ISSUE THREAD

**Issue by dmitsh** [cortexproject/cortex#2316]
FIFO cache limits number of entries, regardless of their size. I would suggest using the total memory size of the cache as the threshold to trigger eviction. That way we will have better control over memory usage, and it will be easier to configure k8s resource requests/limits.
I can put together a PR, if this proposal will be accepted.

**Comment by pracucci** [comment]
It makes sense to me. Fine-tuning a cache based on the max number of items instead of the total cache size looks complicated to me too.

**Comment by dmitsh** [comment]
> It makes sense to me. Fine-tuning a cache based on the max number of items instead of the total cache size looks complicated to me too.

Thanks Marco, I will start working on that.

**Comment by bboreham** [comment]
Can we have another really good look around the Go ecosystem and try to use a cache someone else has already tuned?

**Comment by dmitsh** [comment]
I actually looked up for existing LRU implementations before posting PR. Hashicorp has one, but they use patented algorithm. The are a few others, but they assume the cache items have equal size, so essentially their eviction approach is count based.
