### ISSUE TITLE
GPL license dependency

### ISSUE THREAD

**Issue by tamalsaha** [cortexproject/cortex#2318]
Hi,
This project depends on https://github.com/rafaeljusto/redigomock which uses GPL2 license. This is a problem for us, as we have a transitive dependency via the prometheus-operator.

github.com/coreos/prometheus-operator > github.com/thanos-io/thanos > github.com/cortexproject/cortex > redigomock

Can this be fixed?

**Comment by pracucci** [comment]
The `redigomock` project is only used in a test file in Cortex ([`redis_cache_test.go`](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/cache/redis_cache_test.go)) and it shouldn't be vendored by Thanos (being a Cortex test file) so I'm not sure how this could have an impact on the `prometheus-operator` license. Do you have any further detail to share?

**Comment by tamalsaha** [comment]
I am using fossa.com to run license scans for our projects and this was discovered as a transitive dependency. I don't see a link to share. 
![kubedb-operator - Projects   FOSSA](https://user-images.githubusercontent.com/94814/77448263-ccbe1300-6dad-11ea-8cd9-3a1831f54faf.png)

![kubedb-operator - Projects   FOSSA 2](https://user-images.githubusercontent.com/94814/77448435-07c04680-6dae-11ea-83cc-8216bc668012.png)


You can sign up for Fossa for free and run against cortext project.

**Comment by tamalsaha** [comment]
IANAL, but I don't think it matters from license pov whether some project is only used for testing purposes.

Fossa is doing transitive dependency check even if it was pruned by go mod - it seems.
