### ISSUE TITLE
Moving to Github Actions from Circle CI

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#2340]
The amount of PRs to Cortex has seen a significant uptick in the past months and with the addition of integration tests, the CI usage has increased. But because we're on the free plan I've regularly found myself waiting 30mins for tests to start running. We've reached out to CNCF regarding bumping the plan and they suggested we move to Github action as they have tons of credits there.

I think its a good idea but am curious what you folks think about it. Our growth in usage: 
![image_207](https://user-images.githubusercontent.com/7354143/77752729-05fdb980-7020-11ea-9e7c-cae8e222b3db.png)

**Comment by jtlisi** [comment]
That seems a bit excessive. Maybe when we migrate to GitHub actions we can create a workflow that stops if one step fails.

A PR that is failing to build shouldn’t run tests for instance.

**Comment by pracucci** [comment]
Still valid. I started an experiment at https://github.com/cortexproject/cortex/pull/2661 but haven't had the time to further explore it yet.

**Comment by pracucci** [comment]
_Still valid._

**Comment by pracucci** [comment]
_Still valid_

**Comment by gouthamve** [comment]
This has been implemented.
