### ISSUE TITLE
frequent memcached i/o timeout errors

### ISSUE THREAD

**Issue by KYannick** [cortexproject/cortex#2345]
I'm running a cortex v0.7.0 cluster with 4 memcached clusters to do the caching for the different components (chunks, query-results, index-read and index-write). Now I'm seeing a lot of memcache errors in all the different components (ingester, querier, query-frontend), all similar to:

`level=error ts=2020-03-26T16:10:24.434908677Z caller=memcached.go:164 msg="Failed to get keys from memcached" err="memcache: connect timeout to 10.1.8.40:11211"`

First I looked into the memcached configuration, and followed troubleshooting steps listed [here](https://github.com/memcached/memcached/wiki/Timeouts), but no success. Using the test script there, the memcache pods are alle replying consistently fast (wel below 200ms, the timeout setting in cortex), no timeouts are observed.

Looking deeper into timeouts of a querier pod, I noticed the message is printed around the time the querier itself sends a TCP RST package to the memcached pod. So it looks like the memcached client is killing the connection to memcached, and then prints an error? 

Has anybody had similar issues? Is there a solution for this?

**Comment by nustiueudinastea** [comment]
@KYannick you closed this issue but do you remember if indeed you fixed this problem or not? I am seeing similar issues, although I don't think its negatively affecting performance.

**Comment by KYannick** [comment]
@nustiueudinastea We where not able to find the root cause of those messages. We suspected it had something to do with our underlying infra, but we where not able to prove that. In the end we set up a different platform, not with cortex.

**Comment by nustiueudinastea** [comment]
Got it, thanks for your reply!

**Comment by friedrich-at-adobe** [comment]
@nustiueudinastea if you see memcached timeouts, it's very likely you need to scale up the memcached replicas.
https://github.com/friedrich-at-adobe/cortex-jsonnet/blob/main/cortex-mixin/docs/playbooks.md#cortexmemcachedrequesterrors

memcached timeouts usually mean users are getting results with delay.

**Comment by nustiueudinastea** [comment]
Hey @friedrich-at-adobe, this is happening on a cluster that is unused, so basically zero load. There are periodic timeouts and I can't tell if it's some underlying connectivity issue in AKS or something related to Loki/Memecached.
