### ISSUE TITLE
Docs: clarify the schema handling

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#2348]
See https://github.com/cortexproject/cortex/pull/2218#discussion_r388759271:

> I can't find any explanation of what a periodic table is and what the schema config is for within the Cortex doc. May be work adding an intro section explaining what's that. I've documented it into Loki some time ago (see this https://github.com/grafana/loki/blob/master/docs/operations/storage/table-manager.md) and I believe it could be a good starting point to write the Cortex one.
Not sure it's worth to mention CLI flags here. You can't configure any schema config option via CLI flag and we're about to remove them (#2208). Maybe explaining the config file is better.

**Comment by gouthamve** [comment]
Does this work? https://cortexmetrics.io/docs/configuration/schema-configuration/

**Comment by pracucci** [comment]
The comment mentioned there was mine. I think https://cortexmetrics.io/docs/configuration/schema-configuration/ still lacks of a basic explanation of what it is (I remember that the "periodic table" concept was one of the most difficult things to understand to me, when I addressed Cortex for the first time) and I believe the following description in Loki better addresses it:
https://github.com/grafana/loki/blob/master/docs/operations/storage/table-manager.md

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
A couple of months ago I've improved the [schema config documentation](https://cortexmetrics.io/docs/chunks-storage/schema-configuration/) and I think we can now close this issue.
