### ISSUE TITLE
Metric for chunks stored should take acount of de-duplication

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#2353]
Currently `cortex_ingester_chunks_stored_total` reports all chunks that were sent to the store; below that level the store may avoid the write and return success, but this isn't visible.

Similarly `cortex_ingester_chunk_stored_bytes_total`

(Note these metrics were renamed in April 2020)

(Note that even when the Cortex code doesn't detect duplication the underlying store may do so; there isn't much we can do about that in real-time)

**Comment by gouthamve** [comment]
`chunk_store_stored_chunks_total` and `cortex_chunk_store_stored_chunk_bytes_total` now report per user metric. And this is after deduping :)


See: #2463

**Comment by bboreham** [comment]
I see nothing in the description or CHANGELOG for #2463 about deduping.

**Comment by pstibrany** [comment]
> I see nothing in the description or CHANGELOG for #2463 about deduping.

I added this in https://github.com/cortexproject/cortex/pull/2579, which will eventually be merged into master.

**Comment by pracucci** [comment]
@bboreham Is the issue solved?

**Comment by bboreham** [comment]
Yes I believe it was solved by #2463
