### ISSUE TITLE
Add test for tablemanager when no scaling is enabled

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#2355]
https://github.com/cortexproject/cortex/pull/2328 

In the above PR I removed the tests for the AWS based scaler but that also includes tests that have autoscaling disabled. Adding that test seemed non-trivial but should be added back.

**Comment by pracucci** [comment]
_Still valid._

**Comment by pracucci** [comment]
_Still valid_ @gouthamve gentle reminder for you :)

**Comment by pracucci** [comment]
_Still valid_
