### ISSUE TITLE
Make all the caching components use snappy

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#2380]
We have an easy way to add [snappy](https://en.wikipedia.org/wiki/Snappy_(compression)) compression to caches, and [we do it for the index-read-cache](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/storage/caching_index_client.go#L58). But we should add it to other caches, specially the frontend-results cache.

We had it in the frontend-cache, but we lost it in this refactoring by mistake: https://github.com/cortexproject/cortex/pull/1437

**Comment by RajatVaryani** [comment]
@gouthamve Can I work on this?

**Comment by codesome** [comment]
@RajatVaryani sure go ahead!

**Comment by yeya24** [comment]
Hi, I want to work on supporting snappy cache in the query-frontend, since Thanos can also benefit from it.

Now my idea is just to add a `snappy bool` argument to the function https://github.com/cortexproject/cortex/blob/master/pkg/querier/queryrange/results_cache.go#L128. If you think this way looks ok, I can do some performance testing and open a pr.

**Comment by pracucci** [comment]
Why not directly passing `cache.NewSnappy()` to `NewResultsCacheMiddleware()`?

**Comment by yeya24** [comment]
Hi @pracucci, did you mean to always use `cache.NewSnappy` in `NewResultsCacheMiddleware()`? My idea is to make snappy configurable since if only fifo cache is enabled, then it is not necessary to use snappy.

**Comment by pracucci** [comment]
We should allow to configure which compression should be used, but I'm wondering if we should do it in the parent caller to `NewResultsCacheMiddleware()` and not in the `NewResultsCacheMiddleware()` itself.

**Comment by yeya24** [comment]
I still think that adding a EnableSnappy config to ResultsCacheConfig is better since we don't need to update the function signatures. I will create a pr and we can talk there.

**Comment by ethervoid** [comment]
I think this Issue was closed by https://github.com/cortexproject/cortex/pull/3217

**Comment by pracucci** [comment]
> I think this Issue was closed partially by this PR #3217 . In what more places would you think adding Snappy would be useful?

I think we're good with the query-frontend for now. Going to close the issue.
