### ISSUE TITLE
Add ability to list and delete keys in `pkg/ring/kv`

### ISSUE THREAD

**Issue by rfratto** [cortexproject/cortex#2382]
I'm planning on using `pkg/ring/kv` to implement an API for [grafana/agent](https://github.com/grafana/agent). Two of the things I need to do that currently aren't covered by the `kv.Client` interface are:

- List keys: The list of stored objects will be available through the API, so I need to retrieve the list of keys under a given prefix.
- Delete key: Users will be able to delete stored objects through the API, so I need `kv.Client` to provide the ability to delete a key. 

I believe the only way to handle a list operation is just to add `ListKeys(ctx context.context, prefix string) ([]string, error)` to the Client interface. 

For deletion, there's two ways I can see implementing it:

1. Return a special `kv.ErrDeleteKey` error when doing a CAS, signalling to the implementation that the underlying key should be deleted.
2. Add a `Delete` method to the Client interface. 

I'm happy to implement these myself, but I wanted to open an issue first to collect feedback and thoughts on how to implement it. 

/cc @tomwilkie @gouthamve

**Comment by pracucci** [comment]
@pstibrany Could this be a problem given this interface is also implemented by the Gossip memberlist client? I haven't checked in details, but you may already know.

**Comment by pracucci** [comment]
> aren't covered by the kv.Client interface are

Instead of adding functions to `kv.Client` interface, I'm wondering if we could keep a cleaner design having a dedicated interface

**Comment by pstibrany** [comment]
> I believe the only way to handle a list operation is just to add `ListKeys(ctx context.context, prefix string) ([]string, error)` to the Client interface.

LGTM.

> For deletion, there's two ways I can see implementing it:
> 
> 1. Return a special `kv.ErrDeleteKey` error when doing a CAS, signalling to the implementation that the underlying key should be deleted.
> 2. Add a `Delete` method to the Client interface.

I think explicit `Delete` method will be nicer, `kv.ErrDeleteKey` looks weird – it's not an error.

If you need CAS semantics, I would suggest something like `Delete(context.Context, key string, fn func(value) (delete, repeat bool, err error)) error`, where function decides whether to delete the value or not, and if not, if it should be retried, and Delete will only proceed if value hasn't changed?

`List` is trivial to implement in memberlist client. Delete will be more involved, as currently KV store implementation doesn't gossip about deleted keys. It can be added, but may require additional more complexity (keeping tombstones for deleted keys, extending protocol, deciding how to handle conflicts if one node does the delete and another one updates the key).

**Comment by rfratto** [comment]
> It can be added, but may require additional more complexity (keeping tombstones for deleted keys, extending protocol, deciding how to handle conflicts if one node does the delete and another one updates the key).

Oof, that's more complexity than I have time for right now. If possible, I'd like to do the easy clients first (etcd, Consul) and leave it as unsupported in the memberlist client until I can dedicate more time to implementing it there.

**Comment by pracucci** [comment]
> If possible, I'd like to do the easy clients first (etcd, Consul) and leave it as unsupported in the memberlist client until I can dedicate more time to implementing it there.

Then I would suggest to not add the new functions to the `kv.Client` interface. You can add the functions to the specific etcd/consul clients and create your own interface (in `grafana/agent`) for that.

**Comment by rfratto** [comment]
> Then I would suggest to not add the new functions to the kv.Client interface. You can add the functions to the specific etcd/consul clients and create your own interface (in grafana/agent) for that.

I don't mind doing this, but I'd have to copy some of the existing code from the `kv` package (metrics, config, etc). I'd like for this to eventually make its way into the upstream interface, which means I'm going to try to keep the config schemas compatible for the upstream migration path to be smooth. 

I'll defer to what you'd prefer for the package; let me know and I'll do it.

**Comment by pracucci** [comment]
> I don't mind doing this, but I'd have to copy some of the existing code from the kv package (metrics, config, etc).

Definitely don't want you to copy code. Can the code be refactored to avoid copying?

_Thinking loudly: looks just weird have a common interface between different backend implementations and then some implementations not implementing some features (which maybe it's a thing done in the past, but wouldn't advocate it's a good practice)._

**Comment by pracucci** [comment]
We discussed offline. I initially did consider only the factory (which is few lines, and still OK to copy IMO), but I didn't consider [`metrics`](https://github.com/cortexproject/cortex/blob/master/pkg/ring/kv/metrics.go) and [`prefixedKVClient`](https://github.com/cortexproject/cortex/blob/master/pkg/ring/kv/prefix.go) for which I don't have a brilliant idea to avoid code duplication. For this reason, I'm OK adding the new functions to `kv.Client`.
