### ISSUE TITLE
Links in README.md doesn't work

### ISSUE THREAD

**Issue by VineethReddy02** [cortexproject/cortex#2385]
Hi!

Under Documentation:
**A guide to running Cortex
Steps to run Cortex with Cassandra**

I see links pointing to https://cortexmetrics.io/docs/guides/production/ are resulting in 404.

**Comment by pracucci** [comment]
Thanks for noticing it! May you submit a PR to fix it, please? The correct link is https://cortexmetrics.io/docs/production/
