### ISSUE TITLE
Querier is reporting failure at synchronizing new blocks for not existent deletion-marks

### ISSUE THREAD

**Issue by kubicgruenfeld** [cortexproject/cortex#2387]
I may have found a small bug. We have failures reported every 5 minutes when querier is looking for new blocks in object storage in the metric `cortex_querier_thanos_objstore_bucket_operation_failures_total ` . I just tcpdumped it and the queriers are looking for the deletion-mark.json which are not there for all blocks and so are reporting 404 not found.
Queriers are also not reporting any error in Logs.

**Comment by pstibrany** [comment]
We need to fix this in Thanos first. Created https://github.com/thanos-io/thanos/pull/2365.

**Comment by pstibrany** [comment]
@kubicgruenfeld Thank you for reporting and investigation! Much appreciated!

**Comment by pstibrany** [comment]
Closed by #2467
