### ISSUE TITLE
Delete old WAL in ingester when checkpointing is disabled

### ISSUE THREAD

**Issue by codesome** [cortexproject/cortex#2417]
Currently, the old WAL in ingesters is not truncated if checkpointing is disabled. We need a mechanism to delete exactly the WAL which is already flushed.

**Comment by pracucci** [comment]
@codesome Is this still relevant?

**Comment by codesome** [comment]
As per the latest guidelines set, checkpointing should be always enabled when using WAL in production. Disabling checkpoints is only for development purpose. So, not relevant anymore.
