### ISSUE TITLE
Changelog dead link

### ISSUE THREAD

**Issue by snypez** [cortexproject/cortex#2422]
[CHANGE] AWS based autoscaling has been removed. You can only use metrics based autoscaling now. -applicationautoscaling.url has been removed. See https://cortexmetrics.io/docs/guides/aws/#dynamodb-capacity-provisioning on how to migrate. #2328

https://cortexmetrics.io/docs/guides/aws/#dynamodb-capacity-provisioning gives a 404

**Comment by pracucci** [comment]
The correct link is:
https://cortexmetrics.io/docs/production/aws/#dynamodb-capacity-provisioning

Could you submit a PR to fix it, please?
