### ISSUE TITLE
Multi-cluster queries

### ISSUE THREAD

**Issue by ThePants999** [cortexproject/cortex#2462]
Feature request arising from Slack discussion.

It would be nice to be able to execute a single PromQL query against the data from multiple Cortex clusters, e.g. if we have clusters in multiple regions and want to display a global dashboard.

A pure-Cortex solution might involve:
 - allowing a Querier to be configured with downstream targets, instead of finding them from the hash ring
 - having the Querier expose the same northbound interface as the Ingester, so that it can pass up raw data instead of evaluating a query.
The combination of those would allow a set of global Queriers to aggregate data from a Querier in each cluster before evaluating the query.

Another solution might be to have the Querier expose the Thanos Store API, which would allow more mixing and matching of Thanos and Cortex components. We could use the Thanos Query component at the top level, gathering data from multiple Cortex Queriers (and/or other Thanos components). I've included a diagram of this option. For fun, I've added Thanos Ruler as an example of what else this would allow - rule evaluation based on multi-cluster queries.
![cortex store api](https://user-images.githubusercontent.com/2923823/79272014-b715a800-7e98-11ea-81ec-ca4b85b8729d.png)

**Comment by chriswue** [comment]
The other option would be to make Cortex region aware so that you can have a single geo-distributed cluster where regional data gets stored in region but you can still run queries globally

**Comment by ThePants999** [comment]
Agreed - though this is effectively one way of achieving exactly that!

**Comment by chriswue** [comment]
This way has the advantage that it's based on composition of existing components which is generally good and fits the Unix philosophy however one downside is that all queries generally have to hit all regions since you don't know where the data is located.

If region awareness is built directly into Cortex then that info will be know to the queriers via the index (would most like require replicating all index data into all regions). The downside is that it adds more code to the core product.

**Comment by ThePants999** [comment]
Queries have to hit all regions if you submit the PromQL query at the top level, yes. However, if you as the user know that the data is all within a certain region, you can submit the query directly to that region's Querier(s) instead. (We'd plan to make use of that to have both global and per-region dashboards in Grafana, each using a different data source.)

**Comment by SatyKrish** [comment]
> The other option would be to make Cortex region aware so that you can have a single geo-distributed cluster where regional data gets stored in region but you can still run queries globally

Is there a sample configuration for `geo-distributed` cluster? Please share for reference.
