### ISSUE TITLE
failed to write chunk

### ISSUE THREAD

**Issue by papovyr** [cortexproject/cortex#2476]
Im running cortex v1 on EKS with following backend storage setup
AWS DynamoDB and AWS S3 
I checked I have double write capacity for dynamo db
Files get added to S3 and dynamoDB table get new record so its not permission problem 

However i receive this message in `ingester`s pod 
level=error ts=2020-04-17T01:25:43.09152441Z caller=flush.go:207 org_id=main msg="failed to flush user" err="failed to write chunk, 14 values remaining: context deadline exceeded"

I don't see any missing data 

Is this problem to write to DynamoDB or s3 ? 
This looks like potential bug.

**Comment by jtlisi** [comment]
Your ingesters are failing to flush all of their chunks before timing out. There are a number of config options that could help alleviate this. Would you mind sharing the config you are currently using for your ingesters and table manager?

**Comment by papovyr** [comment]
Thank you,

If it's DynamoDB why it says chunk vs index ?
As chunk is going to s3 and index to dynamoDB?


table-manager config
```
        args:
        - -target=table-manager
        - -server.http-listen-port=80
        - -dynamodb.url=dynamodb://us-east-1/
        - -schema-config-file=/etc/cortex/schema.yaml

        - -table-manager.index-table.write-throughput=1000
        - -table-manager.index-table.read-throughput=300

        - -table-manager.retention-deletes-enabled=true
        - -table-manager.retention-period=336h
```

ingester config 
```
        args:
        - -target=ingester
        - -ingester.join-after=30s
        - -consul.hostname=consul:8500
        - -s3.url=s3://us-east-1/my-cortex-bucket
        - -dynamodb.url=dynamodb://us-east-1/
        - -schema-config-file=/etc/cortex/schema.yaml
        - -store.chunks-cache.memcached.hostname=memcached
        - -store.chunks-cache.memcached.timeout=100ms
        - -store.chunks-cache.memcached.service=memcached
```

An other question argument   `- -ingester.max-chunk-age=12h` is for chunk(s3) or index(dynamoDB) max age,
I want to understand impact if i set this to 1h It will be too many reads from s3 or dynamoDB ? 

Im trying so setup cortex as stateless as possible, so in case of restart of ingesters i will not loose any/much data
As i'm keeping metrics for 336h, what do you think it will be better to use dynamoDB for chunk and index and set ingester.max-chunk-age to 20min, Will this perform good ? 

Thank you,

**Comment by jtlisi** [comment]
When an Ingester flushes a chunk to S3, it also creates an index entry for that chunk in DynamoDB.
