### ISSUE TITLE
configs api does not allow functions in notification templates

### ISSUE THREAD

**Issue by tehlers320** [cortexproject/cortex#2490]
While running in multi-tenant mode (i haven't tried another mode). None of the functions in Alertmanager for notification templates are taken.

https://github.com/prometheus/alertmanager/blob/v0.20.0/template/template.go#L133

While pointing at "configs" host:
`curl -XPOST -H 'X-Scope-OrgID: 0' http://localhost:8080/api/prom/configs/templates -d@mynotification.json`

> Invalid templates: template: mytemplate.tmpl:4: function "join" not defined

How to reproduce:
add a template and put this line in it

> {{ define "__subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}

**Comment by pracucci** [comment]
@jtlisi Are you aware of any issue with that?

**Comment by Wing924** [comment]
this API is documented but not implemented as it looks.
https://github.com/cortexproject/cortex/blob/master/pkg/configs/api/api.go#L94

**Comment by pracucci** [comment]
_Should still be valid_

**Comment by rsteneteg** [comment]
I suspect that the issue is here https://github.com/cortexproject/cortex/blob/master/pkg/configs/api/api.go#L250

when posting the templates are validated to make sure the parse properly but that validation seems to be missing those DefaultFuncs which is used later when actually creating the templates
