### ISSUE TITLE
Support Prometheus style stats=1 query argument for PromQL requests

### ISSUE THREAD

**Issue by garo** [cortexproject/cortex#2498]
Prometheus supports adding a stats=1 argument to any PromQL request. This will result in a "stats" structure in the JSON response. Here's an example what a native Prometheus query can give out.

```
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "results" : [...],
    "stats": {
      "timings": {
        "evalTotalTime": 0.000786023,
        "resultSortTime": 0,
        "queryPreparationTime": 4.5652e-05,
        "innerEvalTime": 0.000734111,
        "execQueueTime": 9.365e-06,
        "execTotalTime": 0.000801582
      }
    }
  }
}
```

Cortex should implement (or extend) this with additional Cortex specific information, such as:
- Was the query splitted into multiple querier instances?
- Cache hit rate (separated for chunks, indices and frontend)
- How many chunks (if any) were fetched from different chunk storage backends.
- How many indices (if any) were fetched from the index storage backends.

This serves a bit different purpose than the Jaeger tracing. Any user should be able to use this on individual query basis without any additional configuration.

**Comment by bboreham** [comment]
I would like this feature too.  It's non-trivial because we'd need to add hooks in Prometheus.

**Comment by bboreham** [comment]
Related: #3685
