### ISSUE TITLE
Gaps when querying ingesters with replication factor = 3 and 2 healthy ingesters in the cluster

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#2504]
Yesterday I've noticed that, in a Cortex cluster with 3 ingesters and a replication factor of 3, during the ingesters rollout there are gaps in queried series (for the series not flushed to storage yet). My gut feeling is that this is a bug in the ring replication strategy, but further investigation needs to be done.

**Comment by bboreham** [comment]
Duplicate of #1290 ?
