### ISSUE TITLE
Querier HTTP metrics are not working with query frontend

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#2507]
After #2437, the querier no longer passes requests from the worker to the weaveworks/common server. This means none of the instrumentation/logging middleware is used on the request.

https://github.com/cortexproject/cortex/blob/fa0fc64235063d770d6aac223b11e016cf64fcf2/pkg/cortex/modules.go#L213

The two possible solutions I see are as follows:

1. Update the weaveworks common server to allow for more control over the instrumentation middleware it configures.

2. Use a separate set of metrics instrumented specifically for the queries the worker services.

**Comment by pracucci** [comment]
I'm experimenting exposing the HTTP middlewares created by the weaveworks common server and I've done a quick test running Cortex both in microservices and single-binary mode. Looks working. I will open a PR so we can discuss about this solution.
