### ISSUE TITLE
cortex_ingester_chunk_size_bytes: why 8k boundary for last bucket?

### ISSUE THREAD

**Issue by jgehrcke** [cortexproject/cortex#2530]
The highest non-inf upper inclusive bound (`le`) value for the histogram metric `cortex_ingester_chunk_size_bytes` is currently set to 8000:

https://github.com/cortexproject/cortex/blob/55a4fcfbc07903fd722e9c72659fd8ff9a873f84/pkg/ingester/metrics.go#L177

What's the rationale for that?

Not knowing much about Cortex internals when I look at the following graph I'd love to have more resolution _within_ that last bucket between 8000 and infinity:
![Screenshot from 2020-04-27 15-19-24](https://user-images.githubusercontent.com/265630/80377685-e5818300-889b-11ea-9c73-d28587a0ccd1.png)

Let's maybe add one or more buckets more?

Is there and explicit, predictable, known upper bond of chunk size (https://github.com/cortexproject/cortex/blob/master/docs/configuration/config-file-reference.md mentions seems to focus on length and age properties, not so much actual data size in bytes).

Any feedback is welcome, especially when I misunderstand something. Thanks!

**Comment by pracucci** [comment]
I think it's reasonable add 2 more buckets (16K, 32K). Could you open a PR about it, please?

**Comment by jgehrcke** [comment]
> Could you open a PR about it, please?

Will do!

Thanks for the quick feedback.
