### ISSUE TITLE
Cassandra: allow HostSelectionPolicy to be set to TokenAwarePolicy 

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#2561]
We should allow the HostSelectionPolicy to be configured.  https://godoc.org/github.com/gocql/gocql#PoolConfig

The TokenAwarePolicy will yield the best performance.

**Comment by pracucci** [comment]
_Still valid_

**Comment by bboreham** [comment]
Help wanted: need someone with knowledge of Cassandra APIs
