### ISSUE TITLE
Add ability to output structured logs in JSON

### ISSUE THREAD

**Issue by GiedriusS** [cortexproject/cortex#2574]
#### Description

Add the ability to switch between log formats. I propose adding a new option `-log.format` that could either be `logfmt` (default and the current format) or `json`. These two options are what Thanos has and that model works well so I think Cortex could have a similar thing. 

The new option would be passed down to https://github.com/cortexproject/cortex/blob/master/pkg/util/log.go.

#### Motivation

It would be nice to have structured logs in a strict format that other systems can effortlessly understand. The use-case is to avoid adding another parsing step on top of Cortex's logs and be able to parse JSON directly. To be even more specific, I'd like to send Cortex logs to Elasticsearch and have as few parsing steps as possible.

If this would be accepted then I can make a PR. It shouldn't be too big AFAICT.

**Comment by pracucci** [comment]
We're all in to add json support. We have a stale PR https://github.com/cortexproject/cortex/pull/2386. Could you take a look at the discussion there, please?

**Comment by GiedriusS** [comment]
I plan on picking this up in the near future.

**Comment by pracucci** [comment]
Done in https://github.com/cortexproject/cortex/pull/2386
