### ISSUE TITLE
I was able to push to master despite branch protection being place

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#2578]
While merging `release-1.0` branch (with latest 1.0.1), I pushed to `master` branch on GitHub expecting to see an error due to branch protection rules in place. However, it "just" worked...

```
$ git push upstream
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 592 bytes | 592.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/cortexproject/cortex
   0ec7b9664..1ea1d190b  master -> master
```

Here is a screenshot of current branch protection:
![Screenshot 2020-05-11 at 16 11 49](https://user-images.githubusercontent.com/895919/81571403-31efb700-93a2-11ea-81e9-7ffc5feead00.png)

![Screenshot 2020-05-11 at 16 12 01](https://user-images.githubusercontent.com/895919/81571408-32884d80-93a2-11ea-8028-a36cc51d87ee.png)

**Comment by codesome** [comment]
Talking about branch protection, release branch also requires similar protection as master (I am just echoing what is done in Prometheus as it was planned to have similar release process in Cortex)

**Comment by pstibrany** [comment]
Tried to do the same today, but got error (as expected, and unlike last time):

```
$ git push upstream
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.11 KiB | 1.11 MiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/cortexproject/cortex
 ! [remote rejected]     master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/cortexproject/cortex'
```
