### ISSUE TITLE
Possible improvement in ObjectClient

### ISSUE THREAD

**Issue by cyriltovena** [cortexproject/cortex#2582]
Before diving into this improvement I figured I'd ask the team.

I've realized in Loki and this is most probably true in Cortex too, that we get a `ReadCloser` and most of the time we do a `ioutil.ReadAll`. This is widely inefficient specially that most of the time we know how much data there is to read. see https://github.com/cortexproject/cortex/blob/master/pkg/chunk/objectclient/client.go#L101

__Why is this inefficient ?__

Because the ioutil.ReadAll has no idea how much data there is to read so it creates a buffer of 512 bytes and let it grow by itself. Which cause two problem allocate 25% more memory and does more allocs which result in more CPU used.

__Solutions__

I see two possible solutions:

1. We could try to change the ObjectClient interface to have returns a 

```
func GetObject(ctx context.Context, objectKey string) (ReadCloserSize, error)

type ReadCloserSize interface {
io.ReadCloser
Size() int64
}
```

For client that can't get the size we could return 0 and consider 0 as unknown.

2. Simply try cast the io.ReadCloser to a `Sizer`

```
type Sizer interface {
Size() int64
}
```
If the cast is successful we can then use the size.

Once one or the other is implemented we will be able to allocate the buffer correctly sized prior reading.

I'm more inclined to use the second solution as it is less intrusive, but I would understand the counter argument that the interface is less clearer.

Let me know and I will start the work.

/cc @gouthamve @pracucci @pstibrany @jtlisi

**Comment by pracucci** [comment]
Looks a nice improvement and I'm OK with that. My personal preference would be the option #1 because the interface would be cleaner, but I wouldn't use `0` as "unknown" because some object stores allows zero-sized objects: we could have the interface `Size() (uint64, error)` and return a const error (ie. `ErrUnsupported`) when not available.

**Comment by gouthamve** [comment]
+1 to the idea and what @pracucci said!

**Comment by pstibrany** [comment]
Instead of adding `Sizer` to ReadCloser, can we add `ObjectSize` method to `ObjectClient`? That should be enough to make client use single allocation, if it so desires. WDYT?

**Comment by pstibrany** [comment]
Another alternative: write new ReadAll method that pools bytes buffers.

**Comment by cyriltovena** [comment]
> Instead of adding Sizer or ReadCloserSizer, can we add ObjectSize method to ObjectClient? That should be enough to make client use single allocation, if it so desires. WDYT?

Usually the size is given for free when you ask the object. Adding a new method to the ObjectClient could increase the API calls to the underlying storage.

> Another alternative: write new ReadAll function that pools bytes buffers.

It could be a good start, but without the size you still have to pay the growing price. But I'll for sure give it a go.

**Comment by pstibrany** [comment]
> Usually the size is given for free when you ask the object. Adding a new method to the ObjectClient could increase the API calls to the underlying storage.

I see. What about making it explicit then? (Using negative value as unknown)

`func GetObject(ctx context.Context, objectKey string) (ReadCloser, int64, error)`

**Comment by cyriltovena** [comment]
I thought about this too. @pracucci has some concern using 0 or negative has unknown.

May be:

`func GetObject(ctx context.Context, objectKey string) (ReadCloser, *int64, error)`

and nil if unknown ?

**Comment by pracucci** [comment]
In Thanos we recently introduced the `ObjectAttributes` struct, which holds size and last modified timestamp. Have you considered something like this?

```
// returned ObjectAttributes is nil if unsupported
func GetObject(ctx context.Context, objectKey string) (ReadCloser, *ObjectAttributes, error)

type ObjectAttributes struct {
  int64 Size
}
```

**Comment by pstibrany** [comment]
I'm fine with Marco's suggestion.

**Comment by pstibrany** [comment]
(It doesn't solve the problem of other attributes being available, but not size, but let's solve that when we get there :))

**Comment by cyriltovena** [comment]
Yeah I like this ! Specially because we need that timestamp for another features.

**Comment by cyriltovena** [comment]
one day !
