### ISSUE TITLE
Unexpected behaviour if using nested variables in grafana templates with block storage

### ISSUE THREAD

**Issue by kubicgruenfeld** [cortexproject/cortex#2612]
We are using the experimental block storage and have an issue with nested variables in Grafana.

If using template variables in Grafana like `label_values(node_load1{hardwarenode='$hardwarenode'}, instance)` and try to query data which is not present in the ingesters anymore, there are no labels found.

If templates are using no nested variables like `label_values(node_load1, instance)`, there is no problem, even querying old data as long as you use `Refresh: 'On Dashboard Load'` in Grafana.

There are some screenshots attached to show the behaviour.

Querying last 7 days with nested variables is working:
<img width="1428" alt="Bildschirmfoto 2020-05-20 um 13 02 24" src="https://user-images.githubusercontent.com/857352/82439092-65190100-9a9a-11ea-9953-39f6fc3d330d.png">

Querying a timerange not present anymore in ingesters there are no labels found for this timerange:
<img width="1427" alt="Bildschirmfoto 2020-05-20 um 13 02 08" src="https://user-images.githubusercontent.com/857352/82439187-8548c000-9a9a-11ea-8f86-de633284305e.png">

It looks like the labels are tried to be retrieved from ingesters for the selected timerange. Since labels are only queried from ingesters, there are no labels found for this timerange and therefore empty. I am not sure if this is expected behaviour or an issue.

**Comment by pracucci** [comment]
Thanks for reporting it. Looks an issue. I'm investigating it.
