### ISSUE TITLE
Question about data structure in Cassandra

### ISSUE THREAD

**Issue by jah-jh** [cortexproject/cortex#2641]
Hi all!

This is not an issue but a question about data structure in case of using Cassandra

I am new in cortex and Cassandra and trying to understand next:

About chunks:
A chunk consists of 3 columns: hash, range,  value

The **hash**, for example, looks like this `0/dded239cb02b50e6:172419b94f2:172442e4dc2:6e84c184` - it is splited colon. So what does each part mean?

**range** - for the test I have selected 1000 rows and got only "0x00". What is the purpose of the column  range in this case?

**value**  - a long long hex data. But when I try to convert this to text, I get only half value as text and another half is unreadable symbols

About index:
**hash** - for example `00:0:d18406:apiserver_registered_watchers:kind`. Looks more readable, but the same question about parts divided by a colon
**range** - also unreadable hex value. What is the purpose?
***value*** - for example `0x41504953657276696365` which transform to text `APIService`.
What is the value that has to be stored in this column?

I leave here a lot of question but it will be great if I get an answer even for one.
Or get info where I can clarify all of that by myself

Regards and have a good day!

**Comment by storyicon** [comment]
@jah-jh Hello, after reading the code, I have done some PPT for these contents, which may help you, but the following content is unofficial:
![image](https://user-images.githubusercontent.com/29772821/83094726-e0029d00-a0d4-11ea-8ba3-fd53038cf072.png)
![image](https://user-images.githubusercontent.com/29772821/83095759-9adf6a80-a0d6-11ea-9edf-5492acaa9660.png)
![image](https://user-images.githubusercontent.com/29772821/83094990-1cce9400-a0d5-11ea-92eb-058f500df873.png)
![image](https://user-images.githubusercontent.com/29772821/83095124-396acc00-a0d5-11ea-9a57-d35233ab41c1.png)
Based on your description, it is clear that you are using the Schema V10+.
You can see the detailed code here: 
https://github.com/cortexproject/cortex/blob/b4b3ebcd6d3c127884ede8eb70cfbadcabe7e37a/pkg/chunk/schema.go#L783

**Comment by jah-jh** [comment]
Thank you.
This is more than I expected

**Comment by jtlisi** [comment]
@storyicon Thanks for the great answer! I think we can close this now.
