### ISSUE TITLE
Clarification on http-prefix ending with a trailing slash

### ISSUE THREAD

**Issue by Sayrus** [cortexproject/cortex#2643]
Hello,

Today I upgraded from Cortex 0.7 where I used `http.prefix=/`. While testing things, I understood that the behavior of `http.prometheus-http-prefix` (and `http.alertmanager-http-prefix`) is different from what `http.prefix` used to do.

Using the value `/` or `/something/` will lead to 404 errors that are hard to spot.

I understand that Cortex is doing strict matching so it might not make sense to normalize URLs to avoid match `http://domain.com//api` as `http://domain.com/api`, however I do think it might be a good idea to warn the user about this behavior. Either in the documentation or as a startup warning `<...-http-prefix> has a trailing slash, this might not behave as you expect`.
When using CLI, this is even more confusing as the expected value to match on the root is nothing, which looks like this: `--http.prometheus-http-prefix=`. This is prone to being deleted as it doesn't looks like we are setting anything.

I have not found anything regarding this decision (I might have missed it) so I am asking here.

Is this the expected behavior? Does it deserve a warning?

Best regards,

**Comment by gouthamve** [comment]
This looks like a bug that needs to be fixed. Will send a fix for it soon!

**Comment by pracucci** [comment]
_Still valid_

**Comment by Sayrus** [comment]
The expected behavior is to ignore trailing slashes, right? @pracucci @gouthamve 

Which would mean that the following have the same behavior:
```
--http.prometheus-http-prefix=
--http.prometheus-http-prefix=/
--http.prometheus-http-prefix=//
```

**Comment by pracucci** [comment]
I believe the right fix would be concatenating paths using `path.Join()` instead of `+` in `pkg/api/api.go`. For example, changing:

```
a.RegisterRoute(a.cfg.PrometheusHTTPPrefix+"/api/v1/admin/tsdb/delete_series", http.HandlerFunc(deleteRequestHandler.AddDeleteRequestHandler), true, "PUT", "POST")
```

to:

```
a.RegisterRoute(path.Join(a.cfg.PrometheusHTTPPrefix, "/api/v1/admin/tsdb/delete_series"), http.HandlerFunc(deleteRequestHandler.AddDeleteRequestHandler), true, "PUT", "POST")
```

@jtlisi What do you think?
