### ISSUE TITLE
how to delete old metric data and export metirc from Ingester ?

### ISSUE THREAD

**Issue by Jamlee** [cortexproject/cortex#2653]
i have deploy single node and scale up to 3 replication. 
is there any to delete old metric data in single node with localstorage?
is there any to export metric data in single node to other back storage like cassandra?

**Comment by pracucci** [comment]
👋 @Jamlee 

> is there any to delete old metric data in single node with localstorage?

Could you give more details about what you would like to delete, specifically?

> is there any to export metric data in single node to other back storage like cassandra?

Could you share more details about your use case here, please?

**Comment by Jamlee** [comment]
@pracucci 
Could you give more details about what you would like to delete, specifically?
some data whom is a month ago.

is there any to export metric data in single node to other back storage like cassandra?
3 single node cluster is  deployed in my production with local storage. could i migrate it to  cassandra without data loss ?

**Comment by pracucci** [comment]
>> is there any to delete old metric data in single node with localstorage?
> for example, some data whom is a month ago.

The local chunks storage is not meant for production usage and doesn't support retention.

>> is there any to export metric data in single node to other back storage like cassandra?
> 3 single node cluster is deployed in my production with local storage. could i migrate it to cassandra without data loss ?

We currently don't provide a tool to migrate data between two backend storages. You would need to build it yourself (we can give inputs, if needed).

**Comment by Jamlee** [comment]
@pracucci, thanks, buddy. got it!
