### ISSUE TITLE
How to treat "sample timestamp out of order"?

### ISSUE THREAD

**Issue by storyicon** [cortexproject/cortex#2662]
My remote write has a large number of stacks, and cortex's distributor prints a large number of "sample timestamp out of order". Should such samples be discarded?
When distributor finds out of order sample, it will return 400. Does this trigger the retry mechanism of Prometheus and cause the sample to Ping Ping Ping Pong continuously? (It looks like this, but I did n’t delve into it)

**Comment by pracucci** [comment]
> My remote write has a large number of stacks, and cortex's distributor prints a large number of "sample timestamp out of order". Should such samples be discarded?

Given a single remote write request (which contains multiple samples), Cortex discards all samples whose timestamp is out of order, while successfully ingest other ones. Then Cortex returns a 400 response status code to signal that at least 1 sample was discarded.

> When distributor finds out of order sample, it will return 400. Does this trigger the retry mechanism of Prometheus and cause the sample to Ping Ping Ping Pong continuously?

No, it doesn't. Prometheus does **not** retry to send the remote write request on 4xx, while it does retry on 5xx or network error (ie. timeout).

> My remote write has a large number of stacks, and cortex's distributor prints a large number of "sample timestamp out of order".

If you constantly see a large number of "sample timestamp out of order" then there's very likely an issue somewhere. It's not expected to see it under normal conditions. The first things to check are:

1. If you have Prometheus HA pairs, make sure the Cortex HA tracker is correctly configured and Prometheus cluster/replica labels correctly setup (see this [brief doc](https://cortexmetrics.io/docs/production/ha-pair-handling/))
2. Make sure all ingesters are healthy and responsive (ingesters latency, error rate, ...)
3. Check for which metrics Cortex logs the "timestamp out of order" error and make sure the related Prometheus exporters are working correctly (ie. no clashing series after Prometheus relabelling, especially on the cAdvisor metrics which expose [metrics with timestamp](https://github.com/google/cadvisor/issues/2123))

**Comment by storyicon** [comment]
Thanks, very valuable response. @pracucci 

We have a panel to monitor `Prometheus Remote Write lag time`:
```
(time() - prometheus_remote_storage_queue_highest_sent_timestamp_seconds{instance_name=~"$name"}) < 100000
```
When this value is very high, the warning for `sample timestamp out of order` will appear in large numbers. I will track prometheus to find the source of the problem.
