### ISSUE TITLE
Add docs for Experimental gRPC store

### ISSUE THREAD

**Issue by VineethReddy02** [cortexproject/cortex#2664]
Add configuration details needed for the cortex config file and steps to integrate the third-party database for index & chunk store.

**Comment by VineethReddy02** [comment]
I will work on this.

**Comment by pracucci** [comment]
@VineethReddy02 A gentle reminder of your promise when we merged the gRPC plugin PR: that documention would have been written in a subsequent PR 😉

**Comment by VineethReddy02** [comment]
I will raise a docs PR this week.

Thanks!
