### ISSUE TITLE
Separate Integration Test Suites

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#2672]
The integration tests on this repo are exceedingly large. I think we should consider adding multiple build tag parameters to organize the tests into separate groups. 

A well thought out set of [build constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints) should allow related groups of tests to be grouped together and still preserve the option to run all integration tests in a row at once.

This would enable use to break up our CICD integration tests into multiple parallel steps which would be nice since after a push it takes ~20 minutes to know if you are passing all of the test cases.

**Comment by pracucci** [comment]
I agree on the strategy, but the problem is that we don't have enough workers/cores in CircleCI. This is the reason why last friday I started experimenting with GitHub actions (CNCF would sponsor some extra capacity there).

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Less a need since when we moved to GitHub actions (CI looks faster), but still a nice to have_

**Comment by jtlisi** [comment]
*still valid*, CI is approach 30+ minutes

**Comment by pracucci** [comment]
_Still valid_
