### ISSUE TITLE
Calrification on -distributor.replication-factor

### ISSUE THREAD

**Issue by ninjaslothx** [cortexproject/cortex#2698]
Hey,
I was just looking for some clarity on the -distributor.replication-factor option.
In the docs it says "The number of ingesters to write to and read from."
Does this mean this value should always be matched to the amount of running ingesters?
Or is it a parallelism setting and this can be set lower than the total ingester count?  

Thanks in advanced!

**Comment by pracucci** [comment]
👋  @ninjaslothx. This question was recently asked in another issue. Please see this reply https://github.com/cortexproject/cortex/issues/2622#issuecomment-632588878. If you have further questions you can reply to #2622.

**Comment by ninjaslothx** [comment]
Apologies I failed to search thoroughly!

**Comment by pracucci** [comment]
> Apologies I failed to search thoroughly!

No problem at all! I just wanted to move the discussion to #2622 so that we can keep further conversations in a single place. Thanks!
