### ISSUE TITLE
Document for the `-target` parameter does not align with the ALL target defined in module manager

### ISSUE THREAD

**Issue by alvinlin123** [cortexproject/cortex#2710]
Currently the command line document for `-target` it says applicable values are `all, distributor, ingester, querier, query-frontend, table-manager, ruler, alertmanager, configs`. 

However, reading [coretex/modules.go](https://github.com/cortexproject/cortex/blob/master/pkg/cortex/modules.go#L554) it looks like there are more possible values for `-target`; take `data-purger` for example. 

I am wondering if this intentionally so, or it was just the document was not updated after adding new module? If it's the later case, I would love to work on this and make the document dynamic, so we don't have to remember to update the document when adding new module.

**Comment by Andrewpk** [comment]
It should also be noted that the cli option prefix is `purger`, while the module is named `data-purger`.

It also appears to depend on various other configured options that are undocumented, such as those relating to the `data-purger` dependency, `store`.

**Comment by Andrewpk** [comment]
I've been looking through the docs, code, and tests (`purger_test.go` was some help) at all of the options needed to get `data-purger` target to start as a standalone module successfully.

**Comment by pracucci** [comment]
> However, reading coretex/modules.go it looks like there are more possible values for -target; take data-purger for example.

Some modules are just internal dependencies and shouldn't be used as a target. However, you're right that the CLI flag documentation is missing: flusher, compactor, store-gateway, data-purger. Could you open a PR to fix it, please?

> It should also be noted that the cli option prefix is purger, while the module is named DataPurger and the target is defined as data-purger.

True. @sandeepsukhani Given series deletion is still marked as experimental, what do you think if we rename the module from `data-purger` to `purger`?

**Comment by sandeepsukhani** [comment]
> True. @sandeepsukhani Given series deletion is still marked as experimental, what do you think if we rename the module from data-purger to purger?

Sounds good. Will open a PR soon.

**Comment by Andrewpk** [comment]
@pracucci I still have been unable to get data-purger starting as a standalone service, otherwise I would have. I'm currently using Cassandra as the storage backend for chunks and index and running into the following error on v1.1.0:
```
caller=cortex.go:348 msg="module failed" module=data-purger error="invalid service state: Failed, expected: Running, failure: line 1:56 no viable alternative at input 'value' (...FROM delete_requests WHERE hash = [?] value...)"
```

Once I'm able to get data-purger running I can submit a PR with knowledge gained from the successful config though!

Also, thank you @sandeepsukhani for working on the delete API. Very cool stuff and great work.

**Comment by pracucci** [comment]
> ```
> caller=cortex.go:348 msg="module failed" module=data-purger error="invalid service state: Failed, expected: Running, failure: line 1:56 no viable alternative at input 'value' (...FROM delete_requests WHERE hash = [?] value...)"
> ```

@sandeepsukhani Are you aware of this issue?

**Comment by sandeepsukhani** [comment]
@Andrewpk can you please share all the logs?

**Comment by Andrewpk** [comment]
@sandeepsukhani I wasn't sure this was the right avenue for the logs, so I submitted a new issue here - https://github.com/cortexproject/cortex/issues/2718

**Comment by alvinlin123** [comment]
> Some modules are just internal dependencies and shouldn't be used as a target. However, you're right that the CLI flag documentation is missing: flusher, compactor, store-gateway, data-purger. Could you open a PR to fix it, please?

I will work on this this or next weekend (hopefully this )
