### ISSUE TITLE
Memcached related: "malformed: key is too long or contains invalid characters".

### ISSUE THREAD

**Issue by zhuyanxi** [cortexproject/cortex#2714]
I am using Cortex to deal with some metrics, but the Cortex Ingester component has the following errors:
level=error ts=2020-06-11T08:58:55.71876902Z caller=memcached.go:164 msg="Failed to get keys from memcached" err="malformed: key is too long or contains invalid characters"
level=error ts=2020-06-11T08:58:55.91751264Z caller=memcached.go:237 msg="failed to put to memcached" name=chunks err="malformed: key is too long or contains invalid characters".

I know the memcached max key size is 250 bytes, so I think this error may coursed by my origin metrics data, but I can't change my metrics data. So, how can I deal with this problem?

(I think that whether Cortex can change the memcached key to a Hash string or not, then the key size will always less than 250.)

**Comment by pracucci** [comment]
👋  @zhuyanxi. We do already use an hash for the chunk, but the tenant/user ID is not hashed. Could you check if the tenant IDs used in your system are very long?

**Comment by zhuyanxi** [comment]
@pracucci Thanks very much for your suggestion. 
I changed some code in `pkg\chunk\cache\memcached.go` to print out more logs about keys. And I found this:

```bash
level=error ts=2020-06-23T02:54:18.382573651Z caller=memcached.go:237 msg="zhuyanxi failed to put to memcached" key="Basic Zm9vMTpxd2U=/70a4b870c51a91e1:172dc85668c:172df186d7c:fc9c26b" err="malformed: key is too long or contains invalid characters"
```

So the key is combined with my tenant ID and S3 object ID, `Basic Zm9vMTpxd2U=` is the tenant ID and it contain a whitespace which `memcached` not allowed . So I  changed `X-Scope-OrgID` from `$http_authorization` to `$remote_user` in my nginx config file:

```bash
proxy_set_header X-Scope-OrgID $remote_user;
```

Then it worked, I solved my problem by change the `X-Scope-OrgID`.

But what if the tanant ID comes from another application and I can not control it. So I think, maybe Cortex can do remove the whitespace when generate the memcached key, or hash the key is more better. Thanks.

**Comment by pracucci** [comment]
Thanks @zhuyanxi for the details. You're right, whitespaces are not allowed, which subsequently limits the tenant ID to not have a whitespace too.

_Let's keep the issue open to further discuss how we could fix it._

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_
