### ISSUE TITLE
[bug] cortex_ingester_memory_chunks become negative after ingester OOM

### ISSUE THREAD

**Issue by Wing924** [cortexproject/cortex#2734]
### What I Did

* start failure test against cortex cluster by sending 4M active series metrics
* cortex can't sand so many metrics and ingesters repeatedly OOM and restarted by k8s

### What I Got

* `cortex_ingester_memory_chunks` become negative after OOM a few times

### What I Expected

* `cortex_ingester_memory_chunks` should be always `>=0`

### Versions

* cortex v1.1.0
* ingesters with WAL enabled
* use cassandra for both index & chunks

<img width="1290" alt="スクリーンショット 2020-06-17 9 49 10" src="https://user-images.githubusercontent.com/8895721/84842444-1900b280-b080-11ea-9165-121447d55cb4.png">

**Comment by pracucci** [comment]
@codesome Has this issue been fixed after Cortex 1.1.0 or am I mistaken?

**Comment by codesome** [comment]
I don't remember exactly regarding the fix, I will take a look.

**Comment by Wing924** [comment]
@codesome any updates?

**Comment by codesome** [comment]
_Still valid_, but I haven't got around investigating this yet
