### ISSUE TITLE
Get rid of pkg/configs/legacy_promql

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#2755]
We should stop using `pkg/configs/legacy_promql` because it cause troubles each time we upgrade Prometheus and some interfaces have changed.

**Comment by pracucci** [comment]
@jtlisi Could you give me some context about why we need `pkg/configs/legacy_promql` and how we can do to get rid of it, please?

**Comment by jtlisi** [comment]
The use of this library predates me working on the Ruler. I'm not sure why it is needed

**Comment by pracucci** [comment]
@bboreham Just [confirmed on Slack](https://cloud-native.slack.com/archives/CCYDASBLP/p1593502386275700?thread_ts=1593502197.275300&cid=CCYDASBLP) they still need it.

**Comment by pracucci** [comment]
_I'm going to close it for now. We'll reconsider it if requirements will change._
