### ISSUE TITLE
Make label name validation optional

### ISSUE THREAD

**Issue by replay** [cortexproject/cortex#2770]
Currently the distributor validates all label names on ingested data, to enforce the Prometheus label requirements as [described here](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)

In our use case of Cortex it would be very useful if there was a way to disable this validation, to allow a wider range of characters in the label names.

The distributor [calls the validation here](https://github.com/cortexproject/cortex/blob/1188a9128287b43854f6ea67e57b6151c6a20cb3/pkg/distributor/distributor.go#L335) and passes in an object of type `validation.Overrides` which satisfies the interface `validation.LabelValidationConfig`. I propose we add an additional method `EnforceLabelNames()` to that type & interface, then we allow the user to configure this setting the same way as the already existing setting `EnforceMetricName()`.

**Comment by pracucci** [comment]
Sure, I'm OK to introduce an option to disable it. However, have you tried to run your system commenting out that validation to make sure everything else work?

**Comment by pstibrany** [comment]
Feel free to send PR with proposed change. I'm bit worried that it may break stuff elsewhere, but since Cortex won't use it (let's not make it visible to the users), it's fine with me.

**Comment by replay** [comment]
> Sure, I'm OK to introduce an option to disable it. However, have you tried to run your system commenting out that validation to make sure everything else work?

Yes, I've used the latest commit in my PR (1f58646639c7c14ab32e8ac7cc3c111ec96f3d53) and ingested a bunch of metrics with chinese characters in label names & values, I was able to query them back without any issues.
