### ISSUE TITLE
Flake in TestPurger_Metrics()

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#2776]
```
--- FAIL: TestPurger_Metrics (0.27s)
    purger_test.go:435: 
        	Error Trace:	purger_test.go:435
        	Error:      	Max difference between 259200 and 172800 allowed is 1, but difference was 86400
        	Test:       	TestPurger_Metrics
FAIL
```

Failed at https://circleci.com/gh/cortexproject/cortex/33030
Passed at https://circleci.com/gh/cortexproject/cortex/33041

**Comment by pracucci** [comment]
@sandeepsukhani Could you look at it, please?

**Comment by sandeepsukhani** [comment]
> @sandeepsukhani Could you look at it, please?

The problem was that the test was chasing a moving target.
Opened a PR to fix it https://github.com/cortexproject/cortex/pull/2777

**Comment by bboreham** [comment]
Back again? https://github.com/cortexproject/cortex/runs/1656724172

**Comment by sandeepsukhani** [comment]
Pushed a possible fix for it https://github.com/cortexproject/cortex/pull/3657.
Most likely it was due to a race between check for expected metric value and updating it.
