### ISSUE TITLE
Ruler: Add an API endpoint to known which Alertmanagers you have discovered

### ISSUE THREAD

**Issue by gotjosh** [cortexproject/cortex#2782]
Prometheus [has an API](https://prometheus.io/docs/prometheus/latest/querying/api/#alertmanagers) to let you know which Alertmanagers you have discovered. The ruler should have something similar given we support some form of service discovery as you can see here:

https://github.com/cortexproject/cortex/blob/173bb1c1939211e7115278663a05cffd2ebdec3b/pkg/ruler/notifier.go#L83-L108

cc: @cstyan

**Comment by gotjosh** [comment]
This is still valid.

**Comment by pracucci** [comment]
_Still valid, help wanted!_

**Comment by gotjosh** [comment]
There's at least two reasons I can think of why we want to do this:

- Our service discovery will try to discover the alertmanagers the moment the ruler is initialized. However, metrics for discovered alertmanagers won't be present until we configure a tenant. It is hard to know whenever we've properly configured and discovered alertmanagers.

- As a precedent, the Prometheus API already implements this and we try to keep parity when sensible. Operators might expect this to be present when it is not.

**Comment by cstyan** [comment]
bump
