### ISSUE TITLE
Update to stop using deprecated `grpc/naming` package

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#2785]
It is gone from the latest gRPC release 1.30.

I found a notice announcing this: https://github.com/grpc/grpc-go/issues/3180

Also interesting: why didn't the deprecated package raise a lint warning?

**Comment by nicolai86** [comment]
I'd like to pick this up. Any objections?

**Comment by pracucci** [comment]
_Still valid. Required by future upgrade to gRPC 1.3.0._

**Comment by jtlisi** [comment]
_still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by jtlisi** [comment]
https://github.com/etcd-io/etcd/pull/12709

**Comment by pracucci** [comment]
We're not using the upstream `grpc/naming`  anymore but, due to convenience, we've imported some of its code in `pkg/util/grpc/naming`. I'm going to close this issue, given we don't have plans to get rid of it, but feel free to reopen it if you want to reconsider it.
