### ISSUE TITLE
Remove deprecated record from chunks WAL after v1.2.0

### ISSUE THREAD

**Issue by codesome** [cortexproject/cortex#2793]
New WAL records were introduced in v1.1.0, so with the v1 guarantees, we need to support the old records for up to 2 releases. As the old record was introduced in v1.0.0, it is supported till v1.2.0, hence can be removed for v1.3.0 and get rid of lot of grpc code + complexity in WAL replay.

I will pick this up in future unless someone does it before me :)

**Comment by codesome** [comment]
Some pointers: https://github.com/cortexproject/cortex/blob/0ea2318b0174d98b4b85590fdd10e7d4568505ae/pkg/ingester/wal.go#L1183-L1185

(It's the `*Record` returned by this method that needs to be removed)

**Comment by pracucci** [comment]
_Still valid._

**Comment by codesome** [comment]
_I will work on this_
