### ISSUE TITLE
Flaky TestSweepImmediateDropsSamples

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#2825]
While running the CI ([see here](https://app.circleci.com/pipelines/github/cortexproject/cortex/6799/workflows/0857eac0-d9df-49b2-a173-959c6d536702/jobs/34219/steps)) for a PR doing changes unrelated to flushing, I've noticed that `TestSweepImmediateDropsSamples` is flaky.

The test has been recently introduced in https://github.com/cortexproject/cortex/pull/2778.

**Comment by pracucci** [comment]
I'm reopening the issue because this test is still flaky ([see here](https://app.circleci.com/pipelines/github/cortexproject/cortex/6845/workflows/e40db45b-2d08-4777-8e2e-7049467bb20e/jobs/34420/steps)):

```
--- FAIL: TestSweepImmediateDropsSamples (0.01s)
    flush_test.go:97: 
        	Error Trace:	flush_test.go:97
        	            				flush_test.go:41
        	            				flush.go:354
        	            				flush.go:319
        	            				flush.go:220
        	            				asm_amd64.s:1373
        	Error:      	Received unexpected error:
        	            	rpc error: code = Code(500) desc = user=1: ingester stopping
        	Test:       	TestSweepImmediateDropsSamples
    flush_test.go:52: 
        	Error Trace:	flush_test.go:52
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 0
        	Test:       	TestSweepImmediateDropsSamples
```

**Comment by pstibrany** [comment]
I think that PR is based on older master (https://github.com/cortexproject/cortex/commit/54f10c2b1223bf16ca955ac517b55fa878d5de50) without the fix.
