### ISSUE TITLE
Wait stable store-gateway ring state before running the initial blocks sync

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#2827]
In the event of a cluster cold start or scale up of 2+ store-gateway instances at the same time we may end up in a situation where each new store-gateway instance starts at a slightly different time and thus each one syncs blocks based on a different state of the ring.

## Example of the issue

Consider this cold start scenario (SG = store-gateway):
- T1: SG1 starts
- T2: SG2 starts
- T3: SG1 begins synching blocks based on the current state of the ring (ring: SG1)
- T3: SG3 starts
- T4: SG2 begins synching blocks based on the current state of the ring (ring: SG1, SG2)
- T5: SG3 begins synching blocks based on the current state of the ring (ring: SG1, SG2, SG3)

In case of a replication factor of 1 (but the same applies to clusters with a replication factor > 1), SG1 will initially sync all blocks, SG2 will initially sync 50% of blocks, SG3 will initially sync 30% of blocks.

## Proposal

An idea would be introducing a buffer period before starting synching blocks. During this buffer period we do monitor the ring and wait until the ring state is stable (doesn't change) for at least X seconds, before running the initial sync.

The same approach could be applied to the sync done by the store-gateway each time the ring topology changes, in order to cover the case of existing store-gateway instances re-synching after a scale up (so that they will re-synch blocks once all scaled up instances have started).

Under normal conditions, it's not necessary to have a very large buffer period. For example, 1 minute could be a reasonable default to cover a cluster deployed to Kubernetes.

**Comment by pracucci** [comment]
_Still valid._

**Comment by amckinley** [comment]
➕ 1, this has bitten us when doing a cold start after migrating Cortex from one k8s cluster to another. We normally run 9 `store-gateways` so each one normally starts up pretty quickly, but when cold starting, all `store-gateways` attempt to fetch the index for all blocks, causing them all to eventually fail when they fill their disks.

**Comment by jtlisi** [comment]
We should verify that the `token-observe-period` feature is operative for all KV stores. If so, that is a valid workaround for this issue.
