### ISSUE TITLE
Stream chunks from ingesters to querier when running the blocks storage

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#2845]
When running a query in a Cortex cluster running the **chunks storage**, the querier fetches (encoded) chunks from ingesters and these chunks are decoded in the querier itself.

On the contrary, when running the **blocks storage**, the chunks are decoded in the ingester and the querier fetches (decoded) SeriesSet from ingesters. This puts extra pressure on the ingesters, based on the query QPS and the number of series touched by each query.

We want to stream chunks from ingesters to querier in the blocks storage too.

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid._

**Comment by jtlisi** [comment]
_still valid_

**Comment by jtlisi** [comment]
Closed by #3889
