### ISSUE TITLE
Flusher doesn't report flush problems via exit code.

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#2879]
Flusher is a Cortex component designed to flush local data (chunks WAL, blocks WAL and unshipped blocks) to long term storage.

Currently, when Flusher finishes it triggers clean shutdown of Cortex. This happens even if there were any errors during the flush. Errors are only reported in the log.

It would be desirable to use exit code as an indicator of whether Flusher has succeeded or not.

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by pstibrany** [comment]
Still valid.
