### ISSUE TITLE
Support for DNS discovery for alertmanagers to find peers in a cluster

### ISSUE THREAD

**Issue by samitpal** [cortexproject/cortex#2883]
It might be a good addition to add DNS discovery capability in multi-tenant alertmanager to discover peers. Right now there is a `-cluster.peer` flag which can be used multiple times but that has to be done statically. I tried with a dns host with multiple IP targets  with `-cluster.peer` but it seems like the dns name does not get re-resolved when a host goes down.

**Comment by pracucci** [comment]
Could you check if https://github.com/cortexproject/cortex/pull/2851 solve your issue, please?

> I tried with a dns host with multiple IP targets with -cluster.peer but it seems like the dns name does not get re-resolved when a host goes down.

@gotjosh Are you aware of this?

**Comment by gotjosh** [comment]
I think this is slightly different but can use similar mechanisms. I've added the capability to discover Alertmanagers from the ruler, this is about discovering other Alertmanagers from the Alertmanager itself.

**Comment by gotjosh** [comment]
Could you please assign this to me @pracucci?

**Comment by pracucci** [comment]
> Could you please assign this to me @pracucci?

Definitely, done! 🙏

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by gotjosh** [comment]
Do we still want this? Moving forward, I'm not sure I see a point in improving the old clustering form.

**Comment by pracucci** [comment]
> Do we still want this? Moving forward, I'm not sure I see a point in improving the old clustering form.

I think the way ahead is the ring-based alertmanager scalability, which is what we're currently working on.

**Comment by jtlisi** [comment]
Closing this because we will be solving the use case of this issue using a ring-based scalable alertmanager
