### ISSUE TITLE
Cleanup cortex flags

### ISSUE THREAD

**Issue by roidelapluie** [cortexproject/cortex#2890]
Some flags double print defaults:

        Preallocated buffer size for downloads (default is 512KB) (default 512000)
        Preallocated buffer size for up;oads (default is 256KB) (default 256000)
        Number of buffers used to used to upload a chunk. (defaults to 1) (default 1)

In addition to that, it would be great to specify values in a user friendly way, e.g. by using proper units (kingpin uses https://github.com/alecthomas/units).

**Comment by pracucci** [comment]
_I'm working on the doc right now. I take care of removing all defaults from CLI flag description (they're auto generated). I would keep the units thing as a separate work._
