### ISSUE TITLE
Use fnv32a hash in the compactor

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#2894]
In https://github.com/cortexproject/cortex/pull/2887 we learned that fnv32a hash acts better when hashed values slightly change (eg. tenant IDs). We should use it in the blocks compactor sharding as well.

**Comment by maxbrodin** [comment]
I might be wrong, but doesn't compactor [already use fnv32a](https://github.com/cortexproject/cortex/blob/master/pkg/compactor/compactor.go#L453)

```go
// Hash the user ID.
hasher := fnv.New32a()
_, _ = hasher.Write([]byte(userID))
userHash := hasher.Sum32()
```

**Comment by pracucci** [comment]
Yeah, my fault. I opened the issue without even looking at the code 🤦
