### ISSUE TITLE
[feat] support snappy compressor for gRPC

### ISSUE THREAD

**Issue by Wing924** [cortexproject/cortex#2898]
### WHAT

Let's support snappy compressor for gRPC.

### WHY

Currently, we only have gzip for gRPC compressor.
The gzip use too much CPU.
The snappy is better than gzip for real-time compressing.

**Comment by bboreham** [comment]
Have you run any benchmarks?  I guess we should know the tradeoff in compression size as well as CPU.  (and memory?)

No objection if those support your proposal.
