### ISSUE TITLE
Ruler panics when deleting and recreating managers

### ISSUE THREAD

**Issue by joe-elliott** [cortexproject/cortex#2907]
If you create a rule group for a user it will cause the ruler to create a prometheus manager for that rule group:

https://github.com/cortexproject/cortex/blob/31fed8bffecc3b834a4d97c2c3b3fe280d15c32c/pkg/ruler/ruler.go#L511

If you then delete all rule groups associated with a user it will drop that user:

https://github.com/cortexproject/cortex/blob/31fed8bffecc3b834a4d97c2c3b3fe280d15c32c/pkg/ruler/ruler.go#L477-L486

If you then create a rule group for that user again it will attempt to recreate a new prometheus rules manager which causes a duplicate metrics registration panic:

```
cortex-1_1       | level=info ts=2020-07-21T17:04:09.304481991Z caller=mapper.go:115 msg="updating rule file" file=/rules/fake/test
cortex-1_1       | panic: duplicate metrics collector registration attempted
cortex-1_1       | 
cortex-1_1       | goroutine 867 [running]:
cortex-1_1       | github.com/prometheus/client_golang/prometheus.(*wrappingRegisterer).MustRegister(0xc003260d80, 0xc002ce6e60, 0xa, 0xa)
cortex-1_1       | 	/home/joe/dev/joe-elliott/cortex/vendor/github.com/prometheus/client_golang/prometheus/wrap.go:102 +0x195
cortex-1_1       | github.com/prometheus/prometheus/rules.NewGroupMetrics(0x3eaa2e0, 0xc003260d80, 0x90)
cortex-1_1       | 	/home/joe/dev/joe-elliott/cortex/vendor/github.com/prometheus/prometheus/rules/manager.go:146 +0xb6b
cortex-1_1       | github.com/prometheus/prometheus/rules.NewManager(0xc0016f82d0, 0xc0016f82d0)
cortex-1_1       | 	/home/joe/dev/joe-elliott/cortex/vendor/github.com/prometheus/prometheus/rules/manager.go:863 +0x172
cortex-1_1       | github.com/cortexproject/cortex/pkg/ruler.(*Ruler).newManager(0xc00014a100, 0x3ed06a0, 0xc001b341c0, 0xc001376b06, 0x4, 0xc003716f00, 0xc003260cc0, 0x1)
cortex-1_1       | 	/home/joe/dev/joe-elliott/cortex/pkg/ruler/ruler.go:554 +0x4c1
cortex-1_1       | github.com/cortexproject/cortex/pkg/ruler.(*Ruler).syncManager(0xc00014a100, 0x3ed06a0, 0xc001b341c0, 0xc001376b06, 0x4, 0xc000dbd350, 0x1, 0x1)
cortex-1_1       | 	/home/joe/dev/joe-elliott/cortex/pkg/ruler/ruler.go:511 +0x69e
cortex-1_1       | github.com/cortexproject/cortex/pkg/ruler.(*Ruler).loadRules(0xc00014a100, 0x3ed06a0, 0xc001b341c0)
cortex-1_1       | 	/home/joe/dev/joe-elliott/cortex/pkg/ruler/ruler.go:474 +0x87f
cortex-1_1       | github.com/cortexproject/cortex/pkg/ruler.(*Ruler).run(0xc00014a100, 0x3ed06a0, 0xc001b341c0, 0x0, 0x0)
cortex-1_1       | 	/home/joe/dev/joe-elliott/cortex/pkg/ruler/ruler.go:427 +0x282
cortex-1_1       | github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main(0xc000880240)
cortex-1_1       | 	/home/joe/dev/joe-elliott/cortex/pkg/util/services/basic_service.go:167 +0x3f7
cortex-1_1       | created by github.com/cortexproject/cortex/pkg/util/services.(*BasicService).StartAsync.func1
cortex-1_1       | 	/home/joe/dev/joe-elliott/cortex/pkg/util/services/basic_service.go:96 +0xa8
tsdbblocksstorages3singlebinary_cortex-1_1 exited with code 2
```

cc @jtlisi @gotjosh

**Comment by joe-elliott** [comment]
@gotjosh @jtlisi 

What do you think is the best fix here?  I'm considering two:

- Leave managers in the map even if there are no related configs
- When adding the manager we are currently wrapping with a user/userid label:
  ```
  reg := prometheus.WrapRegistererWith(prometheus.Labels{"user": userID}, r.registry)
  ```
We could add another label here like "generation" and chuck a GUID in it to prevent collisions, but I feel like that would create some strange metrics/dashboards.

Personally, I prefer the first, but it does introduce a kind of memory leak.

**Comment by jtlisi** [comment]
We had the same problem in the alertmanager. We solve it using the struct defined [here](https://github.com/cortexproject/cortex/blob/master/pkg/alertmanager/alertmanager_metrics.go)

**Comment by gotjosh** [comment]
In this case, it seems like the manager metrics struct [is public](https://github.com/prometheus/prometheus/blob/master/rules/manager.go#L70). We can get away with keeping the map of registries around and not having to refine the metrics which is the only approach I'm not in love with.

**Comment by pracucci** [comment]
@joe-elliott I tend to agree with @gotjosh on this issue. I left a comment in the PR. Adopting Josh idea should be easy. @gotjosh could you take a look at my comment in the PR https://github.com/cortexproject/cortex/pull/2909: is that you what you had in mind or something different?

**Comment by gotjosh** [comment]
That's exactly what I had in mind @pracucci 👌

**Comment by jtlisi** [comment]
@pracucci We don't currently trim down metrics from the ruler. However, I've always felt that was a mistake on my part when I initially implemented it. I'm fine with the map moving forward. However, I think it's worth considering a devoted metrics struct in the future.

**Comment by pracucci** [comment]
> However, I think it's worth considering a devoted metrics struct in the future.

@jtlisi Which ruler metrics would you keep and which discard? And why? _I'm just trying to understand the rationale._

**Comment by jtlisi** [comment]
@pracucci 

The specific metrics I had in mind our:

```
# HELP cortex_prometheus_rule_evaluation_duration_seconds The duration for a rule to execute.
# TYPE cortex_prometheus_rule_evaluation_duration_seconds summary

# HELP cortex_prometheus_rule_group_duration_seconds The duration of rule group evaluations.
# TYPE cortex_prometheus_rule_group_duration_seconds summary
```

**Reason**: Both of these metrics are per-user summaries, which means they're cardinality is: `(<# users> * 7 * <# rulers>)`. Also since they are summaries instead of histograms, aggregating them across instances is not meaningful. I think it would make sense to wrap these metrics and only return the `_sum` and `_count` values. 

I feel this would make the most sense. However, this is **not** a priority and is not causing any ongoing issues.
