### ISSUE TITLE
Cortex frontend downstream url

### ISSUE THREAD

**Issue by Misosooup** [cortexproject/cortex#2921]
Hi,

Does this config support an SRV record? I tried with dnssrv+my.internal.url but it doesn't seem to resolve properly and error out.

Many thanks.

**Comment by pracucci** [comment]
👋  @Misosooup 

The query-frontend downstream URL doesn't support SRV records. Could you share more details about your use case, please?

**Comment by Misosooup** [comment]
I see. We have deployed cortex frontend in ECS. We have set up service discovery with ECS and were given SRV records to route traffic to different services / containers. 

I have deployed it together with our querier at the moment so using an SRV record is no longer required at the moment, but I was hoping it to be a standalone service.

**Comment by pracucci** [comment]
If you're running the query-frontend in front of a Cortex cluster, the suggested way is not using the downstream URL but configuring the querier **worker** to connect to the query-frontend (and here we do support SRV records).

Take a look at the frontend worker and feel free to ask any question (I will happy to help)=:
https://cortexmetrics.io/docs/configuration/configuration-file/#frontend_worker_config

**Comment by Misosooup** [comment]
Ok. I am currently using Thanos's querier instead of Cortex's querier. I didn't want to use dynamodb hence chosen to use Thanos since Cortex block storage is still in the beta phase. 

What I have done now is that the downstream url for cortex frontend is pointing to thanos's querier. I am not sure if this setup is right or not but what I want, is to utilise the parallel query that cortex frontend provides.

**Comment by pracucci** [comment]
Ok. Is having a load balancer in front of Thanos queriers an option, so that you configure the query-frontend downstream URL to the load balancer?

**Comment by Misosooup** [comment]
Yeah that would work too.

**Comment by pracucci** [comment]
Ok @Misosooup. I think having a load balancer in front of your backend Thanos querier would be the expected setup. I'm going to close this issue, but feel free to re-open it if doesn't work for any reason.
