### ISSUE TITLE
Use uber-go/atomic in place of sync/atomic

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#2923]
Same as prometheus/prometheus#7647

**Comment by jvrplmlmn** [comment]
I would like to take on this issue.

**Comment by pracucci** [comment]
Sure @jvrplmlmn I would be glad to review it! Feel free to go on 🙏

**Comment by pstibrany** [comment]
@jvrplmlmn While working on that, would it be also possible to verify other usage of uber-go/atomic and remove unnecessary allocations (calls to `New*`)?
