### ISSUE TITLE
Ruler API should not accept invalid rules files

### ISSUE THREAD

**Issue by cstyan** [cortexproject/cortex#2942]
The Ruler API that allows users to write rules files to Cortex should return an error to users who try to upload invalid rules files, for example a rule group with no name.

cc @gotjosh

**Comment by s-h-a-d-o-w** [comment]
Coincidentally, @gotjosh and I spoke about this just before.

To provide some more details - this is the end point: https://cortexmetrics.io/docs/apis/#set-rule-group

And here a collection of cases that should return an error:
- Empty payload
- No rule group name
- No rules

Possibly also:
- Props that don't exist on the schema. Reason being: A user might've made a typo when trying to specify `interval`.

**Comment by s-h-a-d-o-w** [comment]
Just noticed that this issue overlaps with [this one](https://github.com/cortexproject/cortex/issues/2942).

**Comment by cstyan** [comment]
We can reuse `promtool check rules <files>` for this. I'll have to make some changes upstream so that that check functionality is available as an importable function first though.
