### ISSUE TITLE
[bug] sharding throws "expected type scalar in call to function histogram_quantile"

### ISSUE THREAD

**Issue by annanay25** [cortexproject/cortex#2952]
... while attempting to shard binary expressions.

### Failing test
Adding the following test case
```
{
	desc:   "should skip encoding fractions",
	query:  `histogram_quantile(1/2, sum(rate(cortex_cache_value_size_bytes_bucket[5m])) by (le))`,
	mapped: `histogram_quantile(1 / 2, sum by(le) (__embedded_queries__{__cortex_queries__="{\"Concat\":[\"sum by(le, __cortex_shard__) (rate(cortex_cache_value_size_bytes_bucket{__cortex_shard__=\\\"0_of_2\\\"}[5m]))\",\"sum by(le, __cortex_shard__) (rate(cortex_cache_value_size_bytes_bucket{__cortex_shard__=\\\"1_of_2\\\"}[5m]))\"]}"}))`,
},
```
... to `TestQueryshardingCorrectness` https://github.com/cortexproject/cortex/blob/27e2d46bc2bf6c8d9da6fece93cdb230d2198394/pkg/querier/queryrange/querysharding_test.go#L330 fails at the moment, with the following error message:

```
--- FAIL: TestQueryshardingCorrectness (0.04s)
    --- FAIL: TestQueryshardingCorrectness/should_skip_encoding_fractions (0.00s)
        querysharding_test.go:426:
            	Error Trace:	querysharding_test.go:426
            	Error:      	Expected nil, but got: parser.ParseErrors{parser.ParseErr{PositionRange:parser.PositionRange{Start:19, End:86}, Err:expected type scalar in call to function "histogram_quantile", got instant vector, Query:"histogram_quantile(__embedded_queries__{__cortex_queries__=\"{\\\"Concat\\\":[\\\"1 / 2\\\"]}\"}, sum by(le) (__embedded_queries__{__cortex_queries__=\"{\\\"Concat\\\":[\\\"sum by(le, __cortex_shard__) (rate(cortex_cache_value_size_bytes_bucket{__cortex_shard__=\\\\\\\"0_of_2\\\\\\\"}[5m]))\\\",\\\"sum by(le, __cortex_shard__) (rate(cortex_cache_value_size_bytes_bucket{__cortex_shard__=\\\\\\\"1_of_2\\\\\\\"}[5m]))\\\"]}\"}))", LineOffset:0}}
```

### Current hypothesis

The subtree_folder should avoid encoding `*parser.UnaryExpr, *parser.BinaryExpr` here -
https://github.com/cortexproject/cortex/blob/bebf7c9bead7b2492810e0682b0180440db7700a/pkg/querier/astmapper/subtree_folder.go#L25

... but only when it is used as a numerical literal like in `histogram_quantile(1/2, <vec>)`

/cc @owen-d

**Comment by owen-d** [comment]
Good analysis! I haven't looked into the promql code much since it was refactored, but I'd take a look at `UnaryExpr` to make sure we shouldn't encode that or figure out which circumstances it should vs shouldn't be. 

Regarding the `BinaryExpr`, it should not be encoded in _this_ case, but there are many cases where it should be. There might need to be a check on binary expressions to see if they're composed of two numeric literals, in which case they can avoid encoding.
