### ISSUE TITLE
Document how flusher works with blocks storage

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#2972]
We should improve the flusher documentation and, in particular, cover the blocks storage too.

**Comment by ranton256** [comment]
The best documentation I found is here:
https://cortexmetrics.io/docs/production/ingesters-with-wal/
I hadn't found that yet when I said high level docs were confusing.

It still specifically mentions chunk storage.

"There is a flusher target that can be used to flush the data in the WAL. It’s config can be found here. As flusher depends on the chunk store and the http API components, you need to also set all the config related to them similar to ingesters (see api,storage,chunk_store,limits,runtime_config and schema). Pro tip: Re-use the ingester config and set the target as flusher with additional flusher config, the irrelevant config will be ignored."

"You can run it as a Kubernetes job which will:

    Attach to the volume of the scaled down ingester.
    Recover from the WAL.
    And flush all the chunks.
"
This last bit is basically what I wasn't clear on before.  I was trying to understand if this was intended to be a state you temporarily restarted an ingestor in, or what, which that makes clear, just had some trouble discovering the right place where it was described.

What do you think we should do to make the flusher instructions(mainly purpose) more discoverable? I think having to find it in the WAL docs is what led me a bit astray, so maybe there is somewhere else to hilight this info?

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid, help wanted_

**Comment by pracucci** [comment]
_Still valid, but probably low priority (flusher is not that common)._

**Comment by pracucci** [comment]
_Still valid, but low priority._
