### ISSUE TITLE
Default Cassandra replication factor considered harmful

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#2993]
https://github.com/cortexproject/cortex/blob/9a9648f431e537a3a7b0752161a8d009582ed848/pkg/chunk/cassandra/storage_client.go#L60

Cortex will initialize a keyspace with a replication factor of 1 by default. Even if this value is changed later, it will not alter the Keyspace with the new value. This is not ideal and unless a user carefully ensures this value is set when bootstrapping cortex, they could end up with a cassandra backend that is not fault tolerant. Ideally, this value should default to 3, since this allows for a Quorum to be reached without any particular Cassandra node.

**Comment by pracucci** [comment]
Cassandra backend storage is still marked experimental. We can introduce a config breaking change here, moving from a default of `1` to a default of `3`. What do you think?

**Comment by jtlisi** [comment]
I think that makes sense.
