### ISSUE TITLE
Query on data Cortex works only time range > 30m

### ISSUE THREAD

**Issue by gizmosense** [cortexproject/cortex#2999]
From Grafana , query of multi tenant metrics data only works 30minutes and above .
is there a limitation or a setting to have latest data out out of cortex say 5m ?

**Comment by gizmosense** [comment]
i have a update for above, since i am using cortex for first time , my observations were misplaced.  Indeed 5 mins data also comes out of cortex for multiple clusters but the reason for above yesterday and cortex stopping to ingest/store/send data to grafana could be lot of timestamp errors i was getting   - so i have a question to the cortex users team and admins -  when we scale distributors / ingestors -  is there a possibility of some mismatch on new ingestors coming throwing timestamp errors due to some mistmatch in handling flow or order.   above error got solved only after i stop and started API writing frmo all proms sending data.

**Comment by pracucci** [comment]
👋  @gizmosense 

> is there a limitation or a setting to have latest data out out of cortex say 5m ?

No. You can query back a sample from Cortex as soon as it is successfully ingested in Cortex, even a millisecond after.

> when we scale distributors / ingestors - is there a possibility of some mismatch on new ingestors coming throwing timestamp errors due to some mistmatch in handling flow or order.

No, it shouldn't.

> lot of timestamp errors i was getting

Which errors did you get? Could you share a snippet of logs, please?

**Comment by gizmosense** [comment]
thanks for the response, i use 7 to 10 prom to push data to cortex  and further to grafana.
i solved timestamp errors by adding global external label. but i still get sometime timestamp  errors in cortex ingester and also suddenly data stops coming to grafana one cluster by one .. not sure it is over load or else ?
tried memcache , but memcache k8 svc url never gets identified in ingester during start , although can be reached from within the pod. i will put the error back here once i get  i just cleared and restarted cortex.

**Comment by gizmosense** [comment]
i come back again , now with some findings and requesting more help - because we are trying to setup a production grade .
a) everytime something happens to one of few of prom source  - say some connection error or Prom went down or any network issues , after it is restored in few mins or say 30 mins or more , we start getting timestamp errors  ( initially we had timestamp errors everytime got solved with global external label) 
level=warn ts=2020-08-13T04:13:58.22989026Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=345.377µs err="rpc error: code = Code(400) desc = user=fake: sample timestamp out of order; last timestamp: 1597289367.42, incoming timestamp: 1597289352.42 for series {__name__=\"node_ipvs_backend_connections_active\", app=\"eric-pm-server-3pp-components\", app_kubernetes_io_managed_by=\"Helm\", chart=\"eric-pm-server-3pp-components-0.0.8\", cluster=\"dualstack-udm-5444\", component=\"node-exporter\", heritage=\"Helm\", instance=\"dualstack-udm-5444-worker-4\", job=\"kubernetes-service-endpoints\", kubernetes_name=\"eric-pm-server-node-exporter\", kubernetes_namespace=\"monitoring\", local_address=\"10.1.0.163\", local_port=\"443\", proto=\"TCP\", release=\"eric-pm-server-3pp-components\", remote_address=\"10.1.107.186\", remote_port=\"443\"}" msg="gRPC\n"

Lots of errors like this for different sources and eventually even the working prom data stops showing up in grafana. and all proms stop showing data in Grafana.  
We are still able to see metrics in cortex data source of Grafana , but no data.

b) if for some reason ingestor pod is scaled up or ingester pod and cortex pods restarts  - i start getting following error
caller=flush.go:207 org_id=fake msg="failed to flush user" err="Cannot achieve consistency level QUORUM"
i tried clearing all stuff and resintall cortex components , i couldn't solve this error , until i cleared Cassandra data and reinstalled.
Does cortex flush everytime we resintall cortex pods , or due to error . will the data persist when cortex is resintalled ?

c) for the error b ) , i tried reinstalled ingester or cortex - the consul key hangs in consul and creates problem for fresh installation, only works when i manually delete the consul key of old ingester.

d) i thought of using a good stable daemon based Cassandra in a VM 
[cqlsh 5.0.1 | Cassandra 3.11.7 | CQL spec 3.4.4 | Native protocol v4]
but it does not work with cortex setup i have , 
- aller=log.go:140 msg="error initializing cortex" err="gocql: unable to create session: unable to discover protocol version: dial tcp 10.117.134.94:9042: connect: connection refused\


what could be the issue ?

only cassie-cassandra git library works.
https://signoz.io/blog/ha-prometheus-cortex-cassandra/

**Comment by pracucci** [comment]
> sample timestamp out of order

In my experience, this shouldn't happen in case of a networking issue between Prometheus and Cortex. However, this could happen (and is expected to happen) when Prometheus is **restarted** (eg. after a crash). The reason is that at startup Prometheus replays the WAL and send it to Cortex again and thus it may (and will) send samples already ingested by Cortex. In this scenario, this is an expected condition and doesn't lead to any data loss (on the Cortex side) because if we receive a timestamp older then the most recent one (for a given series), we just discard it and log the message "sample timestamp out of order".

**Comment by pracucci** [comment]
> Cannot achieve consistency level QUORUM

This looks to be a Cassandra-specific error. @jtlisi may help on this.

**Comment by pracucci** [comment]
> Does cortex flush everytime we resintall cortex pods , or due to error . will the data persist when cortex is resintalled ?

It depends how you run it. I would suggest you to this doc page as entrypoint https://cortexmetrics.io/docs/guides/ingesters-rolling-updates/, then I can answer more specific questions (if you have any).

**Comment by pracucci** [comment]
> aller=log.go:140 msg="error initializing cortex" err="gocql: unable to create session: unable to discover protocol version: dial tcp 10.117.134.94:9042: connect: connection refused\

The error you get is "connection refused". Looks a networking issue. Maybe something has been misconfigured.

**Comment by gizmosense** [comment]
> sample timestamp out of order
> 
> In my experience, this shouldn't happen in case of a networking issue between Prometheus and Cortex
> However, this could happen (and is expected to happen) when Prometheus is restarted (eg. after a crash). The reason is that at startup Prometheus replays the WAL and send it to Cortex again and thus it may (and will) send samples already ingested by Cortex.
> In this scenario, this is an expected condition and doesn't lead to any data loss (on the Cortex side) because if we receive a timestamp older then the most recent one (for a given series), we just discard it and log the message "sample timestamp out of order".

thanks for the response : It looks normal if prmetheus send again same data with wrong timestamp or some timestamp mismatch  , but what i see this is only time i see grafana stops showing cortex data . i don't lose metrics identification from cortex datasource , but data does not come anymore , it comes back only after i stop and start prom push

**Comment by gizmosense** [comment]
> aller=log.go:140 msg="error initializing cortex" err="gocql: unable to create session: unable to discover protocol version: dial tcp 10.117.134.94:9042: connect: connection refused\
> 
> The error you get is "connection refused". Looks a networking issue. Maybe something has been misconfigured.

yeah i solved it  it works with Cassandra daemon install now

**Comment by pracucci** [comment]
> it comes back only after i stop and start prom push

You mean after you restart Prometheus?

**Comment by gizmosense** [comment]
> it comes back only after i stop and start prom push
> 
> You mean after you restart Prometheus?

no just stop rewrite api and start write api in config  , brings back data in grafana !
wondering how that can be related to cortex and qyert response behavior

**Comment by pracucci** [comment]
> no just stop rewrite api and start write api in config

Sorry. I'm not sure I do understand. Are you speaking about Prometheus config, right?

If so, Prometheus will reply again the WAL (similarly like when you restart the Prometheus process) and send it to the remote write endpoint (Cortex in this case). The "sample timestamp out of order" is expected because of the reason explained above.

However, doesn't look normal that Prometheus, at some point, stops remote writing and you need to restart it (either restart Prometheus or restart the remote write). Prometheus exposes multiple metrics about the remote write: I would suggest you to take a look at it.

**Comment by gizmosense** [comment]
> no just stop rewrite api and start write api in config
> 
> Sorry. I'm not sure I do understand. Are you speaking about Prometheus config, right?
> If so, Prometheus will reply again the WAL (similarly like when you restart the Prometheus process) and send it to the remote write endpoint (Cortex in this case). The "sample timestamp out of order" is expected because of the reason explained above.
> However, doesn't look normal that Prometheus, at some point, stops remote writing and you need to restart it (either restart Prometheus or restart the remote write). Prometheus exposes multiple metrics about the remote write: I would suggest you to take a look at it.

configmap reload takes care about taking new config without restart for Prometheus , so stop/start of prom data is smoothly done, but as soon as i do that  , Cortex starts send data or grafana starts showing data !!  if WAL is resent during stop and start -it means timestamp errors are solved and back to normal  , cortex sends data to grafana .  but if timestamp errors are thrown , will data query fail in cortex?

**Comment by pracucci** [comment]
> configmap reload takes care about taking new config without restart for Prometheus

What I described above applies anyway. Prometheus live reload the config but, internally, the remote write is restarted when you disable and then re-enable it in the same exact way it would do if you restart Prometheus at all.

**Comment by gizmosense** [comment]
> configmap reload takes care about taking new config without restart for Prometheus
> 
> What I described above applies anyway. Prometheus live reload the config but, internally, the remote write is restarted when you disable and then re-enable it in the same exact way it would do if you restart Prometheus at all.

yes may be push is restarted , so does it mean , some network glitch  timestamp error, we come back live , Prometheus needs to restart push to be able make cortex work well . because Ingester's throwing timestamp causes grafana query to stop - is there a relation to both this behaviors. ?
