### ISSUE TITLE
Unable to query when not using public IPs

### ISSUE THREAD

**Issue by jakubgs** [cortexproject/cortex#3004]
I'm trying to get a 3 host Cortex cluster running, but I don't want to use public IPs for it and avoid having to set up certs.
Since my ports are closed to the public side the connections to other nodes on `9095` port fail:
```
 > curl -s 'http://localhost:9092/prometheus/api/v1/label/__name__/values' | jq .
{
  "status": "error",
  "errorType": "execution",
  "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 12.34.56.78:9095: i/o timeout\""
}
```
All of my hosts are connected via [Tinc](https://www.tinc-vpn.org/) VPN and have IPs in the `10.0.0.0` subnet, but when I try to use them for `grpc_listen_address` to a VPN address on each host like `10.0.0.1-3` the result is a lot of these error in logs:
```
level=error
caller=worker_frontend_manager.go:90
msg="error contacting frontend" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:9095: connect: connection refused\""
```
Where `Error while dialing dial tcp 127.0.0.1:9095: connect: connection refused` clearly indicates that the `worker_fontend_manager` is trying to connect to GRPC via the localhost address, but server is only listening on `10.0.0.*`.

How am I supposed to configure this to use the Tinc VPN IPs?

I looked at the [configuration docs](https://cortexmetrics.io/docs/configuration/configuration-file/#ingester_config) and could not find anything in `frontend_worker_config` section that would let me configure the IP address it should be connecting to GRPC.

**Comment by pracucci** [comment]
👋  @jakubgs 

Few things the come to my mind:
1. Make sure the ingesters have been registered in the `/ring` with the right IP address. By default we detect each Cortex instance IP from a list of default interfaces (eth0 en0). You should just change the `-ingester.lifecycler.interface` CLI flag (or its YAML config option) to pick up the IP from the right network interface.
2. The querier workers (running within the Cortex querier) connects to the query-frontend based on the configured endpoint at `-querier.frontend-address` (or its respective YAML config file). Does this address resolves to the right set of IPs?

**Comment by jakubgs** [comment]
Thanks @pracucci ! Setting `ingester.lifecycler.interface_names` to `tun0` for my VPN interface solved the issue:
```
 > curl -s 'http://localhost:9092/prometheus/api/v1/labels'
{"status":"success","data":[]}
```
Now the queries are coming through!

But I also noticed that there are other `instance_interface_names` settings that don't appear to be documented:
```
 % curl -s http://10.1.33.0:9092/config | grep -A 2 interface
    instance_interface_names:
    - eth0
    - en0
--
    interface_names:
    - tun0
    final_sleep: 30s
--
    instance_interface_names:
    - eth0
    - en0
--
    instance_interface_names:
    - eth0
    - en0
--
    instance_interface_names:
    - eth0
    - en0
```
Should I be changing those too?

>The querier workers (running within the Cortex querier) connects to the query-frontend based on the configured endpoint at `-querier.frontend-address` (or its respective YAML config file). Does this address resolves to the right set of IPs?

I don't think I understand what `fontend.frontend_address` setting is supposed to be? Is it supposed to be the address of a Prometheus instance? Or the Cortex instance itself? Or another Cortex instance? The docs just say:
>Address of query frontend service, in host:port format.

So that means that it would have to be the VPN IP of that host plus the port `server.http_listen_port` of the instance?

**Comment by jakubgs** [comment]
Okay, i set the `frontend_worker.frontend_address` to the address of the local VPN interface + the GRPC port and it works!

Brilliant, thanks for your help @pracucci ! Appreciate it.

**Comment by pracucci** [comment]
Excellent @jakubgs. Happy it's working! 💪
