### ISSUE TITLE
Clarify that the blocks storage doesn't use the schema

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3006]
We should clarify that the blocks storage doesn't use the schema (which is chunks storage specific).

**Comment by pracucci** [comment]
Valuable feedback received on Slack on where people would expect this clarification:

> I would personally expect it on the main Blocks Storage page https://cortexmetrics.io/docs/blocks-storage/, probably in the Architecture section but the Configuration section would also work.
> Then I think it would also be good to have a note in https://cortexmetrics.io/docs/configuration/schema-configuration/

**Comment by pstibrany** [comment]
+ schema flag itself should mention that it’s only needed for chunks

**Comment by pstibrany** [comment]
Btw, #3070 added this warning when Cortex starts with blocks storage and schema at the same time: `"schema configuration is not used by the blocks storage engine, and will have no effect"`
