### ISSUE TITLE
Provide a way to force reload of blocks by querier and store-gateways

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#3020]
In some situations it's useful to reload blocks sooner than configured periodic reload happens.

**Comment by pracucci** [comment]
Few questions:
1. Could you clarify "reload" in the issue description please? Is it rescan or really reloading blocks (eg. re-download blocks index-header on store-gateways)?
2. How should behave in regards to the cache? Should we bypass the cache on read, but still writing it? If yes and we send the same reload request to all instances in a large cluster, could this negatively affect performances and eventually hit object store rate limiting?

**Comment by pstibrany** [comment]
I guess I had a need for this once, but not since. Closing for now.
