### ISSUE TITLE
Add a glossary to the documentation

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3023]
While supporting Cortex users, I've noticed many times there's no clear understanding of some terms we're used to frequently mention in our doc (or while giving support). It's perfectly fine for a newcomer and I believe we should do a better job to explain terms.

Some terminology we should explain:
- tenant / user / org (see https://github.com/cortexproject/cortex/issues/2987)
- flush / flushing
- series
- sample
- chunk (both related to chunks and blocks storage)

_Please comment with other terms you think we should document._

**Comment by ranton256** [comment]
It's already described [here](https://cortexmetrics.io/docs/architecture/#chunks-storage-default), but if you are adding a glossary it should probably cover for new folks what constitutes a chunk.

**Comment by pstibrany** [comment]
> It's already described [here](https://cortexmetrics.io/docs/architecture/#chunks-storage-default), but if you are adding a glossary it should probably cover for new folks what constitutes a chunk.

"Chunk" is also used by TSDB, used by blocks engine. We can explain the difference as well.

**Comment by pracucci** [comment]
👍 👍 👍  on chunk (very good suggestion, thanks!)

**Comment by weeco** [comment]
Some more ideas which I could imagine being helpful to explain:

- index / index symbols / index header
- TSDB (block)
- churn
- ingester handover
- labels & label values
- gateway
- HA Tracker (probably reference to architecture docs?)
- Ring (Hash Ring)
- WAL
- Schema (Config)

**Comment by pracucci** [comment]
_Still valid, help wanted!_
