### ISSUE TITLE
Bad entry in overrides should be more noticeable

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#3031]
Symptom:

```
level=error ts=2020-08-13T10:03:45.497348374Z caller=manager.go:85 msg="failed to load config" err="yaml: unmarshal errors:\n  line 58: key \"redacted\" already set in map"
```

I need sirens going off and lights flashing, because now it has dropped all of my overrides and data is being unfairly rejected.

Related: #2957, #1433

**Comment by bboreham** [comment]
In the community meeting @gouthamve pointed me at `cortex_runtime_config_last_reload_successful`

**Comment by bboreham** [comment]
Also it was suggested that a failure on first load should be a fatal error, which would halt a rolling update.

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
Done in https://github.com/cortexproject/cortex/pull/3707.
