### ISSUE TITLE
Add better documentation for downstream_url

### ISSUE THREAD

**Issue by andsens** [cortexproject/cortex#3039]
This might be subjective and is solely based on my own experience. The docs for `-frontend.downstream-url` do not sufficiently explain what will happen when using it:
```yaml
# URL of downstream Prometheus.
# CLI flag: -frontend.downstream-url
[downstream_url: <string> | default = ""]
```

My impression was that this had something to do with `generator_url` in alerts etc. (don't ask me how I arrived at that conclusion though). Nevertheless, I pointed it at my actual prometheus instance, which resulted in the query-frontend returning 404 errors for all endpoints, and I couldn't for the life of me figure out why. Only when I integrated Jaeger and got some tracing up and running did I see that the requests ended up at Prometheus.

tbh I still don't understand what this is *for*. [I can see what it does](https://github.com/cortexproject/cortex/blob/9c6b2293ef1bc654ccdf16177f803546cf2715da/pkg/querier/frontend/frontend.go#L108-L111), but I don't understand the motivation.

**Comment by pracucci** [comment]
You're right. Documentation is lacking here.

The query-frontend is a queries accelerator. It has been initially built around Cortex and it was working only for cortex (using the Cortex querier workers connecting to the query-frontend and **not** setting `downstream_url`), but then people asked to make it run also in front of a vanilla Prometheus or Thanos.

So the query-frontend has been extended to also run in front of Prometheus / Thanos setting a `downstream_url`. In this setup, the idea is that you set the `downstream_url` to your Prometheus server endpoint or Thanos querier, and query-frontend will accelerate queries.

**Comment by srijan55** [comment]
@andsens @pracucci - added some documentation with this - https://github.com/cortexproject/cortex/pull/4570
Please have a look.
