### ISSUE TITLE
feature: allow caller to say that query is not worth caching

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#3049]
We run weekly reports for customers, which make several sizeable queries over 1 week of data, which are extremely unlikely to be run again until next week, and then on different data.

These queries cause a lot of cache writes, and because Cortex caches everything, they may displace data in the cache that will be needed again.

So I would like some kind of "cache control header" to state this query is not worth caching.

**Comment by pracucci** [comment]
We added basic support for `Cache-Control` in #3054. Does that cover your use case @bboreham ?

**Comment by bboreham** [comment]
I don't think so, since #3054 only changed the query-frontend and the problem I described here is in the querier.

**Comment by pracucci** [comment]
_Still valid._

**Comment by bboreham** [comment]
I guess this is still valid, though I think with blocks store the trade-offs are different - if store-gateway still has the data on its disk it is relatively cheap to re-populate memcached.
