### ISSUE TITLE
Table-Manager: Create/Update table before deleting tables

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#3055]
https://github.com/cortexproject/cortex/blob/e2a36a7385654cc8b99c646c7f90653ad19ad76c/pkg/chunk/table_manager.go#L340-L350

When the table manager actually attempts to sync and operate on the chunk storage backend it will proceed in the following order:

1. Delete
2. Create
3. Update

If any of these operations fail at any point, the entire sync will return. This can lead to issues for users who have delete operations that are unsuccessful, since new tables will not be created. This means new data will not be flushed since no table exists to support it. I propose the following order:

1. Create
2. Update
3. Delete

This order will prioritize write availability over storage retention.

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid, help wanted!_

**Comment by daemon1024** [comment]
Hello, I was looking to getting involved with the project. Can I work on this?

**Comment by pracucci** [comment]
Hi @daemon1024 none is working on this issue. If you're a Cortex user, I would suggest you to start from an issue you will directly benefit from.

For example, the table-manager is used only by the chunks storage, and a good amount of Cortex users (including my employer) are moving or already moved to the blocks storage, so if you're not running the chunks storage I would suggest you to take a look at the [blocks storage issues](https://github.com/cortexproject/cortex/labels/storage%2Fblocks), which is the direction where the community is heading to.

**Comment by daemon1024** [comment]
Hi @pracucci , I am not a Cortex user, I am a student looking to get involved with CNCF in general this seemed like an interesting project hence looking into the `good-first-issues`

**Comment by jtlisi** [comment]
Closing this since chunks storage is now in maintenance mode.
