### ISSUE TITLE
Entire push skips WAL if there's a validation error in any of its samples

### ISSUE THREAD

**Issue by bcharron** [cortexproject/cortex#3059]
If I understand correctly, when using chunk-storage, if a single sample fails validation during ingestion (ie, due to out-of-order or duplicate timestamp), then none of the samples in the request will make it to the WAL either, even though some may have been added to the chunk: https://github.com/cortexproject/cortex/blob/master/pkg/ingester/ingester.go#L435

**Comment by pracucci** [comment]
@codesome Could you investigate this, please?

**Comment by codesome** [comment]
What @bcharron said is true :scream:, fix is small but I am facing tiny issues while writing test for it. I will send a PR to fix this on Monday.
