### ISSUE TITLE
Expose TLS server name parameter in TLS client options

### ISSUE THREAD

**Issue by simonswine** [cortexproject/cortex#3063]
I suggest adding add `tls-server-name` parameter to all TLS client options https://github.com/golang/go/blob/cd10f5f632983e63b156478abdfa0bd57e93898c/src/crypto/tls/common.go#L592

Without having the ability to configure a expected ServerName, it will be relatively hard to supply the correct certificates, as through our ring discovery we are mostly connecting to IP addresses and the certificate will then have the IP SAN set accordingly.

IP address can be quite hard to predict and this might get quite tricky in terms of cert management.

**Comment by pracucci** [comment]
The PR #3156 is still open and should address this.

**Comment by pracucci** [comment]
> The PR #3156 is still open and should address this.

_Still valid_
