### ISSUE TITLE
Empty querier config block breaks querier

### ISSUE THREAD

**Issue by carlpett** [cortexproject/cortex#3079]
I encountered an issue where the querier component would consistently return 503:s on /api/prom/api/v1/query if given "unusual" configuration. There are no logs emitted that indicate what is going wrong, and adding tracing there isn't much to go on either:
![image](https://user-images.githubusercontent.com/214867/91046954-99600880-e619-11ea-96b9-00df6427677a.png)

The config is found here: https://gist.github.com/carlpett/544bc3f807140e51aca53aa8dd68fd5b. Notably, I had a querier block **without any content**. That is, like this:
```yaml
querier:
query_range:
  [...]
```

For some reason, this appears to break the querier setup such that it fails every request with `tsdb.ErrNotReady` here:
https://github.com/cortexproject/cortex/blob/2cb22f830dfd37b199978ad6191a18f444cdae61/vendor/github.com/prometheus/prometheus/web/api/v1/api.go#L263

I haven't determined exactly _why_ having this config breaks, yet.

(Following Slack discussions [here](https://cloud-native.slack.com/archives/CCYDASBLP/p1598006503011500))

**Comment by pracucci** [comment]
Thanks for the report! I've been able to reproduce it. I'm investigating it.

**Comment by pracucci** [comment]
According to the YAML specs, in particular [empty nodes](https://yaml.org/spec/1.2/spec.html#id2786563), when the parser encounters an empty node it resolves it as "null" which in the case of `struct` is the struct with zero values. This looses the defaults we do set before parsing the YAML.
