### ISSUE TITLE
Query tee job

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#308]
A prometheus query reverse-proxy, that we can stick in front of prometheus / cortex.

It will tee queries to both prometheus and cortex, and then compare the result.  Only the result from one service should be returned.  If the results differ (by some fuzz factor), it should alert (by exporting a metric etc).

Probably want to put this between Dev Cortex Grafana and Cortex, teeing/comparing queries against admin Prometheus.

**Comment by gouthamve** [comment]
Can we close this now that we have the test exporter?
