### ISSUE TITLE
-config.expand-env requires argument

### ISSUE THREAD

**Issue by carlpett** [cortexproject/cortex#3082]
If not provided an argument, `-config.expand-env` fails parsing/validation and causes an exit. Easily reproducible with `./cortex -config.expand-env`.
The working usage seems to be `-config.expand-env=true`. 

While the documentation isn't completely clear on the topic, my reading is at least that `-config.expand-env` does not require any argument:
https://github.com/cortexproject/cortex/blob/a87c25fd994a2eec5ab5af0a920cc529b17c0030/docs/configuration/config-file-reference.md#L31

The various unit tests in [main_test.go](https://github.com/cortexproject/cortex/blob/2cbf61af6ed31a811376795a8f9721b890a6e36f/cmd/cortex/main_test.go) seem to get around this somehow?

As a side-note, passing non-boolean arguments is silently accepted as false, for example `-config.expand-env=FOO` would **not** lead to `${FOO}` being expanded, but kept verbatim in the file. I tested that variety since I've used other systems in the past where a list of allowed environment variables needs to be passed, not sure if that would be a common reasoning.

**Comment by Wing924** [comment]
https://github.com/cortexproject/cortex/blob/2cbf61af6ed31a811376795a8f9721b890a6e36f/cmd/cortex/main.go#L83

It looks wrong here.
`flagext.IgnoredFlag` use `flag.FlagSet.Var` internally, which expect a value.
