### ISSUE TITLE
Add TLS support for etcd in ring

### ISSUE THREAD

**Issue by maunavarro** [cortexproject/cortex#3091]
I recently worked on some minor updates that add TLS support to **etcd** . Would like to create a PR to submit these updates for review.

**Comment by pracucci** [comment]
👋  Hi @maunavarro! We would definitely love it. I would just suggest to take a look at [how we name config options](https://cortexmetrics.io/docs/configuration/configuration-file/) for HTTP and gRPC TLS, in order to try to keep naming consistency as much as possible.
