### ISSUE TITLE
Ruler notifier uses a summary instead of histogram to observe latency in notifications

### ISSUE THREAD

**Issue by gotjosh** [cortexproject/cortex#3094]
For every tenant in the ruler, we also spawn a notifier that it is in charge of sending alerts to the Alertmanager. The metrics for this notifier use a summary to observe latency:

https://github.com/prometheus/prometheus/blob/7c0d5ae4e7bc015fabe185202c167293be31bdc9/notifier/notifier.go#L148-L154

In Prometheus, this makes sense, given the notifier is always a singleton as it needs to send _every_ alert to _all_ Alertmanagers. 

However, in Cortex, it does not as the Ruler runs as a distributed service. This makes using a summary pretty inconvenient as computing [aggregates does not work on Summaries](https://prometheus.io/docs/practices/histograms/#quantiles). 

I propose we follow a similar pattern to what we have in the Ruler/Alertmanager metrics and create a new struct that mirrors upstream but uses a histogram instead of a summary to observe latency.

**Comment by pracucci** [comment]
@gotjosh This is still valid, right? If not, could you close it, please?

**Comment by gotjosh** [comment]
It is still valid and more pressing than ever for us.

**Comment by pracucci** [comment]
_Still valid_

**Comment by gotjosh** [comment]
Still valid.
