### ISSUE TITLE
Make ruler HA

### ISSUE THREAD

**Issue by jml** [cortexproject/cortex#310]
Currently the ruler is not HA. There's only one instance that runs all the rules. If it goes down, rules are not being processed.

**Comment by jml** [comment]
Current plan:

- store state about how long condition has been firing for somewhere else (probably dynamodb on weaveworks deployment)
- have rule evaluator that gets sent a rule (group?) and then evaluates it, storing state about firing conditions in thing above, and 
- have single scheduler that sends requests for rule evaluation to evaluators, relying on k8s to do load balancing for us

We'll sort out the config mess later.

Not personally going to do any of this any time soon, although I would personally like to do it. I also think this should wait until #555 is done.

**Comment by jml** [comment]
https://github.com/prometheus/prometheus/issues/422 is relevant here. AFAICT, much of the discussion on the ticket assumes that Prometheus's metric store is the only acceptable place to store 'for' state.

Cortex doesn't have that constraint, but ideally the work would be done such that the storage is behind a golang interface, such that the current in-memory approach and a hypothetical TSDB-backed approach would both work, in addition to whatever dynamodb / bigtable thing we do.

**Comment by jml** [comment]
Lots of this came up from a conversation I had w/ @juliusv a while back. The good ideas are probably his, the bad ones mine.

**Comment by juliusv** [comment]
I don't think this is a concern in terms of ruler statefulness. We get all the samples of a rule evaluation at the same time anyway, so we may as well send them as one request instead of N. Nothing we need to persist over a long time. I'm already doing that for my Prometheus 2.0 port, where `Add()` just adds samples to the appender internally and `Commit()` sends them out.

**Comment by juliusv** [comment]
Ah damn, commented on the wrong issue. Will delete here and repost on the right one.

**Comment by tomwilkie** [comment]
Fixed in #1258. Ruler is now horizontally scalable, and rules are sharded using the ring.  I believe this should be enough.
