### ISSUE TITLE
Query frontend slow log warning: invalid Read on closed Body

### ISSUE THREAD

**Issue by yeya24** [cortexproject/cortex#3111]
We are seeing a lot of warnings in the Thanos Query frontend slow log `http: invalid Read on closed Body`. Since it uses Cortex Query frontend as a library, I tested the Cortex one and it has the same problem.

The warning occurs when it logs a `POST` request. It doesn't affect anything but it is annoying.

```
level=warn ts=2020-08-31T15:01:31.642718692Z caller=frontend.go:198 org_id=fake traceID=f8ac3a930226002 msg="unable to parse form for request" err="http: invalid Read on closed Body"
level=info ts=2020-08-31T15:01:31.6427589Z caller=frontend.go:206 org_id=fake traceID=f8ac3a930226002 msg="slow query detected" method=POST host= path=/api/v1/query time_taken=1m3.598993508s
level=warn ts=2020-08-31T15:02:16.45874421Z caller=frontend.go:198 org_id=fake traceID=653a2ed25929e383 msg="unable to parse form for request" err="http: invalid Read on closed Body"
level=info ts=2020-08-31T15:02:16.458782837Z caller=frontend.go:206 org_id=fake traceID=653a2ed25929e383 msg="slow query detected" method=POST host= path=/api/v1/query time_taken=44.715073818s
level=warn ts=2020-08-31T15:02:28.766424824Z caller=frontend.go:198 org_id=fake traceID=2382a13b1e6ef89 msg="unable to parse form for request" err="http: invalid Read on closed Body"
level=info ts=2020-08-31T15:02:28.766461552Z caller=frontend.go:206 org_id=fake traceID=2382a13b1e6ef89 msg="slow query detected" method=POST host= path=/api/v1/query time_taken=12.206554463s
```

**Comment by pracucci** [comment]
Does it happen when a query request gets canceled?

**Comment by yeya24** [comment]
@pracucci I think no. The requests are not canceled.

What I found today is:
1. This only happens for a `POST` request directly going to downstream URL. So `query_range` API is not affected.

2. We use the client_golang prometheus API to send query requests. When sending the post requests, it sets the content type header to `application/x-www-form-urlencoded`. https://github.com/prometheus/client_golang/blob/master/api/prometheus/v1/api.go#L1014

I tried several times, query frontend throws this error when `application/x-www-form-urlencoded` is set. If I send another POST request without setting this, then no error occurs.

**Comment by melkorm** [comment]
I did a little investigation and perhaps this works like this:

We hit this condition:
https://github.com/cortexproject/cortex/blob/0a33f9d4c8ff23ec00972e33889b388e302a1df8/pkg/querier/frontend/frontend.go#L187
and we write to the response later in the code 
https://github.com/cortexproject/cortex/blob/012fc0b0fa2fce785388917959b1a8168d29d809/pkg/querier/frontend/frontend.go#L224

but the Go docs say:
https://golang.org/pkg/net/http/#ResponseWriter

```   
    // Write writes the data to the connection as part of an HTTP reply.
    //
    // If WriteHeader has not yet been called, Write calls
    // WriteHeader(http.StatusOK) before writing the data. If the Header
    // does not contain a Content-Type line, Write adds a Content-Type set
    // to the result of passing the initial 512 bytes of written data to
    // DetectContentType. Additionally, if the total size of all written
    // data is under a few KB and there are no Flush calls, the
    // Content-Length header is added automatically.
    //
    // Depending on the HTTP protocol version and the client, calling
    // Write or WriteHeader may prevent future reads on the
    // Request.Body. For HTTP/1.x requests, handlers should read any
    // needed request body data before writing the response. Once the
    // headers have been flushed (due to either an explicit Flusher.Flush
    // call or writing enough data to trigger a flush), the request body
    // may be unavailable. For HTTP/2 requests, the Go HTTP server permits
    // handlers to continue to read the request body while concurrently
    // writing the response. However, such behavior may not be supported
    // by all HTTP/2 clients. Handlers should read before writing if
    // possible to maximize compatibility.
    Write([]byte) (int, error)
``` 
and we actually try to read body later on when trying to analyse form data: https://github.com/cortexproject/cortex/blob/0a33f9d4c8ff23ec00972e33889b388e302a1df8/pkg/querier/frontend/frontend.go#L210 

probably one should skip form parsing when we hit request error.

PS. Hope I didn't mix things - I am new to this code 🙈

**Comment by yeya24** [comment]
@melkorm  Thanks for the investigation. But my case seems different. It doesn't have this error https://github.com/cortexproject/cortex/blob/0a33f9d4c8ff23ec00972e33889b388e302a1df8/pkg/querier/frontend/frontend.go#L187

**Comment by melkorm** [comment]
@yeya24 yeah, I can see but I just noticed that we write to http.ResponseWriter here https://github.com/cortexproject/cortex/blob/0a33f9d4c8ff23ec00972e33889b388e302a1df8/pkg/querier/frontend/frontend.go#L194 so perhaps we run in a case when we shouldn't read body later on.
