### ISSUE TITLE
Replace SegmentRange with upstream wal.Segments

### ISSUE THREAD

**Issue by codesome** [cortexproject/cortex#3114]
Now that https://github.com/prometheus/prometheus/pull/6477/ is merged, we can get rid of this custom implementation after we upgrade Prometheus
https://github.com/cortexproject/cortex/blob/2efff16014c8fbb6d77d7c75695fcabed3276b91/pkg/ingester/wal.go#L1083-L1108

**Comment by codesome** [comment]
We could add `hacktoberfest` label to this issue as I expect Prometheus to be upgraded by then :)

**Comment by bsnyder788** [comment]
I will tackle this one!
