### ISSUE TITLE
http_path_prefix not always respected

### ISSUE THREAD

**Issue by TomL-dev** [cortexproject/cortex#3118]
We are running cortex in a cluster form. so we are starting several containers with the target config set.

When starting a distributor with: `http_path_prefix: "/distributor"` in the config, the index page is loaded from the domain.com/distributor page in the browser.
when clicking on `usage statistics` it redirects to `/distributor/all_user_statistics`
but clicking any other link will redirect to their corresponding page on `domain.com` instead of `domain.com/distributor`

to me it seems like not all the urls respect the `http_path_prefix` from the config

using cortex:1.3.0

**Comment by TomL-dev** [comment]
i'm trying to get all cortex modules behind nginx. 
my assumption was that the http_path_prefix will let me prefix all url's

**Comment by pstibrany** [comment]
Unfortunately index page didn't use configured HTTP path prefix at all. In PR #3126 this should be fixed.
