### ISSUE TITLE
Ruler: GET /api/v1/rules is slow

### ISSUE THREAD

**Issue by gotjosh** [cortexproject/cortex#3121]
We have observed consistent slowness (> 3s) when fetching the list of the rules/alerts from this endpoint. Today, while around the area I noticed that we do a `List` of objects in the bucket followed up by a `Get` of each in serial. In the case I mention, we have about 63 rule groups.

Looking around the current object storage we don't support batching but I think the Thanos one does (?). This might be yet another reason to perhaps move in that direction. If not, it feels like we need support for batching. 

Being fair, I'm not swinging to one solution or another just weighting down our options here.

**Comment by pstibrany** [comment]
> Looking around the current object storage we don't support batching but I think the Thanos one does (?)

I don't think it does. We run queries against object store concurrently, where possible. For example in `(*BlocksScanner).scanBucket` we create up to `d.cfg.TenantsConcurrency` workers for scanning individual users, and then feed the channel with results from `List` (`Iter`). I think ruler needs to do something similar.
