### ISSUE TITLE
Poor query latency when using chunks storage w/ Cassandra

### ISSUE THREAD

**Issue by DaInco** [cortexproject/cortex#3123]
Hi,
I've created Cassandra as a long time storage. However, I noticed that the more data in Cassandra, the longer it takes to extract metrics. Cassandra consists of 2 nodes, 8core and 16GB RAM.

When downloading data, the reading speed from the disk reaches 500MB/s, and extracting data from 2 weeks in Grafana takes up to a minute. Longer requests result in timeouts.
I've tried v9 and v10 schema - no improvement. 
In Prometheus with much lower resources take about second.
Is it normal?

**Comment by storyicon** [comment]
I used to think I was the only one who had a similar problem. I'm currently working on an optimization that works like a federated index in a relational database. In my tests, it can optimize a few minutes of queries to about 500ms, but it is not mature enough now.

**Comment by DaInco** [comment]
Thanks for your reply. I'll be waiting for your optimization. Someone else had a similar problem?

**Comment by DaInco** [comment]
Can anyone give me Cortex & Cassandra configuration? Maybe I'm doing something wrong.

**Comment by storyicon** [comment]
@DaInco Can you show your configuration?

**Comment by DaInco** [comment]
@storyicon 
I've tried multiple configuration schema v9, schema v10. I've changed my disk to SSD, and it's no improvement - maybe a little.
my last configuration:

`
# Configuration for running Cortex in single-process mode.
# This should not be used in production.  It is only for getting started
# and development.

# Disable the requirement that every request to Cortex has a
# X-Scope-OrgID header. `fake` will be substituted in instead.
auth_enabled: false

server:
  http_listen_port: 9990

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 1048576000
  grpc_server_max_send_msg_size: 1048576000
  grpc_server_max_concurrent_streams: 10000
  log_level: "info"
 
distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 1048576000
    max_send_msg_size: 1048576000
    use_gzip_compression: true

limits:
  ingestion_burst_size: 99999999
  max_series_per_metric: 10000001
  ingestion_rate: 25000000
ingester:
  # We want our ingesters to flush chunks at the same time to optimise
  # deduplication opportunities.
  spread_flushes: true
  chunk_age_jitter: 0

  walconfig:
    wal_enabled: true
    recover_from_wal: true
    flush_on_shutdown_with_wal_enabled: true

  lifecycler:
    # The address to advertise for this ingester.  Will be autodiscovered by
    # looking up address on eth0 or en0; can be specified if this fails.
    address: xxxxxxxxxx

    # We want to start immediately and flush on shutdown.
    join_after: 0
    min_ready_duration: 0s
    final_sleep: 0s
    num_tokens: 512
    # Use an in memory ring store, so we don't need to launch a Consul.
    ring:
      kvstore:
        store: inmemory
      replication_factor: 2

# Use local storage - BoltDB for the index, and the filesystem
# for the chunks.
schema:
  configs:
  - from: 2020-07-01
    store: cassandra
    object_store: cassandra
    schema: v9
    index:
      prefix: index_
      period: 168h
    chunks:
      prefix: chunk_
      period: 168h

chunk_store:
  chunk_cache_config:
    redis:
      endpoint: xxxxxxxxx:6379
      max_idle_conns: 160
      timeout: 10s
      expiration: 1h
  write_dedupe_cache_config:
    redis:
      endpoint: xxxxxxxx:6379
      max_idle_conns: 160
      timeout: 10s
      expiration: 1h
query_range:
  results_cache:
    cache:
      redis:
        endpoint: xxxxxxxxx:6379
        timeout: 10s
        max_idle_conns: 160
        expiration: 1h
  cache_results: true
  split_queries_by_interval: 24h
storage:
  cassandra:
    addresses: xxxxxxxx:9042,yyyyyyyyy:9042 # configure cassandra addresses here.
    keyspace: cortex   # configure desired keyspace here.
    consistency: "ONE"
    host_verification: false
    timeout: 10s
    SSL: false 
    username: 'xxxxxxx'
    password: 'xxxxxxx'
    auth: true
    replication_factor: 2
    table_options: "caching = { 'keys': 'ALL', 'rows_per_partition': 1024 }  AND compaction = {'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy', 'compaction_window_size': '1', 'compaction_window_unit': 'DAYS', 'max_threshold': '32', 'min_threshold': '4'} AND compression = {'chunk_length_in_kb': '4', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}"
`

**Comment by DaInco** [comment]
I think that problem is not in cassandra but in all chunk storeages. When I chose 7 days in grafana it generates 200k Select requests to db...  It is possible ?

**Comment by jakubgs** [comment]
I don't think this should be closed.

**Comment by jakubgs** [comment]
The performance really is quite jarring. Here's a simple comparison:

## Single Prometheus Instance

```
 > time curl -s 'http://localhost:9090/api/v1/labels' | jq '.data | length'
101
curl -s 'http://localhost:9090/api/v1/labels'  0.01s user 0.01s system 79% cpu 0.014 total
```
__Hardware__: 1 x 4 CPUs, 8 GB RAM
__Result__: 0.015 seconds

## Three Cortex Instances in a Cluster + 3 host Cassandra Cluster

```
 > time curl -s 'http://localhost:9092/prometheus/api/v1/labels' | jq '.data | length'
94
curl -s 'http://localhost:9092/prometheus/api/v1/labels'  0.01s user 0.00s system 0% cpu 3.537 total
```
__Hardware__: 3+3 x 6 CPUs, 16 GB RAM
__Result__: 3.537 seconds

That's quite absurd considering the hardware involved. Can anyone else provide their example?

**Comment by DaInco** [comment]
Have the same issue. Something is wrong. Cassandra is stable but performance is unacceptable. No one knows how to fix it?

**Comment by DaInco** [comment]
Could anyone help??

**Comment by DaInco** [comment]
No one is using cassandra? Maybe we did somethig wrong. Cassandra is stable... Someone from cortex should at least check it.

**Comment by pstibrany** [comment]
> No one is using cassandra? Maybe we did somethig wrong. Cassandra is stable... Someone from cortex should at least check it.

No maintainer (afaik) is familiar with running Cortex on Cassandra, so we rely purely on community support here.

My personal suggestion would be to move to blocks engine on top of some object store (even minio) instead.

**Comment by loguido** [comment]
I also noticed not so good performance with Cassandra, with some tuning, things are going better and probably a Cassandra expert (i am not) would be able to obtain even better performaces. I am considering whether to abandon Cortex.

**Comment by pracucci** [comment]
> I also noticed not so good performance with Cassandra. With some tuning, things are going better and probably a Cassandra expert (i am not) would be able to obtain even better performaces. I am considering whether to abandon Cortex.

As @pstibrany mentioned, Cortex maintainers have no production experience with Cassandra (maybe @jtlisi a bit?). As a data point, at Grafana Labs we've [completed the migration to blocks storage](https://grafana.com/blog/2021/01/28/how-we-live-migrated-massive-cortex-clusters-to-blocks-storage-with-zero-impact-to-grafana-cloud-customers/) and I would generally recommend considering to move to blocks storage.

**Comment by Wing924** [comment]
I use Cassandra on production. I haven’t compared Cassandra with other storage because I run cortex on own data center, but Cassandra looks not so bad.

**Comment by DaInco** [comment]
Can anyone show's cassandra backend cortex config file? 
@Wing924 not so bad? Could you tell more ?
@loguido what did you do?

**Comment by jtlisi** [comment]
@DaInco How many series are you querying against? The chunks storage backend will have a large number of requests to the chunk/index backend by design. Can you provide snapshots from the [cortex-jsonnet reads dashboard](https://github.com/grafana/cortex-jsonnet/tree/master/cortex-mixin) and a bit more infromation about the query you are trying to run?
