### ISSUE TITLE
Having a single index-page for all cortex targets / components is misleading

### ISSUE THREAD

**Issue by Hashfyre** [cortexproject/cortex#3128]
Currently all cortex components expose a single `index.html` that looks like 
![cotex-index-page](https://user-images.githubusercontent.com/581287/92090452-0ed39200-eded-11ea-8f9c-7830ab2d1c6a.png)

However, other than `current config`, which exposes the component's configuration, other endpoints are component specific.

```
Cortex
Admin Endpoints:
  - Current Config          // --> Specific / contextual to the current target / component
  - Usage Statistics
  - HA Tracking Status
  - Alertmanager Status    // --> Dependent on optional target
  - Ingester Ring Status   // --> Distributor service only
  - Ruler Ring Status      // --> Dependent on optional target's service, 404 if not deployed
  - Service Status
  - Compactor Ring Status (experimental blocks storage)
  - Store Gateway Ring (experimental blocks storage)


Dangerous:
 - Trigger a Flush           // --> Ingester service only
 - Trigger Ingester Shutdown // --> Ingester service only
```

It would be nice to have a per target rendering on the index page with urls that are pertinent to that target only. 

As a new user, I was confused for quite a while on why certain endpoints kept giving me 404s. I mistakenly took these 404s as signs of a faulty config on my part spending a good number of hours on it, even though the cortex stack was working as expected. Thus, I believe it could be treated as an UX issue.

**Comment by Hashfyre** [comment]
If per target rendering of the page is a bit much, a simple hierarchical list of the urls under a `<target>:` section, like:
```
distributor:
  - link1
  - link2
  - ...
Ingester:
  - link1
  - link2
  - ...
```
Would be a nice to have thing too.

**Comment by pstibrany** [comment]
Thanks for your report. You're right that this is confusing, and PR #3133 will fix it (although it keeps current sections for now).

**Comment by Hashfyre** [comment]
Thanks so much for taking this up @pstibrany
