### ISSUE TITLE
Running Cortex as a service in DCOS Mesosphere is throwing error

### ISSUE THREAD

**Issue by vikram-yerneni** [cortexproject/cortex#3130]
Hello Cortex'rs,
I am trying to deploy or run Cortex as a Service in DCOS Mesosphere and its throwing this below error:

`level=info ts=2020-09-03T15:07:09.830798562Z caller=modules.go:488 msg="RulerStorage is not configured in single binary mode and will not be started."

level=error ts=2020-09-03T15:07:09.831042466Z caller=log.go:149 msg="error running cortex" err="schema config file needs to be set\nerror initialising module: table-manager\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/go/src/github.com/cortexproject/cortex/pkg/util/modules/modules.go:89\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:290\nmain.main\n\t/go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:164\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"
`

SO based on this error, looks like the Docker container is pulling the data from this official Cortex repo and looking for the Storage information (ruler.storage)
How can I predefine or even define the variable from Cortex  within Mesosphere?

Anyone been through this or any help here will be appreciated. 

Cheers!
Vikram Y

**Comment by pstibrany** [comment]
I've replied in the mailing list: https://groups.google.com/g/cortex-monitoring/c/O7bkUPrbaxg/m/GhVfV7byAQAJ.

**Comment by vikram-yerneni** [comment]
Thanks Peter. I will close this out here...
