### ISSUE TITLE
change MIME for YAML from application/yaml to text/yaml

### ISSUE THREAD

**Issue by Wing924** [cortexproject/cortex#3132]
### WHAT

Let's change MIME for YAML from `application/yaml` to `text/yaml` on API response.

### WHY

When you get `application/yaml` content, the behavior on browsers including Chrome is download them.
But it's better to show text on browser since yaml is human readable text format.

ref. https://www.freeformatter.com/mime-types-list.html (plz search yaml)

**Comment by pracucci** [comment]
I'm unsure about this change. I believe we should keep compatibility with Prometheus, which uses `application/yaml`.

**Comment by pracucci** [comment]
_Closing for now_
