### ISSUE TITLE
Deprecated endpoints in configs

### ISSUE THREAD

**Issue by till** [cortexproject/cortex#3148]
![image](https://user-images.githubusercontent.com/27003/92511364-79ca0200-f20d-11ea-991a-040cb1b43ea1.png)

We are using a lot of these endpoints for a multi-tenant UI on top of Cortex. Are there any notes as to where these endpoints will go? Or if alternatives are already available?

**Comment by pstibrany** [comment]
From what I understand, these endpoints are not going to be removed anytime soon, but "Configs API" is not actively worked on. There are new APIs for Ruler and Alert manager mentioned in the same document that can be used instead.

**Comment by till** [comment]
@pstibrany ah, good to know. Is it possible to point out what _replaces_ them?

E.g., it seems like:

`GET configs:/api/prom/configs/alertmanager` > GET `alertmanager:/api/v1/alerts`

**Comment by bboreham** [comment]
Closing in favour of more general "document this" issue #4206

**Comment by till** [comment]
@bboreham So the other got closed, but this is still not in the docs? I tried to follow PRs. Can you re-open this?

**Comment by bboreham** [comment]
I reopened #4206
