### ISSUE TITLE
Documentation: Config for sending HA Pairs data to Cortex

### ISSUE THREAD

**Issue by shmsr** [cortexproject/cortex#3161]
Documentation Link: https://cortexmetrics.io/docs/production/ha-pair-handling/#context

We need to update the spelling for `Prometheis` to `Prometheus` in the following paragraph:

> Assume that there are two teams, each running their own Prometheus, monitoring different services. 
> Let’s call the **Prometheis** T1 and T2. Now, if the teams are running HA pairs, let’s call the individual 
> **Prometheis**, T1.a, T1.b and T2.a and T2.b.

Is it okay if I send the PR for this?

**Comment by pstibrany** [comment]
Thank you. This is actually correct, "Prometheis" is used as a plural of Prometheus.
