### ISSUE TITLE
QueryRange: Catalogs range validation as an internal error

### ISSUE THREAD

**Issue by gotjosh** [cortexproject/cortex#3163]
Time ranges for range queries are validated against a per-tenant limit.

https://github.com/cortexproject/cortex/blob/e0663b763a53352ae0d7cac0768a657fe5b80fbd/pkg/querier/querier.go#L285-L289

Within Prometheus API, the `query_range` endpoint does all of its validation upfront - meaning that incorrect input errors (400s) are validated before the query is ran.

https://github.com/prometheus/prometheus/blob/a282d2509971174301408c5a5f96946c478dfb0f/web/api/v1/api.go#L387-L452

As it is, Cortex will return a 500 for the validation of this limit which seems incorrect.  Any thoughts?

I'm not sure upstream will accept changes to encapsulate custom validation as part of the API, the other options is to copy the validation code of the code of this particular endpoint which seems unideal.

An example of the error:

```json
{
  "status": "error",
  "errorType": "internal",
  "error": "expanding series: the query time range exceeds the limit (query length: 4414h5m0s, limit: 768h0m0s)"
}
```

**Comment by pstibrany** [comment]
No need to change upstream, we can already convert this error to 422. This happens in https://github.com/cortexproject/cortex/blob/527e1c41b72081d1d43f986ac8a64622c3f05500/pkg/api/queryable.go, which understands some error types and returns appropriate `promql.Err*` expected by Prometheus API (which then translates it to HTTP status code)
