### ISSUE TITLE
Ingester emitting two identical trace spans for every Push call

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#3168]
Identical except for slight differences in timing.
Do we add the middleware twice?

![image](https://user-images.githubusercontent.com/8125524/93015257-eba89f80-f5af-11ea-8206-f21112c0a89c.png)

**Comment by bboreham** [comment]
I suspect this, since taking it out makes the symptom go away:
https://github.com/cortexproject/cortex/blob/f6122f4252a76c444a20528557d100caf93d8c7d/pkg/cortex/cortex.go#L275-L276

**Comment by pracucci** [comment]
You're right. I'm checking how we could fix it without loosing Thanos traces (which are quite useful when debugging the blocks storage).
