### ISSUE TITLE
Oracle Cloud Buckets support

### ISSUE THREAD

**Issue by Hanoko** [cortexproject/cortex#3172]
Hi,

Is there any plan to support Oracle Cloud buckets in any near future?

Best regards

**Comment by pracucci** [comment]
If the question is related to the blocks storage, then let's discuss it in https://github.com/thanos-io/thanos/issues/3164.

**Comment by Hanoko** [comment]
Yes, is related with block storage. Are Cortex and Thanos sharing the support for block storage? I didn't know, let's discuss it on the issue you mentioned.

**Comment by pracucci** [comment]
> Are Cortex and Thanos sharing the support for block storage? 

Yes, we do. Once we implement it into Thanos, backporting it to Cortex will be trivial.

**Comment by pracucci** [comment]
_Still valid, but need to be done in Thanos first._

**Comment by jtlisi** [comment]
_still valid_

**Comment by Hanoko** [comment]
As said on the Thanos issue, you can use the S3 utility from Oracle Cloud Object Storage:
"Can you try to run Thanos object storage against cloud Oracle storage?

See docs: https://thanos.io/tip/thanos/storage.md/#s3

You could run something very simple like https://thanos.io/tip/thanos/storage.md/#s3 to quickly check if storage access works (:

Let us know, we can reopen if something is not working 🤗"

**Comment by pracucci** [comment]
> you can use the S3 utility from Oracle Cloud Object Storage

@Hanoko Could you open a PR to improve the doc and mention it, please?

**Comment by Hanoko** [comment]
Sure, I will do it as soon as possible.

**Comment by bboreham** [comment]
Closing as upstream issue says this should work https://github.com/thanos-io/thanos/issues/3164

Please open a new issue with full details if you find a problem.
