### ISSUE TITLE
Document the /debug API endpoints

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3174]
I think we should document the `/debug/*` API endpoints in https://cortexmetrics.io/docs/api/, including the recently added `/debug/fgprof` #3131.

**Comment by Jigar3** [comment]
Hey :wave:, I want to work on this issue.

**Comment by pracucci** [comment]
Thanks @Jigar3, it's your!

**Comment by Jigar3** [comment]
Apart from the `/debug/fgprof` endpoint which was added in #3131, I was trying to figure out which other endpoints are there in `/debug/*`.

 I found the following ones
1. `/debug/pprof/heap` 
2. `/debug/pprof/profile`
3. `/debug/pprof/trace`
4. `/debug/pprof/goroutine`

These were found using in `./vendor/github.com/hashicorp/consul/api/debug.go` file. In this file, requests are made to these endpoints. I am not entirely sure if these are the remaining `/debug/*` endpoints which you intended to document in this issue. Let me know if I am on the right track.

**Comment by pstibrany** [comment]
pprof endpoints are documented here: https://golang.org/pkg/net/http/pprof/

I don’t think we need to name them all. Visiting /debug/pprof tells you which are available, and I think Cortex docs linking to https://golang.org/pkg/net/http/pprof/ would be enough.

**Comment by Jigar3** [comment]
So, you are trying to imply we shouldn't give documentation about the `pprof` endpoints as they are already available at https://golang.org/pkg/net/http/pprof/`. In essence then, I need to document the `/debug/fgprof` and `/debug/pprof` endpoints where `/debug/pprof` documentation will link to the above URL. Am I correct?

**Comment by pstibrany** [comment]
> So, you are trying to imply we shouldn't give documentation about the `pprof` endpoints as they are already available at [https://golang.org/pkg/net/http/pprof/`](https://golang.org/pkg/net/http/pprof/%60). In essence then, I need to document the `/debug/fgprof` and `/debug/pprof` endpoints where `/debug/pprof` documentation will link to the above URL. Am I correct?

Yes, that is my suggestion.

**Comment by pstibrany** [comment]
We can also link to fgprof documention.
