### ISSUE TITLE
Uniform validation errors type

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3181]
Following up the discussion in https://github.com/cortexproject/cortex/pull/3167#pullrequestreview-487566857, we should uniform the error type used for validation errors.

**Comment by bboreham** [comment]
I would like to see an error type that neatly expresses what went wrong without mentioning the text "http" or "grpc", neither of which are relevant.

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid, but low priority_

**Comment by bboreham** [comment]
Still valid
