### ISSUE TITLE
Alertmanager templates not working

### ISSUE THREAD

**Issue by jpdstan** [cortexproject/cortex#3194]
I'm trying to get [reusable templates](https://prometheus.io/docs/alerting/latest/notification_examples/#defining-reusable-templates) working, but none of the templates that we define for every various integrations (e.g. slack, opsgenie) seem to be respected, i.e. the default alert text gets outputted in the final Slack message, opsgenie alert, etc.

For reference, we used the HTTP API to upload our alertmanager configuration that contains the template files. Here's what a truncated version looks like:

```
$ curl cortex.dev.robinhood.com/api/v1/alerts

template_files:
  slack.tmpl: |
    {{ define "slack.default.text" }}{{ if eq .Status "firing" }}{{ range .Alerts.Firing }}*Description:* {{ .Annotations.description }}
    *Dashboard:* {{ if .Annotations.dashboard }}<{{ .Annotations.dashboard }}|link>{{ else }}No dashboard defined for this alert :disappointed:{{ end }}
    *Runbook:* {{ if .Annotations.runbook }}<{{ .Annotations.runbook }}|link> {{ else }}No runbook defined for this alert :disappointed:{{ end }}
    *Prometheus Graph:* <{{ .GeneratorURL }}|link>
    *Details:*
    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
    {{ end }}
    {{ end }}
    {{ end }}
    {{ end }}

alertmanager_config: |2+
  global:
    slack_api_url: <url>
  route:
     ...
```

This worked perfectly fine when we were using Prometheus + Alertmanager, although that implementation was a little different as we specified the path to the template files, whereas here we're defining the templates inline. This also gives us assurance that the template file is syntactically correct, because they worked at some point and haven't been changed.

The only difference I can think of from Cortex's Alertmanager and Prometheus's Alertmanager is the multitenancy aspect. We've disabled multitenancy (i.e. have the `--auth.enabled=false` flag in our Alertmanager's args), so on the container the templates exist under the `fake` tenant's directory, i.e. `/data/templates/fake`. Perhaps this Alertmanager representation isn't supporting this multitenant structure? 

No errors in the alertmanager logs.

Our alertmanager configuration args:
```
      -alertmanager.storage.gcs.bucketname=
      -alertmanager.storage.path=/data
      -alertmanager.storage.s3.url=<s3_url>
      -alertmanager.storage.type=s3
      -alertmanager.web.external-url=<external_url>:80/alertmanager
      -auth.enabled=false
      -experimental.alertmanager.enable-api=true
      -log.level=debug
      -target=alertmanager
```

**Comment by jpdstan** [comment]
Figured it out -- it turns out in the `alertmanager_config` block you also need to specify the `template_files` with the same name, like so:

```
template_files:
  slack.tmpl: <...>

alertmanager_config:
  templates:
    - 'slack.tmpl'
```

The closest thing I could find to documentation on this was the [HTTP API docs](https://cortexmetrics.io/docs/api/#example-request-body), but even there it doesn't specify this rule. Do we have any better documentation on this? Happy to add some if not.

**Comment by jpdstan** [comment]
Better yet, is there a way we could de-dupe here and just use `template_files` here?

**Comment by gotjosh** [comment]
> Do we have any better documentation on this? Happy to add some if not.

I don't think we do, contributions would certainly be welcome.
