### ISSUE TITLE
Nice to have: add configmap for dynamodb schema and periodic table configuration

### ISSUE THREAD

**Issue by bwplotka** [cortexproject/cortex#320]
Right now I need to copy carefully this bit (with my values):
```
- -s3.url=s3://abc:123@s3.default.svc.cluster.local:4569
- -dynamodb.url=dynamodb://user:pass@dynamodb.default.svc.cluster.local:8000/cortex
- -dynamodb.periodic-table.prefix=cortex_weekly_
- -dynamodb.periodic-table.start=2017-01-06
- -dynamodb.daily-buckets-from=2017-01-10
- -dynamodb.base64-buckets-from=2017-01-17
- -dynamodb.v4-schema-from=2017-02-05
```
between `querier`, `ruler`, `table-manager` and `ingester`. Would be nice to state that somewhere, in single place.

**Comment by tomwilkie** [comment]
Yeah, we would support reading this from a file (which you could put in a config map).  At Weaveworks, we version all our YAMLs, and are working on a method for sharing config between these YAMLs.
