### ISSUE TITLE
Have a way to specify userID in other way than just from `X-Scope-OrgID` header

### ISSUE THREAD

**Issue by bwplotka** [cortexproject/cortex#323]
Currently the only way to distinguish different tenants is to send their metrics with different header. 

I would love to store some time series under different userID based on specific label from the same Prometheus. We can mitigate that on our side by just sticking single userID = single Prom, however that is not currently the case. 

Are there any ideas how to do it by label, or no plans to support such case? (:

**Comment by tomwilkie** [comment]
I've abstracted all this into `weaveworks/common/users`.  We could put all those methods behind a interface, and you could provide you own implementation?

**Comment by Bplotka** [comment]
Make sense, that will work!

Wow, Tom you are prepared for every my issue ^^

**Comment by tomwilkie** [comment]
I think we can close this now; I added the ability to inject a "fake" userid in #1262

**Comment by bboreham** [comment]
I did think that people would want a header named other than “Scope”.
