### ISSUE TITLE
Delete series API call not working (throwing Exception)

### ISSUE THREAD

**Issue by venkataramu** [cortexproject/cortex#3237]
# Enabled Purger configuration in single-process-config.yaml file
auth_enabled: true

server:
  http_listen_port: 9009

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: gzip

ingester:
  lifecycler:
    # The address to advertise for this ingester. Will be autodiscovered by
    # looking up address on eth0 or en0; can be specified if this fails.
    address: 127.0.0.1

    # We want to start immediately and flush on shutdown.
    join_after: 0
    final_sleep: 0s
    num_tokens: 512

    # Use an in memory ring store, so we don't need to launch a Consul.
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

# Use cassandra as storage -for both index store and chunks store.
schema:
  configs:
  - from: 2019-07-29
    store: cassandra
    object_store: cassandra
    schema: v10
    index:
      prefix: index_
      period: 168h
    chunks:
      prefix: chunk_
      period: 168h

storage:
  cassandra:
    addresses: 172.18.0.7 # configure cassandra addresses here.
    keyspace: cortex   # configure desired keyspace here.
  delete_store:
    store: cassandra

purger:
  object_store_type: filesystem
  enable: true
  delete_request_cancel_period: 1m

**delete_requests** table also created in backend(Cassandra have the entries while API call triggered)

# Below API call used for delete series :
curl -X POST  -g 'http://localhost:9009/api/prom/api/v1/admin/tsdb/delete_series?match[]=system_cpu_utilization&start=1600942822&end=1600950022' -H "X-Scope-OrgID: 8"

# But I am getting below exception:
**Invalid null value in condition for column range**

# Cross Checked for tsdb entries also :
curl -XGET 'http://localhost:9009/api/prom/api/v1/admin/tsdb/delete_series' -H "X-Scope-OrgID: 8"
o/p: 
[{"request_id":"2d5b471d","start_time":1600942822,"end_time":1600950022,"selectors":["system_cpu_utilization"],"status":"received","created_at":1600950394.373},{"request_id":"2d5f5718","start_time":1600942822,"end_time":1600950022,"selectors":["system_cpu_utilization"],"status":"received","created_at":1600950324.177},{"request_id":"aeaf607a","start_time":1600942822,"end_time":1600950022,"selectors":["system_cpu_utilization"],"status":"received","created_at":1600950493.747},{"request_id":"ea84cbf5","start_time":1600942822,"end_time":1600950022,"selectors":["system_cpu_utilization"],"status":"received","created_at":1600950155.93}]

**Comment by sandeepsukhani** [comment]
I am not sure I get it. Which call is throwing an exception?
I see the delete requests getting created successfully as per your output for `GET` call.

Also can you please share the logs of purger service if you are running it separately or the whole cortex service if you are running it as single binary?

**Comment by sandeepsukhani** [comment]
Also which cortex version are you using?

**Comment by venkataramu** [comment]
curl -X POST  -g 'http://localhost:9009/api/prom/api/v1/admin/tsdb/delete_series?match[]=system_cpu_utilization&start=1600942822&end=1600950022' -H "X-Scope-OrgID: 8"

 Exception : Invalid null value in condition for column range

Above API call throwing above exception.
**I am running whole cortex as a single binary**

**Backend logs :**

level=error ts=2020-09-24T13:14:09.495381589Z caller=request_handler.go:110 msg="error adding delete request to the store" err="Invalid null value in condition for column range"
level=warn ts=2020-09-24T13:14:09.495427808Z caller=logging.go:71 traceID=6d40b3cedb7ffab8 msg="POST /api/prom/api/v1/admin/tsdb/delete_series?match[]=system_cpu_utilization&start=1600942822&end=1600950022 (500) 2.838429ms Response: \"Invalid null value in condition for column range\\n\" ws: false; Accept: */*; User-Agent: curl/7.58.0; X-Scope-Orgid: 8; "

**Comment by venkataramu** [comment]
> Also which cortex version are you using?

I am running with latest master code

**Comment by sandeepsukhani** [comment]
Are you still seeing entries getting created in the db even if the error is thrown?

**Comment by venkataramu** [comment]
Yes for Every call db entries are creating.

**Comment by sandeepsukhani** [comment]
Your `delete_request_cancel_period` config is set too low it should be ideally 24 hours or at least a few hours more than max chunk age which is 6 hours by default.
Can you post all the cortex logs?

**Comment by sandeepsukhani** [comment]
How are you running Cassandra? Would you be able to get the logs from it with debug logging enabled?

**Comment by venkataramu** [comment]
I am running Cassandra as a Docker Container and Version is Cassandra 3.11.4.
Let me try to enable  Cassandra logs . Once I got the logs I will post .

**Comment by sandeepsukhani** [comment]
In that case, it would be good to have the command that you run it with so that I can reproduce it locally.

**Comment by venkataramu** [comment]
do you have any idea how to enable DEBUG logs for cassandra queries

**Comment by sandeepsukhani** [comment]
I am not sure, I think for now if you can share the command and other configs that you start Cassandra with, that would be great.
I can then run it locally with the exact same setup and try to reproduce it.

**Comment by venkataramu** [comment]
I ran cassandra as a container with cassandra version  3.11.4 and cortex as a single binary

**Comment by venkataramu** [comment]
Hi @sandeepsukhani , 
I observed when restart a cortex server the data is purging from Cassandra, because purger is calling.
For your reference Logs in server : 
level=info ts=2020-09-30T15:15:30.116014469Z caller=purger.go:497 user_id=8 request_id=49642a9e msg="building plan for a new delete request"
level=info ts=2020-09-30T15:15:30.116039886Z caller=purger.go:543 user_id=8 request_id=49642a9e msg="building delete plan" num_plans=1

Please help me on this Am I need to run Purger as a Service rather than in Single binary mode?

**Comment by jakubgs** [comment]
Maybe this should be re-opened? I'm trying to use the API and I'm getting:
```
 > curl -s -XPOST "http://localhost:9092/prometheus/api/v1/admin/tsdb/delete_series?match[]=xyz&start=$(date --date=2021-04-01 +%s)&end=$(date +%s)" 
Invalid null value in condition for column range
```
And in the logs:
```
caller=request_handler.go:111 msg="error adding delete request to the store" err="Invalid null value in condition for column range"
```
So not sure how I'm supposed to use this, since my request is based on the docs:
https://cortexmetrics.io/docs/guides/deleting-series/
https://prometheus.io/docs/prometheus/latest/querying/api/#delete-series

**Comment by jakubgs** [comment]
I added `debug.PrintStack()` and built my own Cortex binary, and this is what I got:
```
level=error ts=2021-04-26T12:27:44.461797466Z caller=request_handler.go:112 msg="error adding delete request to the store" err="Invalid null value in condition for column range"
goroutine 16857 [running]:
runtime/debug.Stack(0xa, 0xc, 0x6)
        /nix/store/wa1660iihcvbmr1q7j2y4gdg5f97zxg5-go-1.15.10/share/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /nix/store/wa1660iihcvbmr1q7j2y4gdg5f97zxg5-go-1.15.10/share/go/src/runtime/debug/stack.go:16 +0x25
github.com/cortexproject/cortex/pkg/chunk/purger.(*DeleteRequestHandler).AddDeleteRequestHandler(0xc00051fe00, 0x2b61c00, 0xc009f66f80, 0xc04f86dc00)
        /home/jakubgs/soft/cortex/pkg/chunk/purger/request_handler.go:113 +0x43d
net/http.HandlerFunc.ServeHTTP(0xc000caeef0, 0x2b61c00, 0xc009f66f80, 0xc04f86dc00)
        /nix/store/wa1660iihcvbmr1q7j2y4gdg5f97zxg5-go-1.15.10/share/go/src/net/http/server.go:2042 +0x44
github.com/cortexproject/cortex/pkg/util/fakeauth.glob..func1.1(0x2b61c00, 0xc009f66f80, 0xc04f86db00)
        /home/jakubgs/soft/cortex/pkg/util/fakeauth/fake_auth.go:54 +0x1c7
net/http.HandlerFunc.ServeHTTP(0xc00051ff20, 0x2b61c00, 0xc009f66f80, 0xc04f86db00)
        /nix/store/wa1660iihcvbmr1q7j2y4gdg5f97zxg5-go-1.15.10/share/go/src/net/http/server.go:2042 +0x44
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x2b61c00, 0xc009f66f80, 0xc04f86db00)
        /home/jakubgs/soft/cortex/vendor/github.com/NYTimes/gziphandler/gzip.go:342 +0x2f0
net/http.HandlerFunc.ServeHTTP(0xc000987e90, 0x2b61c00, 0xc009f66f80, 0xc04f86db00)
        /nix/store/wa1660iihcvbmr1q7j2y4gdg5f97zxg5-go-1.15.10/share/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000203c0, 0x2b61c00, 0xc009f66f80, 0xc04f86d900)
        /home/jakubgs/soft/cortex/vendor/github.com/gorilla/mux/mux.go:212 +0xd3
github.com/weaveworks/common/middleware.Instrument.Wrap.func1.2(0x2b61c00, 0xc009f66f80)
        /home/jakubgs/soft/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:68 +0x4c
github.com/felixge/httpsnoop.CaptureMetricsFn(0x2b5bf40, 0xc040e24a00, 0xc0028bd800, 0x2, 0x2b9a620, 0xc0513d8680)
        /home/jakubgs/soft/cortex/vendor/github.com/felixge/httpsnoop/capture_metrics.go:81 +0x24b
github.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x2b5bf40, 0xc040e24a00, 0xc04f86d900)
        /home/jakubgs/soft/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:67 +0x325
net/http.HandlerFunc.ServeHTTP(0xc000851540, 0x2b5bf40, 0xc040e24a00, 0xc04f86d900)
        /nix/store/wa1660iihcvbmr1q7j2y4gdg5f97zxg5-go-1.15.10/share/go/src/net/http/server.go:2042 +0x44
github.com/weaveworks/common/middleware.Log.Wrap.func1(0x2b61d80, 0xc040e249b0, 0xc04f86d900)
        /home/jakubgs/soft/cortex/vendor/github.com/weaveworks/common/middleware/logging.go:52 +0x1a7
net/http.HandlerFunc.ServeHTTP(0xc0004d9880, 0x2b61d80, 0xc040e249b0, 0xc04f86d900)
        /nix/store/wa1660iihcvbmr1q7j2y4gdg5f97zxg5-go-1.15.10/share/go/src/net/http/server.go:2042 +0x44
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5(0x2b5f340, 0xc046382540, 0xc04f86d800)
        /home/jakubgs/soft/cortex/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:154 +0x5e4
net/http.HandlerFunc.ServeHTTP(0xc0004d98c0, 0x2b5f340, 0xc046382540, 0xc04f86d800)
        /nix/store/wa1660iihcvbmr1q7j2y4gdg5f97zxg5-go-1.15.10/share/go/src/net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc0001dc380, 0x2b5f340, 0xc046382540, 0xc04f86d800)
        /nix/store/wa1660iihcvbmr1q7j2y4gdg5f97zxg5-go-1.15.10/share/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc04ae60aa0, 0x2b6d840, 0xc0513d8500)
        /nix/store/wa1660iihcvbmr1q7j2y4gdg5f97zxg5-go-1.15.10/share/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /nix/store/wa1660iihcvbmr1q7j2y4gdg5f97zxg5-go-1.15.10/share/go/src/net/http/server.go:2969 +0x36c
```

**Comment by jakubgs** [comment]
As far as I can tell the error is caused by the `nil` in this call to `writeBatch.Add()`:
https://github.com/cortexproject/cortex/blob/51662ea3e57cb2639cc057f5b647e8bc671ff282/pkg/chunk/purger/delete_requests_store.go#L135-L138
Which is then passed to `BatchWrite`:
https://github.com/cortexproject/cortex/blob/51662ea3e57cb2639cc057f5b647e8bc671ff282/pkg/chunk/cassandra/storage_client.go#L309-L314

**Comment by jakubgs** [comment]
My dumb fix was to replace `nil` with `[]byte{}`:
```go
	writeBatch.Add(ds.cfg.RequestsTableName, fmt.Sprintf("%s:%s:%s", cacheGenNum, userID, CacheKindResults),
		[]byte{}, []byte(strconv.FormatInt(time.Now().Unix(), 10)))
```
Not sure if that's the correct way, but it does seem to fix adding entries to the `delete_requests` table in Cassandra.

**Comment by jakubgs** [comment]
Crated this PR that introduces the `[]byte{}` fix: https://github.com/cortexproject/cortex/pull/4128
