### ISSUE TITLE
Flaky TestShuffleShardWithCaching

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3241]
**Describe the bug**
`TestShuffleShardWithCaching` is flaky:

```
--- FAIL: TestShuffleShardWithCaching (5.03s)
    ring_test.go:785: lifecycler 2 failed: failed to pick tokens in the KV store, ring: test: failed to CAS test
    ring_test.go:829: 9 != 8
FAIL
```

Happens quite frequently in CI:
- https://app.circleci.com/pipelines/github/cortexproject/cortex/8456/workflows/f62692ad-5a1f-41b5-b73c-a5872b617cdc/jobs/41552
- https://app.circleci.com/pipelines/github/cortexproject/cortex/8455/workflows/69d442df-db1e-43a8-a1a8-ce4d5dc2afb1/jobs/41548

**Comment by pstibrany** [comment]
I'm on it.
