### ISSUE TITLE
Remote write endpoint's error message gets truncated in Prometheus log

### ISSUE THREAD

**Issue by alvinlin123** [cortexproject/cortex#3247]
### Description

[Prometheus has limits on how many bytes it reads from HTTP body for error cases](https://github.com/prometheus/prometheus/blob/072b9649a30e06c71ddd1c64d25f71c4936e56ba/storage/remote/client.go#L41). Currently, Cortex may return long error message where the actual cause of the error gets truncated. Below is an example of the error from Cortex in Prometheus' log: 

```
{
  "caller": "dedupe.go:112",
  "component": "remote",
  "count": 100,
  "err": "server returned HTTP status 400 Bad Request: user=xxx-xxx-xxx-xxx-xxx-xxx-xxx: series={__name__=\"cluster_namespace_job_route:cortex_request_duration_seconds:50quantile\", job=\"cortex/distributor\", route=\"metrics\"}, timestamp=2020-09-24T23:52:",
  "level": "error",
  "msg": "non-recoverable error",
  "remote_name": "blah",
  "ts": "2020-09-24T23:52:07.209Z",
  "url": "http://blah.blah.svc.cluster.local:80/workspaces/xx-XXXXXXX-XXXX-XXX-XXXX-XXXXXXXXXXX/api/v1/remote_write"
}
```

Note that the `err` field is truncated because it's too long, so in this case I have no idea what caused the bad request error. 

### Discussion
One possible way to solve this problem is to move the actual root cause error message to the front of the `err` field such that the `err` field might look like `erver returned HTTP status 400 Bad Request: msg=\"duplicate metrics\" user=xxx-xxx-xxx-xxx-xxx-xxx-xxx: series={__name__=\"cluster_namespace_job_route:cortex_request_duration_seconds:50quantile\", job=\"cortex/distributor\", route=\"metrics\"},"`

**Comment by alvinlin123** [comment]
I created https://github.com/prometheus/prometheus/issues/7982 to see if Prometheus should increase their limit too.

**Comment by pracucci** [comment]
Thanks @alvinlin123 for raising this issue. I personally believe we can do both. I'm OK to move the error message at the front as well as I support your request to increase the err message length in Prometheus too.

**Comment by jtlisi** [comment]
https://github.com/prometheus/prometheus/issues/7982 has been fixed upstream. This should be fine to close
