### ISSUE TITLE
Sort the entries in Cortex Services Status by name

### ISSUE THREAD

**Issue by roidelapluie** [cortexproject/cortex#3251]
**Describe the bug**

In the Cortex Services Status page, the order is not consistent upon refresh. Would be nice to have them sortered to have a stable page across reloads.

**To Reproduce**
1. Start Cortex 
2. Open Cortex Services Status page
3. Refresh (F5)

**Expected behavior**
Get twice the same page if the status has not changed.

**Comment by pstibrany** [comment]
Changing slice to map on this line (with key being the service name) is all that's needed to fix this.

https://github.com/cortexproject/cortex/blob/80b1261bde6b79c9f50f4b9b4450ec0abc19e370/pkg/cortex/status.go#L66

Do you want to submit PR?

**Comment by roidelapluie** [comment]
Yes I will
