### ISSUE TITLE
Add an ability to run mixed number of modules in one instance

### ISSUE THREAD

**Issue by blind-oracle** [cortexproject/cortex#3272]
We're running a flat small Cortex cluster in a single binary mode with a single tenant.

Currently we can either run 'all' target which is a predefined subset of modules or a single target.
Target 'all' does not include, for example, compactor which is needed and it can run in clustered mode using a hash ring.

Same goes, I guess, for alertmanager etc.

So we have to run it separately, although I think it's completely fine to run it inside the main instance I guess.
Maybe we can change **target** configuration parameter to a list and specify several modules to run? Or add another parameter e.g. **targets** to maintain backwards compatibility.

**Comment by pstibrany** [comment]
We have considered this option in the past, but it has never been high priority. Would you like to give it a try and send PR? It shouldn't be too difficult to add this. There are few places in Cortex where we check if given module is running by checking for that module or "All", that would need to be changed. Other than that, I don't think there are any gotchas.

**Comment by blind-oracle** [comment]
Sure, I'll give it a try. What's the preferred approach?
1. Create a new setting to maintain backwards compatibility
2. Modify old option to []string
3. Leave the current setting as string, but parse as a comma-separated list?

I guess (3) can be a good compromise which should be backwards compatible.

**Comment by pstibrany** [comment]
> Sure, I'll give it a try. What's the preferred approach?
> 
> 1. Create a new setting to maintain backwards compatibility
> 2. Modify old option to []string
> 3. Leave the current setting as string, but parse as a comma-separated list?
> 
> I guess (3) can be a good compromise which should be backwards compatible.

Agree, let’s use 3.

**Comment by blind-oracle** [comment]
Done #3275

**Comment by jtlisi** [comment]
#3275

**Comment by pracucci** [comment]
_Reopening because #3275 is still open._
