### ISSUE TITLE
Proposal: Cassandra as block storage

### ISSUE THREAD

**Issue by DaInco** [cortexproject/cortex#3297]
For now, the chunk storage is available in:
- DynamoDB/S3 (see Cortex on AWS)
- BigTable/GCS
- Cassandra (see Cortex on Cassandra)

and for block storage :
- Amazon S3
- Google Cloud Storage
- Microsoft Azure Storage
- Local Filesystem (single node only)

To help people who created Cassandra as a chunk storage migrate to block storage (and improve performance) I suggest adding Cassandra as block storage.

**Comment by pstibrany** [comment]
What is required to support Cassandra is to [write an implementation of `objstore.Bucket` interface](https://thanos.io/tip/thanos/storage.md/#how-to-add-a-new-client) (from Thanos) using Cassandra.

It isn’t a great match, but it certainly is possible.

**Comment by pstibrany** [comment]
> It isn’t a great match, but it certainly is possible.

But effort to do so may too high and it certainly is not on the roadmap.

**Comment by pracucci** [comment]
Blocks storage has been designed to work on object storages. I wouldn't consider Cassandra a good replacement of a block storage and I don't see why we should support it. I'm not super sure about it.

**Comment by pracucci** [comment]
_Going to close. Blocks storage has been designed to run on object stores and we should get stick to our design decisions._
