### ISSUE TITLE
CAS operation on configs

### ISSUE THREAD

**Issue by jml** [cortexproject/cortex#330]
_From @jml on January 24, 2017 18:30_

Would be good to have a compare-and-swap operation on configs to enable reliable tools for automatically updating them.

@tomwilkie I recall you mentioning this in the context of a particular use-case. Can you remember what it is?

_Copied from original issue: weaveworks/service#1084_

**Comment by jml** [comment]
_From @tomwilkie on January 24, 2017 18:34_

We were discussing dashboards / notebooks - we could use the config server to serve them, and if we do we should ensure its hard to accidentally overwrite a concurrent edit.

**Comment by gouthamve** [comment]
Closed in #649
