### ISSUE TITLE
only query the data in s3

### ISSUE THREAD

**Issue by lixy529** [cortexproject/cortex#3321]
Why can I only query the data in s3, but not the data without s3?
What needs to be configured?

version: 1.4.0
engine: blocks

**Comment by pstibrany** [comment]
> Why can I only query the data in s3, but not the data without s3?

Do you mean that querying most-recent data on ingesters doesn't work?

**Comment by lixy529** [comment]
> > Why can I only query the data in s3, but not the data without s3?
> 
> Do you mean that querying most-recent data on ingesters doesn't work?

Yes

**Comment by lixy529** [comment]
This i s my config:
`auth_enabled: false

target: querier

storage:
  engine: blocks

server:
  http_listen_port: 9411
  grpc_listen_port: 9412
  log_level: info

memberlist:
  bind_port: 7944
  join_members:
    - localhost:7946
    - localhost:7947
  abort_if_cluster_join_fails: false

ingester:
  lifecycler:
    id: "Ingester_7944"
    join_after: 10s
    observe_period: 10s
    min_ready_duration: 0s
    final_sleep: 5s
    num_tokens: 512
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1

store_gateway:
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist
    replication_factor: 1

querier:
  active_query_tracker_dir: /home/lixiaoya/jd/web/cortex/tmp/active-query-tracker
blocks_storage:
  tsdb:
    dir: /home/lixiaoya/jd/web/cortex/tmp/cortex_qureier/tsdb
    retention_period: 3h
  bucket_store:
    sync_dir: /home/lixiaoya/jd/web/cortex/tmp/cortex_qureier/tsdb-sync
  s3:
    bucket_name: buckettest
    endpoint: xx.xx.xx.xx:9878
    insecure: true
    secret_access_key: ""
    access_key_id: ""`

**Comment by lixy529** [comment]
This issue has been solved, the distributor is not configured.
