### ISSUE TITLE
Possible gaps when querying ingesters and -distributor.shard-by-all-labels is disabled

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3322]
**Describe the bug**
This is **not** a bug we experienced (because we run Cortex with `-distributor.shard-by-all-labels=true`) but while working on #3252 I realised this could be an issue for specific Cortex setups.

When Cortex is running with WAL enabled (chunks and blocks storage) and transfers on shutdown are disabled during ingesters rollout and `-distributor.shard-by-all-labels=false` (default) there may be gaps when querying series/samples from ingesters because:
1. There will be series spillover during rollout
2. Queriers always query ingesters currently holding the tokens, but some series/samples may be in different ingesters due to the spillover

A similar scenario may occur during ingesters scale up even if transfers on shutdown are enabled. Generally speaking, this issue could occur whenever there's a ring topology change.

**Storage Engine**
- [x] Blocks
- [x] Chunks

**Comment by roidelapluie** [comment]
Duplicate of #3294 - which maybe the title is not correct

**Comment by roidelapluie** [comment]
And #731

**Comment by pracucci** [comment]
_Closing because it's a duplicate of #3294._
