### ISSUE TITLE
Cassandra backend client doesn't backoff on 429 errors when using Cosmos DB

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3330]
**Describe the bug**
The Cassandra client (both index and chunks) doesn't slow down the pressure to the backend when flushing chunks and the backend Cassandra returns 429 (eg. when running on Azure Cosmos DB).

**Storage Engine**
- [ ] Blocks
- [x] Chunks

**Comment by bboreham** [comment]
Can the users of CosmosDB move to blocks instead?

**Comment by alanprot** [comment]
Chunks storage was removed.
