### ISSUE TITLE
Format blocks min/max timestamp in logs

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3332]
**Is your feature request related to a problem? Please describe.**
When investigating problem with blocks, it’s cumbersome to convert timestamps to date/time manually. We should fix logging of all timestamps to use formatted datetime.

This should be done in Cortex and ideally in Thanos and Prometheus too (because some logs come from there).

**Comment by pracucci** [comment]
_Stil valid, help wanted_

**Comment by ChinYing-Li** [comment]
Hi, I'd like to take this issue! My plan is as follows:

1. Implement a custom struct, say, `DateTime` that represents formatted datetime
2. Add something like `func DateTime(ts int64)  DataTime`
3. Make `MinTime` & `MaxTime` in `Block` a `DateTime`
4. Probably need to update many functions that consumes `Block.MinTime` and `Block.MaxTime`

Is there any other thing I should be aware of? Any suggestion is appreciated!

**Comment by pracucci** [comment]
Thanks @ChinYing-Li. Maybe we could start easier defining a formatting function to use in `logger.Log()` calls when we include the block min/max time?

**Comment by ChinYing-Li** [comment]
> When investigating problem with blocks, it’s cumbersome to convert timestamps to date/time manually. We should fix logging of all timestamps to use formatted datetime.

I wonder if the function below is insufficient for logger's consumption? If so, what's the desired format for logging timestamps?
https://github.com/cortexproject/cortex/blob/3fedc1108a49e88274c4b7a7c5b18b573fe51553/pkg/util/time.go#L27-L30

**Comment by pracucci** [comment]
> I wonder if the function below is insufficient for logger's consumption? If so, what's the desired format for logging timestamps?

@ChinYing-Li Sounds good to me. Whatever human-readable timestamp looks good. Don't think a specific format is better than others, as far as it's readable, and using the default formatting just looks good to me.

**Comment by ChinYing-Li** [comment]
@pracucci Looking at the issue statement, should we convert "all" timestamps in `Log` to the more readable format, ? 
Or should we only convert a `Block.minT` or a `Block.maxT` when logging?
I am a bit confused because the issue title and the issue statement seem to contradict each other.
Thank you!

**Comment by pracucci** [comment]
> Or should we convert Block.minT and Block.maxT only?

Only block minT / maxT would be a very good start.

**Comment by ChinYing-Li** [comment]
Upon looking into this, `Block.MinTime` and `Block.MaxTime` do not seem to be logged directly anywhere in the code base, so I suppose it's this function being used for logging (though I did not find this `String` getting called as well):
https://github.com/cortexproject/cortex/blob/76914569aff345a06a95400dc537e5758a90f0c2/pkg/storage/tsdb/bucketindex/index.go#L130-L135

`Block.String` converts `int64` to `Time`, a readable format, which is what this issue need.
I am not sure what else I am missing; any pointer is appreciated!

**Comment by pracucci** [comment]
You're right. I can't find references anymore. I may have implicitly addressed them when I worked on the bucket index. Let me close the issue. We can re-open it (or directly open a PR to fix it) in case we find any.
