### ISSUE TITLE
Cortex MaxMind Issue

### ISSUE THREAD

**Issue by imad-testing** [cortexproject/cortex#3333]
Hello, I'm new to Cortex. Can anyone help me to resolve my issue please?
![Capture](https://user-images.githubusercontent.com/71173607/95837775-a95ab580-0d49-11eb-8855-b20dfd206bc4.PNG)

![Capture2](https://user-images.githubusercontent.com/71173607/95837896-d313dc80-0d49-11eb-8d92-b3364a130f59.PNG)

**Comment by pracucci** [comment]
I believe this issue is unrelated to this project. Please re-open it if this is really the project for which you're asking support.
