### ISSUE TITLE
Unit tests in GitHub actions workflow are not running with -race

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3337]
**Describe the bug**
Unit tests running in CircleCI are running with `-race`. This is enabled in `tools/test` when `$CIRCLECI` is valued. In PR #3302 we did the work to run unit tests on GitHub actions, but we didn't notice this and GitHub actions test are not running with `-race`.

**Expected behavior**
Unit tests should run with the same exact command between CircleCI and GitHub actions.

**Comment by pstibrany** [comment]
> GitHub actions test are running with `-race`

You mean they are NOT running with `-race`, right? And we want to enable it.

**Comment by pracucci** [comment]
> > GitHub actions test are running with `-race`
> 
> You mean they are NOT running with `-race`, right? And we want to enable it.

Yes, it was a typo. Fixed. Thanks!

**Comment by AzfaarQureshi** [comment]
We can either manually set $CIRCLECI before we call tools/test or we can change the makefile/scripts to replace $CIRCLECI with another default GitHub Actions [env variable](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables)

**Comment by pracucci** [comment]
My take:
1. I would keep GitHub actions workflow clean (no hacks setting CIRCLECI env vars)
2. We should make sure the functionality is preserved in CircleCI too (we'll run both for a while, until GitHub actions migration is completed)

That being said you could add another condition to `tools/test`, to make sure the `-race` and code coverage is enabled when running CI in GitHub actions too.

**Comment by AzfaarQureshi** [comment]
Filed a PR here: https://github.com/cortexproject/cortex/pull/3351
