### ISSUE TITLE
Cortex Alertmanager fails to load template filenames which contain directories

### ISSUE THREAD

**Issue by mattmendick** [cortexproject/cortex#3357]
**Describe the bug**
Alertmanager has functionality to receive templates and use them with the provided rules files. However I believe the directory processing logic has a bug in it which causes a failure. 

**To Reproduce**
To see the error message, where 999999 is the tenant ID:

Using the `cortextool` utility (from https://github.com/grafana/cortex-tools) with this command:
```
./cortextool alertmanager load --id 999999 --address https://alertmanager.url.here --key $ALERTMANAGER_API_KEY alerting/policies/alerts.yml alerting/policies/thetemplatefile.tmpl

```
Yields the error:
```
error validating Alertmanager config: unable to create Alertmanager template file \"/tmp/validate-config197042527/templates/999999/alerting/policies/alerting/policies/thetemplatefile.tmpl\": open /tmp/validate-config197042527/templates/999999/alerting/policies/alerting/policies/thetemplatefile.tmpl: no such file or directory\n" status="400 Bad Request"
```

**Expected behavior**
It should be able to create the file at the right directory and use it.

**Additional Context**
I believe the issue is this:

If you provide a filename like `some/path/templatefile.tmpl` it will create `datadir/some/path/` and then try to write `datadir/some/path/some/path/templatefile.tmpl`

Creating directory at: https://github.com/cortexproject/cortex/blob/b13590729ba0e1e071d0bb755b988a688e0b20ea/pkg/alertmanager/multitenant.go#L544

But using the entire path at: https://github.com/cortexproject/cortex/blob/b13590729ba0e1e071d0bb755b988a688e0b20ea/pkg/alertmanager/multitenant.go#L550

550 should be something like `file := filepath.Join(dir, filepath.Base(fn))` to only add `templatefile.tmpl` to the dir already created.

**Comment by gotjosh** [comment]
Hey @mattmendick ! Thanks for reporting this one.

Sadly, we don't support paths (only filenames) as part of the Alertmanager template definitions.

The key difference here is that unlike Prometheus cortex does not have a need to "look" for these files as we store them in object storage (and then write it to disk temporarily to consume it). 

An alternative to what you proposed,  to have a clearer error message to signal that this is not supported and make it clear in the documentation. I can see the appeal of just making it work for our users but I'm generally I'm the opposite side of modifying users configuration.

**Comment by mattmendick** [comment]
Thanks @gotjosh, I created https://github.com/grafana/cortex-tools/issues/114 to address the issue on the `cortextool` side.

**Comment by jtlisi** [comment]
_still valid_

**Comment by pracucci** [comment]
We recently discussed it and it's currently the intended behaviour.

**Comment by Carmezim** [comment]
I am having a similar issue when trying to configure the alertmanager

```
cortextool alertmanager load ./alertmanager_config.ym
```

yields:
```
error validating Alertmanager config: mkdir /tmp/validate-config001396953: read-only file system
```

**Comment by pracucci** [comment]
> error validating Alertmanager config: mkdir /tmp/validate-config001396953: read-only file system

This is a different issue. Let's discuss it in the dedicated issue you've opened #4089.
