### ISSUE TITLE
Support DynamoDB in BlocksConvert Scanner

### ISSUE THREAD

**Issue by andersosthus** [cortexproject/cortex#3362]
Adding support for DynamoDB as an Index source in Blocksconvert Scanner.

I've started working on making the Blocksconvert Scanner work with `DynamoDB` over in my branch (https://github.com/andersosthus/cortex/tree/dynamodb-scanner).

The scanner works (seemingly) now, but there are some issues remaining:
1. The code is basically a duplication of the `BigTable` code adjusted for DynamoDB without much consideration if it's appropriate for the `DynamoDB` part (I removed some stuff that seemed to be `BigTable` specific)
1. As far as I know, `DynamoDB` doesn't have that "sample keys" to get out how many threads one should run, so I opted for a `Scan` for now (fixed to 1 segment since I'm not sure how best to decide how many segments we should run)
1. Due to the use of `Scan`, a series might end up on several `IndexEntryProcessor`, not sure how to handle that, but the quick workaround is to just run with 1 `IndexEntryProcessor` :) With more understanding about how the series names are created, I guess we could maybe add some filters to the `Scans`, and assign a scan per `IndexEntryProcessor`?

But I have produced plan files that validate with the code, so it's kinda working at least.

I want to finish up this, and was wondering if anyone have some pointers about the issues I've raised above?

**Comment by pracucci** [comment]
This is a topic for @pstibrany ;)

**Comment by pstibrany** [comment]
Anders has indicated on the Slack that he has PR in progress that will be posted soon. In the meantime I haven't looked more into these DynamoDB-specific questions, as I'm not familiar with DynamoDB at all, but plan to review the PR once it's ready.

**Comment by andersosthus** [comment]
I did some tests with my code, but it seemed to never finish (8 workers on an 8 cpu machine. Ran for about 48 hours before i killed it). I have been busy with other things since then, but I do intend do look into it again.

All my DynamoDB tables are pretty big, so maybe it will be easier to test with the new date range functionality in 1.5.0 ?

**Comment by andersosthus** [comment]
Yeah, I did use `-scanner.tables` to limit it to the last table, but it has 160m records or something like that, so was still slow. But I'll see if I can find a smaller table, and also run with `-scanner.scan-period-start/end` and see if I can get the size manageable :)

**Comment by pracucci** [comment]
_Reopening because should be addressed by https://github.com/cortexproject/cortex/pull/3828 (at least for schema v9)._
