### ISSUE TITLE
Document the restrictions/recommendations for naming `Tenants`

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#3365]
**Is your feature request related to a problem? Please describe.**

Currently Cortex does not have any guideline for naming a tenant ID. However, there are implications/restrictions when naming a tenant. For instance, a tenant should not contain a `/` character since that character is used as a delimiter by our various backend systems and using `/` in the tenant ID would likely lead to user issues. Another issue would be the length of the tenant ID itself. S3 for instance has a maximum key length of 1024 characters. A sufficiently long tenant ID would make it impossible to store objects persisted by Cortex.

**Describe the solution you'd like**

A set of guidelines to follow when naming a tenant. Also updating the tenant parsing middleware to enforce certain restrictions on incoming tenants to ensure they are valid. Ideally, these restrictions should be designed to ensure any tenant ID chosen by a user would work in all possible storage backends.

**Comment by roidelapluie** [comment]
Just a note: I do not see why we *could not* support / in tenants. It would be up to the object storage backend to e.g. hash the tenant name if there are "impossible" characters.

**Comment by pracucci** [comment]
Other than the `/`, Cortex doesn't support whitespaces in the tenant ID as well. We have some components (like memcached client) which breaks if the tenant ID contains a whitespace.

**Comment by jtlisi** [comment]
> Just a note: I do not see why we could not support / in tenants. It would be up to the object storage backend to e.g. hash the tenant name if there are "impossible" characters.

As things stand having the tenant name in plain text can be very useful when debugging/operating a cluster. I think we should avoid adding extra complexity to our storage implementations when we can restrict the useable character set. In my opinion there would need to be a compelling reason to allow ` ` and `/` characters as tenant identifiers to justify adding additional handling for those characters. Otherwise, we should update the authentication code used internally to enforce a set of restrictions to help users avoid this issue.
