### ISSUE TITLE
Global limits are not applied correctly when using shuffle sharding

### ISSUE THREAD

**Issue by ranton256** [cortexproject/cortex#3367]
**Description**

Global limits, at least for ingesters and maybe for other components like querier, are not being calculated correctly when 

For example here:
pkg/ingester/limiter.go : https://github.com/cortexproject/cortex/blob/0211d278730677ba5516c1252566be69357ed4d9/pkg/ingester/limiter.go#L202

The formula seems to assume a tenant’s series are evenly distributed across all ingesters, but if subring/shuffle sharding is enabled, the tenant’s series end up in only a subset of ingesters.

I think to be correct, this needs to use the default and per-tenant setting, i.e. IngestionTenantShardSize

https://github.com/cortexproject/cortex/blob/f3589368be28605fe0089d94b510ec0509b51350/pkg/util/validation/limits.go#L48
pkg/util/validation/limits.go:48

**To Reproduce**

1. run cortex with shuffle sharding on the ingestion path enabled for ingesters
2. set max_global_series_per_metric and/or max_global_series_per_metric values
3. attempt to ingest up to max_global_series_per_metric or max_global_series_per_metric values.

**Expected behavior**
You can ingest up to global limit / actual number of ingesters in user subring size.
Actual behavior is global number of ingesters total is used as denominator, so limit is lower than expected.

**Environment:**
 - Infrastructure: [EKS]
 - Deployment tool: [helm]

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**

**Comment by ranton256** [comment]
Do you know if we have any similar problem limits on the query path with the frontend to querier shuffle sharding? I have not had time to dig in and check if we have similar problem on that side or not with changes added in https://github.com/cortexproject/cortex/pull/3113

**Comment by pracucci** [comment]
> Do you know if we have any similar problem limits on the query path with the frontend to querier shuffle sharding? 

I checked all global limits we have. I haven't found others affected. The following is my analysis:

Not affected by shuffle sharding:

- `-distributor.ingestion-rate-limit-strategy`

Affected by shuffle sharding and fixed by #3369:

- `-ingester.max-global-series-per-user`
- `-ingester.max-global-series-per-metric`
- `-ingester.max-global-metadata-per-user`
- `-ingester.max-global-metadata-per-metric`
