### ISSUE TITLE
Table-manager: insufficient logging on failures

### ISSUE THREAD

**Issue by iyesin** [cortexproject/cortex#3375]
**Describe the bug**
table-manager does not include in logs (at least) two important for troubleshooting parts of information:
- Request parameters used to query `-metrics.url`
- Backoff/retry parameters that would be used for next attempt 

**To Reproduce**
1. Start Cortex **v1.4** with attached `schema.yaml` and `config.yaml` and `docker run --rm -it -p8080:9009 -p9195:9195 -p7979:7979 -v $PWD/config.yaml:/config.yaml:ro -v $PWD/schema.yaml:/schema.yaml:ro -v $HOME/.aws:/root/.aws:ro --env AWS_PROFILE=bln-prod-admin cortexproject/cortex:v1.4.0 -target=table-manager -config.file=/config.yaml -schema-config-file=/schema.yaml -metrics.url=http://cortexmetrics.io` command. You are free to use actual prometheus instance **without** cortex metrics.
2. Wait till `level=error ts=2020-10-21T16:16:02.222508275Z caller=table_manager.go:243 msg="error syncing tables" err="client_error: client error: 404"` message

**Expected behavior**
- More information about what happened like: `level=error ts=2020-10-21T16:16:02.222508275Z caller=table_manager.go:243 msg="error querying prometheus ({{.metrics.uri}}) with query ({{.metrics.query}})" err="client_error: {{.metrics_server_output}}"`
- A clear and concise description of what happened on application level and what should happen next. Something like line in log `level=info ts={{.ts}} caller=table_manager msg="I would retry query {{.prom.query}} on {{.prom.uri}} after {{.prom.next_try_interval}}"`

**Environment:**
 - Infrastructure: any
 - Deployment tool: any

**Storage Engine**
- [X] Chunks

PS: configs are zipped [_cortex_logs.zip](https://github.com/cortexproject/cortex/files/5417355/_cortex_logs.zip)

**Comment by pracucci** [comment]
Thanks @iyesin for the report. Could you work on a PR to improve logging in the table-manager? Should be easy and I will be happy to review it. Thanks!

**Comment by alanprot** [comment]
Chunks storage was removed.
