### ISSUE TITLE
Add a separate configuration option to set the Table Manager's consistency level on Cassandra sessions

### ISSUE THREAD

**Issue by replay** [cortexproject/cortex#3394]
We've had a production incident where the Table Manager dropped the old Cassandra tables and created the new ones but somehow the Cassandra cluster ended up with a schema mismatch between the cluster nodes (I don't know the exact reason which caused the schema mismatch). After running a repair job on all Cassandra nodes the schema mismatch was resolved, but then we faced other issues due to inconsistencies between the index and chunk tables.

To ensure that a similar situation cannot happen again we'd like to configure the Table Manager to always use the consistency level `ALL` when dropping/creating tables. There already is a Cassandra consistency setting which makes it possible to set the consistency to `ALL`, but this consistency level would then be applied to all Cassandra sessions including normal queries. I think it would make sense to have a separate configuration parameter to configure the consistency level only for the Table Manager.

**Comment by pracucci** [comment]
>  I think it would make sense to have a separate configuration parameter to configure the consistency level only for the Table Manager.

Instead of allowing a specific config option for the table manager, I would prefer/suggest to add a config option to specify the consistency level for table creation/deletion operations.

**Comment by replay** [comment]
In the meantime since I opened this issue I learned more about how Cassandra propagates schema changes.
It uses gossip protocol to propagate schema changes, which is not affected by the consistency level at all, so this issue makes no sense anymore. Here is [a better explanation](https://stackoverflow.com/questions/41248615/set-consistency-level-for-cassandra-ddl)
