### ISSUE TITLE
Alertmanager fails to read fallback config

### ISSUE THREAD

**Issue by jakubgs** [cortexproject/cortex#3395]
## Description

I'm trying to use `fallback_config_file` with Alertmanager service but it fails with:
```
 msg="GET /api/prom/configs/alertmanager (500) 78.226µs Response: \"Failed to initialize the Alertmanager\\n\"
```

## Details

I'm running `1.4.0` binary release form GitHub and I have `fallback_config_file` configured to point to a file I configured the same way I used to for normal Alertmanager. When I check the logs I do not see either of these two errors:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/multitenant.go#L186
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/multitenant.go#L190
But when I query the API:
```
curl -sv http://localhost:9101/api/prom/configs/alertmanager -H 'X-Scope-OrgID: 0'
```
I get back:
```
Failed to initialize the Alertmanager
```
But the code that triggers this error doesn't actually show what caused it because `err` is discarded:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/multitenant.go#L476-L485
So I have no clue what I'm doing wrong. The file is in place, it has read permissions for the service.

**Comment by jakubgs** [comment]
I'm actually confused as to what `fallback_config_file` is supposed to do. The docs state that:
```
# Filename of fallback config to use if none specified for instance.
# CLI flag: -alertmanager.configs.fallback
[fallback_config_file: <string> | default = ""]
```
So I assume this is where I can specify the Alertmanager configuration for alert routes(like email or VictorOps). But then where is the proper canonical place for specifying non-fallback config? There is no `config_file` or `config_dir` setting in the `alertmanager` configuration, so that's confusing.

I __THINK__ I'm supposed to `POST` the config to `/api/prom/configs/alertmanager`, but that is not actually stated anywhere in the documentation, so I'm not sure if I'm correct.

**Comment by jakubgs** [comment]
Also, I'm not sure why I have to specify `X-Scope-OrgID` if I have `auth_enabled: false` set in the config....

**Comment by jakubgs** [comment]
In the `alertmanagerFromFallbackConfig` function I actually see no reference to the fallback config:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/multitenant.go#L490-L507
Which apparently was loaded with `amconfig.LoadFile` but then discarded:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/multitenant.go#L188`
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/multitenant.go#L188

**Comment by jakubgs** [comment]
When I comment out the `fallback_config_file` setting and try to post my config:
```
curl -sv http://localhost:9101/api/prom/configs/alertmanager -H 'X-Scope-OrgID: 0' -XPOST -d @/etc/cortex-alertmanager/routes.yml
```
It just fails with:
```
the Alertmanager is not configured
```
Which is this:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/multitenant.go#L466-L474
So it wants some kind of `userAM` to be active, but where does that come from? The documentation says nothing about this.

**Comment by jakubgs** [comment]
There is something called `loadAllConfigs` that is run at startup:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/multitenant.go#L248-L252
Which apparently loads configs from `am.poll()`
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/multitenant.go#L279-L292
Which gets it from `am.store.ListAlertConfigs`:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/multitenant.go#L303-L310
Which in turn gets them from `a.client.List()`:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/alerts/objectclient/store.go#L34-L52
Which appears to be using the chunk object storage:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/alerts/objectclient/store.go#L22-L25
Which is also used to store the config with `SetAlertConfig`:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/alerts/objectclient/store.go#L84-L92
Which is used by `alertmanagerFromFallbackConfig`:
https://github.com/cortexproject/cortex/blob/23554ce028c090a4a3413ac0e35e5e1dc9fa929f/pkg/alertmanager/multitenant.go#L490-L493

**Comment by jakubgs** [comment]
So I THINK that the `alertmanager` process requires access to the chunk storage configured via `storage_config`:
https://cortexmetrics.io/docs/configuration/configuration-file/#storage_config
But why is this not mentioned anywhere in the documentation?

**Comment by jakubgs** [comment]
Also, the error makes no sense. If Alertmanager requires chunk storage then it should FAIL at startup if it's unavailable. And not return vague `Failed to initialize the Alertmanager` or `the Alertmanager is not configured` that means nothing to the user.

**Comment by jakubgs** [comment]
And I am still failing to see what's the advantage of running this setup over just running Alertmanager as is.

Is there any reason to run your overcomplicated Alertmanager service via Cortex rather than just [Alertmanager](https://github.com/prometheus/alertmanager) itself?

**Comment by gotjosh** [comment]
Hi @jakubgs!

Thanks for documenting your whole saga - helps us find gaps in the documentation. Two quick points:

1. > Also, I'm not sure why I have to specify X-Scope-OrgID if I have auth_enabled: false set in the config....

There's currently a bug in master that is meant to be solved by #3343 for this.

2. The fallback config is meant to provide Cortex tenants with a default configuration in case they have none (e.g. if an alert is received for a tenant, it'll start the corresponding Alertmanager with the fallback configuration)

**Comment by jakubgs** [comment]
Thanks for explaining and pointing to the issue. Appreciate it.

Your documentation doesn't make it very clear what a `tenant` is even. Or am I just bad at searching? What is a `tenant` for? How is it created? Should it be created? Is there a part of docs that addresses this? Because I can't find it.

Also, am I correct in my diagnosis that running of `alertmanager` requires `storage_config` to be provided?
If so, why doesn't it fail at startup if such config is not provided? Surely that would be the sensible thing to do.

**Comment by gotjosh** [comment]
There's always more room for improvement in our documentation! (We'll gladly accept contributions on this 🙌 )

A quick overview is https://cortexmetrics.io/docs/production/auth/ but that does not complete the whole picture. There's a bit more information in https://cortexmetrics.io/docs/architecture/#alertmanager and in the front page wrt multi-tenancy https://cortexmetrics.io/docs/.

> Also, am I correct in my diagnosis that running of alertmanager requires storage_config to be provided?

[This part](https://cortexmetrics.io/docs/architecture/#alertmanager) touches a bit on this subject, we provide several options to store per-tenant configuration (some for historical purposes), [you can revise the flags for options](https://cortexmetrics.io/docs/configuration/configuration-file/#alertmanager_config) - we recommend using any sort of object store for them (S3, GCS, etc).


In my eyes, the most important question you've asked is:

> And I am still failing to see what's the advantage of running this setup over just running Alertmanager as is. Is there any reason to run your overcomplicated Alertmanager service via Cortex rather than just Alertmanager itself?

Which goes back on the subject of multi-tenancy - if you do not require multi-tenancy, there's (generally) no reason to run the Alertmanager from Cortex. The Cortex Ruler (if needed) is compliant with the vanilla Alertmanager.

**Comment by jakubgs** [comment]
>[This part](https://cortexmetrics.io/docs/architecture/#alertmanager) touches a bit on this subject

Ah, indeed, there is this line:

>The Cortex alertmanager is built on top of the Prometheus Alertmanager, adding multi-tenancy support. Like the ruler, the alertmanager requires a database storing the per-tenant configuration.

But it just says "requires a database". It doesn't specify that it requires exactly `storage_config`. What I though is that either the `storage` sections of the `alertmanager` config supply that. Since their docs state:
```
storage:
  # Type of backend to use to store alertmanager configs. Supported values are:
  # "configdb", "gcs", "s3", "local".
  # CLI flag: -alertmanager.storage.type
  [type: <string> | default = "configdb"
```
https://github.com/cortexproject/cortex/blob/fd0548e4288a2cecdcb530ec90c9297a5a36e503/docs/configuration/config-file-reference.md#alertmanager_config

It clearly states that this is used to "store alertmanager configs", but based on my code dive and what you're saying this is NOT where the alertmanager is stored, and in turn it uses `storage_config` for chunk storage.

It's very confusing.

**Comment by jakubgs** [comment]
>Which goes back on the subject of multi-tenancy - if you do not require multi-tenancy, there's (generally) no reason to run the Alertmanager from Cortex. The Cortex Ruler (if needed) is compliant with the vanilla Alertmanager.

That's great to hear, then I can avoid this whole complex setup and just re-use my existing Alertmanager cluster. Great.
I think this information should definitely be mentioned in documentation, like [here](https://cortexmetrics.io/docs/architecture/#alertmanager).

**Comment by gotjosh** [comment]
Thanks for your valuable feedback.

The confusion certainly comes from `client chunk.ObjectClient` - the name is deceiving, this does not require access to the chunk storage. We just re-use use the same object storage client that the chunks package uses.

**Comment by jakubgs** [comment]
Interesting. Let me try building your PR branch and see what actual error I get from it.

**Comment by jakubgs** [comment]
And there we have it:
```
caller=multitenant.go:489
component=MultiTenantAlertmanager
msg="unable to initialize the Alertmanager with a fallback configuration"
user=0
err="local alertmanager config storage is read-only"
```
Though that's weird, becasue my config looks like this:
```yaml
  storage:
    type: 'local'
    local:
      path: '/var/tmp/cortex-alertmanager'
```
And the folder has write permissions for service user:
```
 > ls -l /var/tmp/
total 20
drwxrwxr-x 5 cortex adm  4096 Aug 14 11:55 cortex
drwxrwxr-x 4 cortex adm  4096 Aug 19 14:49 cortex-alertmanager
```

**Comment by jakubgs** [comment]
I tried making it all `777`:
```
 > sudo chmod 777 -R /var/tmp/cortex-alertmanager
```
But I'm getting the same error:
```
err="local alertmanager config storage is read-only"
```

**Comment by jakubgs** [comment]
Oh...
https://github.com/cortexproject/cortex/blob/0c44cc2e3dc04b13be71ecef20cfa90c552de3c7/pkg/alertmanager/alerts/local/store.go#L99-L101

**Comment by jakubgs** [comment]
It appears only `objectclient` type storage supports `SetAlertConfig`:
https://github.com/cortexproject/cortex/blob/0c44cc2e3dc04b13be71ecef20cfa90c552de3c7/pkg/alertmanager/alerts/objectclient/store.go#L84-L92
So I'm confused. Why are you saying in the docs:
```
storage:
  # Type of backend to use to store alertmanager configs. Supported values are:
  # "configdb", "gcs", "s3", "local".
  # CLI flag: -alertmanager.storage.type
  [type: <string> | default = "configdb"
```
When both `configdb` and `local` are clearly not supported since they just fail to set anything.

**Comment by gotjosh** [comment]
@pracucci Similarly to #3401, this can also be categorised as a doc improvement.

@jakubgs the configuration API is marked as experimental because there's a history with `configdb` (`local` is more a testing strategy) - which I believe it's [marked as deprecated at this point](https://cortexmetrics.io/docs/api/#configs-api).

**Comment by gotjosh** [comment]
I'm going to quote @bboreham as I understand this might be unideal - but at the moment is the best we can offer that avoids breaking changes (which is something we value):

> Yes it appears that the old way is deprecated and the new way is experimental. We value honesty over completeness 😉

**Comment by jakubgs** [comment]
So based on that, does that mean I have to run the `configs` module as a separate service to make this work?
```
 > cortex -modules
alertmanager
all
compactor
configs
distributor *
flusher
ingester *
purger *
querier *
query-frontend *
ruler *
store-gateway *
table-manager *

Modules marked with * are included in target All.
```
The `configs` module is not included in `all`, so I assume that means it has to be run separately. Correct?

**Comment by pstibrany** [comment]
> The `configs` module is not included in `all`, so I assume that means it has to be run separately. Correct?

It is now also possible to run it together with other modules, by using `-target=all,configs` or `-target=compactor,ruler,configs`.

**Comment by jakubgs** [comment]
Oh, that's neat. That makes it simpler I guess.

Though it does make me wonder. Why is `config` not included in `all` if it would make it easier to setup the service initially?

**Comment by bboreham** [comment]
Configs service is deprecated.

**Comment by jakubgs** [comment]
What is recommended then?

**Comment by gotjosh** [comment]
> This part touches a bit on this subject, we provide several options to store per-tenant configuration (some for historical purposes), you can revise the flags for options - we recommend using any sort of object store for them (S3, GCS, etc).

**Comment by jakubgs** [comment]
Just so you know, based on https://github.com/cortexproject/cortex/issues/3395#issuecomment-717144961 I've decided to abandon configuring Alertmanager via Cortex. Do with this issue what you will.

**Comment by gotjosh** [comment]
We'll keep it around to improve the documentation - thanks again for the feedback!

**Comment by jakubgs** [comment]
Thanks for explaining things. Cheers.

**Comment by pracucci** [comment]
_Keeping it open to improve the doc._

**Comment by Carmezim** [comment]
Any insights on getting `error validating Alertmanager config: mkdir /tmp/validate-config798960130: read-only file system
` when configuring alerts?

**Comment by bboreham** [comment]
#3888 introduced a new implementation of AlertManager config.
However documentation still appears to be sketchy.
