### ISSUE TITLE
Need metric for monitoring number of blocks per tenant

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#3398]
Cortex should export metrics about number of blocks per each tenant, or perhaps even number of blocks per tenant per time range. Soft-deleted blocks should be counted specially.

This metric should be used for alerting if number of blocks (especially 2h blocks) per tenant is too large. Normally (if compactor isn't lagging behind) it should be between N (number of ingesters) and 0. If it grows over 2 * N  or even more, then compaction is too slow or even broken for given tenant.

**Comment by pracucci** [comment]
> Cortex should export metrics about number of blocks per each tenant, or perhaps even number of blocks per tenant per time range.

From which component would you expose it? I would say compactor, but I'm open to better ideas.

**Comment by pstibrany** [comment]
I'm also thinking compactor.

I was hoping that we could reuse sync information from syncer that we pass to Compactor, but I think it only runs Sync before compactions, not after, so it would be outdated.
