### ISSUE TITLE
How to migrate from Prometheus to Cortex?

### ISSUE THREAD

**Issue by jakubgs** [cortexproject/cortex#3410]
## Description

I've deployed cortex a few months ago, and it's been chugging along nicely([though I'm still trying to get alerts going](https://github.com/cortexproject/cortex/issues/3401)). But I still have an old instance of Prometheus that contains metrics from before I deployed Cortex. How can I still access the data via Cortex?

## Details

I was thinking of two solutions:

* Provide the Prometheus endpoint to Cortex to query past certain place in time for missing data.
  - As far as I know there is no way to do this currently, correct?
* Migrate data from Prometheus local storage into Cortex
  - I found [this](https://cortexmetrics.io/docs/blocks-storage/migrate-storage-from-thanos-and-prometheus/) but I'm not sure if this is relevant, and it's quite confusing.

**Comment by jakubgs** [comment]
The [doc](https://cortexmetrics.io/docs/blocks-storage/migrate-storage-from-thanos-and-prometheus/) states that:

>### Upload TSDB blocks to Cortex bucket
>TSDB blocks stored in Prometheus local disk or Thanos bucket should be copied/uploaded to the Cortex bucket at the location `bucket://<tenant-id>/` (when Cortex is running with auth disabled then `<tenant-id>` must be `fake`)

But it doesn't actually say what it means to "upload to the Cortex bucket". How is that done? Because I don't know.

**Comment by jakubgs** [comment]
It also states that:

>The Cortex blocks storage engine stores series in TSDB blocks uploaded in the storage bucket.

Does this mean that it's impossible to migrate data from Prometheus into a Cortex instance using Cassandra and chunk storage?

**Comment by pracucci** [comment]
The doc you linked is for the Cortex blocks storage. Assuming you're running Cortex with the blocks storage, you can follow that guide and upload Prometheus TSDB blocks to the storage. The "upload" procedure is really an upload from local machine to the object store. The tool to use depends on the object store you're using, like `awscli` for S3 or `gsutil` for Google GCS.

**Comment by pracucci** [comment]
> It also states that:
> 
> > The Cortex blocks storage engine stores series in TSDB blocks uploaded in the storage bucket.
> 
> Does this mean that it's impossible to migrate data from Prometheus into a Cortex instance using Cassandra and chunk storage?

If you running Cortex with the **chunks storage**, then I'm not aware of any publicly available tooling to migrate the data. Maybe @gouthamve knows more about it.

**Comment by jakubgs** [comment]
Oh I see, so the block storage simply uploads the WAL files from Prometheus to S3 or GCS with modified `meta.json`?

That would make sense I guess. Thanks for explaining.

**Comment by jakubgs** [comment]
Do you think it would be difficult to modify Cortex to query a "fallback" Prometheus instance API for data that is missing in it's own store? This way I could retain the old instance just for keeping old data, and just use Cortex for anything new.

**Comment by pracucci** [comment]
> Oh I see, so the block storage simply uploads the WAL files from Prometheus to S3 or GCS with modified `meta.json`?
> 
> That would make sense I guess. Thanks for explaining.

Not the WAL, but compacted TSDB blocks. TSDB blocks are the directories with a name like `01EEG6X4HESPE8R8B7HYR14P8G`.

**Comment by jakubgs** [comment]
Ah, thanks for explaining.

**Comment by wangzhao765** [comment]
@pracucci 
Is there any way to migrate data stored in InfluxDB to Cortex block storage?

**Comment by pracucci** [comment]
> Is there any way to migrate data stored in InfluxDB to Cortex block storage?

I'm not familiar with InfluxDB. A couple of options to investigate come to my mind:
1. Export InfluxDB data into Prometheus TSDB blocks (any tool?)
2. Configure InfluxDB to reply its data and remote write to Cortex (supported? any tool?)

**Comment by pracucci** [comment]
> The tool to use depends on the object store you're using, like awscli for S3 or gsutil for Google GCS.

We're now having a `thanosconvert` tool:
https://cortexmetrics.io/docs/blocks-storage/migrate-storage-from-thanos-and-prometheus/#automatically-migrate-metadata-using-the-thanosconvert-tool

**Comment by bboreham** [comment]
Issue is still valid as the documentation should be updated to include the points made by @jakubgs, e.g. clarify what "upload" means.

**Comment by jakubgs** [comment]
Another few questions:

The instructions don't make this clear, but are those steps intended for a new Cortex setup with an empty bucket, or will they also work for an existing Cortex setup that has already uploaded files to the bucket?

And if it can work with an already working Cortex setup, should cortex be stopped for the upload? Or maybe restarted after upload finishes? If so, which components? Ingesters? Compactors? Store gateways? All of them?

**Comment by bboreham** [comment]
They should work for an existing Cortex setup that has already uploaded files to the bucket.

No need to stop or restart anything; Cortex does periodic re-scans and will pick up the added data.
(I don't know off the top of my head exactly how long to wait, but it's on the order of minutes)

If some of the uploaded data overlaps in time with Cortex data then the compactor will read and re-write that data into one set of non-overlapping blocks. That could take a while, depending on how much data overlaps.

**Comment by jakubgs** [comment]
Thanks for explaining. I'll try it out.

**Comment by jakubgs** [comment]
Yep, I can confirm it works. The compactor picks up the work and reduces the size gradually by pruning and consolidating.

**Comment by jakubgs** [comment]
In general you should be looking at metrics like these:
```
cortex_compactor_block_cleanup_completed_total
cortex_compactor_block_cleanup_failed_total
cortex_compactor_group_vertical_compactions_total
cortex_compactor_blocks_marked_for_deletion_total
cortex_compactor_blocks_cleaned_total
```
Which indicate whether it's actually working.

**Comment by osmanovv** [comment]
#### There is an example for synchronizing local Prometheus with local Cortex ('filesystem' deployment)

First, back up your existing Cortex data (this is the directory mentioned in config section `filesystem/dir`, e.g. `/etc/cortex/single-process-config.yaml`):
```
cp -a /tmp/cortex/tsdb/. /tmp/cortex/tsdb_bak/
```
Then empty that folder and copy Prometheus data to it:
```
rm -r /tmp/cortex/tsdb/fake/*
cp -a /var/lib/prometheus/metrics2/. /tmp/cortex/tsdb/fake/
chown -R cortex:cortex /tmp/cortex/tsdb
systemctl restart cortex
systemctl status cortex
```
