### ISSUE TITLE
cortex_querier_.* metrics no longer differentiates api/prom/v1 routes

### ISSUE THREAD

**Issue by csmarchbanks** [cortexproject/cortex#3432]
After deploying 1.5.0-rc.0 I noticed that some of our dashboards broke, upon digging in I noticed that the `cortex_querier_.*` metrics truncate routes to just `api_prom_api_v1` rather than e.g. `api_prom_api_v1_query`. Metadata is still split into `api_prom_api_v1_metadata`, but not query, query_range, series, etc...

I think this might be related to https://github.com/cortexproject/cortex/pull/3320, but didn't have time yet to fully dig in.

@jtlisi would you be able to see if it is related to #3320?

**Comment by jtlisi** [comment]
Fixed in #3436
