### ISSUE TITLE
Support multiple AWS S3 SSE (Server side encryption) 

### ISSUE THREAD

**Issue by agardiman** [cortexproject/cortex#3437]
**Is your feature request related to a problem? Please describe.**
We have S3 buckets that support just `aws:kms` server side encryption.
I can't use Cortex with those buckets because the S3 storage client hardcodes `AES256` https://github.com/cortexproject/cortex/blob/master/pkg/chunk/aws/s3_storage_client.go#L116

**Describe the solution you'd like**
When using `-ruler.storage.s3.sse-encryption` option (Ruler is just one example) I would like to specify what type of encryption to use, instead of just true or false.

**Describe alternatives you've considered**
If changing the CLI parameter's value type is not an option, then I would add another option, which is
`-ruler.storage.s3.sse-encryption-type` of type String, where values can be `AES256` or `aws:kms`

**Additional infomation**
This might affect Loki as well

**Comment by pracucci** [comment]
Once we add SSE settings to config option, let's create a config structure compatible to [Thanos' one](https://thanos.io/tip/thanos/storage.md/#s3) and let's add it to blocks storage S3 client too.

**Comment by pracucci** [comment]
_Still valid_

**Comment by lucasvmiguel** [comment]
Going to take this issue to work on. 

I believe we don't want to break the config interface changing `ruler.storage.s3.sse-encryption` to receive the encryption type as a string, instead of a boolean. (it would be the cleanest way though)

So, I'll implement that as suggested by @agardiman . I'll create a new field called `ruler.storage.s3.sse-encryption-type` to receive the encryption type as a string to be used.

It should be a pretty straightforward solution, let me know if there is something wrong or that I'm missing.

**Comment by pstibrany** [comment]
> I believe we don't want to break the config interface changing `ruler.storage.s3.sse-encryption` to receive the encryption type as a string, instead of a boolean. (it would be the cleanest way though)

Right. Unfortunately that could break existing setups, as boolean flags can be used without parameter, but string flags require a parameter.

> It should be a pretty straightforward solution, let me know if there is something wrong or that I'm missing.

Looks good to me. Please make sure to mark `sse-encryption` as deprecated, and document behavior when both `sse-encryption` and `sse-encryption-type` are used.

**Comment by pstibrany** [comment]
> It should be a pretty straightforward solution, let me know if there is something wrong or that I'm missing.

Please also check @pracucci's comment https://github.com/cortexproject/cortex/issues/3437#issuecomment-720381870.

**Comment by lucasvmiguel** [comment]
@pstibrany I was just talking to a colleague, it seems that we need/should use S3 client from the Thanos project to implement this enc type config addition.

Therefore, I need to understand better Cortex and Thanos. (any help to understand is welcome)
