### ISSUE TITLE
Support pagination for large prometheus rules responses

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#3450]
We're seeing one of our tenants having just 242 have 3MB worth of data being returned in `/api/prom/api/v1/rules`. This means once we start inching towards the 1000s of rules range we will see the API and UIs becoming clunky and slow. We should add pagination for this.

**Comment by AllenzhLi** [comment]
When alerts is increasing, I can't get rules detail info
```
{
"status": "error",
"data": null,
"errorType": "server_error",
"error": "unable to retrieve rules from other rulers, rpc error: code = ResourceExhausted desc = grpc: received message larger than max (54207607 vs. 4194304)"
}
```
Currently, the grpc_server_recv_msg_max_size is default 4MB，may be this should be 100MB

**Comment by jtlisi** [comment]
_still valid_
