### ISSUE TITLE
S3 objects

### ISSUE THREAD

**Issue by mrmassis** [cortexproject/cortex#3467]
I would like to reduce the number of objects in S3. My question is: what parameters could I configure so that the number of objects in S3 would decrease? Would the size of the chunk influence?
Thanks in advance

**Comment by pracucci** [comment]
Are you running Cortex with the chunks or blocks storage engine?

**Comment by mrmassis** [comment]
Chunks, and Ceph backend.

**Comment by pracucci** [comment]
The number of chunks stored with the Cortex chunks storage is pretty high, and a factor of number of active series and the `-ingester.max-chunk-age` (defaults to 12h). If you're running a fresh Cortex cluster, you may consider switching to the Cortex blocks storage, which stores a low number of large objects (compared to the Cortex chunks storage which stores a large number of small objects).

**Comment by mrmassis** [comment]
Tkz for the answer.
In my infra I cant use the block storage. Is avaliable to the porpouse only object store.

**Comment by pracucci** [comment]
> In my infra I cant use the block storage. Is avaliable to the porpouse only object store.

If you don't have access to an object store, you may try to run the Cortex blocks storage with the "filesystem" backend, using Ceph to share the filesystem across nodes. It's something we never tried, but it should work as much as it's working with the Cortex chunks storage.

**Comment by mrmassis** [comment]
Object store I have access, but RBD not.

**Comment by chancez** [comment]
@mrmassis They are not referring to block device storage (RBD), they're referring to the cortex "blocks" storage, which stores files on a local disk, then flushes them to object storage (S3) at regular intervals. You do need relatively stable persistent local storage for each ingester.

**Comment by bboreham** [comment]
You can read more about this "blocks" at https://cortexmetrics.io/docs/blocks-storage/
