### ISSUE TITLE
userID not being set despite X-Scope-OrgID and X-Scope-UserID being set

### ISSUE THREAD

**Issue by oneubauer** [cortexproject/cortex#3469]
**Describe the bug**
It seems I'm unable to get the distributor+ingester to properly set userID.

**To Reproduce**
1. Start Cortex using block mode (I'm using a lightly modified cortex helm chart)
2. set nginx gateway to proxy the incoming POSTs and add X-Scope-OrgID and X-Scope-UserID to "test_user"
3. Configure prometheus to remote_write. No auth yet. I'm trying to work this out first.

**Expected behavior**

Looking at distributer's all_user_stats and the block storage bucket, I would expect to see an entry for "test_user". 
I see "fake" instead for User and name of the subdir in the bucket, respectively.
 

Note: confirmed with tcpdump that all traffic from proxy ->  distributor and from distributer -> ingester does have the headers properly set.
Also note, all metrics **_are_** actually being collected. I just want the block storage to store them in different subdirs based on user, and have distributor stats broken out by user.

**Environment:**
 - Infrastructure: Kubernetes (gke)
 - Deployment tool: helm

**Storage Engine**
-  Blocks

**Additional Context**
I might be missing some configuration, but I was under the impression from everything I had read that X-Scope-OrgID and/or X-Scope-UserID would be trusted by cortex to define the UserID. Wondering if this is a problem specific to using block storage, or if I'm doing something else wrong?

**Comment by pstibrany** [comment]
> I was under the impression from everything I had read that X-Scope-OrgID and/or X-Scope-UserID would be trusted by cortex to define the UserID

This is only true when Cortex is configured with enabled authorization. When using `-auth.enabled=false` then Cortex uses “fake” user, and ignores `X-Scope-OrgID`. Cortex doesn’t use `X-Scope-UserID` header.

**Comment by oneubauer** [comment]
Ah! Thank you very much!
