### ISSUE TITLE
ruler: Support S3 authentication via env vars

### ISSUE THREAD

**Issue by jgulick48** [cortexproject/cortex#3488]
**Is your feature request related to a problem? Please describe.**
When configuring Ruler to use S3 of the storage of rules, Authentication has to be specified via the config file instead of being able to use env vars.

**Describe the solution you'd like**
Add support for env var based s3 authentication which does work for ingesters, store-gateway, and compactor when using blocks storage.

**Describe alternatives you've considered**
Adding an init container to fill the env vars into the config on startup. 

**Additional context**
We are using a Helm chart to manage our deployment of Cortex and the values.yaml file is stored in a git repo. We would prefer to not have to add credentials to this file and instead be able to pull these credentials from environment variables.

**Comment by pracucci** [comment]
The Cortex YAML config supports env variables replacement ([see doc](https://cortexmetrics.io/docs/configuration/configuration-file/#use-environment-variables-in-the-configuration)). Would that work as a temporary workaround to allow you to configure S3 credentials as env variables?

**Comment by pracucci** [comment]
_Closing because can be solved via env variables replacement in the YAML config._
