### ISSUE TITLE
QoD caused by start=<huge-negative-value>&end=<positive-value> (huge start-end range)

### ISSUE THREAD

**Issue by bwplotka** [cortexproject/cortex#349]
Follow up of: https://github.com/weaveworks/cortex/issues/327

My QoD is still valid. I dived into the issue and it seems that the confusion here is because Prometheus wrongly parses my mistaken `start=1489025420000` timestamp. From query perspective it is not really start > time problem, but actually underlying int64 overflow I fixed here:  https://github.com/prometheus/prometheus/pull/2501 caused start to be huge negative value.

This means that QoD is still possible and is caused not by `start > end`, but actually huge range (e.g `start=MinInt64&end=MaxInt64`)

@tomwilkie do you have any idea how to handle this properly? IMO Some limiter or further validation is needed.

**Comment by tomwilkie** [comment]
Yeah, we'll just have to limit the size of the biggest query to something like 13months.

**Comment by Bplotka** [comment]
Or configured by flag

**Comment by juliusv** [comment]
Is it really a query of death though? It should at least just time out after 2 minutes (default `promql.Engine` timeout), right?

**Comment by tomwilkie** [comment]
I wonder if we honour the context cancelled stuff in the chunk store...

**Comment by juliusv** [comment]
As far as I can see, we don't care about the context done-ness anywhere in the chunk store :-/

I filed another issue for that because that's a bigger undertaking to make all of the chunk store context cancellation aware: https://github.com/weaveworks/cortex/issues/381

**Comment by bboreham** [comment]
I think a limit on length of date range should be done in the Prometheus code that first unpacks the query request. Cortex doesn't see the dates until the query comes down into the chunk store.

It would be appropriate to have a limit in the chunk store on things that are uniquely chunk store concerns, e.g. how many buckets the query touches.
