### ISSUE TITLE
Tenant-ID confusion

### ISSUE THREAD

**Issue by TomL-dev** [cortexproject/cortex#3493]
**Is your feature request related to a problem? Please describe.**
I'm trying to figure out/understand the multi-tenantcy. It's quite unclear for me and the documentation ([Authentication and Authorisation](https://cortexmetrics.io/docs/guides/auth/)) is quite short/high level. After searching through older issues in github, i found links to both the [glossary](https://cortexmetrics.io/docs/guides/glossary/#tenant) and the [limitations](https://cortexmetrics.io/docs/guides/limitations/#tenant-id-naming) which gave me more insights. 

Also the whole concept of multi tentantcy is a bit unclear. lets say i have 2 zones where my prometheis are remote-writing to cortex. They both have their own tenant-id. So it's easy to track how much data each zone/tenant is writing to cortex. But on the query side you should use the same tenant-id if you want to query that data. There is no way to query both zones as far as i'm aware. If this is true, we should use the same tenant-id and find data by the `cluster` label in the metrics. But then i lose the overview of which tenant is writing how much data its sending. But if we should use the same tenant-id, then you can only limit who can/can't access the data, right? Maybe a solution can be to allow for multiple values in the `X-Scope-OrgID` header? not sure if this is feasible. 

**Describe the solution you'd like**

- link from [Authentication and Authorisation](https://cortexmetrics.io/docs/guides/auth/) to either/both: [glossary](https://cortexmetrics.io/docs/guides/glossary/#tenant) and/or [limitations](https://cortexmetrics.io/docs/guides/limitations/#tenant-id-naming)
- explain more in depth how it's working
- add tips/tricks
- support for multiple values in `X-Scope-OrgID`?

**Comment by pstibrany** [comment]
> * support for multiple values in `X-Scope-OrgID`?

There is proposal for this, and work on this feature has started.

https://github.com/cortexproject/cortex/pull/3364

**Comment by TomL-dev** [comment]
Nice, i've missed that!

**Comment by TomL-dev** [comment]
will it come with requested documentation updates as well?

**Comment by pstibrany** [comment]
> will it come with requested documentation updates as well?

Probably not. We can keep this issue until that is fixed. (Feel free to send PR if you want)
