### ISSUE TITLE
ResourceExhausted desc = grpc: received message larger than max

### ISSUE THREAD

**Issue by AllenzhLi** [cortexproject/cortex#3503]
**Describe the bug**
When alerts is increasing, I can't get all rules detail info
`
{
"status": "error",
"data": null,
"errorType": "server_error",
"error": "unable to retrieve rules from other rulers, rpc error: code = ResourceExhausted desc = grpc: received message larger than max (54207607 vs. 4194304)"
}
`

**My cortex config**

`auth_enabled: true

server:
  http_listen_port: 9009

  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000
`

**Comment by pstibrany** [comment]
Unfortunately you're hitting the limit on the client side. It defaults to 4 MB and currently Ruler doesn't expose options to change it.

Ruler exposes only TLS options: https://github.com/cortexproject/cortex/blob/e69d6288033eb5d7ba14e155c5b1f2d912699ed2/pkg/ruler/ruler.go#L66

It should also expose other gRPC options: https://github.com/cortexproject/cortex/blob/7fe8ef659c43e326e38f5141e98e640b693aef1a/pkg/util/grpcclient/grpcclient.go#L105

Would you be interested in sending the PR? Changing one for another should be backward-compatible change.

**Comment by AllenzhLi** [comment]
> Unfortunately you're hitting the limit on the client side. It defaults to 4 MB and currently Ruler doesn't expose options to change it.
> 
> Ruler exposes only TLS options:
> 
> https://github.com/cortexproject/cortex/blob/e69d6288033eb5d7ba14e155c5b1f2d912699ed2/pkg/ruler/ruler.go#L66
> 
> It should also expose other gRPC options:
> 
> https://github.com/cortexproject/cortex/blob/7fe8ef659c43e326e38f5141e98e640b693aef1a/pkg/util/grpcclient/grpcclient.go#L104-L107
> 
> Would you be interested in sending the PR? Changing one for another should be backward-compatible change.

Is there any plan to support expose options to change it ？

**Comment by pstibrany** [comment]
I've sent PR #3523 to expose these options.

**Comment by pstibrany** [comment]
Note that PR also changes the limits, especially the one you're hitting is changed from 4 MiB to 100 MiB, so you may not even need to change those settings now.

**Comment by AllenzhLi** [comment]
This is really good news.
