### ISSUE TITLE
What is the required version of Memcached?

### ISSUE THREAD

**Issue by jakubgs** [cortexproject/cortex#3509]
I can't find any information in the docs on the minimal version of Memcached required.

I can see that the version used in Docker Compose files is `1.6.1`:
https://github.com/cortexproject/cortex/blob/8a55590c192d8c85f2fa125893fb67e55dbf96d7/development/tsdb-blocks-storage-s3/docker-compose.yml#L22
https://github.com/cortexproject/cortex/blob/c03547e730bb67d23fb5eefd08d87df01db72a1b/.circleci/config.yml#L156
As well as here:
https://github.com/cortexproject/cortex/blob/c03547e730bb67d23fb5eefd08d87df01db72a1b/integration/e2e/images/images.go#L9

Is that the minimal version? Or would it work with an earlier version?

**Comment by pracucci** [comment]
At Grafana Labs we're running memcached `1.5.17`, but later versions should be fine too.

**Comment by jakubgs** [comment]
Okay, thanks for confirming earlier version will work. Though the docs could benefit from a "Requirements" page. Thanks!

**Comment by pracucci** [comment]
> Though the docs could benefit from a "Requirements" page.

Good point that we should mention supported dependencies versions. I'm keeping the issue open for the doc improvement.

**Comment by bboreham** [comment]
Also works with 1.4.36, FWIW.

**Comment by jtlisi** [comment]
LGTM

**Comment by pracucci** [comment]
_Still valid_
