### ISSUE TITLE
Queryfrontend behind NGINX

### ISSUE THREAD

**Issue by TomL-dev** [cortexproject/cortex#3514]
I'm trying to get the queryfrontend behind nginx on a subpath. I did make it work for all others but the queryfrontend only works half. With half i mean i do see the metrics and config on the http_path_prefix domain. but querying data from the datasource/caches doesn't seem to work

Lets say i have a DNS. sbx.cortex.foo.com.

I want to have all my cortex components behind `/cortex/<module-name>`.
To make this work I configured the `http_path_prefix` for each module to be `/cortex/<module-name>`

This works now for all modules, and the metrics and config are available at `/cortex/<module-name>/metrics` and `/cortex/<module-name>/config`.

However when I try to query data from grafana to the queryfrontend I can't seem to make it work.

For the datasource i used `/cortex/queryfrontend/prometheus`, or all other variants i could think of. Also tried the legacy path.

I can make it work by configuring `http_prefix` to `/` and `http_path_prefix` to `/`. Then i'm able to query the data from grafana by pointing the datasource to `<dns>/prometheus`

I would like some guidance/help on getting this sorted out.

_If this turns out to be under-documented or unclear i can update the docs via pull-request if necessary._

**Comment by pracucci** [comment]
The Prometheus-compatible API endpoints are exposed under the `-http.prometheus-http-prefix` prefix, which defaults to `/prometheus`. Have you tried changing it?
