### ISSUE TITLE
UI for alert management

### ISSUE THREAD

**Issue by vishmit123** [cortexproject/cortex#3533]
Is there a UI for alert management (muting/unmuting/etc)

**Comment by gotjosh** [comment]
There is, the alertmanager comes with the same UI as the [Prometheus Alertmanager](https://github.com/prometheus/alertmanager)

**Comment by roidelapluie** [comment]
but you need a frontend to add the tenant id header.

**Comment by gotjosh** [comment]
As Julien pointed out, you do something that takes care of Authorization / Authentication e.g. https://github.com/rewe-digital/cortex-gateway

**Comment by gotjosh** [comment]
I think we can close this one @pracucci
