### ISSUE TITLE
Load Balancer in front of the Cortex cluster to eliminate single point of failure

### ISSUE THREAD

**Issue by shybbko** [cortexproject/cortex#3548]
As of now I am running a VM-based Cortex cluster. When quering the cluster for metrics or pushing them into the cluster I use an address of an arbitrarily chosen node. My feeling is that this is not the best way to do that. While it's OK when all nodes are healhy, this might become an issue when some of them are not.

A solution for that might obviously be putting a load balancer in front of the cluster (ie. nginx, as presented on the architecture diagram https://cortexmetrics.io/docs/architecture/), but to eliminate that single point of failure, now that balancer would need to be clustered.

So I began to wonder whether there is a best practice, the one recommended by Cortex, for dealing with this problem?

**Comment by pracucci** [comment]
👋  @shybbko! The common use case is to setup a load-balancer in front of Cortex (both query-frontend and distributors) and make sure the load balancer is in a HA setup a well. When running in the cloud, the load balancer is typically provided by the cloud provider (eg. ELB on AWS), while when running on bare metal the specific setup for the load balancer in HA depends on your setup.

**Comment by shybbko** [comment]
All right, the balancer it is then. Thanks!
