### ISSUE TITLE
Cortex API endpoints should return consistent HTTP status code for tenant error

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#3556]
Authentication middleware already returns `http.StatusUnauthorized` if tenant is missing completely. If call to `tenant.TenantID(ctx)` returns an error, this should be reported as `http.StatusBadRequest` instead. This is not consistent across Cortex codebase.

_Originally posted by @pracucci in https://github.com/cortexproject/cortex/pull/3549#discussion_r533429608_

**Comment by jtlisi** [comment]
_still valid_
