### ISSUE TITLE
Improve our getting started guide

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#3567]
There are a few things I noticed while following @codesome's Rawkode podcast: https://www.youtube.com/watch?v=lI-4jHKv2Y0

* **People need to install Golang, and compile Cortex/Prometheus for them to run through the getting started guide**. This is not trivial at all even for Prometheus, we need to install node and yarn for asset compilation. We should be using release binaries instead.

* **Prometheus config puts both Cortex and Prometheus under the same job**: They should be different jobs in the Prometheus config.

* **User will likely hit an issue with the network interface not found.**: The guide currently assumes users are running with an interface named `eth0` but that is not true at all. We should either default to localhost or have a bigger list of interfaces.

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_

**Comment by AyushRaj8271** [comment]
Hey there ! I would like to work on this issue .
