### ISSUE TITLE
Add support for Redis Cache storage in TSDB

### ISSUE THREAD

**Issue by kamijin-fanta** [cortexproject/cortex#3568]
### Is your proposal related to a problem?

Currently, only in-memory and memcached caches are supported. However, if the user is already running another KVS, there wants to use it.

Also, many accesses to object storage can occur when the cache is cleared. It may be possible to solve this by using an external KVS that can be persisted.

### Describe the solution you'd like

Add Redis or Cassandra support. There should be many users like Memcached.

### Describe alternatives you've considered

Add this support to Thanos. However, Thanos prioritizes a simple setup. So it seems that there are plans to add support for Groupcache.

https://github.com/thanos-io/thanos/issues/3535

### Additional context

none

**Comment by pracucci** [comment]
👋  @kamijin-fanta. Just to better understand it: would you like to add Redis support for caching, in addition to memcached? How does Cassandra fits into this picture?

**Comment by kamijin-fanta** [comment]
I want to work on this 👍 

I'm not familiar with Redis, so the HA configuration looks complicated. There are also Replication, Cluster, and Sentinel types. So building a Cassandra HA configuration looks easy. Cassandra is also supported to add nodes when having a lot of data.

Thanos cache does not require strong integrity. Cassandra has an eventual consistency model, so it is resistant to failures.

**Comment by pracucci** [comment]
I don't think supporting Cassandra for caching purposis is a good idea. We shouldn't do it. On the contrary, I'm open to support Redis for caching in the blocks storage. We already have a Redis caching client in Cortex (which we use for the chunks storage) and we should start from there.

**Comment by kamijin-fanta** [comment]
OK. First, I'll implement Redis Cache.

**Comment by pracucci** [comment]
_Still valid_

**Comment by bboreham** [comment]
Looks like the associated PR needs further review.
