### ISSUE TITLE
Crash and restart of store-gateway puts extra pressure on other store-gateways

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#3570]
During recent incident, we have observed following behaviour:

1. Some store gateways have crashed, and restarted
2. On restart, store gateways join the ring and start the initial sync of blocks. During this sync, they are in the JOINING state.
3. Other (ACTIVE) store-gateways notice that ring has changed, because of change of state from ACTIVE to JOINING (for restarted gateways). This triggers synchronization of the blocks on these ACTIVE store-gateways.
4. ACTIVE store-gateways will also load blocks that belong to JOINING instances. 
5. After JOINING store-gateways are finished with initial-sync, they change state to ACTIVE again, which triggers another sync in other store-gateways (this will actually unload blocks from other instances).

Step 4. is problematic, because it puts extra pressure on store-gateways that hasn't crashed -- they will have disproportionally bigger number of blocks loaded. This can eventually make them crash as well, if they run out of resources. If they crash, they will start initial-sync in JOINING state again, making other ACTIVE store-gateways start loading more blocks.

**Comment by pracucci** [comment]
> Step 4. is problematic, because it puts extra pressure on store-gateways that hasn't crashed -- they will have disproportionally bigger number of blocks loaded.

Agree and we need to fix it. The reason why I did it was so to cover the scale you scale up to a number of blocks >= replication factor. Let's say you start 10 new store-gateway at the same time. They will all be JOINING while synching blocks: if other ACTIVE store-gateways start to offload blocks before the JOINING store-gateways are still loading blocks, there will be a period of time during which some blocks are not loaded by any store-gateway and queries will fail.

Thoughts?

**Comment by pstibrany** [comment]
> Agree and we need to fix it.
> 
> The reason why I did it was so to cover the scale you scale up to a number of blocks >= replication factor. Let's say you start 10 new store-gateway at the same time. They will all be JOINING while synching blocks: if other ACTIVE store-gateways start to offload blocks before the JOINING store-gateways are still loading blocks, there will be a period of time during which some blocks are not loaded by any store-gateway and queries will fail.

You are right, we don't want to existing store-gateways to start *offloading* blocks before JOINING store-gateways are ready to serve requests. On the other hand, if existing ACTIVE gateways *don't have the blocks yet*, they should also not *start loading* them either because JOINING gateways are already doing that.

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
This should have been fixed by #4271, because after that PR the JOINING state doesn't expand the replication set anymore.
