### ISSUE TITLE
Detect if a customer is sending "non-deduped" HA pair data

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#3572]
**Is your feature request related to a problem? Please describe.**

A lot of users use HA pairs with Prometheus and every single user has different external labels they set to identify cluster and replica. While we provide ample documentation, a lot of our users still miss it and send us data that we don't dedupe. This will cause 2x as much data and will break the dashboards. 

The only way we can fix it is when the user notices and then notifies us. While I don't have a solution for it, we need to make it easier for our users to find out that they're sending HA pair data. Some kind of metric makes the most sense but not sure how to detect it.

**Comment by pracucci** [comment]
> Some kind of metric makes the most sense but not sure how to detect it.

When this happens, we expect to see an increased number of `sample-out-of-order`, `duplicate-sample` and `duplicate-timestamp` (less likely), right?

**Comment by pracucci** [comment]
_Still valid_
