### ISSUE TITLE
Python 3.5 on Cortex Version: 3.0.1-1 Docker 

### ISSUE THREAD

**Issue by gregzee** [cortexproject/cortex#3607]
I have noticed that the latest version of Cortex Version: 3.0.1-1 has a deprecated version of Python 3.5, which causes failures on some analyzers and responders. It looks like, some analyzers use 3.7+.

Smaller side issue; 
All of the latest analyzers are not deployed in the latest image. (that is an easy fix on my end) but wanted to bring this to light.

It would be greatly appreciated if the image was updated to include the latest analyzers & responders with the appropriate python version.

Thank you :)

**Comment by pracucci** [comment]
> I have noticed that the latest version of Cortex Version: 3.0.1-1 has a deprecated version of Python 3.5

Uhm, the latest version of Cortex is `1.5.0` (and there's `1.6.0-rc.0` out right now). Are we talking about the same Cortex project? 😄

**Comment by gregzee** [comment]
@pracucci NOPE! 😭 😭 Sorry!
