### ISSUE TITLE
Please add AWS to the cortex-vendors-announce list

### ISSUE THREAD

**Issue by ranton256** [cortexproject/cortex#3612]
Please add AWS to the cortex-vendors-announce list so that we can address any embargoed issues in a timely way should any arise.

Per the https://github.com/cortexproject/cortex/security/policy#membership-criteria

  [x] Have an actively monitored security email alias for our project.
  [x] Have a public hosted version/distribution of Cortex.  --> aws.amazon.com/prometheus/ is based on Cortex
  [x] Have a user base not limited to your own organization. 
  [x] Not be a downstream or rebuild of another vendor.
  [x] Be a participant and active contributor in the community.
  [x] Accept the Embargo Policy that is outlined above.
  [x] Be willing to contribute back as outlined above.

Once approved, I will provide the email alias separately because it will trigger a page, and don't want it shared publicly for reasons of avoiding excess hilarity or sleep loss :)

Thanks, very much

**Comment by tomwilkie** [comment]
LGTM - send me the email on slack and I'll add it to the list.
