### ISSUE TITLE
Ruler: rule group limit enforcement has off-by-one error

### ISSUE THREAD

**Issue by mattmendick** [cortexproject/cortex#3615]
**Describe the bug**
The ruler seems to have an issue where the rules per group limit is forcing one fewer than the limit, yielding an error message like this:
```
per-user rules per rule group limit (limit: 15 actual: 15)
```

**To Reproduce**
Submit a rule group with the same number of rules as the limit, ie: 15 rules in a group with the limit set to 15.

**Expected behavior**
The submitted rule group should be allowed to contain up to and containing the limit specified. The limit set to 15 should allow a group with 15 rules to be accepted.

**Comment by pracucci** [comment]
_Still valid_

**Comment by mtanda** [comment]
@pracucci 
We hit this issue in Grafana Cloud. Do you have plan to fix this?

**Comment by pracucci** [comment]
> Do you have plan to fix this?

There's an open PR https://github.com/cortexproject/cortex/pull/3616 which got stuck. I talked to Matt -- the PR author -- and they're fine if anyone takes it over.

**Comment by pracucci** [comment]
Fixed in #3616.

**Comment by mtanda** [comment]
Thanks for quick fix!
