### ISSUE TITLE
Reduce number of bucket API calls done by compactor

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3633]
The work done to introduce the [bucket index](https://cortexmetrics.io/docs/proposals/blocks-storage-bucket-index/) has reduced the number of **baseline** bucket API calls done by queriers and store-gateways. However, the compactor is still doing a large number of bucket API calls.

I did a brief analysis and below is the split down of the bucket API calls, with some details about the compactor. This analysis could be a baseline to discuss further improvements.

## Analysis of a cluster with 7.2K tenants

We're running a Cortex cluster (blocks storage) with 7.2K tenants and a very low QPS. Shuffle sharding is enabled, and each tenant series are ingested in 3 ingesters. Below is an analysis of the bucket API calls over the last 24h (pricing based on Google GCS).

- 6754205  class A ops / day at $0.05  every 10k = 33.7$ / day = 1013$ / month
- 21937274 class B ops / day at $0.004 every 10k = 8.7$  / day  = 261$ / month

compactor:
- 5676115  class A ops (84% of the cluster)
  - upload 26% (legit, needs to upload compacted blocks)
  - delete 30% (legit, needs to delete source blocks)
  - iter   43%
- 14314950 class B ops (65% of the cluster)
  - attributes 2.4%
  - exists     44%
  - get        53% (legit, needs to download blocks to compact)

Estimated compactor calls to `Exists()`:
- Tenant deletion mark
  - 1x tenant every `compaction_interval`
  - 1x tenant every `cleanup_interval`
- `block.MarkForDeletion()`
  - 1x deleted block
- `block.Delete()`
  - 1x deleted block
- `BaseFetcher.loadMeta()`
  - 1x block every compaction "run" (can happen multiple times for the same tenant over the same `compaction_interval`)

Estimated compactor calls to `Iter()` (about 2.4M/day):
- Blocks cleaner
  - [non significative] 1x every 1K tenants every `cleanup_interval` (to discover tenants)
- Compactor
  - [non significative] 1x every 1K tenants every `compaction_interval` (to discover tenants)
  - [estimated ~250k/day] 1x tenant every compaction "run" (`BaseFetcher.fetchMetadata()`, called at least twice)
- [estimated ~1.3M/day] Bucket index updater (used by blocks cleaner)
  - 1x tenant every `cleanup_interval` (to list blocks)
  - 1x tenant every `cleanup_interval` (to list deletion marks)
- [estimated ~550K/day] `block.Delete()`
  - 1x every block to delete (to list `<block-id>/`)
  - 1x every sub-path in the block structure of a block to delete (to list `<block-id>/chunks/`)

_In this specific cluster, compactor is configured with block range periods `12h,24h,168h,672h`._

**Comment by pracucci** [comment]
> `block.Delete()`
> - 1x every block to delete (to list <block-id>/)
> - 1x every sub-path in the block structure of a block to delete (to list <block-id>/chunks/)

We could cut them by 50% running a "list objects" API call with prefix but without delimiter, so that we get back objects at any "depth".

**Comment by pracucci** [comment]
> `block.MarkForDeletion()`
> - 1x deleted block

Idea: I'm wondering if we really need to check the existence of `deletion-mark.json` before uploading it. By its nature, it shouldn't be a big deal if we skip the check and we overwrite it in the remote case it already exists.

**Comment by pstibrany** [comment]
> * [estimated ~550K/day] `block.Delete()`
>   
>   * 1x every block to delete (to list `<block-id>/`)
>   * 1x every sub-path in the block structure of a block to delete (to list `<block-id>/chunks/`)

One possibility how to save on Delete (and Upload) operations would be to use larger chunks files. They are currently limited to 512 MB, which is hardcoded in Prometheus. By doubling the limit, we would only need 1/2 of operations for uploading and deleting chunks files. (N times higher -> 1/N of operations).

Making the limit configurable would affect both Prometheus and Thanos.

Alternative way to implement it would be concatenating chunks files during upload time (so in the long-term storage, we would only keep single segment file) while preserving original lengths in the `meta.json`, and then modifying bucket read operations addressing individual segment file such that they address correct offset in concatenated file instead. This wouldn't affect querying or caching, only number of operations required to upload and delete segment files.

**Comment by pstibrany** [comment]
> * 1x every sub-path in the block structure of a block to delete (to list `<block-id>/chunks/`)

New meta.json files contain this list already, perhaps we can use it when deleting block.

**Comment by pracucci** [comment]
_Still valid_
