### ISSUE TITLE
Support s3forcepathstyle in blocks_config

### ISSUE THREAD

**Issue by nivekuil** [cortexproject/cortex#3635]
**Is your feature request related to a problem? Please describe.**

The s3 chunks storage config supports s3forcepathstyle as added in https://github.com/cortexproject/cortex/pull/1476 but the blocks storage config does not. 

**Describe the solution you'd like**

Have the same options between the chunks/block style config. `region` is also missing from the blocks config, and the `endpoint` format appears to be different as well, not accepting a scheme?

**Comment by pracucci** [comment]
👋  @nivekuil 

> region is also missing from the blocks config

You can use the `endpoint` to specify the region's endpoint. Being the S3 client a generic client for S3-compatible API endpoints (eg. Minio) it's preferrable having a flexible `endpoint` over `region`.

> and the endpoint format appears to be different as well, not accepting a scheme

We alway enforce HTTPS. If you really need HTTP, then you can set `insecure: true` to switch to HTTP.

**Comment by pracucci** [comment]
> The s3 chunks storage config supports s3forcepathstyle as added in #1476 but the blocks storage config does not.

Could you share more details about your use case and why you need the `s3forcepathstyle`?

**Comment by nivekuil** [comment]
It's a matter of consistency mostly: if I were moving from chunks storage to blocks storage, it seems like unnecessary complexity to learn a new, breaking configuration for essentially the same function.  That is unless the reduced config options is the right way for both, and the extra options on chunk_storage I mention are actually deprecated.

The s3forcepathstyle is useful when you're running your own S3 endpoint as it saves you from thinking about DNS. Maybe there are other reasons most (all?) other S3 clients support it, but that's my main concern.

**Comment by pracucci** [comment]
I see the point about keeping consistency, but between the two the direction where the project is heading to is to keep to object store config in blocks storage.

**Comment by pracucci** [comment]
> I see the point about keeping consistency, but between the two the direction where the project is heading to is to keep to object store config in blocks storage.

More about this topic: https://github.com/cortexproject/cortex/issues/2262

**Comment by nivekuil** [comment]
I see. Actually, if it's reusing Thanos's implementation which uses the MinIO client under the hood then it already uses path style by default. It seems to work for me! Worth documenting, perhaps.
