### ISSUE TITLE
frontend_worker.frontend_address ignored in 1.6.0

### ISSUE THREAD

**Issue by jakubgs** [cortexproject/cortex#3644]
# Description

I upgraded to `1.6.0` and noticed the value of `frontend_worker.frontend_address` was ignored.

# Details

If I check the config in `1.6.0` I can see it set to the IP I want:
```
 > curl -s http://10.1.33.0:9092/config | grep -A2 frontend_worker
frontend_worker:
  frontend_address: 10.1.31.152:9095
  scheduler_address: ""
```
But when I look at the connections I can see it connecting to localhost:
```
 > sudo netstat -pnt | grep 10.1.31.152:9095

 > sudo netstat -pnt | grep 127.0.0.1:9095  
tcp        0      0 127.0.0.1:48792         127.0.0.1:9095          ESTABLISHED 1510541/cortex
tcp6       0      0 127.0.0.1:9095          127.0.0.1:48792         ESTABLISHED 1510541/cortex
```
But when I downgrade to `1.5.0` it works again as expected:
```
 > sudo netstat -pnt | grep 10.1.31.152:9095
tcp        0      0 10.1.31.155:44850       10.1.31.152:9095        ESTABLISHED 519751/cortex

 > sudo netstat -pnt | grep 127.0.0.1:9095
```

**Comment by jakubgs** [comment]
I checked the logs and it's clearly trying to connect to `127.0.0.1:9095`:
```
 > sudo journalctl -fu cortex | grep 'Starting querier'
caller=worker.go:112 msg="Starting querier worker connected to query-frontend" frontend=127.0.0.1:9095
```
Despite config clearly stating otherwise:
```
 > curl -s http://localhost:9092/config | grep frontend_address    
  frontend_address: 10.1.31.152:9095
```
I don't get how this is possible considering the value seems to be directly taken from the YAML:
https://github.com/cortexproject/cortex/blob/2f7d37d7368cce61ee028a27c2a4a21f9d8fe552/pkg/cortex/cortex.go#L97
https://github.com/cortexproject/cortex/blob/2f7d37d7368cce61ee028a27c2a4a21f9d8fe552/pkg/querier/worker/worker.go#L22-L23
https://github.com/cortexproject/cortex/blob/2f7d37d7368cce61ee028a27c2a4a21f9d8fe552/pkg/querier/worker/worker.go#L111-L112

**Comment by jakubgs** [comment]
I tried using the CLI flag instead but it makes no difference:
```
caller=worker.go:112 msg="Starting querier worker connected to query-frontend" frontend=127.0.0.1:9095
```
Service:
```
 > grep ExecStart /lib/systemd/system/cortex.service
ExecStart=/usr/local/bin/cortex -querier.frontend-address=10.1.31.152:9095 -config.file=/etc/cortex/config.yml -schema-config-file /etc/cortex/schema.yml
```

**Comment by jakubgs** [comment]
I think I found it:
https://github.com/cortexproject/cortex/blob/2f7d37d7368cce61ee028a27c2a4a21f9d8fe552/pkg/cortex/modules.go#L289-L295
Shouldn't this `||` be `&&` instead? Since my `SchedulerAddress` is empty it will just overwrite my setting for `FrontendAddress`.

I mean, this `if` means that regardless if whether I set one or the other it will still default to `127.0.0.1:9095`.

**Comment by jakubgs** [comment]
@pstibrany looks like you broke this in eba13a81e73d9835a9adaf29ce6d8cd0d385c44f.

**Comment by pstibrany** [comment]
> Shouldn't this `||` be `&&` instead? Since my `SchedulerAddress` is empty it will just overwrite my setting for `FrontendAddress`.

You're right, well spotted! Would you like to send a PR?

**Comment by jakubgs** [comment]
I'm eating breakfast. I can later.
