### ISSUE TITLE
MaxCacheFreshness should be relative to the sender's time

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#3655]
`MaxCacheFreshness` is described as "to prevent caching very recent results that might still be in flux", and defaults to one minute.

However the frontend applies it against Cortex's idea of "now".  If the sender's clock is a minute behind then this setting is ineffective.  Ideally it should be applied against the sender's "now".

(I came up with this while trying to think how #3648 could happen)

**Comment by pracucci** [comment]
You're right. Even assuming sender clock is in sync, if the sender is lagging behind more than `MaxCacheFreshness`, queries will cache gaps in query results.

However, I'm wondering how to actually fix it. One of the nice properties of query-frontend is that it doesn't directly depend on any other Cortex service (it basically acts as a proxy). However, to guess the sender's "now" it would need to query either distributors or ingesters.

**Comment by bboreham** [comment]
Well it only gets to think about caching data after talking to queriers, which talk to ingesters.

I agree it's not a simple thing.

**Comment by pracucci** [comment]
> Well it only gets to think about caching data after talking to queriers, which talk to ingesters.

Right. Could be propagated back from queriers within the query response and used it when available.
