### ISSUE TITLE
Ruler doesn't reshard rules on unhealthy instance

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3689]
**Describe the bug**
If a ruler instance is unhealthy, its rules aren't resharded across healthy rulers and such rules won't be evaluated until either the unhealthy ruler is removed from the ring or gets back to an healthy state.

The reason is that the ruler ring client is configured with replication factor = 1 (as designed) but that means `ring.Get()` will return a `ReplicationSet` with 1 instance, regardless it's healthy or unhealthy (`ring.Get()` doesn't check it and the `ShouldExtendReplicaSetOnState()` only checks the state, not the heartbeat timeout).

_Let's discuss how to fix it._

**Comment by jtlisi** [comment]
If I'm not mistaken, [rulers are automatically removed from the ring](https://github.com/cortexproject/cortex/blob/eac49c736ddf27dae018d5f41442056ec4af3fab/pkg/ruler/ruler.go#L279) if they are unhealthy for a period of time. The timeout for an unhealthy ruler is `10*ring.HeartBeatTimeout`. Could this be tuned to help ameliorate this issue.

**Comment by pracucci** [comment]
You're right @jtlisi. I know I set `ringAutoForgetUnhealthyPeriods = 10` in the store-gateway and ruler just picked it, but I'm wondering if such multiplier is too high. We're currently running with an heartbeat timeout = 10m, which means a ruler gets removed after 100m. WDYT?

**Comment by pracucci** [comment]
_Still valid_

**Comment by pracucci** [comment]
_Still valid_
