### ISSUE TITLE
Race condition between queries and closing TSDB in ingester

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3704]
**Describe the bug**
When the ingester is shutting down (graceful stop), TSDB is closed but we don't wait until in-flight queries are completed before closing it. This leads to error logs like the following:

```
level=warn ts=2021-01-18T10:47:58.080281469Z caller=grpc_logging.go:55 duration=8.779921ms method=/cortex.Ingester/QueryStream err="open querier for block REDACTED: open chunk reader: can't read from a closed head" msg="gRPC\n"
```

**Expected behavior**
We should wait until any read/write from/to TSDB is completed before closing it.

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Comment by pracucci** [comment]
From a quick look, I doubt we're not even waiting for write requests to complete before closing TSDB.

**Comment by roidelapluie** [comment]
An alternative would be to cancel write/reads prior to closing the tsdb.

**Comment by pracucci** [comment]
> An alternative would be to cancel write/reads prior to closing the tsdb.

I think we would have to wait until they're effectively canceled anyway.

**Comment by pracucci** [comment]
_Still valid._

**Comment by pracucci** [comment]
_Still valid_

**Comment by bboreham** [comment]
Is this the same as #3350?  Message seems different.
