### ISSUE TITLE
Distributor reports "empty ring" error when using config "-distributor.ring.consul.hostname"

### ISSUE THREAD

**Issue by zhuyanxi** [cortexproject/cortex#3730]
**Describe the bug**
As it is said in the document(https://cortexmetrics.io/docs/configuration/configuration-file/#distributor_config), the distributor ring should use a prefix:
```yaml
    # The consul_config configures the consul client.
    # The CLI flags prefix for this block config is: distributor.ring
    [consul: <consul_config>]
```
But when I changed my previous config `-consul.hostname` to `-distributor.ring.consul.hostname`, an error will occur:
```bash
level=error ts=2021-01-22T02:28:13.52717631Z caller=pool.go:161 msg="error removing stale clients" err="empty ring"
level=error ts=2021-01-22T02:28:16.74446672Z caller=client.go:229 msg="error getting path" key=collectors/ring err="Get \"http://localhost:8500/v1/kv/collectors/ring?stale=&wait=10000ms\": dial tcp 127.0.0.1:8500: connect: connection refused"
```
It seemed that Distributor didn't find the Ingester address in the consul ring. And when I visited the website of `/ring`, there was no ingester ring showed in the web page.
But after I changed the config back to `-consul.hostname`, it worked just fine without any error.

**Expected behavior**
There should be no error and the web page of `/ring` should show the ingester ring.

**Environment:**
 - Infrastructure: Kubernetes(v1.18.6)
 - Deployment tool: Helm(v3.4.1)

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Comment by pracucci** [comment]
> But when I changed my previous config -consul.hostname to -distributor.ring.consul.hostname, an error will occur

This part of the config is a bit tricky because of some tech debt. The `-consul.hostname` configures the ingesters ring (needs to be set on distributor too), while `-distributor.ring.consul.hostname` configures the distributors ring. Basically both ingesters and distributors form a ring (each service a dedicated ring): the ingesters ring is required, while the distributors ring is used only if you configure global limits.

**Comment by zhuyanxi** [comment]
Thank you,  @pracucci . 
So, I see that the `-consul.hostname` config is used to let `distributor` to find the `ingester` ring. But the `-distributor.ring.consul.hostname` is just used to configure the distributor ring.
