### ISSUE TITLE
Cortex feature request/improvement - Refresh AWS object store credentials for expired tokens

### ISSUE THREAD

**Issue by ncauchois** [cortexproject/cortex#3731]
Cortex version : v1.6.0.

Object storage provider : AWS.

What happened:

The s3 client is not updated with the new credentials when the old ones have expired.

How to reproduce :

1. We would create a role in Vault which will generate AWS credentials that are rotated automatically by vault.
2. A Vault agent is configured alongside every sidecar. This agent continuously updates and rotates the access and secret keys - it does this in a way which writes out the credentials to a 'sink'. So e.g, in our case it's /vault/secrets/credentials.
3. Cortex picks up the credentials successfully. All this is working.
4. Eventually since those credentials only last 10 hour, they expire. Vault agent in this time would have automatically written out new credentials to /vault/secrets/credentials again, but cortex does not reinitialise the client, so spends the rest of the time attempting to use old credentials.

**Comment by pracucci** [comment]
I would like to better understand your setup first. How have you configured the S3 client (in Cortex) to read from `/vault/secrets/credentials`? Could you share a config snippet (hiding sensitive information)?

**Comment by ncauchois** [comment]
Content of `/vault/secrets/credentials` :
```
[default]
aws_access_key_id = xxx
aws_secret_access_key = xxx
```

And I export the environment variable :
```
AWS_SHARED_CREDENTIALS_FILE=/vault/secrets/credentials
```

**Comment by pracucci** [comment]
I was checking the implementation in the S3 client we use (Minio, which is based on AWS SDK) and credentials read from file never expire ([source code](https://github.com/minio/minio-go/blob/master/pkg/credentials/file_aws_credentials.go)) once they've been successfully read the first time.

Some ideas:
1. Add a "max TTL" in Minio file-based credentials
2. Force an expire on credentials every X in the Thanos S3 client (a bit hacky)

**Comment by pracucci** [comment]
Please be aware that this problem doesn't exist if you use the IAM-based authentication.

**Comment by sfc-gh-jburns** [comment]
Would it perhaps be better to have a file watcher that reloads credentials when the file contents change? Encoding expiration expectations into the config seems likely to create surprising coupling between very different configurations.

**Comment by pracucci** [comment]
I still believe this should be fixed in Minio client. Anyone willing to open an issue there, to discuss it further?
