### ISSUE TITLE
managing retention period for chunks stored in GCP

### ISSUE THREAD

**Issue by shybbko** [cortexproject/cortex#3733]
Hi

What would be the best / recommended way to manage metrics retention period for long-term storage in a scenario when GCS is used for data (chunk) storage and BigTable is used to store indices? Should GCP-native retention policy be used here?

Thanks!

**Comment by pracucci** [comment]
> Should GCP-native retention policy be used here?

Yes, exactly. You should setup a GCS bucket policy to delete chunks older than the retention period.

**Comment by shybbko** [comment]
Perfect. Thanks for the quick answer, appreciate it!
