### ISSUE TITLE
Displaying currently-connected-to instance ID in web UI

### ISSUE THREAD

**Issue by shybbko** [cortexproject/cortex#3754]
**Is your feature request related to a problem? Please describe.**
When your Cortex cluster web UI is hidden behind LB and you reach it you never really know which node you're hitting. That's okay when everything is in line and the cluster is in perfect state, but when things go south you'd sometimes want to know which node is the one that you're currently talking to.

**Describe the solution you'd like**
Display the current node ID / name on either the main web UI page (ie. http://cortex:9009/) or some / all of the subpages, ie. http://cortex:9009/ingester/ring) in a similar manner the current time is displayed on the /ingester/ring page.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by pracucci** [comment]
👋  Thanks for opening the issue.

I see the problem you're trying to solve. Talking specifically about the ring, this may not be a real issue when using consul or etcd as backend key-value store, but ring may be inconsistent between different nodes when using gossip memberlist.

I'm fine to display this information in the ring UI page.

> either the main web UI page

I'mo not sure there's a real value in the main page. It's just a list of links.

**Comment by shybbko** [comment]
> I'mo not sure there's a real value in the main page. It's just a list of links.

Just an example. Not insisting ;)

**Comment by pracucci** [comment]
I checked the current "admin pages" and I believe displaying the node would be a valuable information in the following pages:
- Ring status page
- `/memberlist`

Feel free to add it to other pages, if you think the information would be useful. Thanks!

**Comment by bboreham** [comment]
Generally I query the ring on a distributor; sometimes a querier.  They don't have a concept of "instance ID" but they do have a hostname. Reporting that is a fine idea.

**Comment by jtlisi** [comment]
still valid
