### ISSUE TITLE
Compactor with Swift backend creates SLOs for deletion markers

### ISSUE THREAD

**Issue by bcharron** [cortexproject/cortex#3766]
**Describe the bug**
In TSDB storage, when using the Swift backend, the compactor creates segments (Static Large Objects (SLO)) for deletion markers because it `"could not guess file size"` due to `"unsupported type of io.Reader: *bytes.Reader"`

**To Reproduce**
1. Start Cortex 1.7.0-rc0 compactor
2. Wait for a compaction
3. Witness the following message in the compactor's logs:

```
level=warn ts=2021-01-29T21:23:33.917626747Z caller=swift.go:282 msg="could not guess file size, using large object to avoid issues if the file is larger than limit" name=1/markers/01EX7Z5804AH7DD3VVJX3HC0RW-deletion-mark.json err="unsup
ported type of io.Reader: *bytes.Reader"
```

and files like these
```
| segments/312/f30314558374748544d58455446563156384e50424a50314251562f64656c6574696f6e2d6d61726b2e6a736f6e6af94969dd9868b861bc8b8c3b20fa4ed20e4ed77823869a027ebfe142a15ce3da39a3ee5e6b4b0d3255bfef95601890afd80709/0000000000000001         |
| segments/312/f30314558374a38524557524532313135455a4351425445374a502f64656c6574696f6e2d6d61726b2e6a736f6e4093b95fbaf2963b9314312e883cb01c2d607e601d37767e5080325db8be8f53da39a3ee5e6b4b0d3255bfef95601890afd80709/0000000000000001         |
| segments/312/f30314558374b5a5038575146305842564535524b3551363659332f64656c6574696f6e2d6d61726b2e6a736f6ee396bfc6b10a47661b0eb11312a3433090a6a2b4fda5ac7800526d7ac5dbcc02da39a3ee5e6b4b0d3255bfef95601890afd80709/0000000000000001         |
| segments/312/f30314558374e504d325752583136454b4e4d385a4657304556502f64656c6574696f6e2d6d61726b2e6a736f6efad97cf5c3652d52d248b01e81544be9f067ccee07008246788ca3957e892180da39a3ee5e6b4b0d3255bfef95601890afd80709/0000000000000001         |
```

**Expected behavior**
I would expect the (typically very small) deletion markers to be created as single files rather than SLOs

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helmfile

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**
- All Swift options are left to default values
- The compactor config:
```
compactor:
    block_deletion_marks_migration_enabled: false
```
- Not sure if this issue can be addressed in Cortex or Thanos; let me know if I should move it.

**Comment by pracucci** [comment]
This was supposed to be fixed in https://github.com/thanos-io/thanos/pull/3476 (for blocks upload), but we may have missed deletion marks. I'm going to take a look

**Comment by pracucci** [comment]
The issue you're reporting was fixed in this commit https://github.com/thanos-io/thanos/commit/86be7c366bdd9bc47655f6232fbc9dd83d37bbbd#diff-017de055a970d28101133f6bafec9c670ec3702f6e5806c4988b18244088e3a6 and we've already upgraded Thanos dependency in Cortex. I double checked and the fix is included in Cortex [`1.7.0-rc.0`](https://github.com/cortexproject/cortex/tags).

**Comment by bcharron** [comment]
Sorry to re-open, but we're using "quay.io/cortexproject/cortex:v1.7.0-rc.0" and getting these from the compactor.

**Comment by pracucci** [comment]
> Sorry to re-open, but we're using "quay.io/cortexproject/cortex:v1.7.0-rc.0" and getting these from the compactor.

Ok. Thanks for the quick follow up. I will take another (better) look shortly.
