### ISSUE TITLE
1.7.0-rc0 querier incorrectly interpreting ring from 1.6.0 ingesters

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#3769]
**Describe the bug**
The symptom I noticed was queriers not fetching information from the ingesters that had it.
However it is easier to show on the `/ring` page:

1.6.0 querier returns:

Instance ID | Availability Zone | State | Address | Registered At | Last Heartbeat | Tokens | Ownership | Actions
-- | -- | -- | -- | -- | -- | -- | -- | --
ingester-7dfdbf869c-4hvdw |   | ACTIVE | 10.244.224.180:9095 | 2021-01-28 09:32:17 +0000 UTC | 2021-02-01 10:01:07 +0000 UTC | 512 | 10.158641894850563% | Forget
ingester-7dfdbf869c-6r4fn |   | ACTIVE | 10.244.221.144:9095 | 2021-01-28 07:50:03 +0000 UTC | 2021-02-01 10:01:08 +0000 UTC | 512 | 9.89586552835439% | Forget
ingester-7dfdbf869c-d4pr2 |   | ACTIVE | 10.244.220.95:9095 | 2021-01-28 09:12:31 +0000 UTC | 2021-02-01 10:01:06 +0000 UTC | 512 | 9.111226328907355% | Forget
ingester-7dfdbf869c-gp2ns |   | ACTIVE | 10.244.208.53:9095 | 2021-01-28 08:31:31 +0000 UTC | 2021-02-01 10:01:06 +0000 UTC | 512 | 9.926150415541175% | Forget
ingester-7dfdbf869c-j7d52 |   | ACTIVE | 10.244.229.179:9095 | 2021-01-28 07:29:40 +0000 UTC | 2021-02-01 10:01:05 +0000 UTC | 512 | 9.072090082120171% | Forget
ingester-7dfdbf869c-mlzwr |   | ACTIVE | 10.244.222.55:9095 | 2021-01-28 08:10:59 +0000 UTC | 2021-02-01 10:01:04 +0000 UTC | 512 | 10.601690716715924% | Forget
ingester-7dfdbf869c-q5896 |   | ACTIVE | 10.244.228.137:9095 | 2021-01-28 07:39:42 +0000 UTC | 2021-02-01 10:01:10 +0000 UTC | 512 | 9.671895324641815% | Forget
ingester-7dfdbf869c-r98dz |   | ACTIVE | 10.244.223.122:9095 | 2021-01-28 10:59:13 +0000 UTC | 2021-02-01 10:01:08 +0000 UTC | 512 | 10.563680811450743% | Forget
ingester-7dfdbf869c-rjxrp |   | ACTIVE | 10.244.209.190:9095 | 2021-01-28 08:43:02 +0000 UTC | 2021-02-01 10:01:07 +0000 UTC | 512 | 9.86297999272658% | Forget
ingester-7dfdbf869c-xgmg5 |   | ACTIVE | 10.244.225.13:9095 | 2021-01-28 07:57:09 +0000 UTC | 2021-02-01 10:01:09 +0000 UTC | 512 | 11.135778904691287% | Forget

1.7.0-rc0 querier returns:

Instance ID | Availability Zone | State | Address | Registered At | Last Heartbeat | Tokens | Ownership | Actions
-- | -- | -- | -- | -- | -- | -- | -- | --
ingester-7dfdbf869c-4hvdw |   | ACTIVE | 10.244.224.180:9095 | 2021-01-28 09:32:17 +0000 UTC | 2021-02-01 09:53:32 +0000 UTC | 512 | 0.3203722881899151% | Forget
ingester-7dfdbf869c-6r4fn |   | ACTIVE | 10.244.221.144:9095 | 2021-01-28 07:50:03 +0000 UTC | 2021-02-01 09:53:23 +0000 UTC | 512 | 0.12026363986550449% | Forget
ingester-7dfdbf869c-d4pr2 |   | ACTIVE | 10.244.220.95:9095 | 2021-01-28 09:12:31 +0000 UTC | 2021-02-01 09:53:36 +0000 UTC | 512 | 0.12366164012897332% | Forget
ingester-7dfdbf869c-gp2ns |   | ACTIVE | 10.244.208.53:9095 | 2021-01-28 08:31:31 +0000 UTC | 2021-02-01 09:53:36 +0000 UTC | 512 | 0.0832138350427183% | Forget
ingester-7dfdbf869c-j7d52 |   | ACTIVE | 10.244.229.179:9095 | 2021-01-28 07:29:40 +0000 UTC | 2021-02-01 09:53:35 +0000 UTC | 512 | 19.463768023872692% | Forget
ingester-7dfdbf869c-mlzwr |   | ACTIVE | 10.244.222.55:9095 | 2021-01-28 08:10:59 +0000 UTC | 2021-02-01 09:53:34 +0000 UTC | 512 | 19.719515675613543% | Forget
ingester-7dfdbf869c-q5896 |   | ACTIVE | 10.244.228.137:9095 | 2021-01-28 07:39:42 +0000 UTC | 2021-02-01 09:53:37 +0000 UTC | 512 | 20.038082408727632% | Forget
ingester-7dfdbf869c-r98dz |   | ACTIVE | 10.244.223.122:9095 | 2021-01-28 10:59:13 +0000 UTC | 2021-02-01 09:53:33 +0000 UTC | 512 | 20.86624107809417% | Forget
ingester-7dfdbf869c-rjxrp |   | ACTIVE | 10.244.209.190:9095 | 2021-01-28 08:43:02 +0000 UTC | 2021-02-01 09:53:32 +0000 UTC | 512 | 18.94527755653143% | Forget
ingester-7dfdbf869c-xgmg5 |   | ACTIVE | 10.244.225.13:9095 | 2021-01-28 07:57:09 +0000 UTC | 2021-02-01 09:53:34 +0000 UTC | 512 | 0.31960385393342094% | Forget

Note that the "Ownership" column shows all around 10% in the first case, while some at 20% and some near 0% in the second.

'Show Tokens' is identical in each case.

**Storage Engine**
- [ ] Blocks
- [x] Chunks

**Comment by bboreham** [comment]
@pstibrany reckons this is because some tokens in my ring are unsorted, and Cortex 1.7.0 expects tokens to be sorted.
If you do a rolling update with hand-over, then the order is preserved from old to new.

So this should at least be listed as a breaking change in the release notes; better if the code reading the ring checked for sorted, and best of all if there was a way to convert un-sorted stored tokens to sorted.

**Comment by pracucci** [comment]
I unintentionally introduced the breaking change in [this PR](https://github.com/cortexproject/cortex/pull/3601/files?w=1#diff-e773119be1c2446745f5b5eeb2d7b436e99cb21c02e1fdfc40e42d041d541ad8), specifically I removed tokens sorting from `Desc.getTokens()` and `Desc.getTokensByZone()` because I was assuming all tokens in the ring were already sorted.

From a quick analysis, ingester tokens can be written to the ring in 4 places:
- `Lifecycler.verifyTokens()`: always sorted since it's creation ([PR](https://github.com/cortexproject/cortex/pull/1727/files#diff-4d46760513b4f0a55e4cebb89e6a055859204f00ca50220cd42b5191b018b152R508))
- `Lifecycler.autoJoin()`: at least sorted since May 2018 ([PR](https://github.com/cortexproject/cortex/pull/807)) but were sorted even before
- `Lifecycler.initRing()`: no guarantee that tokens read from file are sorted
- `Lifecycler.ClaimTokensFor()`: no guarantee that the tokens of the leaving ingesters are sorted

_I'm working on a fix._
