### ISSUE TITLE
list rule endpoints not working as expected for s3

### ISSUE THREAD

**Issue by bo-tu** [cortexproject/cortex#3772]
**Describe the bug**
We deployed ruler into Cortex(version 1.6.0).  

1. When using local file system to store rules as below,
-ruler.storage.type=local
-ruler.storage.local.directory=/tmp

then the rulers endpoints as below can return result as expected
curl -H 'X-Scope-OrgID: Tenant_ID' http://127.0.0.1:8080/prometheus/api/v1/rules
curl -H 'X-Scope-OrgID: Tenant_ID' http://127.0.0.1:8080/api/v1/rules

2. When using s3 storage to store rues as below,
 -ruler.storage.type=s3
 -ruler.storage.s3.url=s3://us-west-2/{{ .Values.bucketPrefix }}-rules
 -ruler.enable-sharding=true

Also,  I uploaded rule file into s3://Bucket_Name/rules/Tenant ID/Name_Space/testrulefile.yaml
The return of "curl -H 'X-Scope-OrgID:  Tenant_ID' http://127.0.0.1:8080/api/v1/rules" is "no rule groups found"
The return of "curl -H 'X-Scope-OrgID: Tenant_ID' http://127.0.0.1:8080/prometheus/api/v1/rules" is below,
{
status: "success",
data: {
groups: [ ]
},
errorType: "",
error: ""
}

**To Reproduce**
1. Start Cortex ( I reproduced it for v1.5.0 and v1.6.0)
2. Enable rulers with s3 
3. Test endpoints of "list-rule-groups" and "list-rules"
     https://cortexmetrics.io/docs/api/#list-rule-groups
     https://cortexmetrics.io/docs/api/#list-rules

**Expected behavior**
Here is the content for my testrulefile.yaml, 
 - name: example
      rules:
        - alert: HighRequestLatency
          expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
          for: 10m
          labels:
            severity: page
          annotations:
            summary: High request laten

Here the result  for "curl -H 'X-Scope-OrgID: Tenant_ID' http://127.0.0.1:8080/api/v1/rules" when storage type is local 
rule1.yaml:
    - name: example
      rules:
        - alert: HighRequestLatency
          expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
          for: 10m
          labels:
            severity: page
          annotations:
            summary: High request laten
           
Here is the result of "curl -H 'X-Scope-OrgID:  Tenant_ID' http://127.0.0.1:8080/prometheus/api/v1/rules" when storage type is local. 
{"status":"success","data":{"groups":[{"name":"example","file":"rule1.yaml","rules":[{"state":"inactive","name":"HighRequestLatency","query":"job:request_latency_seconds:mean5m{job=\"myjob\"} \u003e 0.5","duration":600,"labels":{"severity":"page"},"annotations":{"summary":"High request laten"},"alerts":[],"health":"ok","lastError":"","type":"alerting","lastEvaluation":"2021-01-22T02:25:32.866070128Z","evaluationTime":0.001256741}],"interval":60,"lastEvaluation":"2021-01-22T02:25:32.86605967Z","evaluationTime":0.001271424}]},"errorType":"","error":""}

I expect these two endpoint will return the same message when storage type is s3.

**Environment:**
 - Infrastructure:  Kubernetes
 - Deployment tool:  helm

**Storage Engine**
- [  ] Blocks
- [ X ] Chunks

**Additional Context**

**Comment by bo-tu** [comment]
I'm not sure if this is a real bug, or my s3 bucket name does not follow the scheme defined here - https://github.com/cortexproject/cortex/blob/master/pkg/ruler/rules/objectclient/rule_store.go#L22

could you give me any advice?  thanks

**Comment by pracucci** [comment]
> I uploaded rule file into s3://Bucket_Name/rules/Tenant ID/Name_Space/testrulefile.yaml

Could you try to use the HTTP API to upload rules instead of manually uploading them to the bucket, please? The API is [documented here](https://cortexmetrics.io/docs/api/#set-rule-group), but remember to enable it via `-experimental.ruler.enable-api=true`.

**Comment by bo-tu** [comment]
Hi @pracucci thanks a lot for your advice.
I tried "curl -v -X POST  -H 'Content-Type: application/yaml' -d "@test.yaml" https://xxxxx/api/v1/rules/ns" to upload rules.  Here is the test.yaml(I run yamllint test.yaml,  and result is fine)
---
name: rg_test
interval: 15s

However,  I got error as below,  any idea?  thanks
level=debug ts=2021-02-02T23:20:43.580165254Z caller=api.go:454 org_id=400 traceID=443c2faec8a30913 msg="attempting to unmarshal rulegroup" userID=400 group="---name: rg_testinterval: 15s"
level=error ts=2021-02-02T23:20:43.580347199Z caller=api.go:459 org_id=400 traceID=443c2faec8a30913 msg="unable to unmarshal rule group payload" err="yaml: mapping values are not allowed in this context"

If changing test.yaml as below,
interval: 15s,
then I can get message of  "invalid rules config: rule group name must not be empty"  as expected.

**Comment by bo-tu** [comment]
Hi @pracucci ,

curl removed the line break in the test.yaml.  Then I try `curl -v -X POST  -H 'Content-Type: application/yaml' --data-binary "@test.yaml" https://xxxxx/api/v1/rules/ns` to upload it to s3 bucket.

Currently,  the endpoint of "list-rule-groups" and "list-rules" works now. 

thanks a lo :-)
