### ISSUE TITLE
Remove global logger

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#3779]
A global logger from `pkg/util/log` is used throughout the codebase. This issue is meant to track removing usage of the global logger from the codebase.

See: 
https://github.com/cortexproject/cortex/blob/3df3149ef131982e8f9038fb291d005e85caa16f/pkg/util/log.go#L17-L19

**Comment by pracucci** [comment]
_Still valid. We've done much work, but global logger is still not fully eradicated._

**Comment by pracucci** [comment]
Still valid. This is also a pre-requisite for all components we'll move to dskit.

**Comment by pracucci** [comment]
> so I override this public logger to my own logger right now, what's the proper way to let cortex use customized logger?

That's expected way to do it, until we'll get rid of the global logger.
