### ISSUE TITLE
Expose Prometheus-side alert information

### ISSUE THREAD

**Issue by jml** [cortexproject/cortex#378]
Standalone prometheus shows active, pending, and inactive alerts at `/alerts`. This is separate from the alertmanager view of alerts. We should expose (at least as an API), the ruler's view of what's actually alerting. This can be useful in debugging problems between prometheus and alertmanager.

**Comment by tomwilkie** [comment]
This was brought up on #prometheus channel recently, and there seems to be acceptance that everything Prometheus exposes in the UI should be available via an API.

We should do this in a way that is compatible, and maybe even fix the upstream "issue" at the same time: https://github.com/prometheus/prometheus/issues/1570

**Comment by gouthamve** [comment]
Closing in favor of #1720
