### ISSUE TITLE
Support for IP addresses in memcached_client_config

### ISSUE THREAD

**Issue by arthurk** [cortexproject/cortex#3788]
The current `memcached_client_config` configuration only accepts DNS names as a `host` or `addresses` value. It would be great if we can specify IP addresses too.

https://cortexmetrics.io/docs/configuration/configuration-file/#memcached_client_config

**Comment by pracucci** [comment]
You could be able to use this:

```
# EXPERIMENTAL: Comma separated addresses list in DNS Service Discovery format:
# https://cortexmetrics.io/docs/configuration/arguments/#dns-service-discovery
# CLI flag: -<prefix>.memcached.addresses
[addresses: <string> | default = ""]
```

It `addresses` contains a comma separated list of IPs, they will just be used straightaway. I will update the doc to make it more clear.

**Comment by arthurk** [comment]
I tried putting the IPs into the `addresses` field and it works. Thanks for adding it to the docs!
