### ISSUE TITLE
Upgrade gRPC to 1.30.0 or newer

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#3790]
Upgrade of gRPC is blocked by an etcd issue - see #2897.  This is to remind us to do the upgrade once the blocker is removed.

**Comment by jtlisi** [comment]
There has been some movement on this issue upstream: https://github.com/etcd-io/etcd/issues/12652

I expect we will be able to upgrade in the not too distant future.

**Comment by vooon** [comment]
Hello,
FYI it is possible to use gRPC 1.36 with that https://github.com/etcd-io/etcd/releases/tag/v3.5.0-alpha.0
But it would require update imports and need to remove usage of `grpc/naming` package from cortex.

**Comment by pracucci** [comment]
Closed by #3884.
