### ISSUE TITLE
Honor context cancellation in chunk store

### ISSUE THREAD

**Issue by juliusv** [cortexproject/cortex#381]
Currently the chunk store does not inspect anywhere whether the passed-in context was cancelled. This means it doesn't honor query timeouts and can be query-of-death-ed pretty easily.

**Comment by tomwilkie** [comment]
https://github.com/weaveworks/cortex/pull/407 should help a little here

**Comment by bboreham** [comment]
I believe #618 will address this for the AWS store.  Haven't checked everywhere.

**Comment by gouthamve** [comment]
We've checked and we do context propagation in C* and BT/GCS clients now.
