### ISSUE TITLE
Proposal: make bucket index mandatory for the blocks storage

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3814]
**Describe the solution you'd like**
I would like to propose to make the **bucket index mandatory** when running the blocks storage.

Cortex 1.7.0 is introducing the support to the bucket index ([doc](https://cortexmetrics.io/docs/blocks-storage/bucket-index/)), which is a per-tenant `.json` file containing the list of the tenant's blocks and deletion marks. The bucket index is periodically written by the compactor and read by querier/ruler/store-gateway in order to have a almost updated view over the bucket without having to scanning it (eg. run "list objects" API calls which are slow and expensive).

Making it mandatory would simplify the Cortex code removing the need to keep a dual implementation (either scan the bucket in querier/ruler/store-gateway or read bucket index) and would also offer an (hopefully) better default setup for Cortex users.

At Grafana Labs we're running the bucket index in production since 1 month and we haven't had any issue (so far) while it reduced the number of API calls to the object store and allowed us to scale up queries with no waiting time (no initial bucket scanning required anymore).

**Comment by pracucci** [comment]
A pre-requisite is to have the compactor running in the single binary mode too.

**Comment by pracucci** [comment]
_Still valid_

**Comment by jimmy0012** [comment]
To offer another perspective, not using the bucket index is useful for our team when we want to prioritize not downloading from s3 as much as possible
