### ISSUE TITLE
Feature request: tenant federation across all tenants

### ISSUE THREAD

**Issue by rekup** [cortexproject/cortex#3848]
**Is your feature request related to a problem? Please describe.**
When using tenant federation to run queries across all tenants, it is inconvenient to define all tenants in the `X-Scope-OrgID` header.

**Describe the solution you'd like**
I'd much appreciate an option to run queries across all tenants without the need to specify every tenant in the `X-Scope-OrgID` header. Maybe this could be implemented using e new header (e.g. `X-Scope-OrgID-Regex: .+` or `X-Scope-OrgID-All: true`

**Describe alternatives you've considered**
An alternative way to achieve the same result would be to periodically query the distributors `all_user_stats` endpoint to get a list of tenants (e.g. `curl -H "Accept: application/json" http://cortex-distributor:8080/all_user_stats | jq 'map(.userID)|join("|")'`) and then use this as value for the `X-Scope-OrgID` header

**Comment by pstibrany** [comment]
Note that method described in Alternatives only returns recently active tenants (depending on various configuration options) with data in ingesters, but if tenant has not pushed any data for couple of days, ingesters will not be aware of such tenant.

When using blocks storage it is possible to scan for users in the bucket, but new users with no blocks in the storage yet, will not be available there.

So any solution to this issue must combine the two sources -- scanning the bucket and users in ingesters. "scanning the bucket for users" is not available when using chunks engine.
