### ISSUE TITLE
Can't run single-process, single-instance example code

### ISSUE THREAD

**Issue by lbordowitz** [cortexproject/cortex#3854]
I get the following error when I try to run the [Getting Started](https://cortexmetrics.io/docs/getting-started/getting-started-chunks-storage/) code on the v1.6.0 release branch:

```
level=info ts=2021-02-22T20:25:15.710539627Z caller=main.go:187 msg="Starting Cortex" version="(version=, branch=, revision=)"
level=info ts=2021-02-22T20:25:15.710701712Z caller=server.go:229 http=[::]:9009 grpc=[::]:9095 msg="server listening on addresses"
level=warn ts=2021-02-22T20:25:15.71102301Z caller=net.go:15 msg="error getting interface" inf=eth0 err="route ip+net: no such network interface"
level=warn ts=2021-02-22T20:25:15.711085719Z caller=net.go:15 msg="error getting interface" inf=en0 err="route ip+net: no such network interface"
```

I'm evaluating different time series DBs in order to move our prometheus instance to remote storage.

**Comment by pracucci** [comment]
Some Cortex services needs to auto-detect their own IP address. We do this querying the network interface, by default eth0 and en0. If the default interfaces are not available on the system, then Cortex is unable to autodetect the IP.

To fix it, you should provide Cortex services the name of the network interface available on your system. Look for "instance-interface" in the [configuration file doc](https://cortexmetrics.io/docs/configuration/configuration-file/).

Related to: https://github.com/cortexproject/cortex/issues/2889

**Comment by ehjizao** [comment]
> 
Hi ,

My interface is  'em1', and I have changed all the 6 instance-interface-names parameters into 'em1', but it still raised similar error.
Could you please help me how to resolve it? How to change the default interface? Thanks a lot.

[root@host cortex]# ifconfig
em1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.144.137.213  netmask 255.255.252.0  broadcast 10.144.139.255
        
[root@host cortex]# ./cortex-linux-amd64 -config.file=./docs/configuration/single-process-config-blocks.yaml -alertmanager.sharding-ring.instance-interface-names em1  -compactor.ring.instance-interface-names em1 -distributor.ring.instance-interface-names em1 -frontend.instance-interface-names em1  -ruler.ring.instance-interface-names em1  -store-gateway.sharding-ring.instance-interface-names em1
level=info ts=2022-01-07T09:13:35.921731509Z caller=main.go:193 msg="Starting Cortex" version="(version=1.11.0, branch=release-1.11, revision=43c646ba3)"
level=info ts=2022-01-07T09:13:35.922300401Z caller=server.go:260 http=[::]:9009 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2022-01-07T09:13:35.92516425Z caller=inmemory.go:172 msg="created in-memory index cache" maxItemSizeBytes=134217728 maxSizeBytes=1073741824 maxItems=maxInt
level=warn ts=2022-01-07T09:13:35.926140131Z caller=net.go:19 msg="error getting interface" inf=eth0 err="route ip+net: no such network interface"
level=warn ts=2022-01-07T09:13:35.926280234Z caller=net.go:19 msg="error getting interface" inf=en0 err="route ip+net: no such network interface"
level=error ts=2022-01-07T09:13:35.926382417Z caller=log.go:106 msg="error running cortex" err="No address found for [eth0 en0]
