### ISSUE TITLE
All hell broke loose I - fall back to flush when killing two ingesters at once

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#387]
When killing two ingesters at once, we fell back to flushing.  We shouldn't - we should be able to transfer in this case.

**Comment by tomwilkie** [comment]
They have gone away now so no logs as to why this happened

**Comment by tomwilkie** [comment]
The joining ingesters said: `time="2017-04-05T14:14:31Z" level=info msg="Auto-joining cluster after timout." source="ingester_lifecycle.go:161"`

**Comment by jml** [comment]
No change necessary. Need to test this before marking as fixed.

**Comment by gouthamve** [comment]
I don't think this has enough context to be actionable right now. And I think it's either already fixed or requires a larger discussion about the joining and leaving. I'm closing this and if this issue still exists, please open a new one with more details.
