### ISSUE TITLE
Unexpected IDENTIFIER"  when using `absent_over_time` in alert rule 

### ISSUE THREAD

**Issue by maxmeyer** [cortexproject/cortex#3875]
**Describe the bug**
`cortex` reports errors for new `loki` query functions in alert rules - https://grafana.com/docs/loki/latest/logql/:

* absent_over_time
* Maybe some others

**To Reproduce**
1. Create file with this content in `./rules.d/test.yml`:
    ~~~
   namespace: test
   groups:
     - name: example
       rules:
         - alert: HighThroughputLogStreams
           expr: absent_over_time({job=~".*-logs"}[24h])
           for: 2m
    ~~~

1. Run cortex
   ```  
   docker run --network docker-monitoring-server_monitoring_server_internal --rm --name loki-validate-rules-1ac285e537173b6a -it -v $(pwd)/rules.d/:/rules.d grafana/cortex-tools:latest rules lint --backend=loki /rules.d/test.yml
   ERRO[0000] unable parse rules file                       error="could not parse expression: parse error at line 1, col 1: syntax error: unexpected IDENTIFIER" file=/rules.d/test.yml
   ```

**Expected behavior**

```
INFO[0000] SUCCESS: 1 rules found, 0 linted expressions
```

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: none

**Storage Engine**
- [ ] Blocks
- [x] Chunks

**Additional Context**

**Comment by pracucci** [comment]
Shouldn't this issue reported to Loki?

**Comment by maxmeyer** [comment]
Mmmh, they "only" mention cortex in their documentation to validate loki rules. I thought it needs to be added to cortex' codebase to get the issue fixed.

**Comment by cyriltovena** [comment]
`grafana/cortex-tools:latest rules lint --backend=loki`

Seems like we support Loki. I'll dig into this.

**Comment by cyriltovena** [comment]
@maxmeyer Just also want to let you know that this example is an inefficient rule.

Something like this would perform better:
```
namespace: test
groups:
 - name: example
   rules:
     - alert: HighThroughputLogStreams
       expr: absent_over_time({namespace="dev",job=~".*-logs"}[2m])
       for: 2m
```

e.g. you need at least one equality matcher and you don't need to evaluate 24h every 2m too.

**Comment by maxmeyer** [comment]
Thanks for letting me know. The "real" rule filters on equality with a static string, but is evaluated every 2m. I changed that to 1h.

**Comment by cyriltovena** [comment]
I believe it's fixed now.

**Comment by maxmeyer** [comment]
Wonderful. Thanks a lot.
