### ISSUE TITLE
Validate tenant IDs

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#3882]
Some restrictions on tenant IDs are [documented]( https://cortexmetrics.io/docs/guides/limitations/#tenant-id-naming) but not enforced.

**Comment by pracucci** [comment]
We're currently validating it when [multiple tenant IDs](https://github.com/cortexproject/cortex/blob/c8c028f3b19ae69417e54c5670256d683299793c/pkg/tenant/resolver.go#L109) are specified (query federation) but not for the normal use case of a single tenant specified in the request.

**Comment by bboreham** [comment]
`\` and `/` were disallowed by #4375 

Whitespace is still documented as unsupported but allowed by the code.
