### ISSUE TITLE
Blocks Storage arch picture missing dependency for querier

### ISSUE THREAD

**Issue by hafe** [cortexproject/cortex#3885]
The querier needs to access object store which is not shown in the architecture picture.

It is however mentioned in the text:
"Queriers and store-gateways periodically iterate over the storage bucket to discover blocks recently uploaded by ingesters."

Without object storage credentials, querier logs: "failed to scan bucket storage to find blocks" err="Access Denied."

**Comment by pracucci** [comment]
Yes, both querier and ruler need to access the object storage to scan buckets. The "arrow" was intentionally omitted in the architecture diagram shown in https://cortexmetrics.io/docs/blocks-storage/ to focus on the query execution path, which is how samples are read and processed.
