### ISSUE TITLE
Querier Select() in-memory cache

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#3938]
**Is your feature request related to a problem? Please describe.**
I'm investigating the performances of a query like this:
```
(
  (
    sum by (role, datacenter) (scrape_samples_post_metric_relabeling) 
    - sum by (role, datacenter) (scrape_samples_post_metric_relabeling offset 24h)
  ) 
  > 25000
)
and 
(
  (
    avg by (role, datacenter) (scrape_samples_post_metric_relabeling) 
    / avg by (role, datacenter) (scrape_samples_post_metric_relabeling offset 24h)
  ) 
  > 1.1
)
```

When PromQL executes such query, it calls `querier.Select()` 4 times:
1. `{__name__="scrape_samples_post_metric_relabeling"}` on query timerange (because of the `sum()` grouping)
2. `{__name__="scrape_samples_post_metric_relabeling"}` on query timerange - 24h (because of the `sum()` grouping)
3. `{__name__="scrape_samples_post_metric_relabeling"}` on query timerange (because of the `avg()` grouping)
4. `{__name__="scrape_samples_post_metric_relabeling"}` on query timerange - 24h (because of the `avg()` grouping)

For each `.Select()` invocation, the Cortex querier fetches series from ingesters and/or storage, even if the parameters of the `Select()` for 1 and 3 are the exact same, and same for 2 and 4.

**Describe the solution you'd like**
Despite such query is quite an edge case, I'm wondering what would be the sentiment to add an in-memory cache on `Select()` results. The cache would be local to the `querier`, so valid only during the executing of a single query (and then would be trashed away along with the `querier` struct which is created on a per-query basis).

The downside of this approach is that the querier memory utilisation would increase during the execution of a query whose execution calls `Select()` multiple times because the returned `storage.SeriesSet` would be cached until the query execution terminates.

Thoughts?

**Comment by pracucci** [comment]
Would be very interesting if we would have a way to know in advance if PromQL would fetch the same exact series sets multiple times and enable this logic conditionally based on that, but I'm not sure how we could do it.

**Comment by pracucci** [comment]
> I'm wondering what would be the sentiment to add an in-memory cache on Select() results

Actually a simple cache wouldn't be enough because `Select()` is called concurrently thanks to our `LazyQuerier`. What we could do is add a wrapper over `Select()` to wait for the results a previously called one with same params if any is in progress + a result cache (as previously suggested).

Consider we concurrently call `Select()` my concern about increased memory utilisation may not be true anymore (or at least not so significative).

**Comment by pracucci** [comment]
Building it on top of `storage.Querier` is not as easy as it looks because a `storage.SeriesSet` cannot be iterated twice. However, it's an optimisation which I believe we can still do in `blocksStoreQuerier`, covering the case of series fetched from the storage (which is slower than fetching from ingesters).

**Comment by jtlisi** [comment]
> Actually a simple cache wouldn't be enough because Select() is called concurrently thanks to our LazyQuerier. What we could do is add a wrapper over Select() to wait for the results of a previously called one with same params if any is in progress + a result cache (as previously suggested) if a query with same params already completed.

If the `Select` calls are executing concurrently we could use the [singleflight](https://pkg.go.dev/golang.org/x/sync/singleflight) library to implement shared results.

**Comment by pracucci** [comment]
> If the Select calls are executing concurrently we could use the singleflight library to implement shared results.

Good shout. Yes, we would need something like that.

**Comment by pracucci** [comment]
_Closing for now. After a brief investigation look at super easy to build and, given `Select()` is called concurrently thanks to the `LazyQuerier`, it may not be that effective in terms of query latency._
