### ISSUE TITLE
Add a metric to track samples dropped in distributor by metric_relabel

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#3954]
If you have a `metric_relabel_configs ... action: drop` then those samples disappear from `cortex_distributor_received_samples_total`. 

I'd like them to be counted in `cortex_discarded_samples_total`.

Relating to the feature added in #3329

**Comment by bboreham** [comment]
Still relevant

**Comment by bboreham** [comment]
Still relevant

**Comment by pedro-stanaka** [comment]
I will try to resolve this one this week. Trying to get involved with the project here.

**Comment by pedro-stanaka** [comment]
@bboreham I tried to solve this issue on #4503, would really appreciate the feedback there.

**Comment by pedro-stanaka** [comment]
Waiting for feedback on PR, should be able to merge soon.
