### ISSUE TITLE
cortex_discarded_samples_total should be independent of replication factor

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#3955]
`cortex_discarded_samples_total` is generated by both distributors and ingesters, but since each ingester will tend to reject the same samples, those numbers will be multiplied by the replication factor.

If ingester push requests returned the number of samples accepted and rejected then distributor could aggregate the results (although that seems tricky if just one call fails entirely).

Similar idea proposed in #3890

**Comment by LeviHarrison** [comment]
I'd like to take a shot at this, if that's alright. Looking into the code, it seems that the place were `cortex_discarded_samples_total` is being generated in the ingester is here:
https://github.com/cortexproject/cortex/blob/c28d326289ee186f18c3149a452fea12ca3007e2/pkg/ingester/ingester_v2.go#L859-L873
So I should remove these additions and return the total rejected in a new field in `cortexpb.WriteResponse`, right?

**Comment by bboreham** [comment]
Sounds like you are on the right track!  Let us know how you get on.

Take care that the protobuf retains backwards-compatibility, and allow for the case that an older distributor is calling a new ingester  or vice-versa (metrics don't have to be accurate in this case, but don't crash).

**Comment by bboreham** [comment]
still valid.

**Comment by bboreham** [comment]
still valid.
