### ISSUE TITLE
Ruler_storage doesn't support local

### ISSUE THREAD

**Issue by TomL-dev** [cortexproject/cortex#3979]
**Describe the bug**
ruler_storage config doesn't support local as described in the documentation.

from the [documentation](https://github.com/cortexproject/cortex/blob/master/docs/configuration/config-file-reference.md#ruler_storage_config) you can use: local as a backend.

```
# Backend storage to use. Supported backends are: s3, gcs, azure, swift,
# filesystem, configdb, local.
# CLI flag: -ruler-storage.backend
[backend: <string> | default = "s3"]
```
i have configured: 

```yaml
ruler_storage:
  backend: local
  local:
    directory: "/ruler/local/"
```

but the cortex module refuses this config:

cortex_ruler.1.ircc8gniudzs@x    | error loading config from /etc/config.yml: Error parsing config file: yaml: unmarshal errors:
cortex_ruler.1.ircc8gniudzs@x    |   line 54: field local not found in type rulestore.Config

bearing my golang skills i see here:
https://github.com/cortexproject/cortex/blob/master/pkg/ruler/rulestore/config.go referencing https://github.com/cortexproject/cortex/blob/master/pkg/storage/bucket/client.go which has no `local` entry. my assumption is that this isn't accepting the `local` entry

**To Reproduce**
1. Start Cortex: cortex:v1.8.0-rc.1
2. use local config for ruler_storage

**Expected behavior**

start with provided config

**Environment:**
 - Infrastructure: docker-swarm
 - Deployment tool: docker-stack deploy

**Storage Engine**
- [ ] Blocks
- [ ] Chunks

**Additional Context**

**Comment by pracucci** [comment]
👋  @TomL-dev. Sorry for the misleading doc. The doc is built on top of `master`: the `local` support has been added in #3932, after the Cortex 1.8.0 was cut. The `local` support to `ruler_storage` will be included in Cortex 1.9.0 (or you can already use it running the `master` version).
