### ISSUE TITLE
Configuration file Maximum number of simultaneous http connections

### ISSUE THREAD

**Issue by y-vectorfield** [cortexproject/cortex#3986]
In the document,  a explanation of maximum number of simultaneous http connections as follows,

```
# Maximum number of simultaneous http connections, <=0 to disable
# CLI flag: -server.http-conn-limit
[http_listen_conn_limit: <int> | default = 0]
```

However,  line 1 should as follows,

```
# Maximum number of simultaneous http connections, <0 to disable
```

if <=0, default value is wrong value.

**Comment by pracucci** [comment]
The connection limit is not applied with a value of 0 or less than 0. I think the documentation is correct. Feel free to reopen the issue otherwise.
