### ISSUE TITLE
Configuration file type

### ISSUE THREAD

**Issue by y-vectorfield** [cortexproject/cortex#3988]
In this document, following sentence has a typo,

```
# Register the intrumentation handlers (/metrics etc).
```

intrumentation -> instrumentation

```
# Register the instrumentation handlers (/metrics etc).
```

**Comment by pracucci** [comment]
Thanks @y-vectorfield. Would you like to open a PR to fix it, please?

**Comment by y-vectorfield** [comment]
@pracucci ,
OK. I'll fix it and open a pull request soon.

**Comment by pracucci** [comment]
This is a tiny typo fix to do in `weaveworks/common`. Help wanted 🤗

**Comment by y-vectorfield** [comment]
Oh, sorry I forgot this issue.
@pracucci ,
OK. I'll fix it and open a pull request soon.

**Comment by y-vectorfield** [comment]
@pracucci ,
I opened a pull request #4309.
