### ISSUE TITLE
Querying /series api endpoint should query Ingesters & Long-Term Storage

### ISSUE THREAD

**Issue by disfluxly** [cortexproject/cortex#4000]
**Is your feature request related to a problem? Please describe.**
Any queries that hit the `/series` api endpoint will only return values that are in the ingesters. This makes using `label_values()` within Grafana Dashboard Variables problematic, as adjusting the dashboard time range to anything outside of the ingester retention will return nothing. This breaks any kind of dynamic dashboarding when looking at historical data. 

**Describe the solution you'd like**
Any queries that hit the `/series` api endpoint should be treated just like the `query_range` queries. They should query both the ingesters and the long-term storage for datapoints.

**Describe alternatives you've considered**
Possibly using the `query_result()` dashboard variable with a group by and then getting the label values by regex.

**Additional context**
Ignoring the `start` and `end` parameters of the `/series` endpoint was added as part of this MR here: https://github.com/cortexproject/cortex/pull/2617

**Comment by pracucci** [comment]
If you're running the blocks storage, the feature is still behind a feature flag (because experimental). You can enable it via `-querier.query-store-for-labels-enabled=true` or its respective YAML config option.

**Comment by pracucci** [comment]
> Is it close to stable or are there known issues I should watch out for?

We're running it at Grafana Labs since few weeks and so far so good.

**Comment by pracucci** [comment]
Closing because it's supported by blocks storage.
