### ISSUE TITLE
ruler doesn't support global external labels

### ISSUE THREAD

**Issue by jml** [cortexproject/cortex#404]
You can configure Prometheus to add labels to any time series or alert that it sends to other systems using `global.external_labels` (see https://prometheus.io/docs/operating/configuration/#configuration-file).

It uses these labels when writing output for recording and alerting rules.

Because our rules configuration only allows for rules files, we have no way of supporting this setting in the ruler.

**Comment by jtlisi** [comment]
#1571 will make these a bit easier to implement. The upstream Prometheus rules Manager has the params for external labels in this function: https://github.com/prometheus/prometheus/blob/37d666949c9475e298666cc8e0e787d76fa8fd77/rules/manager.go#L825

However, we will need to allow users to configure their rules with external labels

**Comment by gotjosh** [comment]
We should also consider specifying whenever the global external labels should be applied to alerts or rules or both.

**Comment by jtlisi** [comment]
@gotjosh I think it would make sense for the external label to be directly associated with the rule group.

**Comment by gouthamve** [comment]
We also need `alert_relabel_rules` as part of the global config.

**Comment by gotjosh** [comment]
The stanza described by Goutham is: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alert_relabel_configs

**Comment by friedrichg** [comment]
Fixed by https://github.com/cortexproject/cortex/pull/4499
