### ISSUE TITLE
Allow to configure bucket caching for compactor

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#4047]
**Is your feature request related to a problem? Please describe.**
We have a Cortex cluster with a large number of tenants (tens of thousands). Discovering tenants in the bucket is very slow. The bucket listing is done by every compactor but we could reduce the load on the bucket configuring bucket caching for the compactor as well.

**Describe the solution you'd like**
Bucket caching for the compactor was not allowed because it's generally not safe, but there are few operations (like tenants discovery) for which it's expected to be safe, and I believe we should do it.

**Comment by pstibrany** [comment]
> but there are few operations (like tenants discovery) for which it's expected to be safe, and I believe we should do it.

Agree. Good idea!

**Comment by pracucci** [comment]
_Still valid_
