### ISSUE TITLE
Documentation for alertmanager_storage_config  CLI is not correct.

### ISSUE THREAD

**Issue by mizunos** [cortexproject/cortex#4051]
Currently in documentation:
\# CLI flag: -alertmanager-storage.backend 

This cause my alertmanager pod to error out.  

Looking at cortex -h for alertmanager it seemed that it should be  -alertmanager.storage.type instead.

**Comment by pracucci** [comment]
The Cortex documentation is not versioned yet so it reflects the latest version. `-alertmanager-storage.backend` has been introduced in Cortex 1.8.0.
