### ISSUE TITLE
Ruler GRPC options not being respected

### ISSUE THREAD

**Issue by jpdstan** [cortexproject/cortex#4063]
**Describe the bug**
It seems that [a subset of flags](https://github.com/cortexproject/cortex/blob/eb6a6f546448f07aecbc105afdf374e06f89ea8d/pkg/util/grpcclient/grpcclient.go#L41-L45) within the ruler configuration are not being respected. Notice how they are not taking the flags `f` as input. 

**To Reproduce**
We saw this issue due to errors like
```
level=warn ts=2021-04-08T16:06:54.640040321Z caller=manager.go:619 user=fake group=kubernetes_container_memory_0 msg="Rule sample appending failed" err="rpc error: code = ResourceExhausted desc = trying to send message larger than max (23101504 vs. 16777216)"
```

wherein you can see the default max value for `ruler.client.grpc-max-send-msg-size`: `16777216` (`16 << 20`). This is inconsistent with the flag we set:

```
      -ruler.client.grpc-max-send-msg-size=104857600
```

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: jsonnet

**Storage Engine**
- [x] Blocks

**Comment by pstibrany** [comment]
Hello,

`ruler.client.*` flags are only used when ruler is communicating with other rulers.

When ruler communicates with ingesters, they use settings set by `-ingester.client.*` flags instead.

**Comment by jpdstan** [comment]
ah makes sense. Thanks @pstibrany
