### ISSUE TITLE
Build failing while trying with CGO_ENABLED set to 1

### ISSUE THREAD

**Issue by guhaneswaran** [cortexproject/cortex#4076]
**Describe the bug**
Build failing while trying with CGO_ENABLED set to 1. Tring to understand the reason for disabling CGO_ENABLED. Is there any other workaround as customizing cortex  while including external binaries is looking for CGO_ENABLED set to 1

**To Reproduce**
build cortex with CGO_ENABLED=1

**Expected behavior**
Build to be successful with CGO_ENABLED=1

**Environment:**
 - Infrastructure: Centos VM

**Comment by jtlisi** [comment]
As a project, I don't think we are interested in supporting CGO. CGO comes with a unique set of tradeoffs and as a project we aren't interested in them at this point. [This article](https://www.cockroachlabs.com/blog/the-cost-and-complexity-of-cgo/) lays out some of the downsides of using CGO.

**Comment by jtlisi** [comment]
Closing this for now
