### ISSUE TITLE
Ingester can end up with incorrect state of TSDB when it fails to remove all files when closing idle TSDB.

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#4082]
**Describe the bug**
Under some conditions, ingester can close TSDB and delete local files, eg. when TSDB is idle for too long. After cleanup, ingester removes in-memory entry about the user from `i.TSDBState.dbs` map.

However, if ingester fails to delete the local files, it still deletes this entry. This can be problematic if same user starts sending new samples -- ingester will try to reopen existing TSDB, but as some files have been deleted, such TSDB will be broken, which can lead to weird errors.

Instead we suggest to keep entry in `i.TSDBState.dbs` map if files deletion fails, but in `closed` state, or possibly some `error` state.

**Comment by pracucci** [comment]
_Still valid_
