### ISSUE TITLE
Unable To Configure Alertmanager: mkdir /tmp/validate-configxxxxx read-only file system

### ISSUE THREAD

**Issue by Carmezim** [cortexproject/cortex#4089]
**Describe the bug**
Disclaimer: I'm using the helm chart

Unable to make POST requests to configure the alertmanager given the helm chart hardcodes `readOnlyRootFilesystem: true` and I was wondering if there is a proper way to handle that not involving deactivating read only permissions for root.

**To Reproduce**
1. Port Forward the Alertmanager server to local MacBook
2. Perform a POST request to the alertmanager `/api/v1/alerts` with a valid configuration (or use cortex tool to load from a local file).
3. Receive error `error validating Alertmanager config: mkdir /tmp/validate-config258330117: read-only file system
`

**Expected behavior**
There is a way to define the validation directory rather using a default in root dir or Cortex does not try to access root dir for validation.

**Environment:**
 - Infrastructure: K8s port forwarded to MacBook
 - Deployment tool: helm

**Storage Engine**
- [ x ] Blocks
- [ ] Chunks

**Additional Context**

It'd be helpful if the temp dir for validation could be provided for Cortex.

**Comment by Carmezim** [comment]
This validation:
https://github.com/cortexproject/cortex/commit/04ec41354a342d5cd861b1652e3320f5bfa39911#diff-1cfea70822c401f368e69a551a36b729fd8ac414bf25071031c65e0b33f30252R145

**Comment by Carmezim** [comment]
cc @pstibrany

**Comment by Carmezim** [comment]
Solved by configuring the `/tmp` dir for alertmanager
```
extraVolumes:
    - name: tmp-volume
        emptyDir: { }
  extraVolumeMounts:
    - name: tmp-volume
      mountPath: /tmp
```

**Comment by pracucci** [comment]
Can you make the `/tmp` dir writable? Alternatively you may consider configuring a different tmp dir for golang (should be done via `TMPDIR` env variable but I haven't tried).

**Comment by Carmezim** [comment]
@pracucci thanks! I forked the helm chart and disabled the root read only permissions and it's fine! 
Got that same #4093 issue afterwards that hoping should be worked around with different buckets.

Thank you
