### ISSUE TITLE
Alertmanager configuration load failure because of bucket index

### ISSUE THREAD

**Issue by thibautcharry** [cortexproject/cortex#4093]
**Describe the bug**
In Cortex 1.7.0+ Blocks Storage mode, when the Alertmanager is configured to use the same bucket as the one for time series, a `bucket-index.json.gz` file is also being created in the `alerts` directory by the Compactor.

This leads to the Alertmanager not being able to sync configs:

v1.7.0
```
level=info ts=2021-04-20T16:02:14.084049747Z caller=multitenant.go:508 component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"
level=warn ts=2021-04-20T16:02:14.133749432Z caller=multitenant.go:490 component=MultiTenantAlertmanager msg="error while synchronizing alertmanager configs" err="proto: wrong wireType = 7 for field Templates"
```

v1.8.0
```
level=info ts=2021-04-20T18:58:18.638629309Z caller=multitenant.go:537 component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"
level=warn ts=2021-04-20T18:58:18.685270486Z caller=multitenant.go:519 component=MultiTenantAlertmanager msg="error while synchronizing alertmanager configs" err="failed to load alertmanager configurations for owned users: failed to fetch alertmanager config for user bucket-index.json.gz: proto: wrong wireType = 7 for field Templates"
```

#3904 seems to mention the same issue but as far as I understand its purpose is only to indicate which files are problematic
#4080 might be the same problem but I thought it would be clearer to open a new issue

**To Reproduce**
1. Use Cortex 1.7.0+ in order for the bucket index to be enabled by default on the Compactor
2. Configure the Alertmanager with for example:
    ``` 
    -alertmanager.storage.type=gcs
    -alertmanager.storage.gcs.bucketname=test-bucket
    ```
3. Use the same bucket for the configuration of Blocks Storage:
    ```
    -blocks-storage.gcs.bucket-name=test-bucket
    ```
4. Create an alertmanager configuration so that the `alerts` directory is created on the bucket
5. Wait for the Compactor to scan the bucket and upload the bucket index
6. Check if the Alertmanager is now logging the error mentioned above

**Expected behavior**
I expected either for the Compactor to not create the bucket index file inside the `alerts` directory or for the Alertmanager to ignore this file and be able to sync the configs. Or maybe it is by design and it is recommended to use a different bucket for the Alertmanager.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Jsonnet

**Storage Engine**
- [X] Blocks
- [ ] Chunks

**Comment by mizunos** [comment]
Can we use a different storage bucket for alert manager and ruler instead as a work around for now?

**Comment by thibautcharry** [comment]
> Can we use a different storage bucket for alert manager and ruler instead as a work around for now?
This is what I'm doing on my side to work around this issue.

**Comment by pstibrany** [comment]
> Can we use a different storage bucket for alert manager and ruler instead as a work around for now?

Yes, absolutely. Blocks *should* be stored in a separate bucket, otherwise compactor is confused as you can see. Rules and alerts can be stored in the same buckets.

**Comment by pracucci** [comment]
We should improve the doc to make it clear that blocks should be stored in a dedicated bucket. Help wanted to update the doc! 🤗

**Comment by mizunos** [comment]
I am more than happy to help with the doc as it is still fresh on my mind of all the steps I had performed to set it up

**Comment by pracucci** [comment]
> I am more than happy to help with the doc as it is still fresh on my mind of all the steps I had performed to set it up

Sure @mizunos , please go on! 🙏
