### ISSUE TITLE
Backfill historical data from Prometheus into Cortex

### ISSUE THREAD

**Issue by ahadjidj** [cortexproject/cortex#4136]
Migrating form Prometheus to Cortex requires waiting to have enough data in Cortex for switching the lights. The delay is required if we want to do performance benchmarks on larger datasets.

For these scenarios, it would be great to have a tool to export existing data from Prometheus and loaded in batch into a Cortex cluster.

**Comment by pracucci** [comment]
When running Cortex with the blocks storage, you can pick Prometheus TSDB blocks (stored on disk) and upload them to the bucket, doing a simple manipulation of the `meta.json` file of each block. Please take a look at this documentation for more info:
https://cortexmetrics.io/docs/blocks-storage/migrate-storage-from-thanos-and-prometheus/
