### ISSUE TITLE
Add tracing to the tenant federation mergeQueryable

### ISSUE THREAD

**Issue by simonswine** [cortexproject/cortex#4147]
This is a work item that came out the review of https://github.com/cortexproject/cortex/pull/4117

The mergeQueryable aggregates data from underlying queryables concurrently. Understanding the call sequence is only possible providing spans.

/assign @simonswine 

Some examples that creates spans:

https://github.com/cortexproject/cortex/blob/d382e1d80eaf0847e3b57592b970a4f1bf3121df/pkg/querier/blocks_store_queryable.go#L318

https://github.com/cortexproject/cortex/blob/5009276fdd385587a13f1492520cc38647512bc6/pkg/querier/worker/scheduler_processor.go#L134

**Comment by pstibrany** [comment]
Your first linked example is what I would suggest to use… getting spanlogger from existing context, closing it at the end of method, and passing **new** context to the called methods is a good start. Additionally logging supplied tenantIDs via new spanlogger (to make them visible when viewing the trace) would be useful.

We can go even further and create one child span per processed tenant – that can be useful for people troubleshooting slow queries to understand if there is specific tenant that was slow for some reason.

**Comment by vlad-diachenko** [comment]
I have implemented a logic to add `tenant_id` tag to each tracing span if tenant_id is defined in context.
Also, I have added a few additional spans to mergeQuerier:
- `mergeQuerier.select`
- `mergeQuerier.labelValues`
- `mergeQuerier.labelNames`
