### ISSUE TITLE
undestand active_series_metrics_enabled

### ISSUE THREAD

**Issue by mrmassis** [cortexproject/cortex#4153]
Hi everyone,
i need understand the flag: active_series_metrics_enabled. Whats metrics this enable the tracking. I did a curl in cortex with and without this flag, and the result was the same. In other words, no new metrics.

How i interprete this flag?

Tkz in advance.

**Comment by pracucci** [comment]
From the CHANGELOG:
```
* [ENHANCEMENT] Ingester: added new metric `cortex_ingester_active_series` to track active series more accurately. Also added options to control whether active series tracking is enabled (`-ingester.active-series-metrics-enabled`, defaults to false), and how often this metric is updated (`-ingester.active-series-metrics-update-period`) and max idle time for series to be considered inactive (`-ingester.active-series-metrics-idle-timeout`). #3153
```

Does it answer your question?

**Comment by mrmassis** [comment]
More one question,
whats the component that export this metric?

**Comment by mrmassis** [comment]
I enable this funcion, but i cant found this metric:
```
...
  ingester:
    active_series_metrics_enabled: true

```

**Comment by mrmassis** [comment]
i cant found in the ingester and in the distributor (/metrics)

**Comment by mrmassis** [comment]
Hi,
Worked here. Tkz by suport!

**Comment by danfromtitan** [comment]
The [config doc ](https://cortexmetrics.io/docs/configuration/configuration-file/#ingester_config) is misleading when it says [active_series_metrics_enabled: <boolean> | default = true] - for most people that means even if I don't include it in Helm values, this property it's enabled by default. Once I added all three active-series-metrics-* to config, only then the metric shows-up.
