### ISSUE TITLE
unable to list rules

### ISSUE THREAD

**Issue by cloudcafetech** [cortexproject/cortex#4172]
getting issue in ruler 

```level=error ts=2021-05-11T09:05:53.409907768Z caller=ruler.go:445 msg="unable to list rules" err="Get \"http://configs.monitoring.svc.cluster.local:80/private/api/prom/configs/rules\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"```

**Comment by pracucci** [comment]
> context deadline exceeded (Client.Timeout exceeded while awaiting headers)

I've the feeling that, for some reason, the HTTP request has not been fully (or correctly) sent to the ruler. Which client are you using?

**Comment by cloudcafetech** [comment]
- Which client are you using?
Not able to understand.

**Comment by pracucci** [comment]
Who is sending the request `GET http://configs.monitoring.svc.cluster.local:80/private/api/prom/configs/rules`?
