### ISSUE TITLE
`/ruler/rule_groups` doesn't work with object stores

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#4177]
`/ruler/rule_groups` endpoint added in #3529 doesn't work when used with object store. Problem is that code calls [`ListRuleGroupsForUserAndNamespace`](https://github.com/cortexproject/cortex/blob/5d55a28c796dc1f44a864a0c701744f8f3f4e5cb/pkg/ruler/ruler.go#L863) to find all rule groups, but it doesn't call `LoadRuleGroups` required to actually *load* those rule groups. This step is necessary for some stores, eg. when using object store.

Tests currently pass, because `mockRuleStore` doesn't require this extra step.

Expected fix should change `mockRuleStore` to *require* `LoadRuleGroups`, and also fix `ListAllRules` to perform this load.

**Comment by pracucci** [comment]
@AllenzhLi is it something you could work on?

**Comment by AllenzhLi** [comment]
> @AllenzhLi is it something you could work on?

I can try to fix it this weekend.
