### ISSUE TITLE
Memcached client error message should include the cache name

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#4178]
**Describe the bug**
This error message doesn't say which cache was involved (index, metadata, chunks, etc.):
```
level=warn ts=2021-05-12T14:47:45.076049765Z caller=memcached_client.go:382 msg="failed to fetch items from memcached" numKeys=2535 firstKey=S:01F5FBARXPESQTKV2EH44JB0B3:28400064 err="read tcp 10.244.221.99:60966->10.244.222.6:11211: i/o timeout"
```

This was with Cortex v1.8.0.

**Expected behavior**
Add a tag like `cache=index`.

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Comment by pracucci** [comment]
This should have been fixed by https://github.com/thanos-io/thanos/pull/3929 which has been vendored in https://github.com/cortexproject/cortex/pull/4102.

_Closing for now, but let me know if it doesn't fix it._
