### ISSUE TITLE
Alertmanager status page isn't working if cluster disabled or sharding enabled

### ISSUE THREAD

**Issue by damnever** [cortexproject/cortex#4190]
**Describe the bug**
Alertmanager status page isn't working if cluster disabled or sharding enabled.

**To Reproduce**
Set `-alertmanager.sharding-enabled` to true, the status page of alertmanager will panic.

**Expected behavior**
It should show non-cluster status or hide the page.

I have sent a [PR](https://github.com/cortexproject/cortex/pull/4184) for this.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Storage Engine**
- [x] Blocks

**Additional Context**

v1.9.0

**Comment by gotjosh** [comment]
This is related to https://github.com/prometheus/alertmanager/pull/2581 which has been fixed upstream.

**Comment by pracucci** [comment]
Fixed by https://github.com/cortexproject/cortex/pull/4184.
