### ISSUE TITLE
Expose all HTTPClientConfig fields in ruler config

### ISSUE THREAD

**Issue by maver1ck** [cortexproject/cortex#4214]
**Is your feature request related to a problem? Please describe.**
I'm using Loki on Openshift. To connect to alertmanager I need to set up bearer token. Unfortunately following option is not exposed
https://github.com/cortexproject/cortex/blob/7f9e9ec7a6e5363a095b5de6d2b4b03b40c4ffa5/vendor/github.com/prometheus/common/config/http_config.go#L141

**Describe the solution you'd like**
Expose all HTTPClientConfig  in
https://github.com/cortexproject/cortex/blob/master/pkg/ruler/notifier.go#L167

**Comment by maver1ck** [comment]
@jtlisi Maybe you can help ?

**Comment by jtlisi** [comment]
@maver1ck I see no reason why we couldn't add support for bearer tokens here. Are you interested in opening a PR?

**Comment by maver1ck** [comment]
@jtlisi 
Main reason is that without this functionality you can't use Loki alerting on Openshift.
