### ISSUE TITLE
Ingester static per-instance limits not respected if runtime configuration file used

### ISSUE THREAD

**Issue by edma2** [cortexproject/cortex#4228]
**Describe the bug**
When using a runtime configuration file, default Ingester instance limits set in the static configuration are ignored.

**To Reproduce**
1. Pass a runtime configuration file to Cortex with `runtime_config.file`. Don't set any Ingester instance limits in the runtime file.
2. Configure `ingester.instance_limits.max_series = 10000000` (or whatever value) in the static Cortex config.
3. Start Cortex (SHA or version) v1.9
4. Observe `cortex_ingester_instance_limits{limit="max_series"}` is all 0.

**Expected behavior**
`cortex_ingester_instance_limits` should be 10000000.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] Kubernetes
 - Deployment tool: [e.g., helm, jsonnet] kubectl

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**

From what I can tell, the bug seems to be that this function only returns `nil` when the runtime config is disabled entirely:
https://github.com/cortexproject/cortex/blob/198b350918dfe0e3b9e14d60d70e7aaa4e585f70/pkg/cortex/runtime_config.go#L129

But if we're using the runtime config, but without any Ingester limits set, it will always return the default zero-value struct which has no limits (0).

**Comment by pracucci** [comment]
That's right. I think an easy way to solve this would be changing `IngesterLimits` data type in `runtimeConfigValues` from `ingester.InstanceLimits` to `*ingester.InstanceLimits` so that we can check the case when no ingester limits were set in the runtime config (if `nil` then none was set).

What do you think @edma2 ? Wanna attempt a fix?

**Comment by pstibrany** [comment]
> That's right. I think an easy way to solve this would be changing `IngesterLimits` data type in `runtimeConfigValues` from `ingester.InstanceLimits` to `*ingester.InstanceLimits` so that we can check the case when no ingester limits were set in the runtime config (if `nil` then none was set).
> 

Note that overriding `UnmarshalYAML` for  `*InstanceLimits` was supposed to prevent this situation: https://github.com/cortexproject/cortex/blob/94b0137e7133652f32a6ca641510b8c4c861791e/pkg/ingester/instance_limits.go#L26. Idea was that runtime config values will use "default" values for missing fields in runtime config file.

I see that the test to verify this behaviour is missing from `runtime_config_test.go`. I would start with adding a test there.

**Comment by pstibrany** [comment]
Ah, but if there is no field specified, then this `UnmarshalYAML` isn't even called to set the defaults. :(

Marco's solution should indeed fix the problem.
