### ISSUE TITLE
Upgrade alertmanager to 0.22.1+

### ISSUE THREAD

**Issue by ShuzZzle** [cortexproject/cortex#4234]
Updating alertmanager adds new functionality such as negative matches/timebased routing....
Full Notes: https://github.com/prometheus/alertmanager/releases/tag/v0.22.0

**Comment by pstibrany** [comment]
Working on this. Upgrading to master, to get https://github.com/prometheus/alertmanager/pull/2569 and hopefully https://github.com/prometheus/alertmanager/pull/2571 soon as well.
