### ISSUE TITLE
Cortex monitoring metrics

### ISSUE THREAD

**Issue by gliptak** [cortexproject/cortex#4242]
**Is your feature request related to a problem? Please describe.**

I might have missed this in the documentation, looking for listing metrics allowing to monitor Cortex infrastructure

**Describe the solution you'd like**

A detailed list of Cortex metrics published

**Describe alternatives you've considered**

I was able to get some pointers from (no longer updated?) https://grafana.com/grafana/dashboards/9820

**Comment by pstibrany** [comment]
Apart from reading `/metrics` on running Cortex instance (which may actually work pretty well depending on your needs), there is no complete list of metrics.

You can find more up-to-date dashboards and alerts in this repository: https://github.com/grafana/cortex-jsonnet/

**Comment by gliptak** [comment]
@pstibrany thank you for the repo pointer. Access to `/metrics` might not be available in all environments.

**Comment by pracucci** [comment]
> Access to /metrics might not be available in all environments.

Cortex metrics are typically meant to be used by who operates the Cortex cluster. In such scenario, `/metrics` is expected to be available to the Cortex operator.

**Comment by gliptak** [comment]
I would look at this as "admin" dashboard in Grafana. I will review what metrics https://github.com/grafana/cortex-jsonnet/ exposes
