### ISSUE TITLE
Have the max chunks per query limit shared between ingesters and storage gateways

### ISSUE THREAD

**Issue by treid314** [cortexproject/cortex#4255]
**Is your feature request related to a problem? Please describe.**
The config option `-querier.max-fetched-chunks-per-query` counts and limits the number of chunks returned independently for the ingester and storage gateway for a query. While, `-querier.max-fetched-series-per-query` and `-querier.max-fetched-chunk-bytes-per-query` limits the sum of series and chunk bytes returned between the ingester and store gateways for a query.

**Describe the solution you'd like**
The proposed solution is to migrate the `-querier.max-fetched-chunks-per-query` limit to the new QueryLimiter to limit the number of chunks returned as a sum of chunks returned from the ingester and storage gateway.

**Additional context**
`-querier.max-fetched-chunks-per-query` was previously marked as experimental.

**Comment by pracucci** [comment]
> -querier.max-fetched-chunks-per-query was previously marked as experimental.

I just realised it wasn't marked as experimental:
https://cortexmetrics.io/docs/configuration/v1guarantees/

Since it was done after cutting 1.9, let me do right now so we can gain some time.
