### ISSUE TITLE
Memberlist: TCPTransport: unknown message type: msgType: Rw==

### ISSUE THREAD

**Issue by cabrinha** [cortexproject/cortex#4273]
**Describe the bug**

Every 30s, members of any ring using the memberlist gossip protocol log this message:

```
{"caller":"tcp_transport.go:313","level":"error","msg":"TCPTransport: unknown message type","msgType":"Rw==","ts":"2021-06-09T22:02:21.264338815Z"}
```

**To Reproduce**
1. Start Cortex (v1.9.0)
2. Join memberlist

**Expected behavior**
This log message shouldn't appear.

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: Helm

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**
Every 30s:

```
{"caller":"tcp_transport.go:313","level":"error","msg":"TCPTransport: unknown message type","msgType":"Rw==","ts":"2021-06-09T22:02:21.264338815Z"}
```
`Rw==` is a base64 encoded `G` and I'm not sure if this is a red herring or not. Is there a text message coming through that starts with `Gossip` or something?

https://github.com/cortexproject/cortex/blob/master/pkg/ring/kv/memberlist/tcp_transport.go#L243

**Comment by cabrinha** [comment]
These messages are coming from Prometheus scraping my pods.

**Comment by ubergesundheit** [comment]
@cabrinha Are you simply ignoring the log lines or is it possible to configure something so it does not occur?

**Comment by ShuzZzle** [comment]
> @cabrinha Are you simply ignoring the log lines or is it possible to configure something so it does not occur?

Yeah just don't scrape the Pod/Service at 7946 where memberlist is. That's pretty much all. If you use the cortex-helm-chart and the provided ServiceMonitors then that should not happen

**Comment by ubergesundheit** [comment]
Thank you for your quick reply! I am in fact seeing this in loki which uses this project as a depencency. I'll see if its possible to scrape metrics on another port. But the ServiceMonitors are a good pointer I guess :)
