### ISSUE TITLE
Looking for Recommendation on Ingester Resource Configuration/Optimization

### ISSUE THREAD

**Issue by prprasad2020** [cortexproject/cortex#4284]
We have a Cortex(v1.7) deployment with Authentication enabled and running on Kubernetes cluster(AWS EKS). We are doing a load/performance test using [Avalanche](https://github.com/open-fresh/avalanche) to figure out how much data can Cortex handle with a baseline configuration. 

We have deployed 4 ingesters with 6GB memory & 1.5 cpu limits for the pods. It could handle ~27K metrics per second from one avalanche replica(data is fired to one tenant). Ingesters are collecting data and uploading data to S3 bucket without any issues. But when we increase the rate to ~30K metrics per second, ingesters could collect data without any issues, but when ingesters try to upload data to S3, one or two ingesters are over utilizing memory and Kubernetes is killing those pods. Any idea why those are gradually and continuously utilizing memory ?

Now we are planning to increase the replica count of ingesters to 6 or 7 and try to find the resource requirement to handle ~50K metrics per second from one avalanche replica. I will post an update here once we have the results. Anyone has any idea/recommendations on how much resources will ingesters need to handle such kind of metrics count ?

Also we noticed that if we fire ~100K metrics per second from 10 avalanche replicas(data is fired to two tenants), Cortex could handle those metrics with only 4 ingesters. It is weird that it could handle such kind of metrics count when avalanche is sending data from multiple replicas to one tenant but could not handle when avalanche is sending data from one replica to one tenant. If anyone has any theory/explanation those are welcome. TIA.

**Comment by pracucci** [comment]
> We have a Cortex(v1.7)

Could you upgrade to Cortex 1.9? The S3 client memory utilization when uploading large objects is something that has been improved at some point, so I would suggest you to test with the latest version (generally speaking it's always a good idea to run the latest stable version).

> But when we increase the rate to ~30K metrics per second

I guess you mean samples/sec. However, the ingesters memory utilisation is primarily influenced by the number of in-memory series (number of different series hold in the ingester memory). You can query `cortex_ingester_memory_series` metric exposed by Cortex ingesters to see the actual number of in-memory series. With that number I can give suggestions about the sizing of the ingester.

To give you an idea, we target to 1.5M series / ingester with 25GB memory limit / ingester.

**Comment by prprasad2020** [comment]
Hi @pracucci 

Thank you for the clear explanation. I'll try to upgrade the version to v1.9 and do the testing.

> I guess you mean samples/sec.

I'm using `irate(cortex_distributor_received_samples_total[5m])` metric in a Grafana dashboard to check the ingestion rate per tenant. is this incorrect ? or are there any other metric to check samples/sec rate ? Our goal is to find Cortex configurations to at least handle 1mil samples/sec.

I created a graph to view `cortex_ingester_memory_series` metric as you mentioned above. In the current configuration, we have 9 ingesters with 6GB memory / 1.5 CPU limits each. And currently 7300 metrics ingested per second. In each ingesters in-memory series is around 24000-25000 _(below screenshots)_ .

![Normal metrics per second value](https://github.com/prprasad2020/Prasad-images/blob/main/Cortex/Issue-4284/mps%20current.PNG?raw=true)
![Normal in-memory series](https://github.com/prprasad2020/Prasad-images/blob/54b12a8dcea0eac727cfae025555e98fe2bfb2fc/Cortex/Issue-4284/in-memory%20current.PNG?raw=true)

When I tried to ingest 118000 metrics per second, in memory usage went up to 950K-1mil and some ingesters went down when uploading blocks to S3 _(below screenshots)_ .

![metrics per second value when load test](https://github.com/prprasad2020/Prasad-images/blob/54b12a8dcea0eac727cfae025555e98fe2bfb2fc/Cortex/Issue-4284/mps.PNG?raw=true)
![in-memory series when load test](https://github.com/prprasad2020/Prasad-images/blob/54b12a8dcea0eac727cfae025555e98fe2bfb2fc/Cortex/Issue-4284/in-memory.PNG?raw=true)
 

> To give you an idea, we target to 1.5M series / ingester with 25GB memory limit / ingester.

Since our ingesters only have 6GB memory limit, this should be the reason why they were terminated with OOMKilled when those received around 1mil series. Are there any metrics to check the ingested samples/sec and in-memory series relationship ?

**Comment by pracucci** [comment]
> If we increase the ingester count can't those handle 1mil series with out 25GB memory/ingester ?

Yes, adding more ingesters is another option. However, 6GB looks quite a low memory limit for ingesters. I would suggest to increase that memory limit anyway. The rule of thumb we apply at Grafana Labs is 16GB limit every 1M in-memory series / ingester.

**Comment by prprasad2020** [comment]
> Yes, adding more ingesters is another option. However, 6GB looks quite a low memory limit for ingesters. I would suggest to increase that memory limit anyway. The rule of thumb we apply at Grafana Labs is 16GB limit every 1M in-memory series / ingester.

Thanks, I'll try to increase the memory limit at least to 10GB / ingester. Because we are mostly towards horizontal scaling rather than vertical scaling.

I have upgraded the version to Cortex v1.9 as you recommended. We will try to do few more load tests on this version and get back to you with an update. I observe that when ever we send data to a fresh tenant, initial S3 upload is happening after 3Hrs and after that every 2Hrs, is this the normal behavior ? Also do you know the relationship between in-memory series and ingested samples in Cortex-ingester ?

**Comment by pracucci** [comment]
> I observe that when ever we send data to a fresh tenant, initial S3 upload is happening after 3Hrs and after that every 2Hrs, is this the normal behavior ?

Yes. A TSDB block is compacted from head with series having timestamp between [-3h ago, -1h ago]. This explain that behaviour.

**Comment by pracucci** [comment]
> Also do you know the relationship between in-memory series and ingested samples in Cortex-ingester ?

I'm not sure I understand the question. Could you elaborate it, please?

**Comment by prprasad2020** [comment]
> I'm not sure I understand the question. Could you elaborate it, please?

Sorry, let me explain. When I sent around total of 117K samples per second(_12 separate tenants_), I can see in-memory series is between 560K-630K per ingester(_we have total of 18 ingesters_). I was wondering about the method / the way how these ingested samples are distributed among those ingesters ? How is this in-memory series calculated and how does the ingested samples rate affect the in-memory series of an ingester ? Thanks.

**Comment by pracucci** [comment]
I'm missing a bit some details about your setup and what you're seeing so, instead of trying to give you a direct answer, I'm going to explain how things work, so you can further investigate it by yourself.

A "series" is a time-series, which is a stream of timestamp-value pairs. Is pair is called "sample". Cortex shard series across ingesters so, assuming the number of ingesters doesn't change over time, a series is sharded to an ingester + replicas (if replication factor is 3, the series is sharded across a total of 3 ingesters).

When you see an increase in samples / sec it may be caused by two reasons:
1. The number of series has increased
2. The number of series has not changed but the scrape interval decreased and samples of 1 series are scraped by Prometheus (and thus sent to Cortex) more frequently

Series are "created" in the ingester memory as soon as the 1st sample of that series is received and stored in the TSDB head (per-tenant). Every 2h the TSDB head is compacted into a new block which is then shipped to the object storage. The new block contains samples with timestamp between [-3h, -1h] so samples with timestamp over the last 1h (compared to the most recent sample ingested) will be kept in memory and flushed in the next head compaction.

If a series gets stale (which means, if no more samples are received for a series) the series will still stay in-memory (and get counted towards the total number of in-memory series in ingesters) until the next head compaction will flush it.

**Comment by prprasad2020** [comment]
> A "series" is a time-series, which is a stream of timestamp-value pairs. Is pair is called "sample". Cortex shard series across ingesters so, assuming the number of ingesters doesn't change over time, a series is sharded to an ingester + replicas (if replication factor is 3, the series is sharded across a total of 3 ingesters).

Thank you for the explanation, this is clear to me now. We have completed write path load testing and come up with some results, I'll finalize a document and send it to community as well.

I was wondering about the compactor storage, it is utilized over 90% most of the time. Also I noticed when I fire huge load Storage gateway disk utilizations also going up and it is always above 95%. I'm using few Grafana dashboards to display data and when I check 6hours data, it does not display data since storage gateway did not query those blocks due to disk space issues. Do you have any recommendations for planning the capacity on Compactor and Storage Gateway disks ?

**Comment by pracucci** [comment]
> Do you have any recommendations for planning the capacity on Storage Gateway disk ?

First of all make sure Compactor is running successfully. Compactor compacts smaller blocks into bigger ones (index is optimized) and deduplicates samples which were replicated due to the Cortex replication (chunks are optimized).

That being said, the easiest way is to have a reactive approach. Add an alert with linear prediction on store-gateway disks and scale up the replicas when required (make sure you've enabled the sharding in store-gateways). My general suggestion is to start with 100GB disks for each store-gateway.

**Comment by prprasad2020** [comment]
Thanks a lot for all the recommendation and suggestions @pracucci. We have concluded our load testing according to our requirement and came up with the results. I have attached a summarized document for anyone's reference. I'll share this in Cortex slack channel as well.

### [Cortex Load Testing](https://github.com/cortexproject/cortex/files/6922789/Cortex.Load.Testing.pdf)
