### ISSUE TITLE
Deprecate chunks storage

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#4295]
In #4268 we announced the chunks storage deprecation but there are other follow up actions we should take. This meta issue is used to track the next actions.

- [ ] Close all issues relating to the chunks storage ([list](https://github.com/cortexproject/cortex/labels/storage%2Fchunks))
- [ ] Stop using chunks storage in the e2e tests
- [ ] Change the default config to blocks storage

**Comment by bboreham** [comment]
Changing the default to blocks would be very disruptive to someone who is using chunks.
We could add a message in the logs saying "You are using deprecated chunks storage"...

**Comment by friedrich-at-adobe** [comment]
Although experimental in chunks, it would be nice to get the [delete series API](https://cortexmetrics.io/docs/guides/deleting-series/) in blocks
https://github.com/cortexproject/cortex/issues/4267

**Comment by pstibrany** [comment]
> Although experimental in chunks, it would be nice to get the [delete series API](https://cortexmetrics.io/docs/guides/deleting-series/) in blocks
> #4267

There is https://github.com/cortexproject/cortex/pull/4274 proposal for that.

**Comment by alvinlin123** [comment]
We have removed chunkstore support in https://github.com/cortexproject/cortex/pull/4812.
