### ISSUE TITLE
Ingester Ingested Samples Rate is doubled after upgrading to Cortex v1.9

### ISSUE THREAD

**Issue by prprasad2020** [cortexproject/cortex#4311]
I was using Cortex v1.7 and upgraded it to v1.9 yesterday. I used `cortex_distributor_received_samples_total` and `cortex_ingester_ingested_samples_total` to check distributor received rate and ingester ingested rate. And it was roughly same values when I'm running Cortex v1.7, but when I upgraded it to v1.9 `cortex_ingester_ingested_samples_total` metric value increased ~2.5x and `cortex_distributor_received_samples_total` value is staying same as before. I can see in-memory series(`cortex_ingester_memory_series`) in each ingester is also increased ~2.5x. Because of this ingester memory utilization is also higher than before. I have not increased the ingestion rate or did not configure new Prometheus remote writes, basically load is same as before. Anyone has any idea why this is happening ? 

I'm using below queries to get rates,
Distributor received samples rate : `sum(rate(cortex_distributor_received_samples_total[1m]))`
Ingester ingested samples rate : `sum(rate(cortex_ingester_ingested_samples_total[1m]))`

Below are the screenshots from Graphs before and after upgrade.

- Samples ingetion rates before,

![alt text](https://github.com/prprasad2020/Prasad-images/blob/cc17615109e6bf7e3efa5317cb4b74fe90fa50c0/Cortex/Issue-4311/cortex-1.7.PNG?raw=true)

- Samples ingetion rates after,

![alt text](https://github.com/prprasad2020/Prasad-images/blob/cc17615109e6bf7e3efa5317cb4b74fe90fa50c0/Cortex/Issue-4311/cortex-1.9.PNG?raw=true)

- In-memory series before,

![alt text](https://github.com/prprasad2020/Prasad-images/blob/a53185724a7d510600e80d54efe69ae1d44d691e/Cortex/Issue-4311/cortex-1.7%20in-memory.PNG?raw=true)

- In-memory series after,

![alt text](https://github.com/prprasad2020/Prasad-images/blob/cc17615109e6bf7e3efa5317cb4b74fe90fa50c0/Cortex/Issue-4311/cortex-1.9%20in-memory.PNG?raw=true)

**Comment by ShuzZzle** [comment]
I think this belongs to the helm-chart repo so we are also tracking it there: https://github.com/cortexproject/cortex-helm-chart/issues/168

**Comment by ShuzZzle** [comment]
Solution: replication_factor changed from "1" -> "3" thus results in 3x the amount of Party :tada:

**Comment by prprasad2020** [comment]
Closing this since it was an issue with the distributor replication factor.
