### ISSUE TITLE
Cortex creates block with too many chunks

### ISSUE THREAD

**Issue by roidelapluie** [cortexproject/cortex#4330]
**Describe the bug**

In our store-gateway, we see the following errors:

rpc error: code = Aborted desc = fetch series for block 01F005X5F5CP97PPHXXFT8F9WS: exceeded chunks li
mit: limit 2000000 violated (got 2000009)"

**Expected behavior**

I expect cortex not to create blocks it can't read.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: ansible

**Storage Engine**
- [x] Blocks
- [ ] Chunks

Cortex 1.8.0

**Comment by pracucci** [comment]
We have a limit on the max number of chunks a single query can fetch. You can increase that limit via `-store.query-chunk-limit` CLI flag or its respective YAML config option.

**Comment by roidelapluie** [comment]
Yes sorry, I was confused because I am investigating another bug in the same time. I mixed everything.
