### ISSUE TITLE
Distribute arm64 images

### ISSUE THREAD

**Issue by rverma-nsl** [cortexproject/cortex#4364]
**Is your feature request related to a problem? Please describe.**
Graviton instances provides cheaper and equally efficient for general purpose workload. We should be able to run cortex, currently loki and tempo are fully arm64 compatible.

**Describe the solution you'd like**
Distribute arm64 binaries/images

**Comment by bboreham** [comment]
As of 1.10 (currently at rc.1) we have ARM binaries and packages.

Not container images yet.  Happy to review PRs.

**Comment by WeiTangLau** [comment]
any update on this? As this is stopping me from using cortex :(

**Comment by rafilkmp3** [comment]
Hi this must be reoopen,

I trying to deploy to my EKS graviton cluster and I need arm64 image build and pushed and now there is only amd64 arch. 


```
podman image inspect quay.io/cortexproject/cortex:v1.14.0 | jq -r '.[] | .Architecture'
amd64
```

**Comment by morsik** [comment]
@rafilkmp3 I think you should just migrate to Grafana Mimir which is successor to Cortex. And it has arm64 images ;)

**Comment by yeya24** [comment]
> 

Have you tried v1.14.1? I believe we have arm image for 1.14.1 not, 1.14.0.
https://hub.docker.com/r/cortexproject/cortex/tags?page=1&name=1.14
https://quay.io/repository/cortexproject/cortex?tab=tags
