### ISSUE TITLE
AlertManager client configuration

### ISSUE THREAD

**Issue by callumj** [cortexproject/cortex#4373]
**Is your feature request related to a problem? Please describe.**
With a large amount of tenants I've found our AlertManager instance is hitting the gRPC message receive limits:

```
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (18779797 vs. 16777216)
```

**Describe the solution you'd like**
Similar to the ingester, querier, etc there is a common `grpc_client_config` struct that exposes more configuration for the gRPC client. 

There a two solutions:

1. Move the `alertmanager_client.go` code to utilize more of `grpcclient.go` to produce the flags and `DialOption`
2. Copy most of the configuration values from `grpc_client_config` into `alertmanager_client` struct

I am happy to work on this, but wanted to get the contributor's preference on the direction. 1 is cleaner but is more of a refactor, 2 is cheaper but does duplicate the common config logic.

**Describe alternatives you've considered**
N/A

**Additional context**
I notice the [comment](https://github.com/cortexproject/cortex/blob/master/pkg/alertmanager/alertmanager_client.go#L54):

```
// We prefer sane defaults instead of exposing further config options.
```

Was this more to reduce the surface area configuration for a user and less about considering these defaults to be fine for any customer?

**Comment by bboreham** [comment]
Any idea what was in that message? 18MB seems like a lot for alerts, but I don't know your specific situation.
