### ISSUE TITLE
Cortex return 5xx due a single ingester outage

### ISSUE THREAD

**Issue by alanprot** [cortexproject/cortex#4381]
**Describe the bug**
Cortex can return 5xx due a single ingester failure when a tenant is being throttled (4xx). In this case, distributor can return the error from the bad ingester (5xx) even though the other 2 returned 4xx. See [this](https://github.com/cortexproject/cortex/blob/master/pkg/ring/batch.go#L126).

Looking at this code seems that if we have replication factor = 2, 1 ingester down and the other 2 returning 4xx we can have for example:

4xx + 5xx + 4xx = 5xx
or
5xx + 4xx + 4xx = 4xx
etc

**To Reproduce**
I could create a unit test that reproduce the behavior:
https://github.com/alanprot/cortex/commit/fd36d97e010f93e28db21e3a1e981e17cd281a80
1. Start Cortex (SHA or version)
a4bf1035478641626fcbdd5fd12325c08a2bba76
2. Perform Operations(Read/Write/Others)
Write
**Expected behavior**
Cortex should return the error respecting the quorum of the response from ingesters.
So, if 2 ingesters return 4xx and one 5xx, cortex should return 4xx. This means that if distributor receive one 4xx and one 5xx,  it needs to wait the response of the third ingester.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
Kubernetes
 - Deployment tool: [e.g., helm, jsonnet]
Helm
**Storage Engine**
- [X] Blocks
- [ ] Chunks

**Additional Context**

**Comment by bboreham** [comment]
Can you say a bit more about the 5xx error?  The code you changed in #4388 is counting errors per-series, whereas I would expect a 5xx to be more of a whole-process error.

**Comment by alanprot** [comment]
This code counts the error per series... If i get more errors than expected, it returns the error (globally).

So lets say i have replication_set=3 and one series returns error X and Y. As the Y error was the second one (and this one is the one that breached the threshold), it will be the one returned.

So basically we return the error that breached the `maxFailures` of the first series that also breach it.

So, if you have one series that for some reason returned a 4xx error and after a 5xx, distributor will return a 5xx (assuming replication factor = 2). 

This change is only counting the error by "Family", so if one series get a 4xx and another a 5xx, it will wait for the third ingester to decide if it need to return 5xx or 4xx.

**Comment by bboreham** [comment]
OK but how can you get a 5xx error for a single series?  What's an example where this happens?

**Comment by alanprot** [comment]
Push 5XX: https://github.com/cortexproject/cortex/blob/master/pkg/ingester/ingester_v2.go#L751

Possible 4xx: https://github.com/cortexproject/cortex/blob/master/pkg/ingester/ingester_v2.go#L952

**Comment by bboreham** [comment]
That 5xx is saying the whole process is unavailable, not a single series.

If you don't need to count 5xx's per-series, that might make the fix simpler.

**Comment by alanprot** [comment]
So I guess the proposal is to return immediately on the first 4xx error (so we don't need to keep track of 5xx and 4xx separately).

The only thing to consider on this case is: we can have samples accepted for 2 ingesters and still return 4xx..

Let's consider this scenario:
* ReplicationFactor = 3
* ShardSize = 15
* Ingester 7 is running hot for a given tenant (this can happen in a normal operation as the sharding does not guarantee a 100% evenly distribution across ingesters)
* Push TimeSeries A that goes to ingester 1, 5 and 7. **This request will return 4xx even though it got ingested by 2 ingesters**

As discussed with @bboreham on slack in this case it may be ok to fail it back to the caller because (a) nothing changes - 2 and 3 still captured the data and (b) it's a bad state to be in - you have reduced redundancy - so it's ok to have alarms going off.

Besides that, it will behave similar to the case where 2 ingesters return 4xx and 1 return 2xx where we return 4xx to the caller and the data may still be available (but unstable) for querying: https://github.com/cortexproject/cortex/issues/731

What the others think?

**Comment by bboreham** [comment]
Thinking some more about this, there can be a genuine mix of outcomes across the request.
E.g. suppose you receive 100 samples for 100 series; 50 of them are errors that receive 4xx outcome, and 50 go to ingesters that have crashed so receive 5xx outcomes.
We should send a 5xx back to the caller so they can retry.

So now I'm thinking it should be a "latching" behaviour: for each series:
 - a single 4xx is valid to return for that series
 - fewer than [quorum] succesful results means a 5xx for that series

Across the whole request:
 - all series succeeded - return 2xx
 - one or more 5xx - return 5xx
 - one or more 4xx and no 5xx - return 4xx

**Comment by bboreham** [comment]
It is sub-optimal that in the "mixed result" case the sender will retry everything.  The remote write protocol could be enhanced to return which subset need retrying.  Though I suspect this is more work than it deserves.

**Comment by alanprot** [comment]
Yeah... I'm just a little concerned about the change in behaviour here.

Nowadays if 1 ingester (for a given series) return 4xx and the other 2 returns 2xx, cortex will return 2xx.

With the proposed change, it will return 4xx, right?

**Comment by bboreham** [comment]
> Nowadays if 1 ingester (for a given series) return 4xx and the other 2 returns 2xx, cortex will return 2xx.
> With the proposed change, it will return 4xx, right?

Yes.  For all the cases I can imagine (e.g. limit is 1000 and one ingester has 1001 series while the other two have 999), it makes no practical difference.

However I could be failing to imagine something important.

**Comment by alanprot** [comment]
@pracucci @tomwilkie Any thoughts about this?

**Comment by pracucci** [comment]
> Nowadays if 1 ingester (for a given series) return 4xx and the other 2 returns 2xx, cortex will return 2xx.

Following this example, I think that if the quorum is reached if the other 2 returns 2xx and so Cortex should return 2xx.

**Comment by alanprot** [comment]
@pracucci For sure, that's the case on both solution... 
but the question is, should we return 4xx on the first 4xx from ingesters or should we wait for a quorum of 4xx?

**Comment by alanprot** [comment]
Just as information those are the possible 4xx erros that can happen on the Push ([ingesterV2](https://github.com/cortexproject/cortex/blob/master/pkg/ingester/ingester_v2.go#L822)):

```
storage.ErrOutOfBounds
storage.ErrOutOfOrderSample
storage.ErrDuplicateSampleForTimestamp
errMaxSeriesPerUserLimitExceeded
errMaxSeriesPerMetricLimitExceeded
errExemplarRef
```

**Comment by bboreham** [comment]
Thanks Alan.  For all of those case ingester A can accept the sample while ingester B rejects, depending on whether A missed some earlier sends.

I argue that it is not important whether we send 400 back to the user in these cases, when just one ingester rejects a sample: 
 - Nothing different happens in Cortex - the two ingesters will persist the data and return it for queries
 - The sender will output a log message.  This is fine - the user must be close to some limit or problemmatic scenario.

Given that the exact state of each ingester depends on which previous sends have arrived, I don't think changing the behaviour to depend on which ingester responds first with 4xx is material.

**Comment by alanprot** [comment]
> You called status.FromError() which is probably ok given current usage, but would need to go onto the description of DoBatch that error results from the callback must conform to such an interface.

So add a documentation in the DoBatch function? Or you wanna change the DoBach callback to return a well defined type? Something like:
```
callback func(InstanceDesc, []int) error TO callback func(InstanceDesc, []int) Status
```

> Can we distinguish a solid return from a timeout / failed to talk ? 
 
We could get another counter for "Unknown" - this is the bucket where timeouts will fall into. But this will make the code even more complex with a third Counter. Im not sure if i see the point as timeouts are translated to 5xx anyway at the end of the day.


> Two error counters doesn't seem too bad (e.g. failed4xx and failed5xx); can't see why we would need a total if that is the sum of the others.

Fair.

> We don't need rpcsFailed; can do a select / err <- / default so we use the chan size to ensure we push max one error.

Make sense,  i just kept what was being done before...

**Comment by bboreham** [comment]
> So add a documentation in the DoBatch function?

Yes, a comment.

**Comment by alanprot** [comment]
Hi @bboreham 

I tried to make the code a little cleaner on https://github.com/cortexproject/cortex/pull/4388/commits/2c3cccecf3ff6d3886ab14a0cfeff7ad7ecf95a3 but unfortunately i cannot get rid of the "remaining" field because of concurrency.

>  can't see why we would need a total if that is the sum of the others.

In other words, if i get the total (or remaining) from the other counters , i can get an already modified value from another go routine causing inconsistent result. I can make a commit without that and we can see that the tests fail.

About the "rpcsFailed" I don't really see why we need that but it was there since 4ever... maybe i'm not seeing something so I would prefer to keep it for now. (The error channel is used [here](https://github.com/cortexproject/cortex/blob/master/pkg/ring/batch.go#L102) so, seems fine..)
