### ISSUE TITLE
query all tenants at once

### ISSUE THREAD

**Issue by phin1x** [cortexproject/cortex#4408]
**Is your feature request related to a problem? Please describe.**
cortex supports multiple tenants ids in the X-Scope-OrgID header (if the feature is activated). at the moment you have to specify a explicit list of tenant ids in the header but you can't query all tenants at once.

we are using cortex for our kubernetes clusters where every namespace is a customer. at the moment we are using a modified version of the [prometheus auth](https://github.com/rancher/prometheus-auth) project from rancher to provide multi tenancy but this is a bit hacky. a cleaner solution would be that every namespace becomes a tenant in cortex. as an administrator we want to query all tenants but this would add much more complexity because we need to compute a list of all namespaces from all clusters.

**Describe the solution you'd like**
allow a user to query all tenants, for example with a wildcard (single *) in the  X-Scope-OrgID header or a second header in the http request (for example X-Scope-Administrator).

**Describe alternatives you've considered**

**Additional context**

**Comment by anjmao** [comment]
I also need something similar to display data from multiple tenants in single grafana dashboard. Maybe querier could be configured to understand multi tenant queries and add/remove tenantID labels. Also querier could allow to return labels with all known tenants for tenant dropdown variable eg:**(label_values(cortex_tenant_info))**
