### ISSUE TITLE
We're flushing virtually empty chunks in prod

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#448]
Somethings not right:

<img width="430" alt="screen shot 2017-05-30 at 11 47 01" src="https://cloud.githubusercontent.com/assets/444037/26580284/52d8b76a-452f-11e7-89e6-a294f8de332c.png">

50th percentile chunk length is ~10!

I suspect https://github.com/weaveworks/cortex/pull/415/files might be to blame.

**Comment by tomwilkie** [comment]
This also causes the ingesters to not shutdown cleanly, as they try and flush their flush queue after successfully transferring (which they shouldn't).

**Comment by aaron7** [comment]
Fixed by #449

**Comment by tomwilkie** [comment]
Worth keeping this open until we actually understand why we are doing this.

**Comment by bboreham** [comment]
What were the findings of the experiment to set the value to 1 hour?

**Comment by bboreham** [comment]
If the underlying series change a lot, e.g. in Kubernetes if you start and stop a lot of pods, you will get a lot of very short timeseries.

**Comment by bboreham** [comment]
Note the "event sampling" feature gives you raw data to understand why series are being flushed.

**Comment by bboreham** [comment]
I think this issue applies to a specific incident so long ago that we won't make any more progress; closing.
