### ISSUE TITLE
Chunks Storage (deprecated)

### ISSUE THREAD

**Issue by mrmagicli** [cortexproject/cortex#4482]
Excuse me, why deprecated chunks storage? If we use block storage, can you give me a plan which can use in local system? because we didn't buy cloud services.

**Comment by NiklasWagner** [comment]
I think [Minio](https://min.io/) is the recommended approach.

**Comment by pracucci** [comment]
> I think Minio is the recommended approach.

Correct. If you're just running it for testing on a single machine, then you can also use the `filesystem` backend storage (`-blocks-storage.backend=filesystem`).

**Comment by till** [comment]
I am in a similar boat: We are converting from chunks (`v1.1.0`) to blocks (`v1.10.0`) right now and it seems that an index for chunks is somewhere in a boltdb. And we can't display data over the past week (from before the upgrade). Any hints what to convert, or how to force Cortex to rebuild the index? Data wasn't deleted, we just can't query it anymore.
