### ISSUE TITLE
Flake in TestPurger_Metrics()

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#4513]
https://github.com/cortexproject/cortex/pull/4511/checks?check_run_id=3768593384
```
--- FAIL: TestPurger_Metrics (2.40s)
    purger_test.go:438: expected 0, got 172800
FAIL
FAIL	github.com/cortexproject/cortex/pkg/chunk/purger	40.455s
```

Note previous #2776, #2840

**Comment by aknuds1** [comment]
This also flaked for #4602, see [build](https://github.com/cortexproject/cortex/runs/4726617203?check_suite_focus=true).
