### ISSUE TITLE
Support other tracing provider other than Jaeger via OpenTelemetry

### ISSUE THREAD

**Issue by roystchiang** [cortexproject/cortex#4515]
**Is your feature request related to a problem? Please describe.**
Currently, Cortex only supports Jaeger as backend for tracing. I would like the ability to use other tracing providers such as AWS X-Ray.

**Describe the solution you'd like**
The current tracing client only supports Jaeger, while OpenTelemetry supports Jaeger and other tracing providers.

The integration with OpenTelemetry should be backward compatible in a way such that existing clusters using Jaeger do not have to run OpenTelemetry collectors.

**Describe alternatives you've considered**
Instead of integrating the tracing on Cortex, we submit PR for weavworks/common where tracing is currently configured. I wanted to see what the maintainers' opinions are.

**Comment by alvinlin123** [comment]
Feature still wanted.

**Comment by alanprot** [comment]
We have a OTEL bridge now: https://cortexmetrics.io/docs/guides/tracing/
