### ISSUE TITLE
Running Cortex on Kubernetes

### ISSUE THREAD

**Issue by charannaik** [cortexproject/cortex#4535]
![image](https://user-images.githubusercontent.com/17873898/138225464-7974cbbb-45e6-4d54-b1aa-0b1df0a4fc2b.png)

The rolling update strategy with maxSurge, maxUnavailable does not apply to the statefulsets and hence not applicable to ingesters.

**Comment by charannaik** [comment]
Reopening. Need clarification on the reported.

**Comment by alanprot** [comment]
This seems odd indeed.
Maybe we should to replace that with the PDB documentation.

https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/ingester/ingester-poddisruptionbudget.yaml

**Comment by kd7lxl** [comment]
> Maybe we should to replace that with the PDB documentation.

PDBs and update strategies apply to different cases. PDBs only apply in the context of node maintenance, like draining a node. The rollout policy applies to rolling out changes to the pod spec. For high availability, both policies must be in place. It makes sense for them to have corresponding policies, like each specifying `maxUnavailable: 1`.

**Comment by alvinlin123** [comment]
> Reopening. Need clarification on the reported.

I just learned that the document in question was written assuming `Deployment`; may be even before `Statefulset` was available in k8s. That's why it talks about `maxUnavailable` and `maxSurge`
