### ISSUE TITLE
Blocks Storage docs "Local Filesystem" links to a 404

### ISSUE THREAD

**Issue by joelhoisko** [cortexproject/cortex#4556]
On the [Blocks Storage](https://cortexmetrics.io/docs/blocks-storage/) page the link to "Local Filesystem" links to a [Thanos  404 page](https://thanos.io/storage.md/#filesystem). Maybe it's supposed to link to [these docs](https://thanos.io/tip/thanos/storage.md/#filesystem) instead?

**Comment by bboreham** [comment]
Sounds likely - do you want to make a PR to fix it?
