### ISSUE TITLE
Unable to delete rules from ruler

### ISSUE THREAD

**Issue by mac133k** [cortexproject/cortex#4575]
**Describe the bug**
For some reason it is not possible to delete rules (alerting or recording) from ruler. This however only applies to the rules that are one and only in the namespace/group. In other words if I create 2 rules in a namespace, I can delete one of them and that is it - when I try to delete the last one I get the error:

`Error: {"status":"error","data":null,"errorType":"server_error","error":"Access Denied."}
`

Rules can be created without any problems from Grafana alerting dashboard (unified alerting mode) or directly via ruler API (I use curl). Deletion attempts fail in the same way using both methods - the above error is shown. Debug logging is enable on the ruler's host and the logs show the same:

attempt with Grafana:

`Nov 30 14:23:48 node2 cortex: level=warn ts=2021-11-30T14:23:48.170054987Z caller=logging.go:72 traceID=10087272f7b88921 msg="DELETE /api/prom/rules/alerting/alerting (500) 1.650067ms Response: \"{\\\"status\\\":\\\"error\\\",\\\"data\\\":null,\\\"errorType\\\":\\\"server_error\\\",\\\"error\\\":\\\"Access Denied.\\\"}\" ws: false; Accept-Encoding: gzip; User-Agent: Grafana/8.2.5; X-Scope-Orgid: test-org1; "`
 
attempt with curl:

```
Nov 30 14:24:51 node2 cortex: level=debug ts=2021-11-30T14:24:51.808131537Z caller=bucket_client.go:259 msg="deleting rule group" user=test-org1 namespace=alerting key="YWxlcnRpbmc=/YWxlcnRpbmc="
Nov 30 14:24:51 node2 cortex: level=error ts=2021-11-30T14:24:51.809393865Z caller=bucket_client.go:262 msg="unable to delete rule group from namespace" user=test-org1 namespace=alerting key="YWxlcnRpbmc=/YWxlcnRpbmc=" err="Access Denied."
Nov 30 14:24:51 node2 cortex: level=warn ts=2021-11-30T14:24:51.809474251Z caller=logging.go:72 traceID=06b504b9d1afcd5b msg="DELETE /api/v1/rules/alerting (500) 6.990508ms Response: \"{\\\"status\\\":\\\"error\\\",\\\"data\\\":null,\\\"errorType\\\":\\\"server_error\\\",\\\"error\\\":\\\"Access Denied.\\\"}\" ws: false; Accept: */*; Content-Type: application/yaml; User-Agent: curl/7.58.0; X-Scope-Orgid: test-org1; "
```

**To Reproduce**
1. Add a new namespace with 1 rule: rule1.
2. Try to delete rule1: access denied error.
3. Add one more rule to the namespace: rule2
4. Try to delete rule1: success.
5. Try to delete rule2: access denied error.

**Expected behavior**
I expected deletions to work every time.

**Environment:**
 - Infrastructure: VMs with CentOS7, each Cortex service runs on a dedicated host, Minio storage for metrics, rules, alert configs.
 - Deployment tool: Ansible using Cortex role from Cloud Alchemy

**Storage Engine**
- Blocks

**Additional Context**

Ask me.

**Comment by um3ggh1u** [comment]
It looks like a problem with the S3 backend (Access Denied). Do you have enough privileges to perform that deletion?

**Comment by mac133k** [comment]
@um3ggh1u was right - the missing permission on S3 was DeleteObject, although it was not that obvious, because it was affecting only the last rule in a namespace/group and deletions were possible otherwise. After granting that permission deletions started to work as expected.
