### ISSUE TITLE
Easier Way to Clean Unhealthy Instances from Ring

### ISSUE THREAD

**Issue by disfluxly** [cortexproject/cortex#4591]
**Is your feature request related to a problem? Please describe.**
The ring/memberlist can grow in size with Unhealthy instances, especially for Distributors. I just cleaned out 3300+ distributors from the distributor/ring that were "Unhealthy", all of which were from previous deployments. This seemed to be causing `handler queue full` errors in logs along with some memberlist timeouts, resulting from the size of the memberlist file being gossiped around the ring (also got better with the 1.11 changes to forward only changes)

**Describe the solution you'd like**
Short-Term Solution: Have a "Forget All Unhealthy" button/api that can be used to cleanup the rings when needed. Currently each instance has to be forgotten one at a time.

Long-Term Solution: Services should remove instances that haven't been healthy in X seconds from the ring/memberlist. This should be a toggle, perhaps enabled by default for distributors, and disabled by default for ingesters.

**Describe alternatives you've considered**
Currently running a script that deletes each Unhealthy instance from the ring one at a time.

**Comment by nikhil-nomula** [comment]
Thank you for creating this!

**Comment by disfluxly** [comment]
Just to add onto this, it appears that having all these unhealthy instances in the distributor ring causes some pretty bad CPU performance degradation. Here's some graphs across Cortex Services:

![image](https://user-images.githubusercontent.com/31159882/146577184-3cdf6c78-f29f-4ffc-80f1-4736bf1c0a38.png)

![image](https://user-images.githubusercontent.com/31159882/146577218-664dc0c6-4d19-4238-a4f8-55d2a8bb12d9.png)

![image](https://user-images.githubusercontent.com/31159882/146577296-b7fa27f0-5f10-426c-9577-8e1959f6212a.png)

![image](https://user-images.githubusercontent.com/31159882/146577414-00732fed-c206-4b8f-b8dd-662062e0aef9.png)

The far left side of the graph is when I started forgetting instances. I had to stop a few times in between (each plateau) because either my laptop went to sleep or I lost VPN. The right side is when all Unhealthy instances have been removed. Good news is that I can downsize my cluster quite a bit now and save quite a bit of cash I guess...

Of note, there was no change in the number of writes per second we were getting, or the number of queries we were getting, that would impact the CPU. In addition, this is after we had already moved to Cortex 1.11. Memory does not seem impacted.

**Comment by bboreham** [comment]
The "long-term" part is discussed at length in #1521; let's not fork the conversation.
I felt the idea of a "forget all unhealthy" button was a reasonable and simple improvement.

Also I will mention there have been some optimisations in the memberlist code recently, e.g. https://github.com/grafana/dskit/pull/76
