### ISSUE TITLE
How to implement metrics & visualize in Grafana without Promethues, Only using Cortex?

### ISSUE THREAD

**Issue by harshasrimal** [cortexproject/cortex#4593]
Currently we implemented metrics with Prometheus, Cortex and Grafana in a kubernetes environment. We have visualized metrics in Grafana using Prometheus data-source by using cortex-query-frontend-headless service. We have integrated Cortex in the Prometheus helm chart by using a remote_write url

```
remote_write:
    url: http://cortex.cortex/api/prom/push
```

Is there any way to visualize metrics in Grafana for a sample application without using Prometheus, only using Cortex? If No why Prometheus is required? ,If Yes please mention a document,

**Comment by pstibrany** [comment]
Cortex doesn't scrape metrics from targets. There must be some other process that *writes* data to Cortex. Prometheus or Grafana Agent are common sources of such data, but there are others too.

**Comment by harshasrimal** [comment]
Thank you @pstibrany  for you quick response.

**Comment by alvinlin123** [comment]
Looks like the question is answered, so I will go ahead and close this issue; feel free to re-open if this is not the case.
