### ISSUE TITLE
Cortex - S3 and data replication

### ISSUE THREAD

**Issue by andygr** [cortexproject/cortex#4598]
Hello,

I configured Cortex, Grafana and Prometheus in local docker environment. I connected Prometheus and Cortex to Grafana and I was able to see metrics from both.

However in S3 I can't see any folder or file (was waiting for more than 3 hours). 
If I create a folder in S3 bucket, I will be able to see the folder in Cortex docker /data/cortex/tsdb-sync/.

I don't know why I am able to see files or folders from S3 to Cortex but not the other way around.

My Cortex config is the following, any comment or suggestion would be much appreciated:

`
auth_enabled: false

server:
      http_listen_port: 9009
      grpc_server_max_concurrent_streams: 1000
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      
distributor:
      pool:
        health_check_ingesters: true
      shard_by_all_labels: true

ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600

ingester:
      lifecycler:
        final_sleep: 0s
        join_after: 0s
        num_tokens: 512
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      max_transfer_retries: 0

frontend:
      log_queries_longer_than: 10s
      
frontend_worker:
      match_max_concurrent: true
      
limits:
      enforce_metric_name: false
      max_query_lookback: 0s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
querier:
      active_query_tracker_dir: /data/cortex/querier
      query_ingesters_within: 12h
      store_gateway_addresses: dns+cortex-store-gateway.monitoring:9095
query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          memcached:
            expiration: 1h
          memcached_client:
            timeout: 1s
      split_queries_by_interval: 24h

 ruler:
      enable_api: true
      enable_sharding: false
      storage:
        type: local
        local:
           directory: /data/rules

store_gateway:
      sharding_enabled: false
      sharding_ring:
        kvstore:
          store: inmemory

storage:
      engine: blocks
      index_queries_cache_config:
        memcached:
          expiration: 1
        memcached_client:
          timeout: 1s
      
          
blocks_storage:
      tsdb:
        dir: /data/cortex/tsdb
      bucket_store:
        sync_dir: /data/cortex/tsdb-sync
      backend: s3
      s3:
        bucket_name: <omitted>
        endpoint: s3.eu-west-1.amazonaws.com
        access_key_id: <omitted>
        secret_access_key: <omitted>

ruler_storage:
    backend: s3
    s3:
      bucket_name: <omitted>
      endpoint: s3.eu-west-1.amazonaws.com
      access_key_id: <omitted>
      secret_access_key: <omitted>

alertmanager_storage:
    backend: s3
    s3: 
      bucket_name: <omitted>
      endpoint: s3.eu-west-1.amazonaws.com
      access_key_id: <omitted>
      secret_access_key: <omitted>

chunk_store:
      chunk_cache_config:
        memcached:
          expiration: 1h
        memcached_client:
          timeout: 1s
    
compactor:
      data_dir: /tmp/cortex/compactor
      sharding_ring:
        kvstore:
          store: inmemory

`

**Comment by alanprot** [comment]
I believe that the blocks will be flushed to s3 only if they have more than 3 hours from the first sample to the last sample in the head.

```
/ compactable returns whether the head has a compactable range.
// The head has a compactable range when the head time range is 1.5 times the chunk range.
// The 0.5 acts as a buffer of the appendable window.
func (h *Head) compactable() bool {
	return h.MaxTime()-h.MinTime() > h.chunkRange.Load()/2*3
}
```
