### ISSUE TITLE
Frontend: Parameter 'LogQueriesLongerThan' does not behave as described in the docs

### ISSUE THREAD

**Issue by matej-g** [cortexproject/cortex#4610]
Hello :wave: 

At Thanos, we have noticed that the `LogQueriesLongerThan` does not behave as is described in the docs:
`Log queries that are slower than the specified duration. Set to 0 to disable. Set to < 0 to enable on all queries.` 

In particular, setting the parameter to < 0 does not make it to log all queries, it actually disables logging (quick glance at the code seem to confirm this). 

What is the correct way to handle this? Should the functionality be adjusted to adhere to the docs or should the docs be amended to describe current behavior?

**Comment by alanprot** [comment]
I think it may be ok to change the behavior to log everything if < 0 as the default value is 0 and anybody that changed this to be < 0 was trying to enable the logs on all queries. Thoughts @alvinlin123 @bboreham ?

**Comment by alvinlin123** [comment]
Yes I agree, this sounds like a bug and we should fix the code to do what document says.

**Comment by matej-g** [comment]
Thanks for chiming in, a opened a quick PR to fix this https://github.com/cortexproject/cortex/pull/4633.

**Comment by alanprot** [comment]
Gotcha... So what you recommend? Change the `query-stats-enabled` to be subject to `LogQueriesLongerThan` and fix the `LogQueriesLongerThan` behaviour? I think the main thing about `query-stats-enabled` is to return the stats info in the response header, not to log the queries itself, so maybe they should just be unrelated nobs.
