### ISSUE TITLE
err=googleapi: Error 403: Provided scope(s) are not authorized, forbidden -Logs from cortex Ingester Pod

### ISSUE THREAD

**Issue by manju-priyadharshini** [cortexproject/cortex#4627]
**Describe the bug**
The Ingester is not able to push the metrics into gcs bucket.

**To Reproduce**
1. Start Cortex (1.10.0)
2. Push metrics from cortex api (/api/prom/push)

**Expected behavior**
The metrics is not persisted to gcs bucket, ingester throws exception.
**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [helm]

**Storage Engine**
 [ ] Chunks

**Additional Context**
engine: chunks
    gcs:
      # Name of GCS bucket. Please refer to
      # https://cloud.google.com/docs/authentication/production for more information
      # about how to configure authentication.
      # CLI flag: -gcs.bucketname
      bucket_name: cortexpoc
      # The size of the buffer that GCS client for each PUT request. 0 to disable
      # buffering.
      # CLI flag: -gcs.chunk-buffer-size
      chunk_buffer_size: 0
      # The duration after which the requests to GCS should be timed out.
      # CLI flag: -gcs.request-timeout
      request_timeout: 0s
      # Enabled OpenCensus (OC) instrumentation for all requests.
      # CLI flag: -gcs.enable-opencensus
      enable_opencensus: true

Log Lines:

level=error ts=2022-01-18T09:14:33.367577347Z caller=flush.go:267 org_id=xxxxxxx msg="failed to flush user" err="googleapi: Error 403: Provided scope(s) are not authorized, forbidden"

**Comment by roobalimsab** [comment]
Hi, I am also facing the same issue in all my cortex pods. Getting 403 while communicating with gcs. Can you share how you fixed it?
