### ISSUE TITLE
Distributor zone awareness support

### ISSUE THREAD

**Issue by danfromtitan** [cortexproject/cortex#4639]
Do distributors support zone awareness ? 

The [zone aware replication page](https://cortexmetrics.io/docs/guides/zone-aware-replication/) seems to suggest so, but the [Cortex configuration page](https://cortexmetrics.io/docs/configuration/configuration-file/) doesn't have any mention of zone awareness in distributor config section.

**Comment by danfromtitan** [comment]
There is no distributor zone-awareness-enabled Config [as the document suggests](https://cortexmetrics.io/docs/guides/zone-aware-replication/#distributors--ingesters-time-series-replication).

**Comment by alanprot** [comment]
What would be zone-awareness for distributors?

Zone awareness makes more sense when we need quorum right? 
On ingester we need quorum to succeed a write for instance.

Distributor does not hold any state that need to be relocated.

Maybe what you want to achieve is to spread your distributors across all azs? If so and you are using k8s, seems that pod topology is what you wanna: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
