### ISSUE TITLE
Does Cortex query rolled up timeseries?

### ISSUE THREAD

**Issue by veeralpatel-opsramp** [cortexproject/cortex#4650]
I'm a beginner to Prometheus and Cortex.

I was wondering, let's say:

1. I have timeseries A of resolution 1 second
2. I then create a roll up rule to roll up A into a new timeseries B of resolution 1 hour

Now, let's say I make a last 48 hours aggregation query on timeseries A in Cortex.

1. Will Cortex automatically query B for me instead of A? If so do you know where the code for this is?
2. Now let's say I don't create timeseries B. Will Prometheus or Cortex automatically roll up A for me into a higher resolution timeseries and query it?

If this is implemented in Prometheus, not Cortex, would still be really interested in getting the answer!

**Comment by bboreham** [comment]
No, that's not implemented.  See #4322 which I think is similar.
