### ISSUE TITLE
Documentation: Spelling / Typo

### ISSUE THREAD

**Issue by feathered-path** [cortexproject/cortex#4657]
Hello, 
I attached the snippet from the https://cortexmetrics.io/docs/architecture/ docs below where the word `loses` was implied but `looses` was used.  NOT A BIG DEAL! Just thought, maybe someone would want to know.  Have a great day!

Replication
Write-ahead log (WAL)
The replication is used to hold multiple (typically 3) replicas of each time series in the ingesters. If the Cortex cluster **_looses_** an ingester, the in-memory series hold by the lost ingester are also replicated at least to another ingester. In the event of a single ingester failure, no time series samples will be lost while, in the event of multiple ingesters failure, time series may be potentially lost if failure affects all the ingesters holding the replicas of a specific time series.

**Comment by friedrich-at-adobe** [comment]
thank you for reporting!
