### ISSUE TITLE
memory cost 

### ISSUE THREAD

**Issue by mrmagicli** [cortexproject/cortex#4661]
**Describe the bug**
As you know, we use cortex to scale up our prometheus. I found that we collected more than 30 millions series now.  However, the memory cortex cost more than 500G. Can somebody give me a method to reduce memory cost?

I have set max_chunk_age as 30m already.

**Environment:**
 - Infrastructure:  bare-metak

**Storage Engine**
-  Chunks

**Comment by friedrich-at-adobe** [comment]
Chunks is deprecated. If you are thinking about improving costs, your best bet is migrating to blocks storage as you can potentially save 60% in costs.
