### ISSUE TITLE
Mysterious flush of underutilised chunks 1hr after ingester rollout

### ISSUE THREAD

**Issue by awh** [cortexproject/cortex#467]
On the 15th of June:
![screenshot from 2017-06-19 17-23-20](https://user-images.githubusercontent.com/1504438/27295498-13ea51d0-5515-11e7-8d8c-2de8b93238b2.png)

On the 19th of June:
![screenshot from 2017-06-19 17-23-33](https://user-images.githubusercontent.com/1504438/27295513-1ff314b2-5515-11e7-8fcd-2e25cbcdf091.png)

Both of these happened approximately one hour after an ingester upgrade in which chunks were successfully transferred from terminating ingesters. Chunk max idle is 1h, possibly related?

CC @tomwilkie any thoughts?

**Comment by tomwilkie** [comment]
Do you know if these are spurious?  Or did 800k/3 timeseries stop being
written to?

**Comment by awh** [comment]
Oh - could those be series from metrics related to the ingesters which have now gone away?

**Comment by awh** [comment]
Querying for `{job="cortex/ingester"}` returns only 1406 time series.

**Comment by tomwilkie** [comment]
I assume this was part of a rolling upgrade of all of cortex?  What does `count({job=~"cortex/.*"})` return?

**Comment by awh** [comment]
9862, and no, in both cases it was just the ingester that was rolled out (in the first instance we had upgraded all of cortex but delayed the ingester whilst we understood #458, and in the second instance we only needed to do the ingester to deploy #460)

**Comment by awh** [comment]
It's almost like the state reconstructed from transferred chunks in the new ingesters is not identical to that in the old, and so they are making different decisions about what should be flushed...

**Comment by awh** [comment]
This is also happening on rolling reboots.

**Comment by leth** [comment]
As @awh said, we just had a single ingester replaced, due to a node reboot, and the queue peaked at 600K

**Comment by leth** [comment]
I've been doing a bit of digging into the code around transferring chunks.

It looks like all chunks are transferred to a new ingester which was found in the PENDING state.
However whether this is the correct ingester to transfer to depends on whether

**Comment by leth** [comment]
Oops

**Comment by leth** [comment]
I had a brainwave last night; during ingester handover the old and new ingesters are no longer in `ACTIVE` state, so [the distributor will pick an extra ingester](https://github.com/weaveworks/cortex/blob/master/pkg/ring/ring.go#L184), which was not selected before the handover started.
After the handover has finished, it will return to selecting ingester covering the original part of the ring (the new ingester), and the extra ingester will no longer be selected.
After $idleChunkTime the extra ingester will flush these idle chunks.

**Comment by leth** [comment]
To prevent the ingester picker from picking a temporary node (and allow N concurrent upgrades), we'd need to ensure `replication - quorum - N > 1`, and allow the picker to select fewer nodes during a handover (`quorum < X < replication`).

**Comment by tomwilkie** [comment]
Good catch!

We can work round this by including leaving ingesters in the N, but not
writing to them, as you suggest. Should be an easy fix.

**Comment by awh** [comment]
Aye, good spot :clap:
