### ISSUE TITLE
Is that possible to query for the “raw” data within a time range with exact ingested time stamps without considering arbitrary step for range queries

### ISSUE THREAD

**Issue by venkatchinmay** [cortexproject/cortex#4690]
**feature request**
Hi, I would like to retrieve data AS it was collected and recorded by cortex.
I do not want to use an **arbitrary step** for range queries.

**solution**
I need a **“raw”** data within a time range with exact ingested time stamps 

@pracucci - could you please help 
If it is possible to get, so how ?
if it is not possible why ? and suggest any alternative

**Comment by pracucci** [comment]
You could consider using the remote read API `POST <prometheus-http-prefix>/api/v1/read` to read the raw samples.

**Comment by venkatchinmay** [comment]
thanks @pracucci for quick reply 
https://cortexmetrics.io/docs/api/#remote-read
does it supported for cortex directly or **did we need to add any additional configuration** 
could you please help on this
