### ISSUE TITLE
Cortex is not getting deployed on in OKE Cluster(in Oracle Cloud Infra).

### ISSUE THREAD

**Issue by kadursandy** [cortexproject/cortex#4728]
Cortex is not getting deployed on in OKE Cluster(in Oracle Cloud Infra). We use 3 worker nodes with ARM based architecture.

K8S Cluster Version "v1.22.5"
Helm Chart "1.3.0"
Cortex Version: v1.11.0

Pre-requisite: OKE cluster with 3 worker nodes (ARM architecture/processor).OCI CLI and Kubectl configured for cluster access.

**To Reproduce**
1. Helm Install - helm install cortex --namespace cortex -f cortex-values.yaml cortex-helm/cortex --version 1.3.0
2. Kubectl get all -n cortex

**Expected behavior**
All the Cortex micro services to be up and running without any issues.

**Environment:**
 - Infrastructure: OKE(K8S v1.22.5)
 - Deployment tool: Helm chart v1.3.0

**Storage Engine**
- [X] Blocks

**Additional Context**
All the pods are gone to "crashloopbackoff" state. 
Question:
1.  Is Cortex architecture dependant, Does it support x86 arch only on worker nodes?
2. Does is support arm64 arch/processor on worker nodes?
3. if support for arm64 is not there, then when will the support come in . 

Please let me know. OCI OKE clusters supports both arm64 and x86_64 based processors on worker(compute) nodes.

**Comment by alanprot** [comment]
What is the error?
What docker image are you using? I don't think cortex build arm images yet.

**Comment by kadursandy** [comment]
Image: quay.io/cortexproject/cortex:v1.11.0
pod status: CrashLoopBackOff
Error: There is no specific error in logs/describe/events, message Back-off restarting failed container is there.

**Comment by chillaxd** [comment]
Yes, by default there is no cortex arm docker image. But you can build your own. 
You can check chiranjitdatta/cortex-arm64:v1.11.0 for cortex arm binary version of v1.11.0 which I have built.
