### ISSUE TITLE
Cortex get lots of error every 2 hours

### ISSUE THREAD

**Issue by sockyone** [cortexproject/cortex#4742]
**Describe the bug**
We are monitoring our error code return from Cortex. We realize that every 2 hours, the error rate is very high and delayed our data. I don't think this is because of remoteWrite protocol. Is it Cortex job or something?

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm chart

**Storage Engine**
- [x] Blocks
![image](https://user-images.githubusercontent.com/35925547/170434854-518cdedd-7f15-4603-80ab-0681b9ff0e4d.png)

**Comment by alanprot** [comment]
Can you share the logs from distributor or the responde body? 
 This may give some clues

**Comment by sockyone** [comment]
@alanprot it's almost code 500, and code 400. I can't find more helpful logs.
It's timed-out and out-of-order sample errors, but why does it only happens every 2 hours?
![image](https://user-images.githubusercontent.com/35925547/170438870-6edb8c68-3b68-46ee-bbfb-e8d580cd9cfe.png)

**Comment by alanprot** [comment]
Every 2 hours (assuming 2 hours blocks) ingester should be comparing the head (creating a new block).. this may cause ingester to uses more resource (cpu,disk) and maybe timeouts ? Can u check ingesters cpu during that time ?

**Comment by sockyone** [comment]
> Every 2 hours (assuming 2 hours blocks) ingester should be comparing the head (creating a new block).. this may cause ingester to uses more resource (cpu,disk) and maybe timeouts ? Can u check ingesters cpu during that time ?

One of theme has high cpu usage (4cores). I also increase it but after cortex restart, error rates increase and never decrease. I'm unable to recover the cluster, data always delay. (image 2).
Is there any trick for tuning Cortex cluster, or any monitoring tools for Cortex? 
![image](https://user-images.githubusercontent.com/35925547/170444263-e7566bae-18d7-4728-99a0-501209c8651b.png)
![image](https://user-images.githubusercontent.com/35925547/170469975-a8cb8811-f64a-4661-b638-418f7925c59d.png)

**Comment by TaylorMutch** [comment]
Something I ran into was networking bottlenecks within the Kubernetes cluster I was running into. Updating to a faster CNI (instead of kube-proxy) helped solve my "every 2 hours my distributor breaks" problem
