### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by 13881802223** [cortexproject/cortex#4764]
**Describe the bug**

**To Reproduce**
1. Start Cortex (SHA or version)
2. Perform Operations(Read/Write/Others)

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Storage Engine**
- [ ] Blocks
- [ ] Chunks

**Additional Context**

**Comment by jeromeinsf** [comment]
Hi

**Comment by alvinlin123** [comment]
Hi, how are you. 

I thank you for your kindness to hello us, but I will close this issue for now because I believe @jeromeinsf 's `HI` addresses your `Hello`;  the ping round-trip is completed. 

Feel free to reopen if `HI` was the wrong response to your `Hello` ping.
