### ISSUE TITLE
Ruler doesn't report success/failure of rule evaluation

### ISSUE THREAD

**Issue by jml** [cortexproject/cortex#477]
This is partly due to the underlying Prometheus library API. We should at least suggest some upstream changes. 

Having this information would make debugging issues in a running cortex deployment much easier.

**Comment by leth** [comment]
Prometheus does expose a metric: `prometheus_rule_evaluation_failures_total`

**Comment by jml** [comment]
This would naturally fall out of https://github.com/weaveworks/cortex/issues/310#issuecomment-327781080

Probably we can just put the prometheus metrics in our dashboards, making this not a Cortex bug.

**Comment by jml** [comment]
Would love to do this, but 
 1. am obviously not doing it
 2. less likely to get to this with recent changes
