### ISSUE TITLE
Missing -ingester-client.expected-timeseries flag in config file

### ISSUE THREAD

**Issue by jakubgs** [cortexproject/cortex#4810]
**Describe the bug**
This document describes the `-ingester-client.expected-timeseries` flag:

>### `-ingester-client.expected-timeseries`
>
>When push requests arrive, pre-allocate this many slots to decode them. Tune this setting to reduce memory allocations and garbage. This should match the `max_samples_per_send` in your `queue_config` for Prometheus.

Which appears to be a real flag:
https://github.com/cortexproject/cortex/blob/4e9fc3a2b5ab6a76787d59eb441f3af2765f1de8/pkg/cortexpb/timeseries.go#L48

But I was unable to find this flag in the config file syntax:
https://cortexmetrics.io/docs/configuration/configuration-file/

Either I'm blind, or it's just not available. I did try putting `expected_timeseries` inside of `ingester_client` section, but it failed.

I'm struggling to tune my setup to avoid ever increasing `prometheus_remote_storage_shards_desired`, and this setting seemed like a sensible place to start.

**Comment by friedrichg** [comment]
It's mentioned in [arguments](https://cortexmetrics.io/docs/configuration/arguments/) 

Prealloc is hidden, so you won't be able to configure it via config.file
https://github.com/cortexproject/cortex/blob/70f1ea2645e068ad29163e1f75183940a88143ff/pkg/cortex/cortex.go#L106

This config would affect pushes between distributor and ingester. Not the traffic between prometheus and distributors.

`prometheus_remote_storage_shards_desired` increasing can have many reasons. Any error 5xx or high latency coming from distributors would trigger an increase (among others) . For example, lack of cpu and memory resources in distributors can cause this.

It might be also that prometheus has many timeseries to send, so increasing [max_shards](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) is simply the sensible thing to do.

Also use prometheus latest version, as that can increase the performance for all of this.

**Comment by jakubgs** [comment]
>This config would affect pushes between distributor and ingester. Not the traffic between prometheus and distributors.

I understand that. That's what I wanted to try.

None of the reasons you listed actually explain what's happening with my setup. I'm using latest Cortex and latest Prometheus and despite that prometheus desired shards keep increasing, and then suddenly drop(sometimes):

![image](https://user-images.githubusercontent.com/2212681/182913922-8dd7baa2-c3fa-4ed8-9d08-19fd77cb1cda.png)

But despite that Prometheus stays on 20 (max) shards for some nodes:

![image](https://user-images.githubusercontent.com/2212681/182914013-f1fa0b41-7ec7-49a8-a898-f27b9796b88b.png)

And Cortex distributors ingesting metrics look fine with just few spikes in 400s:

![image](https://user-images.githubusercontent.com/2212681/182913860-6b28dd09-37b6-4c2c-9a4b-d31812ebab69.png)

While the load of both distributors and ingesters is also low, below 1.0, with hosts that have 2 CPUs:

![image](https://user-images.githubusercontent.com/2212681/182914189-8a548fed-c6fe-4e43-9b4b-ce07a40f8329.png)

So:

- Cortex cluster is not overloaded
- Distributors respond with 200s
- Desired shards grow and suddenly drop
- Used shards don't go down anyway

I have no idea what's happening.

**Comment by friedrichg** [comment]
Thanks for sharing more detail.

I noticed immediately you have sudden spikes from 1 to 20. You want to aim at a stable number of shards.

This is the config I used for most prometheus that push to cortex

```
remote_write:
- url: https://...
  queue_config:
    capacity: 5000
    max_samples_per_send: 1000
    max_shards: 20
    min_shards: 5
```

For larger prometheus, we do increase these numbers.

----
is one of the  prometheus getting severely delayed as well?

Use [PrometheusRemoteWriteBehind](https://github.com/prometheus/prometheus/blob/8207b132fd96f13639b220d46a4d6d47550af404/documentation/prometheus-mixin/alerts.libsonnet#L181-L201) from the mixin to check this.

**Comment by jakubgs** [comment]
I'm using:
```yaml
    queue_config:
      capacity: 5000
      min_shards: 2
      max_shards: 20
      max_samples_per_send: 1000
      # WARNING: Disable retries by setting minimum too high.
      min_backoff: 30d
      max_backoff: 30d
      batch_send_deadline: 10s
```
But I've tried MANY different configurations. I also described this in the issue I opened with Prometheus:

* https://github.com/prometheus/prometheus/issues/11116

I tried the formula you linked and there are indeed spikes, up to ~40:

![image](https://user-images.githubusercontent.com/2212681/183033400-921c00c3-3615-4198-8884-6a0648994ebf.png)

**Comment by jakubgs** [comment]
Those spikes kinda correlate with spikes in pending samples:

![image](https://user-images.githubusercontent.com/2212681/183033753-a05148a5-1e5c-489b-aca9-cf0a0a3e8418.png)

And also correlate with `sample-out-of-order` errors that ingesters show:

![image](https://user-images.githubusercontent.com/2212681/183033910-6b263fe3-ca98-4da1-977e-d5151b7f0272.png)

What does that mean?

* Prometheus is slow to send some samples and then retries, but fails since Cortex always rejects out of order samples?
* Cortex distributors are slow to send samples to ingesters so when they get to ingesters they get rejected as out of order?
* Possibly something else?

**Comment by friedrichg** [comment]
For backoff and retries, the recommended is:

```
    max_retries: 3
    min_backoff: 30ms
    max_backoff: 100ms
```

If you leave it empty, you will get defaults and those are normally ok. Disabling backoff is not recommended

- Prometheus retries won't generate out of order errors, it's expected that prometheus will send them in order. 
- At the same time, out of order errors are 4xx, they will not be retried by prometheus.

Questions
1. Are you using cortex prometheus [HA](https://cortexmetrics.io/docs/guides/ha-pair-handling/) ?
2. Do you have 2 or more prometheus pushing identical metrics?
3. Is one of the prometheus getting severely delayed (Alert PrometheusRemoteWriteBehind) ?
4. How many prometheus are sending to cortex? are all affected?

**Comment by jakubgs** [comment]
The `max_retries` setting has been removed some years ago and does nothing:

* https://github.com/prometheus/prometheus/pull/5649

I have seen endless stream of `out-of-order` errors from Prometheus so I disabled retries for that reason. Here's a graph:

![image](https://user-images.githubusercontent.com/2212681/183115172-f0a5bc1b-4934-4bba-bd6b-3003bb5e5549.png)

Ever since I've set `min_backoff` to 30 days I haven't seen these large volumes of discarded samples. So not sure if Prometheus is actually retrying things in order, because every time I'd restart an instance I'd see high volume of dropped samples.

>Are you using cortex prometheus [HA](https://cortexmetrics.io/docs/guides/ha-pair-handling/)?

No, I have one Prometheus instance per data center.

>Do you have 2 or more prometheus pushing identical metrics?

No.

>Is one of the prometheus getting severely delayed (Alert PrometheusRemoteWriteBehind)?

You can see the graph with the spikes in https://github.com/cortexproject/cortex/issues/4810#issuecomment-1206173370.

>How many prometheus are sending to cortex? are all affected?

Five in total sending to 2 distributors. If you're asking about about shards used or growing shards desired there are two instances targeting one of the distributors that have this issue. As for pending samples spikes it's mostly one Prometheus instnace, but not exclusively.

![image](https://user-images.githubusercontent.com/2212681/183116292-e299cbbd-9f33-4384-9bb5-7fd17d1d056a.png)

**Comment by friedrichg** [comment]
> The max_retries setting has been removed some years ago and does nothing:

I don't configure max_retries, I just pasted the defaults. Using a large backoff will only make your prometheus not retry. 
Not a good choice

> > Is one of the prometheus getting severely delayed (Alert PrometheusRemoteWriteBehind)?
> >
> You can see the graph with the spikes in https://github.com/cortexproject/cortex/issues/4810#issuecomment-1206173370.

The graph shows storage remote errors, it doesn't show if prometheus is getting delayed. Prometheus will normally retry temporary network/server errors without issues.

It's standard to tolerate up to 2 minutes of delay 

https://github.com/prometheus/prometheus/blob/8207b132fd96f13639b220d46a4d6d47550af404/documentation/prometheus-mixin/alerts.libsonnet#L191

If the prometheus is not getting severely delayed, this is not an important issue to investigate

---
If prometheus is indeed getting severely delayed then an investigation is due

If prometheus is receiving errors from cortex, the specific error will be in prometheus logs.
If there are no errors in prometheus logs, then the issue may be latency. 

Distributor latency can be viewed using the [writes](https://github.com/cortexproject/cortex-jsonnet/blob/main/cortex-mixin/dashboards/writes.libsonnet) dashboard

distributor latency should be below 100ms, per [playbook](https://github.com/cortexproject/cortex-jsonnet/blob/main/cortex-mixin/docs/playbooks.md#write-latency)

**Comment by friedrichg** [comment]
The flag -ingester-client.expected-timeseries is documented as an argument. That flag is also not the first thing to touch when debugging remote write issues.

I will close this issue because the initial question has been answered.

Feel free to ask more questions in cncf slack #cortex or via https://github.com/cortexproject/cortex/discussions

**Comment by jakubgs** [comment]
Thanks for explaining those things. I will continue investigating using relevant parts the write dashboard config you linked.
