### ISSUE TITLE
Get out of `io/ioutil` module because it is deprecated

### ISSUE THREAD

**Issue by alvinlin123** [cortexproject/cortex#4828]
I was working on https://github.com/cortexproject/cortex/issues/4817, and got bunch of lint error about `io/ioutil` is deprecated. I tried to fixed some while upgrading to Go 1.19, but there are just too many violations, so I will ignore https://staticcheck.io/docs/checks#SA1019 for now in `golangci.yml`, and come back to it later on.

https://pkg.go.dev/io/ioutil has info on which package to migrate to.

**Comment by yeya24** [comment]
As https://github.com/cortexproject/cortex/pull/4851 has been merged, are we ready to close this now?

**Comment by alvinlin123** [comment]
Argh, yes we should. I forgot to close it. Thanks for the reminder.
