### ISSUE TITLE
Cannot cleanly shut down an ingester without affecting querying

### ISSUE THREAD

**Issue by SuperMatt** [cortexproject/cortex#4838]
Is there any way to cleanly shut down an ingester without affecting querying?

Whenever I shutdown an ingester it moves into "LEAVING" state within the ingester ring, but the queriers still try to access data from them, and therefore in Grafana we see a message that the query could not be completed because it's in the stopping state.

Ideally when an ingester is in the leaving state, the queriers and distributors should not try to contact it, but this don't happen until it has completely finished and removes itself from the ring.

**Comment by alvinlin123** [comment]
Hi @SuperMatt do you have replication factor setup on distributor? If the distributor factor is 3, then a single ingester in LEAVING state should not cause the query call to fail, because distributor only need 2 out of 3 ingesters to be healthy to serve the query request.

**Comment by alvinlin123** [comment]
Oh, I also see that you have a discussion going on in the Slack channel :-) Is your question answered? May I go ahead and close this issue?

**Comment by SuperMatt** [comment]
I have closed the question, thanks.

**Comment by neoreddog** [comment]
For those who are experiencing a similar issue like me and want to see this slack discussion:
https://cloud-native.slack.com/archives/CCYDASBLP/p1662025070877609
