### ISSUE TITLE
recording rule in ruler can not generate new metrices

### ISSUE THREAD

**Issue by wolf666666** [cortexproject/cortex#4859]
**Describe the bug**
Several thousands of computers need to be monitored, and there are about 100 cpu cores in one computers, 
Some promQL can not be executed successfully as too much metric data, the result is always timeout, So i create some recording rules to improve the performance, but the recording rule also can not generate results. there are some error in the log files:
"level=error ts=2022-09-14T07:16:37.120161885Z caller=chunk_store.go:526 org_id=PC-001 traceID=6a79e21e8cbc0026 msg=\"error querying storage\" err=\"context deadline exceeded\""

Here is the recording rules stored in the ruler.
instance_recording_rules.yaml:
    - name: instance_rules
      interval: 15s
      rules:
        - record: instance:node_cpus:count
          expr: count(node_cpu_seconds_total{mode="idle"}) without (cpu,mode)
        - record: instance_mode:node_cpu_seconds:rate5m
          expr: sum(rate(node_cpu_seconds_total[5m])) without (cpu)
        - record: instance:node_cpu_utilization:ratio
          expr: sum(instance_mode:node_cpu_seconds:rate5m{mode!="idle"}) without (mode) / instance:node_cpus:count

**To Reproduce**
1. Start Cortex (1.10.0) (ingester, query, query frontend, destributer, ruler, etc)
2. push recording rule to the ruler

**Expected behavior**
the recording rule can generate new metrics successfully even there several TB metric data.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: [ansible]

**Additional Context**

**Comment by alvinlin123** [comment]
@wolf666666 would you be able to share the log from the Ruler? Did Ruler timeout evaluate queries ?
