### ISSUE TITLE
Error "out of bounds" after uploading data from future

### ISSUE THREAD

**Issue by kojderszymon** [cortexproject/cortex#4868]
**Describe the bug**
When data is sent (via remote_write) from the future to the Cortex (e.g., data two hours later or more), the Cortex stops accepting any current data. Errors appear in the logs: "err: out of bounds". This is most likely related to the inability to upload data older than an hour back (after uploading data from 2 hours ago, the current data is too old compared to the latest sample).

**Questions**
- Is there a way around the problem by uploading data from the future as another tenant or something like that?
- Is there a setting that will help me upload future data without restrictions?
- Is there a chance that this will be fixed in the future?

**Comment by alanprot** [comment]
That's because currently we can only append data to the tsdb head chunk. 

One thing you can try is to keep the head chunks open for more time tweaking this config

```
  # TSDB blocks range period.
  # CLI flag: -blocks-storage.tsdb.block-ranges-period
  [block_ranges_period: <list of duration> | default = 2h0m0s]
```

**Comment by friedrichg** [comment]
I think out of bounds is more related to data being too old, not about data in the future.
This issue is a duplicate of https://github.com/cortexproject/cortex/issues/2366
