### ISSUE TITLE
Templates in use are being removed by alertmanager cleanup logic

### ISSUE THREAD

**Issue by dpericaxon** [cortexproject/cortex#4888]
**Describe the bug**
With the implementation of Cortex with a sidecar, templates continuously get removed every 15seconds. Through a discussion on [slack](https://cloud-native.slack.com/archives/CCYDASBLP/p1664472167491769?thread_ts=1664388746.634659&cid=CCYDASBLP), the issue is that the `local` storage implementation doesn't fill in the `Templates` slice. So the cleanup logic marks all the templates as stale. 

**To Reproduce**
1. Deploy Helm Chart https://github.com/cortexproject/cortex-helm-chart
2. Follow the instructions [here](https://github.com/cortexproject/cortex-helm-chart/blob/a9df59bbb852ef8d19a69351ef006cf40d5ac764/docs/guides/configure_rules_via_sidecar.markdown) to set up the sidecar configuration for alertmanager.
3. Add some templates into configmaps that the sidecar is watching. It will mount those configmaps onto the filesystem and then within 15 seconds they will be deleted. 

**Expected behavior**
The cleanup logic should not delete templates in use.

**Environment:**
 - Infrastructure: Kubernetes(AKS)
 - Deployment tool: Cortex Helm Chart https://github.com/cortexproject/cortex-helm-chart

**Additional Context**
Our Configuration:
```
alertmanager:
  external_url: /api/prom/alertmanager
  enable_api: true
  data_dir: /data/
  storage:
    type : local
    local:
      path: /data
```

**Comment by alvinlin123** [comment]
Initial suspicions is that the [local storage implementation does not fill in the `Templates` slice of `alertspb.AlertConfigDesc` struct](https://github.com/cortexproject/cortex/blob/3df8097b71655baadd4db1390726c834582799ef/pkg/alertmanager/alertstore/local/store.go#L153), which is used to detect which template is in-use.

**Comment by alvinlin123** [comment]
We should cut a fix release for this bug.

**Comment by alanprot** [comment]
Hi..

Can you share where those templates files end up?

Lets say u have 2 users, with 1 templates each, seems that the folder structure should be:


```
/data/user1.yaml
/data/user1/templates/template-yyy-tpl
/data/user2.yaml
/data/user2/templates/template-xxx-tpl
```

Is that correct?
