### ISSUE TITLE
Support for "Out-of-order"

### ISSUE THREAD

**Issue by kojderszymon** [cortexproject/cortex#4895]
Is there any work related to support for "Out-of-order" samples planned (due to changes in Prometheus - https://github.com/prometheus/prometheus/pull/11075)?

**Comment by alvinlin123** [comment]
There is a similar issue in the backlog, and yes I think Cortex should support out of order samples. 

https://github.com/cortexproject/cortex/issues/2366

**Comment by wgliang** [comment]
+1
