### ISSUE TITLE
Not able to get IAM credentials with IMDSv1 

### ISSUE THREAD

**Issue by friedrichg** [cortexproject/cortex#4896]
**Describe the bug**
Cortex is not able get IAM credentials with IMDSv1 auth

**To Reproduce**
1. Ensure http://169.254.169.254/latest/api/token is not accessible for pods. (For example: using [kube2iam](https://github.com/jtblin/kube2iam))
2. Start container with IAM role with Cortex [e2cfc51](https://github.com/cortexproject/cortex/commit/e2cfc5130f837f3cb5aa0752123c3482a0df8912)

<details>
<summary>Click to expand!</summary>

```
$ /bin/cortex -blocks-storage.backend=s3 -blocks-storage.s3.bucket-name=bucket --target compactor --log.level=debug -blocks-storage.s3.endpoint=s3.dualstack.eu-west-1.amazonaws.com
level=info ts=2022-10-05T20:31:27.500222976Z caller=main.go:194 msg="Starting Cortex" version="(version=1.13.0, branch=master, revision=e2cfc51)"
level=info ts=2022-10-05T20:31:27.500504103Z caller=server.go:306 http=[::]:9009 grpc=[::]:9008 msg="server listening on addresses"
level=debug ts=2022-10-05T20:31:27.500922031Z caller=api.go:141 msg="api: registering route" methods=GET path=/config auth=false
level=debug ts=2022-10-05T20:31:27.501010322Z caller=api.go:141 msg="api: registering route" methods=GET path=/ auth=false
level=debug ts=2022-10-05T20:31:27.501028576Z caller=api.go:141 msg="api: registering route" methods=GET path=/debug/fgprof auth=false
level=debug ts=2022-10-05T20:31:27.501092732Z caller=api.go:141 msg="api: registering route" methods=GET path=/memberlist auth=false
level=debug ts=2022-10-05T20:31:27.501181221Z caller=api.go:141 msg="api: registering route" methods=GET,POST path=/compactor/ring auth=false
level=debug ts=2022-10-05T20:31:27.501209338Z caller=api.go:141 msg="api: registering route" methods=GET path=/services auth=false
level=debug ts=2022-10-05T20:31:27.501263744Z caller=module_service.go:54 msg="module waiting for initialization" module=compactor waiting_for=memberlist-kv
level=info ts=2022-10-05T20:31:27.501381946Z caller=module_service.go:64 msg=initialising module=server
level=debug ts=2022-10-05T20:31:27.501487025Z caller=module_service.go:54 msg="module waiting for initialization" module=memberlist-kv waiting_for=server
level=info ts=2022-10-05T20:31:27.501624576Z caller=module_service.go:64 msg=initialising module=memberlist-kv
level=debug ts=2022-10-05T20:31:27.501672565Z caller=module_service.go:54 msg="module waiting for initialization" module=compactor waiting_for=server
level=info ts=2022-10-05T20:31:27.501683884Z caller=module_service.go:64 msg=initialising module=compactor
level=info ts=2022-10-05T20:31:27.501896465Z caller=blocks_cleaner.go:144 component=cleaner msg="started blocks cleanup and maintenance"
level=error ts=2022-10-05T20:31:27.540353246Z caller=blocks_cleaner.go:155 component=cleaner msg="failed to run blocks cleanup and maintenance" err="failed to discover users from bucket: Access Denied"
level=info ts=2022-10-05T20:31:27.540381948Z caller=compactor.go:621 component=compactor msg="discovering users from bucket"
level=info ts=2022-10-05T20:31:27.540545681Z caller=cortex.go:422 msg="Cortex started"
```

</details>

3. Get access denied from s3

`
level=error ts=2022-10-05T20:31:27.540353246Z caller=blocks_cleaner.go:155 component=cleaner msg="failed to run blocks cleanup and maintenance" err="failed to discover users from bucket: Access Denied"
`

**Expected behavior**
it should continue without problem

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: jsonnet

**Additional Context**
It works in the previous commit [f550642](f55064269adc4eaf7f896f4ada1b311e9199aee3)

Previous
https://github.com/cortexproject/cortex/blob/f55064269adc4eaf7f896f4ada1b311e9199aee3/vendor/github.com/minio/minio-go/v7/pkg/credentials/iam_aws.go#L291-L298

Current
https://github.com/cortexproject/cortex/blob/e2cfc5130f837f3cb5aa0752123c3482a0df8912/vendor/github.com/minio/minio-go/v7/pkg/credentials/iam_aws.go#L291-L301

This bugfix https://github.com/minio/minio-go/pull/1682 is most likely the culprit

**Comment by alvinlin123** [comment]
@friedrichg I am curious about the use of disabling the IMDv2's session API? The reason I am asking is I want to make a case to have the minio revert/fix the bug fix :)

**Comment by alvinlin123** [comment]
@friedrichg this is resolved with your merge right?

**Comment by friedrichg** [comment]
yes, Thanks!
