### ISSUE TITLE
Removing the `_config` suffix from the index name on configuration doc page

### ISSUE THREAD

**Issue by songjiayang** [cortexproject/cortex#4908]
For example, when I first visit   https://cortexmetrics.io/docs/configuration/configuration-file/#server_config page, I will think the `server_config` is the right name rather than `server` , how about changing the document and  removing the `_config` suffix like [mimir](https://grafana.com/docs/mimir/latest/operators-guide/configure/reference-configuration-parameters/).

**Comment by friedrichg** [comment]
The idea is good, but I am afraid we could face license issues doing that
