### ISSUE TITLE
Add active series  metric to ingester stats page

### ISSUE THREAD

**Issue by songjiayang** [cortexproject/cortex#4917]
**Is your feature request related to a problem? Please describe.**
Now, the cortex ingester stats page  has some series yet, is it possible to add the `cortex_ingester_active_series` metric?

![image](https://user-images.githubusercontent.com/1459834/196029260-6532a2a5-f2d0-419e-9e01-4397af1d6eff.png)

**Comment by yeya24** [comment]
@songjiayang This would be a nice feature to have. Would you like to contribute?

**Comment by songjiayang** [comment]
very happy to.
