### ISSUE TITLE
Cortex goroutine panic

### ISSUE THREAD

**Issue by t00350320** [cortexproject/cortex#4922]
**Describe the bug**
One cortex node(1/3) paniced when write 15M series /30s. The process stopped (unkown error because we didn't write logs at that moment )  . Everytime it  throws out a panic at IterateAllChunks.

gcflags is added 
`
go build  -gcflags="all=-N -l" cmd/cortex/main.g
`  to build a new "cortex" binary in order to dig out the local variables.

(dlv) bt
 0  0x0000000000474ee1 in runtime.raise
    at /usr/local/go/src/runtime/sys_linux_amd64.s:168
 1  0x0000000000471320 in runtime.systemstack_switch
    at /usr/local/go/src/runtime/asm_amd64.s:436
 2  0x000000000043f6b0 in runtime.fatalthrow
    at /usr/local/go/src/runtime/panic.go:1044
 3  0x000000000043f471 in runtime.throw
    at /usr/local/go/src/runtime/panic.go:992
 4  0x0000000000455f16 in runtime.sigpanic
    at /usr/local/go/src/runtime/signal_unix.go:815
 5  0x000000000051fe2b in encoding/binary.bigEndian.Uint64
    at /usr/local/go/src/encoding/binary/binary.go:126
 6  0x0000000000b98265 in github.com/prometheus/prometheus/tsdb/chunks.(*ChunkDiskMapper).IterateAllChunks
    at /home/opensource/cortex/vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go:791
 7  0x0000000000f39252 in github.com/prometheus/prometheus/tsdb.(*Head).loadMmappedChunks
    at /home/opensource/cortex/vendor/github.com/prometheus/prometheus/tsdb/head.go:631
 8  0x0000000000f370de in github.com/prometheus/prometheus/tsdb.(*Head).Init
    at /home/opensource/cortex/vendor/github.com/prometheus/prometheus/tsdb/head.go:518
 9  0x0000000000f20b2d in github.com/prometheus/prometheus/tsdb.open
    at /home/opensource/cortex/vendor/github.com/prometheus/prometheus/tsdb/db.go:750
10  0x0000000000f1f3dc in github.com/prometheus/prometheus/tsdb.Open
    at /home/opensource/cortex/vendor/github.com/prometheus/prometheus/tsdb/db.go:576
11  0x0000000002771faa in github.com/cortexproject/cortex/pkg/ingester.(*Ingester).createTSDB
    at /home/opensource/cortex/pkg/ingester/ingester.go:1812
12  0x0000000002775289 in github.com/cortexproject/cortex/pkg/ingester.(*Ingester).openExistingTSDB.func1
    at /home/opensource/cortex/pkg/ingester/ingester.go:1942
13  0x0000000000c5cb82 in golang.org/x/sync/errgroup.(*Group).Go.func1
    at /home/opensource/cortex/vendor/golang.org/x/sync/errgroup/errgroup.go:75
14  0x0000000000473541 in runtime.goexit
    at /usr/local/go/src/runtime/asm_amd64.s:1571

(dlv) frame 6
 runtime.raise() /usr/local/go/src/runtime/sys_linux_amd64.s:168 (PC: 0x474ee1)
Warning: debugging optimized function
Frame 6: /home/opensource/cortex/vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go:791 (PC: b98265)
(dlv) locals
chkCRC32 = hash.Hash32(*hash/crc32.digest) 0xc00102c690
segIDs = []int len: 61, cap: 61, [...]
segID = 445
mmapFile = ("*github.com/prometheus/prometheus/tsdb/chunks.mmappedChunkFile")(0xc00dc6d800)
fileEnd = 134217702
idx = 27156479
chunkRef = 1911287603183
startIdx = 27156463
seriesRef = 12348302
mint = 1665777616366
(dlv) p segIDs
[]int len: 61, cap: 61, [431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491]
(dlv) frame 5
 runtime.raise() /usr/local/go/src/runtime/sys_linux_amd64.s:168 (PC: 0x474ee1)
Warning: debugging optimized function
Frame 5: /usr/local/go/src/encoding/binary/binary.go:126 (PC: 51fe2b)
(dlv) args
b = []uint8 len: 8, cap: 107061223, [...]
~r0 = 0
(dlv) p b
[]uint8 len: 8, cap: 107061223, [4,0,0,0,72,139,148,36]
(dlv) 

**To Reproduce**
1. Start Cortex (latest)
2. Perform Operations(Write)
16C128G*3 TARGET=ALL
15M writes ops/30s

**Expected behavior**
start up successfully

**Environment:**
 - Infrastructure: [e.g., Kubernetes]
 - Deployment tool: [binary]

**Comment by t00350320** [comment]
For 445 chunk, we try to execute " tar " cmd, and get this error:
`
tar zcvf 000445.tar.gz 000445
000445
tar: 000445: File shrank by 107061222 bytes; padding with zeros
`
We contact our Cloud service experts, they find some slot errors in kernel dmseg:
![image](https://user-images.githubusercontent.com/41465048/196679111-74af6b0f-167f-4750-a6ac-38fd96612b85.png)

Then we try to redeploy our cortex sevice, any progress will be posted here.

**Comment by yeya24** [comment]
@t00350320 You are running the latest version of Cortex did you mean Cortex main or the latest release? If it is main I suspect it is related to the Prometheus TSDB upgrade.
From the error message you shared yeah looks like it is a TSDB issue related to mmaped head chunks.

**Comment by t00350320** [comment]
> 

Cortex main code rather than released

**Comment by alanprot** [comment]
Can you try the version before the prometheus update? So we can discover if is related?

**Comment by t00350320** [comment]
> Can you try the version before the prometheus update? So we can discover if is related?

yes, will try tomorrow

**Comment by t00350320** [comment]
A replaced node works well under previous main version and latest . So the error was related with disk's slot error. I will close this issue.
