### ISSUE TITLE
distributor replica detect instance error

### ISSUE THREAD

**Issue by t00350320** [cortexproject/cortex#4923]
**Describe the bug**
We built a 3-node cortex cluster with these configuration 
[cortex-3.txt](https://github.com/cortexproject/cortex/files/9826063/cortex-3.txt)
[cortex-1.txt](https://github.com/cortexproject/cortex/files/9826065/cortex-1.txt)
[cortex-2.txt](https://github.com/cortexproject/cortex/files/9826066/cortex-2.txt)
.  Node 10.177.197.238 is offline and replaced by another one 10.177.171.218.  

The Push api shows lots of errors 
“level=warn ts=2022-10-20T03:43:07.670948766Z caller=logging.go:86 traceID=5738fe55523606b1 msg="POST /api/v1/push (500) 577.508µs Response: \"at least 2 live replicas required, could only find 1 - unhealthy instances: 10.177.197.238:9004\\n\" ws: false; Connection: close; Content-Encoding: snappy; Content-Length: 14355; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.29.1; X-Prometheus-Remote-Write-Version: 0.1.0; X-Scope-Orgid: fake; "
"
10.177.38.157  cortex-1
10.177.179.117  cortex-2
10.177.197.238   cortex-3 offline
10.177.171.218   cortex-3 new one

ip:8004/memberlist 
![image](https://user-images.githubusercontent.com/41465048/196851571-d6bd5e37-5fb0-44e6-b6f4-4e6596bff98e.png)

**To Reproduce**
1. Start Cortex (SHA or version)
2. Perform Operations
stop one cortex, then  a new one added

**Environment:**
 - Infrastructure: [e.g., Kubernetes]
 - Deployment tool: [e.g.,binary]
 -branch: main branch latest code

**Comment by alanprot** [comment]
Seems the `replication_factor ` is set to 2.

This would cause 5xx during rollouts or single instance being restarted as cortex writes in quorum.

**Comment by t00350320** [comment]
> Seems the `replication_factor ` is set to 2.
> 
> This would cause 5xx during rollouts or single instance being restarted as cortex writes in quorum.

en,  the error log  "at least 2 live replicas required, could only find 1 - unhealthy instances" lasts for more than ten hours . When I browse to ip:8004/ingester/ring and push the invalid InstancdID's Forget , everything works fine. It seems the 'Forget' button's code function should be  execute in background rather than a manul operation.  I'll dig out the final reason and update here.
![image](https://user-images.githubusercontent.com/41465048/196881869-228d0322-e234-4f80-b546-7271f16125e2.png)

**Comment by alanprot** [comment]
Oh..

Usually ingesters are deployed as statefulsets (which means that they come back with the instance ID).

Was it a clean shutdown? If it was a clean shutdown and you set `unregister_on_shutdown` to true (the default value) the ingester should remove itself from the ring upon shutdown.

There is no auto forget for ingesters as right now. Making the replacement pod come with the same name as the old one would be the ideal solution here i guess.

**Comment by friedrichg** [comment]
If ingester is unhealthy, it needs to be forgotten via UI

Duplicated of https://github.com/cortexproject/cortex/issues/1521
