### ISSUE TITLE
behaviour of avg_over_time in sum

### ISSUE THREAD

**Issue by flipsed** [cortexproject/cortex#4924]
**Describe the bug**
In prometheus I can do the following query:
```
sum(avg_over_time(node_memory_Cached_bytes[10m]) + avg_over_time(node_memory_MemFree_bytes[10m]))
```

but the same query in cortex results in the following error:
```
"invalid parameter \"query\": 1:52: parse error: unexpected identifier \"avg_over_time\" in aggregation"
```

**To Reproduce**
Run the query above

**Expected behavior**
I would expect the query to return the same result in prometheus and cortex

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

**Comment by alanprot** [comment]
What cortex version are you using?

I just run this query and it did not throw any parser error.

**Comment by flipsed** [comment]
I believe we're running on version 1.3.0 which is quite dated - I'll close the issue for now since it's likely resolved by upgrading

**Comment by flipsed** [comment]
@alanprot we're actually running version 1.11.1 - I was just thrown off earlier because our helm chart is `^1.3.0`

**Comment by alanprot** [comment]
Humm.. are you using grafana?

I can run this query just fine:
![Screen Shot 2022-10-20 at 9 27 45 AM](https://user-images.githubusercontent.com/4027760/197005530-0123a82f-ff81-491c-8089-1972ba504cca.png)

**Comment by flipsed** [comment]
I can also run the query in grafana but when I use the cortex HTTP API, querying the following url `https://<internal-cortex-domain>/prometheus/api/v1/query?query=sum(avg_over_time(node_memory_Cached_bytes[10m])+avg_over_time(node_memory_MemFree_bytes[10m]))` I get the error.
```bash
{"status":"error","errorType":"bad_data","error":"invalid parameter \"query\": 1:50: parse error: unexpected identifier \"avg_over_time\" in aggregation"}
```

For context, I need to make a query with a sum of averages programmatically via the cortex API in one of our applications

**Comment by alanprot** [comment]
This seems some url encode problem.. can u try the post method ?

**Comment by flipsed** [comment]
yup it's a url encoding error... The plus sign from that query was being parsed as a parameter. The query started working when I encoded `+` to `%2B`
thanks @alanprot
