### ISSUE TITLE
Changing  `at_modifier_enabled`  defult value or delete this configuration

### ISSUE THREAD

**Issue by songjiayang** [cortexproject/cortex#4927]
The @ modifer to stable with Prometheus v2.33, to see the PR [#10121](https://github.com/prometheus/prometheus/pull/10121) , Whether the default value can be changed to true or delete related configuration.

I think it's time to simple cortex configurations.

**Comment by yeya24** [comment]
Agree we should enable this option by default. Same as the negative offset feature.

**Comment by alanprot** [comment]
I agree as well. Do you wanna raise a pr for it ?

**Comment by songjiayang** [comment]
very happy to
