### ISSUE TITLE
Queries return 500 when ingesters are scaling up

### ISSUE THREAD

**Issue by harry671003** [cortexproject/cortex#4930]
**Describe the bug**
When ingesters are scaling up, I noticed that the queries are failing and returning 500.
This is because multiple ingesters from different AZs are starting up.
It might be introduced by https://github.com/cortexproject/cortex/pull/4847/, where ingesters are added to the ring during WAL replay.

```
/api/v1/query?query=avg%28avg_over_time%28kubecost_network_region_egress_cost%7B%7D%5B1h%5D%29%29+by+%28cluster_id%29&time=1666288800

'{"status":"error","errorType":"internal","error":"expanding series: rpc error: code = Unavailable desc = Starting"}' 
Query: 'avg(avg_over_time(kubecost_network_region_egress_cost{}[1h])) by (cluster_id)'
```

**To Reproduce**
1. Scale ingester HPA from 10 to 20. This will cause new ingesters to be created.
2. Queries will fail while the ingesters are scaling up.

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

**Comment by songjiayang** [comment]
Similar problem, when an ingester is in `LEVAING` status,  I visit  `distributer/all_user_stats` page, it raise an error  
![image](https://user-images.githubusercontent.com/1459834/197677313-5dbb7ebe-7887-4543-8ed7-767d2bf3a1c9.png)

**Comment by t00350320** [comment]
hi,@harry671003 
you'll try this as alan replyed at https://github.com/cortexproject/cortex/issues/4931
```
# If not 0, how often to rejoin the cluster. Occasional rejoin can help to fix
# the cluster split issue, and is harmless otherwise. For example when using
# only few components as a seed nodes (via -memberlist.join), then it's
# recommended to use rejoin. If -memberlist.join points to dynamic service that
# resolves to all gossiping nodes (eg. Kubernetes headless service), then rejoin
# is not needed.
# CLI flag: -memberlist.rejoin-interval
[rejoin_interval: <duration> | default = 0s]
```

it works in my cortex.yaml 
```
memberlist:
  node_name: "cortex-3"
  bind_port: 7946
  join_members:
    - xx:7947
  abort_if_cluster_join_fails: false
  rejoin_interval: 5s

```

**Comment by harry671003** [comment]
@t00350320 - This seems to be a different issue. 
#4930 occurs when ingester is scaled up and it joins the ring before the ingester service has finished starting up. The query requests sent to the new ingesters, it'll fail at: 
https://github.com/cortexproject/cortex/blob/master/pkg/ingester/ingester.go#L867

**Comment by harry671003** [comment]
I was not able to reproduce the issue in our latest cortex cluster.
One other thing we changed was the heart-time for the ingester ring. This used to be 5s and now it's 1m. This might be the reason why the queries no longer fail. Because the ingesters are not getting added to the ring before WAL replay has finished.

I'll close the issue now.
