### ISSUE TITLE
3 Ingesters crash loop failing to open TSDB for one tenant

### ISSUE THREAD

**Issue by friedrichg** [cortexproject/cortex#4954]
**Describe the bug**
3 Ingesters for the same tenant failed at the same time

**To Reproduce**
1. Large cluster running 7e3e1b4decc787c38ec3941a0310661e9324260e (v1.12.0-rc.0)
2. Three ingesters failed and crashloop with this error in the same tenant:

```
level=error ts=2022-11-06T10:40:28.254451917Z caller=cortex.go:448 msg="module failed" module=ingester-service err="invalid service state: Failed, expected: Running, failure: opening existing TSDBs: unable to open TSDB for user xx: failed to open TSDB: /data/tsdb/xx: /data/tsdb/xx/chunks_head/001552: invalid magic number 0"
```

**Expected behavior**
- Ingesters should ignore problems in chunks_head and start
- 3 Ingesters should not fail at the same time with the same error in the same tenant as this causes surely data loss

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: jsonnet

Related https://github.com/prometheus/prometheus/issues/7397

**Comment by alvinlin123** [comment]
This should be fixed after this PR: https://github.com/cortexproject/cortex/pull/4903 because we updated Prometheus version that contains fix for https://github.com/prometheus/prometheus/issues/7397
