### ISSUE TITLE
async tsdb chunkswrite needs a configuration 

### ISSUE THREAD

**Issue by t00350320** [cortexproject/cortex#4957]
AFAK, vendor/prometheus has imported an async tsdb chunkswrite method. Related configuration is a hard code with   "DefaultWriteQueueSize = 0". We'll add a configuration in yaml file.

**Comment by yeya24** [comment]
Yeah I think it makes sense to expose the configuration. @t00350320 Would you like to submit a PR?

**Comment by t00350320** [comment]
> Yeah I think it makes sense to expose the configuration. @t00350320 Would you like to submit a PR?

yeah, i will do it.

**Comment by alanprot** [comment]
Closing this as the PR got merged.
