### ISSUE TITLE
query failed after migrating data from thanos to cortex

### ISSUE THREAD

**Issue by yk-zheng-zz** [cortexproject/cortex#4982]
**Describe the bug**
Cortex couldn't fetch metrics from gcs after migrating from thanos to cortex

querying metrics failed with error message
`
runtime error: invalid memory address or nil pointer dereference
` 

store gateway failed to fetch data with logs like this:

> level=warn ts=2022-11-09T03:54:32.789494936Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=194.561245ms err="rpc error: code = Unknown desc = send series response hints: rpc error: code = Canceled desc = context canceled" msg="gRPC\n"
> level=warn ts=2022-11-09T03:54:43.372146185Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=335.225359ms err="rpc error: code = Aborted desc = fetch series for block 01G67ACHVPYDMCZ7BW4FNPTZPG: load chunks: get range reader: fetching range [22080000, 25120000]: context canceled" msg="gRPC\n"

**To Reproduce**
1. Copy Thanos data from Thanos bucket in gcs to cortex bucket in gcs.
2. Use thanoscovert to convert the data.
3. Query metrics

**Expected behavior**
I expect that we can query metrics after migrating

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: thanoscovert

**Additional Context**
 we used the same service_account of gcs but different buckets for Thanos and cortex
 Executing thanoscovert command was completed successfully and there was no error and failure during executing

**Comment by friedrichg** [comment]
which thanos version? which cortex version?

**Comment by yk-zheng-zz** [comment]
hi
we are using following version
thanos: v0.10.0
cortex: v1.11.0

**Comment by yeya24** [comment]
@yk-zheng-zz Could you please send the goroutine dumps for the runtime panic error?
The error log you showed seems another error so having the dump is the easiest for us to pinpoint the issue

**Comment by yk-zheng-zz** [comment]
@yeya24 
here are the querier's logs

```
[querier-7ff7bb8c6f-xzzhn] level=error ts=2022-11-28T04:12:57.520643357Z caller=engine.go:895 msg="runtime panic in parser" err="runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 2391113850 [running]:\ngithub.com/prometheus/prometheus/promql.(*evaluator).recover(0xc00ded9020, 0xc00127be58, 0xc00127be70)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:893 +0x345\npanic(0x2412da0, 0x3e0e600)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/cortexproject/cortex/pkg/querier.(*blockQuerierSeries).Iterator(0xc002666810, 0x0, 0x2)\n\t/__w/cortex/cortex/pkg/querier/block.go:115 +0x115\ngithub.com/prometheus/prometheus/storage.ChainedSeriesMerge.func1(0xc000aca300, 0xc000aca3c0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/storage/merge.go:435 +0xd7\ngithub.com/prometheus/prometheus/storage.(*SeriesEntry).Iterator(0xc0000b1b00, 0x3e77588, 0x493e0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/storage/series.go:32 +0x2b\ngithub.com/prometheus/prometheus/promql.(*evaluator).eval(0xc00ded9020, 0x2d12618, 0xc003599500, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:1481 +0xb67\ngithub.com/prometheus/prometheus/promql.(*evaluator).Eval(0xc00ded9020, 0x2d12618, 0xc003599500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:908 +0xb2\ngithub.com/prometheus/prometheus/promql.(*Engine).execEvalStmt(0xc0001ecbd0, 0x2d11540, 0xc005887260, 0xc00ded8f00, 0xc02e2914a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:640 +0xd96\ngithub.com/prometheus/prometheus/promql.(*Engine).exec(0xc0001ecbd0, 0x2d11540, 0xc005887260, 0xc00ded8f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:543 +0x4fe\ngithub.com/prometheus/prometheus/promql.(*query).Exec(0xc00ded8f00, 0x2d11540, 0xc005887140, 0x2d11540)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:183 +0x9d\ngithub.com/prometheus/prometheus/web/api/v1.(*API).queryRange(0xc000ed9c20, 0xc002a0aa00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/web/api/v1/api.go:463 +0xee9\ngithub.com/prometheus/prometheus/web/api/v1.(*API).Register.func1.1(0x2cffb80, 0xc0027ffa80, 0xc002a0aa00)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/web/api/v1/api.go:265 +0xa5\nnet/http.HandlerFunc.ServeHTTP(0xc000efeb40, 0x2cffb80, 0xc0027ffa80, 0xc002a0aa00)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/prometheus/prometheus/util/httputil.CompressionHandler.ServeHTTP(0x2ccd1a0, 0xc000efeb40, 0x2d053a0, 0xc0027ffa40, 0xc002a0aa00)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/util/httputil/compression.go:90 +0x7e\ngithub.com/prometheus/common/route.(*Router).handle.func1(0x2d053a0, 0xc0027ffa40, 0xc002a0a900, 0x0, 0x0, 0x0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/common/route/route.go:83 +0x27f\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000efd140, 0x2d053a0, 0xc0027ffa40, 0xc002a0a900)\n\t/__w/cortex/cortex/vendor/github.com/julienschmidt/httprouter/router.go:387 +0xc7e\ngithub.com/prometheus/common/route.(*Router).ServeHTTP(0xc000eb9660, 0x2d053a0, 0xc0027ffa40, 0xc002a0a900)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/common/route/route.go:121 +0x4c\ngithub.com/cortexproject/cortex/pkg/api.getHTTPCacheGenNumberHeaderSetterMiddleware.func1.1(0x2d053a0, 0xc0027ffa40, 0xc002a0a900)\n\t/__w/cortex/cortex/pkg/api/middlewares.go:26 +0x206\nnet/http.HandlerFunc.ServeHTTP(0xc0027ff980, 0x2d053a0, 0xc0027ffa40, 0xc002a0a900)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/weaveworks/common/middleware.Instrument.Wrap.func1.2(0x2d053a0, 0xc0027ffa40)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:70 +0x4c\ngithub.com/felixge/httpsnoop.CaptureMetricsFn(0x2d053a0, 0xc0027ff960, 0xc0005a7110, 0x2, 0x2d3ab38, 0xc001f0a7c0)\n\t/__w/cortex/cortex/vendor/github.com/felixge/httpsnoop/capture_metrics.go:81 +0x24b\ngithub.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x2d053a0, 0xc0027ff960, 0xc002a0a900)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:69 +0x325\nnet/http.HandlerFunc.ServeHTTP(0xc02e2913b0, 0x2d053a0, 0xc0027ff960, 0xc002a0a900)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc000112b40, 0x2d053a0, 0xc0027ff960, 0xc002a0a700)\n\t/__w/cortex/cortex/vendor/github.com/gorilla/mux/mux.go:210 +0xd3\ngithub.com/cortexproject/cortex/pkg/querier/stats.WallTimeMiddleware.Wrap.func1(0x2d053a0, 0xc0027ff960, 0xc002a0a700)\n\t/__w/cortex/cortex/pkg/querier/stats/time_middleware.go:25 +0xca\nnet/http.HandlerFunc.ServeHTTP(0xc000574420, 0x2d053a0, 0xc0027ff960, 0xc002a0a700)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/weaveworks/common/middleware.glob..func1.1(0x2d053a0, 0xc0027ff960, 0xc002a0a500)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/http_auth.go:17 +0x147\nnet/http.HandlerFunc.ServeHTTP(0xc0005745a0, 0x2d053a0, 0xc0027ff960, 0xc002a0a500)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x2d053a0, 0xc0027ff960, 0xc002a0a500)\n\t/__w/cortex/cortex/vendor/github.com/NYTimes/gziphandler/gzip.go:342 +0x302\nnet/http.HandlerFunc.ServeHTTP(0xc000e1d4d0, 0x2d053a0, 0xc0027ff960, 0xc002a0a500)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc000ac3200, 0x2d053a0, 0xc0027ff960, 0xc002a0a300)\n\t/__w/cortex/cortex/vendor/github.com/gorilla/mux/mux.go:210 +0xd3\ngithub.com/weaveworks/common/middleware.Instrument.Wrap.func1.2(0x2d053a0, 0xc0027ff960)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:70 +0x4c\ngithub.com/felixge/httpsnoop.CaptureMetricsFn(0x2d00de0, 0xc02e291310, 0xc0005a7840, 0x2, 0x2d3ab38, 0xc001f0a780)\n\t/__w/cortex/cortex/vendor/github.com/felixge/httpsnoop/capture_metrics.go:81 +0x24b\ngithub.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x2d00de0, 0xc02e291310, 0xc002a0a300)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:69 +0x325\nnet/http.HandlerFunc.ServeHTTP(0xc00029d450, 0x2d00de0, 0xc02e291310, 0xc002a0a300)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/weaveworks/common/middleware.Log.Wrap.func1(0x2d050a0, 0xc0027ff8c0, 0xc002a0a300)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/logging.go:53 +0x1a9\nnet/http.HandlerFunc.ServeHTTP(0xc0006fccc0, 0x2d050a0, 0xc0027ff8c0, 0xc002a0a300)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5(0x2d03570, 0xc00f4d6d00, 0xc002a0a200)\n\t/__w/cortex/cortex/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:154 +0x5e4\nnet/http.HandlerFunc.ServeHTTP(0xc0006fcd00, 0x2d03570, 0xc00f4d6d00, 0xc002a0a200)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/weaveworks/common/httpgrpc/server.Server.Handle(0x2ccd1a0, 0xc0006fcd00, 0x2d11540, 0xc005886720, 0xc02e290ff0, 0xc005886720, 0x2300d40, 0x3dbcec0)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/httpgrpc/server/server.go:61 +0x2f1\ngithub.com/cortexproject/cortex/pkg/querier/worker.(*schedulerProcessor).runRequest(0xc00071a4b0, 0x2d11540, 0xc005886720, 0x2cc3ca0, 0xc02e291130, 0x85a87b884d2cd508, 0xc014664ac8, 0x11, 0x1, 0xc02e290ff0)\n\t/__w/cortex/cortex/pkg/querier/worker/scheduler_processor.go:160 +0x9a\ngithub.com/cortexproject/cortex/pkg/querier/worker.(*schedulerProcessor).querierLoop.func1(0x2d11498, 0xc001ab1a80, 0xc044695680, 0xc00071a4b0, 0x2d33c08, 0xc006903350, 0xc058353c80, 0x10)\n\t/__w/cortex/cortex/pkg/querier/worker/scheduler_processor.go:144 +0x1f8\ncreated by github.com/cortexproject/cortex/pkg/querier/worker.(*schedulerProcessor).querierLoop\n\t/__w/cortex/cortex/pkg/querier/worker/scheduler_processor.go:129 +0x106\n"
[querier-7ff7bb8c6f-xzzhn] level=error ts=2022-11-28T04:12:57.521599272Z caller=scheduler_processor.go:103 msg="error processing requests from scheduler" err="rpc error: code = Unknown desc = context canceled" addr=10.42.6.147:9095
[querier-7ff7bb8c6f-xzzhn] level=error ts=2022-11-28T04:12:57.521606285Z caller=scheduler_processor.go:103 msg="error processing requests from scheduler" err="rpc error: code = Unknown desc = context canceled" addr=10.42.6.147:9095
[querier-7ff7bb8c6f-xzzhn] level=warn ts=2022-11-28T04:12:57.52169024Z caller=logging.go:72 traceID=453febbafd8b62c9 orgID=cis-net msg="GET /prometheus/api/v1/query_range?end=1665712162&query=a10_cur_conn&start=1665705943&step=691 (500) 261.265427ms Response: \"{\\\"status\\\":\\\"error\\\",\\\"errorType\\\":\\\"internal\\\",\\\"error\\\":\\\"expanding series: failed to receive series from 10.42.8.214:9095: rpc error: code = Canceled desc = context canceled\\\"}\" ws: false; X-Scope-Orgid: cis-net; uber-trace-id: 453febbafd8b62c9:21f1c429f076319e:1f60010aeb23dea9:0; "
[querier-7ff7bb8c6f-xzzhn] level=warn ts=2022-11-28T04:12:57.521706179Z caller=logging.go:72 traceID=453febbafd8b62c9 orgID=cis-net msg="GET /prometheus/api/v1/query_range?end=1665618877&query=a10_cur_conn&start=1665576035&step=691 (500) 261.302039ms Response: \"{\\\"status\\\":\\\"error\\\",\\\"errorType\\\":\\\"internal\\\",\\\"error\\\":\\\"expanding series: failed to receive series from 10.42.8.214:9095: rpc error: code = Canceled desc = context canceled\\\"}\" ws: false; X-Scope-Orgid: cis-net; uber-trace-id: 453febbafd8b62c9:001f6643561dfb1d:03a49f1845daf486:0; "
[querier-7ff7bb8c6f-xzzhn] level=error ts=2022-11-28T04:12:57.5217373Z caller=scheduler_processor.go:193 org_id=cis-net msg="error notifying frontend about finished query" err="rpc error: code = Canceled desc = context canceled" frontend=10.42.65.142:9095
[querier-7ff7bb8c6f-xzzhn] level=error ts=2022-11-28T04:12:57.521739475Z caller=scheduler_processor.go:193 org_id=cis-net msg="error notifying frontend about finished query" err="rpc error: code = Canceled desc = context canceled" frontend=10.42.65.142:9095
[querier-7ff7bb8c6f-xzzhn] level=error ts=2022-11-28T04:12:57.521748024Z caller=scheduler_processor.go:148 org_id=cis-net msg="error notifying scheduler about finished query" err=EOF addr=10.42.6.147:9095
[querier-7ff7bb8c6f-xzzhn] level=error ts=2022-11-28T04:12:57.521749678Z caller=scheduler_processor.go:148 org_id=cis-net msg="error notifying scheduler about finished query" err=EOF addr=10.42.6.147:9095
```

here are the store-gatway's logs
```
[store-gateway-1] level=warn ts=2022-11-28T04:12:57.613748149Z caller=memcached_client.go:412 name=chunks-cache msg="failed to fetch items from memcached" numKeys=102 firstKey=subrange:cis-net/01GHRZZVQ4ZAFFNZTYTPRS2E9V/chunks/000001:10192000:10208000 err="failed to wait for turn. Instance: : context canceled"
[store-gateway-1] level=warn ts=2022-11-28T04:12:57.614206179Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=353.338259ms err="rpc error: code = Aborted desc = fetch series for block 01GHRZZVQ4ZAFFNZTYTPRS2E9V: load chunks: get range reader: fetching range [10192000, 11824000]: Get \"https://storage.googleapis.com/qa-cortex-roc-mon-aas/cis-net/01GHRZZVQ4ZAFFNZTYTPRS2E9V/chunks/000001\": context canceled" msg="gRPC\n"
[store-gateway-1] level=warn ts=2022-11-28T04:12:57.798620006Z caller=memcached_client.go:412 name=index-cache msg="failed to fetch items from memcached" numKeys=58 firstKey=S:01GHRH7CCCSH3WGFCXX448FNGF:9754112 err="failed to wait for turn. Instance: : context canceled"
[store-gateway-1] level=warn ts=2022-11-28T04:12:57.798845288Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=283.504194ms err="rpc error: code = Aborted desc = fetch series for block 01GHRH7CCCSH3WGFCXX448FNGF: preload series: read series range: get range reader: Get \"https://storage.googleapis.com/qa-cortex-roc-mon-aas/cis-net/01GHRH7CCCSH3WGFCXX448FNGF/index\": context canceled" msg="gRPC\n"
[store-gateway-1] level=warn ts=2022-11-28T04:12:57.871385699Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=355.862809ms err="rpc error: code = Unknown desc = send series response hints: rpc error: code = Canceled desc = context canceled" msg="gRPC\n"

[store-gateway-0] level=warn ts=2022-11-28T04:12:57.592977995Z caller=memcached_client.go:412 name=index-cache msg="failed to fetch items from memcached" numKeys=58 firstKey=S:01GHRH7CCCSH3WGFCXX448FNGF:9754112 err="failed to wait for turn. Instance: : context canceled"
[store-gateway-0] level=warn ts=2022-11-28T04:12:57.595204522Z caller=memcached_client.go:412 name=chunks-cache msg="failed to fetch items from memcached" numKeys=1 firstKey=attrs:cis-net/01GHRMRFV02NB0TZ2PENAG4VWQ/chunks/000001 err="failed to wait for turn. Instance: : context canceled"
[store-gateway-0] level=warn ts=2022-11-28T04:12:57.5955539Z caller=grpc_logging.go:55 duration=334.617565ms method=/gatewaypb.StoreGateway/Series err="rpc error: code = Aborted desc = fetch series for block 01GHRH7CCCSH3WGFCXX448FNGF: preload series: read series range: get range reader: Get \"https://storage.googleapis.com/qa-cortex-roc-mon-aas/cis-net/01GHRH7CCCSH3WGFCXX448FNGF/index\": context canceled" msg="gRPC\n"
[store-gateway-0] level=warn ts=2022-11-28T04:12:57.646008803Z caller=memcached_client.go:412 name=index-cache msg="failed to fetch items from memcached" numKeys=58 firstKey=S:01GHRRNPRVAE9S70XA57YZC6MX:14217360 err="failed to wait for turn. Instance: : context canceled"
[store-gateway-0] level=warn ts=2022-11-28T04:12:57.646202371Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=385.199677ms err="rpc error: code = Aborted desc = fetch series for block 01GHRRNPRVAE9S70XA57YZC6MX: preload series: read series range: get range reader: Get \"https://storage.googleapis.com/qa-cortex-roc-mon-aas/cis-net/01GHRRNPRVAE9S70XA57YZC6MX/index\": context canceled" msg="gRPC\n"
```

**Comment by yeya24** [comment]
@yk-zheng-zz Is the panic in the querier log? I saw `[querier-7ff7bb8c6f-xzzhn] level=error ts=2022-11-28T04:12:57.520643357Z caller=engine.go:895 msg="runtime panic in parser" err="runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 2391113850 [running]:\ngithub.com/prometheus/prometheus/promql.(*evaluator).recover(0xc00ded9020, 0xc00127be58, 0xc00127be70)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:893 +0x345\npanic(0x2412da0, 0x3e0e600)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/cortexproject/cortex/pkg/querier.(*blockQuerierSeries).Iterator(0xc002666810, 0x0, 0x2)\n\t/__w/cortex/cortex/pkg/querier/block.go:115 +0x115\ngithub.com/prometheus/prometheus/storage.ChainedSeriesMerge.func1(0xc000aca300, 0xc000aca3c0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/storage/merge.go:435 +0xd7\ngithub.com/prometheus/prometheus/storage.(*SeriesEntry).Iterator(0xc0000b1b00, 0x3e77588, 0x493e0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/storage/series.go:32 +0x2b\ngithub.com/prometheus/prometheus/promql.(*evaluator).eval(0xc00ded9020, 0x2d12618, 0xc003599500, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:1481 +0xb67\ngithub.com/prometheus/prometheus/promql.(*evaluator).Eval(0xc00ded9020, 0x2d12618, 0xc003599500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:908 +0xb2\ngithub.com/prometheus/prometheus/promql.(*Engine).execEvalStmt(0xc0001ecbd0, 0x2d11540, 0xc005887260, 0xc00ded8f00, 0xc02e2914a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:640 +0xd96\ngithub.com/prometheus/prometheus/promql.(*Engine).exec(0xc0001ecbd0, 0x2d11540, 0xc005887260, 0xc00ded8f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:543 +0x4fe\ngithub.com/prometheus/prometheus/promql.(*query).Exec(0xc00ded8f00, 0x2d11540, 0xc005887140, 0x2d11540)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/promql/engine.go:183 +0x9d\ngithub.com/prometheus/prometheus/web/api/v1.(*API).queryRange(0xc000ed9c20, 0xc002a0aa00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/web/api/v1/api.go:463 +0xee9\ngithub.com/prometheus/prometheus/web/api/v1.(*API).Register.func1.1(0x2cffb80, 0xc0027ffa80, 0xc002a0aa00)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/web/api/v1/api.go:265 +0xa5\nnet/http.HandlerFunc.ServeHTTP(0xc000efeb40, 0x2cffb80, 0xc0027ffa80, 0xc002a0aa00)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/prometheus/prometheus/util/httputil.CompressionHandler.ServeHTTP(0x2ccd1a0, 0xc000efeb40, 0x2d053a0, 0xc0027ffa40, 0xc002a0aa00)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/util/httputil/compression.go:90 +0x7e\ngithub.com/prometheus/common/route.(*Router).handle.func1(0x2d053a0, 0xc0027ffa40, 0xc002a0a900, 0x0, 0x0, 0x0)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/common/route/route.go:83 +0x27f\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000efd140, 0x2d053a0, 0xc0027ffa40, 0xc002a0a900)\n\t/__w/cortex/cortex/vendor/github.com/julienschmidt/httprouter/router.go:387 +0xc7e\ngithub.com/prometheus/common/route.(*Router).ServeHTTP(0xc000eb9660, 0x2d053a0, 0xc0027ffa40, 0xc002a0a900)\n\t/__w/cortex/cortex/vendor/github.com/prometheus/common/route/route.go:121 +0x4c\ngithub.com/cortexproject/cortex/pkg/api.getHTTPCacheGenNumberHeaderSetterMiddleware.func1.1(0x2d053a0, 0xc0027ffa40, 0xc002a0a900)\n\t/__w/cortex/cortex/pkg/api/middlewares.go:26 +0x206\nnet/http.HandlerFunc.ServeHTTP(0xc0027ff980, 0x2d053a0, 0xc0027ffa40, 0xc002a0a900)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/weaveworks/common/middleware.Instrument.Wrap.func1.2(0x2d053a0, 0xc0027ffa40)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:70 +0x4c\ngithub.com/felixge/httpsnoop.CaptureMetricsFn(0x2d053a0, 0xc0027ff960, 0xc0005a7110, 0x2, 0x2d3ab38, 0xc001f0a7c0)\n\t/__w/cortex/cortex/vendor/github.com/felixge/httpsnoop/capture_metrics.go:81 +0x24b\ngithub.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x2d053a0, 0xc0027ff960, 0xc002a0a900)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:69 +0x325\nnet/http.HandlerFunc.ServeHTTP(0xc02e2913b0, 0x2d053a0, 0xc0027ff960, 0xc002a0a900)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc000112b40, 0x2d053a0, 0xc0027ff960, 0xc002a0a700)\n\t/__w/cortex/cortex/vendor/github.com/gorilla/mux/mux.go:210 +0xd3\ngithub.com/cortexproject/cortex/pkg/querier/stats.WallTimeMiddleware.Wrap.func1(0x2d053a0, 0xc0027ff960, 0xc002a0a700)\n\t/__w/cortex/cortex/pkg/querier/stats/time_middleware.go:25 +0xca\nnet/http.HandlerFunc.ServeHTTP(0xc000574420, 0x2d053a0, 0xc0027ff960, 0xc002a0a700)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/weaveworks/common/middleware.glob..func1.1(0x2d053a0, 0xc0027ff960, 0xc002a0a500)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/http_auth.go:17 +0x147\nnet/http.HandlerFunc.ServeHTTP(0xc0005745a0, 0x2d053a0, 0xc0027ff960, 0xc002a0a500)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x2d053a0, 0xc0027ff960, 0xc002a0a500)\n\t/__w/cortex/cortex/vendor/github.com/NYTimes/gziphandler/gzip.go:342 +0x302\nnet/http.HandlerFunc.ServeHTTP(0xc000e1d4d0, 0x2d053a0, 0xc0027ff960, 0xc002a0a500)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc000ac3200, 0x2d053a0, 0xc0027ff960, 0xc002a0a300)\n\t/__w/cortex/cortex/vendor/github.com/gorilla/mux/mux.go:210 +0xd3\ngithub.com/weaveworks/common/middleware.Instrument.Wrap.func1.2(0x2d053a0, 0xc0027ff960)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:70 +0x4c\ngithub.com/felixge/httpsnoop.CaptureMetricsFn(0x2d00de0, 0xc02e291310, 0xc0005a7840, 0x2, 0x2d3ab38, 0xc001f0a780)\n\t/__w/cortex/cortex/vendor/github.com/felixge/httpsnoop/capture_metrics.go:81 +0x24b\ngithub.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x2d00de0, 0xc02e291310, 0xc002a0a300)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:69 +0x325\nnet/http.HandlerFunc.ServeHTTP(0xc00029d450, 0x2d00de0, 0xc02e291310, 0xc002a0a300)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/weaveworks/common/middleware.Log.Wrap.func1(0x2d050a0, 0xc0027ff8c0, 0xc002a0a300)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/logging.go:53 +0x1a9\nnet/http.HandlerFunc.ServeHTTP(0xc0006fccc0, 0x2d050a0, 0xc0027ff8c0, 0xc002a0a300)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5(0x2d03570, 0xc00f4d6d00, 0xc002a0a200)\n\t/__w/cortex/cortex/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:154 +0x5e4\nnet/http.HandlerFunc.ServeHTTP(0xc0006fcd00, 0x2d03570, 0xc00f4d6d00, 0xc002a0a200)\n\t/usr/local/go/src/net/http/server.go:2049 +0x44\ngithub.com/weaveworks/common/httpgrpc/server.Server.Handle(0x2ccd1a0, 0xc0006fcd00, 0x2d11540, 0xc005886720, 0xc02e290ff0, 0xc005886720, 0x2300d40, 0x3dbcec0)\n\t/__w/cortex/cortex/vendor/github.com/weaveworks/common/httpgrpc/server/server.go:61 +0x2f1\ngithub.com/cortexproject/cortex/pkg/querier/worker.(*schedulerProcessor).runRequest(0xc00071a4b0, 0x2d11540, 0xc005886720, 0x2cc3ca0, 0xc02e291130, 0x85a87b884d2cd508, 0xc014664ac8, 0x11, 0x1, 0xc02e290ff0)\n\t/__w/cortex/cortex/pkg/querier/worker/scheduler_processor.go:160 +0x9a\ngithub.com/cortexproject/cortex/pkg/querier/worker.(*schedulerProcessor).querierLoop.func1(0x2d11498, 0xc001ab1a80, 0xc044695680, 0xc00071a4b0, 0x2d33c08, 0xc006903350, 0xc058353c80, 0x10)\n\t/__w/cortex/cortex/pkg/querier/worker/scheduler_processor.go:144 +0x1f8\ncreated by github.com/cortexproject/cortex/pkg/querier/worker.(*schedulerProcessor).querierLoop\n\t/__w/cortex/cortex/pkg/querier/worker/scheduler_processor.go:129 +0x106\n"
`, anything else?

**Comment by yeya24** [comment]
@yk-zheng-zz It looks like https://github.com/cortexproject/cortex/blob/v1.11.0/pkg/querier/block.go#L115 `c.Raw` is probably nil so it caused panic.
`c.Raw` means the block is probably a downsampled block in Thanos and I guess `thanosconvert` doesn't convert downsampled blocks metadata but you uploaded all blocks from Thanos bucket to the Cortex bucket?

That's just my guess but I highly suspect that. Maybe try removing all downsampled blocks and query again.

**Comment by yk-zheng-zz** [comment]
@yk-zheng-zz how could I know which block is downsampled block?

**Comment by yeya24** [comment]
By checking your block's meta.json file. If it is a downsampled block the downsample section is not 0. I think the Thanos bucket tool list also works.

**Comment by yeya24** [comment]
Cool. I will close this issue if it works for you. Opened a pr #5006 to add a note about downsampled blocks.
