### ISSUE TITLE
Remove support of `reject_old_samples` and `reject_old_samples_max_age` in favour of Out Of Order Samples support

### ISSUE THREAD

**Issue by alvinlin123** [cortexproject/cortex#4990]
We are likely to release [out of order sample support](https://github.com/cortexproject/cortex/pull/4964/files) in Release 1.15, which deprecates `reject_old_samples` and `reject_old_samples_max_age`. As promised in https://cortexmetrics.io/docs/configuration/v1guarantees/, we will keep the deprecated flags for 2 minor releases, so we will remove the 2 flags in release 1.17.

**Comment by yeya24** [comment]
Based on the dicussion from https://github.com/cortexproject/cortex/pull/4964, the new OOO feature cannot cover all use cases of `reject_old_samples` and `reject_old_samples_max_age` so let's not deprecate these flags for now.
