### ISSUE TITLE
Support redis caching bucket

### ISSUE THREAD

**Issue by yeya24** [cortexproject/cortex#5049]
**Is your feature request related to a problem? Please describe.**
Right now for caching bucket in store gateway, only memcached is supported as the backend.
Redis also has a quite large user base and it has some nice features like client side caching.
Thanos is working on the client side caching feature https://github.com/thanos-io/thanos/pull/5593 so it would be nice to reuse it in Cortex.

**Describe the solution you'd like**
Since Cortex uses Thanos's cacheing bucket library directly so we should have it supported here pretty easy. We just need to expose the feature through configs.

**Describe alternatives you've considered**

**Additional context**

**Comment by wgliang** [comment]
This is a great feature, very much looking forward to it, we also have the same appeal. Each (cortex) cluster needs to create 3 memcached nodes, which is somewhat unacceptable to me, and I prefer to use a redis to handle it.

**Comment by wgliang** [comment]
Are `index` and `metadata` data also considered to support switching to redis?

**Comment by yeya24** [comment]
@wgliang Yeah I think so. Having the caching bucket implemented will cover both `chunks` and `metadata` cache. For `index` let me create another issue to track.

**Comment by yeya24** [comment]
I believe this can be closed.
