### ISSUE TITLE
Support to prometheus native histogram

### ISSUE THREAD

**Issue by jeromeinsf** [cortexproject/cortex#5060]
**Is your feature request related to a problem? Please describe.**
Experimental native histogram support was released with [Prometheus v0.40.x](https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md#2400--2022-11-08). 

**Describe the solution you'd like**
We should implement native histogram support (behind a feature flag) 

**Describe alternatives you've considered**

**Additional context**

**Comment by amouhadi** [comment]
just checking if there is any plan for supporting prometheus native histogram
 great news opentelemetry collector now supports the conversion as well
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17370

**Comment by friedrichg** [comment]
@amouhadi yes that is the plan

**Comment by friedrichg** [comment]
https://github.com/cortexproject/cortex/pull/5289 this tracks how many samples for this histogram is cortex dropping. It's a start

**Comment by hkfgo** [comment]
Hey just checking in again to see if anything's changed. Is native histogram support still on the roadmap?

**Comment by yeya24** [comment]
Yeah I believe it is still on the roadmap. We need to wait our upstream project Thanos to support native histograms first.

**Comment by yeya24** [comment]
If I understand correctly, Thanos already supports native histogram on all components other than downsampling.
We should start integrating with native histograms on Cortex

**Comment by gburton1** [comment]
How's the checklist above looking? Any recent updates?

**Comment by hkfgo** [comment]
I see an August date for native histogram support, under the `cortex` project page. Is that date an estimate?

**Comment by yeya24** [comment]
Thanks. I updated the checklist above.
I think the ingestion path and query path are almost done. Things left:
- Ruler
- Querier queries histogram iterator when asked for float histogram

Also some tests need to be added.
