### ISSUE TITLE
shuffle_sharding_ingesters_lookback_period config doesn't work

### ISSUE THREAD

**Issue by marianafranco** [cortexproject/cortex#5086]
**Describe the bug**

During some experiments with shuffle sharding I noticed that queries are always going to all ingesters instead of going to only the ones in the tenant's subring. The problem seems to be related to the `-querier.shuffle_sharding_ingesters_lookback_period` config.

According to the cortex docs:

```
# When distributor's sharding strategy is shuffle-sharding and this setting is >
# 0, queriers fetch in-memory series from the minimum set of required ingesters,
# selecting only ingesters which may have received series since 'now - lookback
# period'. The lookback period should be greater or equal than the configured
# 'query store after' and 'query ingesters within'. If this setting is 0,
# queriers always query all ingesters (ingesters shuffle sharding on read path
# is disabled).
# CLI flag: -querier.shuffle-sharding-ingesters-lookback-period
[shuffle_sharding_ingesters_lookback_period: <duration> | default = 0s]
```

However, in the code I see that the config that is passed to the `ShuffleShardWithLookback` function is the distributor's `ShuffleShardingLookbackPeriod`:

https://github.com/cortexproject/cortex/blob/faf193e14d33321760b9da4028bdd5321af25685/pkg/distributor/query.go#L117-L124

The distributor's `ShuffleShardingLookbackPeriod` is dynamically injected with the querier's `ShuffleShardingIngestersLookbackPeriod` during distributor's initialization:

https://github.com/cortexproject/cortex/blob/fe25f6600d7da0f260dd95069a44222f555da73c/pkg/cortex/modules.go#L195

My understand is that the `initDistributorService` method is not called during queriers initialization so the distributors `ShuffleShardingLookbackPeriod` will be never set which results on the queries going to all ingesters in the ring, ignoring the `-querier.shuffle_sharding_ingesters_lookback_period` config.

**To Reproduce**
1. Start Cortex (SHA or version): 1.14.1
2. Enable shuffle sharding on the write and read path
3. Enable tracing on queriers
4. Set `-querier.shuffle_sharding_ingesters_lookback_period` to bigger than 0
5. Perform some querier
6. Check the trace to see that queriers always query all ingesters

**Expected behavior**
I expected queries to go only to the ingesters in the tenant's subring.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Additional Context**

None.

**Comment by alanprot** [comment]
humm.. i think that the distributors service is initialized during querier initialization. We can see the dependency graph here:

https://github.com/cortexproject/cortex/blob/0d4cd74d5b273045d928bc5d54aa8d881b3444b3/pkg/cortex/modules.go#L738-L766


Relevant part:
```
		Querier:                  {TenantFederation},
		TenantFederation:         {Queryable},
		Queryable:                {Overrides, DistributorService, Overrides, DeleteRequestsStore, Ring, API, StoreQueryable, MemberlistKV},

```

**Comment by marianafranco** [comment]
You are right @alanprot. There was an error on my config, shuffle sharding on the read path is working now. Closing this.
