### ISSUE TITLE
unnecessary `replace` in go.mod for weaveworks/common

### ISSUE THREAD

**Issue by ryepup** [cortexproject/cortex#5087]
https://github.com/cortexproject/cortex/blob/0d4cd74d5b273045d928bc5d54aa8d881b3444b3/go.mod#L228

This is no longer true; after https://github.com/weaveworks/common/pull/254 and https://github.com/weaveworks/common/pull/262, it supports grpc v1.47.0

**Comment by ryepup** [comment]
related to https://github.com/grafana/loki/issues/8085

**Comment by kama910** [comment]
Hello, may I take this issue please?

**Comment by alanprot** [comment]
Yeah! go ahead!
