### ISSUE TITLE
Switch Cortex Ruler to query Query Frontend

### ISSUE THREAD

**Issue by yeya24** [cortexproject/cortex#5105]
**Is your feature request related to a problem? Please describe.**
As we can see from the Cortex architecture https://cortexmetrics.io/docs/architecture/, Ruler queries ingesters (and store gateways) to get data for rules evaluation. This works fine currently but it hard to reuse some features supported in query frontend like vertical query sharding to make rule evaluation faster.

By switching Ruler to query Query Frontend, it simplifies the current architecture to make Query Frontend the entrypoint for both external and internal queries. Ruler components can use less resources as it doesn't need to embed a querier anymore.

**Describe the solution you'd like**
This feature should be behind a feature flag. If the flag is specified, Ruler will query Query Frontend instead. The implementation should be similar to how Thanos does https://github.com/thanos-io/thanos/blob/main/cmd/thanos/rule.go#L795, by having a custom query func and send HTTP requests to query frontend.

**Describe alternatives you've considered**

**Additional context**

**Comment by xuyangwang0825** [comment]
Hi @yeya24!
I'm interested in this issue and would like to work on it under the LFX Mentorship. I've started studying the Cortex architecture and how Thanos do the query.

**Comment by yeya24** [comment]
Hi @xuyangwang0825, thanks for expressing interest in this project. Feel free to apply through the LFX website!

**Comment by mallikpramod** [comment]
Hello @yeya24 
it's Pramod Kumar Mallik, i get to know about cortex quite some day ago and i started learning and searching about it, and i found it quite interesting mainly about partitioning compactor and vertical query sharding. 
So i would like to join with this project and being guided by you.

**Comment by yeya24** [comment]
Hi @mallikpramod, please apply in the LFX mentorship website but I don't think I am mentoring this project. We have @alvinlin123 and @qinxx108 mentoring it.

**Comment by xuyangwang0825** [comment]
Hi @yeya24 
May I ask if not receiving any notifications means that I'm not selected for the project? My status on the LFX portal still shows as pending.

**Comment by yeya24** [comment]
@xuyangwang0825 Yes, selected mentee name should be in the LFX project page.

**Comment by xuyangwang0825** [comment]
🥹

**Comment by SungJin1212** [comment]
@yeya24 
I interested in this issue. Can I address this issue?

**Comment by yeya24** [comment]
Hi @SungJin1212, it would be great if you could start a proposal outlining possible approaches and alternatives.

**Comment by SungJin1212** [comment]
@yeya24 
I was thinking below approaches. Could you please take a look?
1. Define _queryFrontendQueryable_ implementing Select func querying to the query frontend using prom client like the thanos.
2. In ruler init part on modules.go, initiate the manager using _queryFrontendQueryable_

**Comment by SungJin1212** [comment]
@yeya24 
I make a draft pr. (https://github.com/cortexproject/cortex/pull/6151/files) I would appreciate some guidance.
