### ISSUE TITLE
Need help: consistency check failed because some blocks were not queried: 01GR9A9WN8S0282B110CFVCA9M

### ISSUE THREAD

**Issue by Marcusfve** [cortexproject/cortex#5129]
Hey folks.
I need little bit help with Cortex configuration.
We are using Docker swarm to run Cortex cluster, every component on its own container and we have 3 of every component. (Replication factor = 3)
The problem is that when we query 30 days worth of data in grafana then sometimes an error pops up.
`internal: expanding series: consistency check failed because some blocks were not queried: 01GR9A9WN8S0282B110CFVCA9M`
5 mins - 2 days of data is okay, no problem. But problem comes when we query 30 days worth of data. And the error is not constant, sometimes it comes up, then goes away and then later it comes up again but with new block with failed consistency check.

And maybe these 2 errors are related to that problem
`expanded matching posting: get postings: read postings range: get range reader: The specified key does not exist.`

`msg="consistency check failed" attempt=3 missingblocks=01GR8WJE58NGRT84W1GCJ54PH5`

Cortex, version 1.11.1
We use docker volumes for persistent storage.
Minio S3 Object Store.
Nginx redirects prometheus remote write between 3 distributors and also 3 query frontends are behind nginx ( grafana --> nginx ---> query frontend )

I put only 1 ingester, 1 distributor and so on configuration here because ingester1, ingester2, ingester3 are with identical configuration but they are on different VM, they are in consul ring.

Can someone take a look on my configuration and confirm that it looks okay?

Feel free to ask for more information.

Docker compose file:

`version: '3.9'

services:

  distributor1:
    hostname: distributor1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    image: cortex
    networks:
      - cortex
    ports:
      - "9009:9009"
      - "9095:9095"
    volumes:
      - /srv/certs:/etc/cortex/certs
    command:
      -config.file=/etc/cortex/cortex.yaml
      -server.http-tls-cert-path=/etc/cortex/certs/server.cer
      -server.http-tls-key-path=/etc/cortex/certs/server.key
      -target=distributor
      -distributor.ring.store=consul
      -distributor.ring.consul.hostname=consul:8500
      -distributor.ingestion-rate-limit-strategy=global
      -consul.hostname=consul:8500
      -distributor.extend-writes=true
      -auth.enabled=true
      -distributor.health-check-ingesters=true
      -distributor.ingestion-rate-limit=60000
      -distributor.replication-factor=3
      -distributor.shard-by-all-labels=true
      -ring.heartbeat-timeout=10m
      -validation.reject-old-samples=true
      -validation.reject-old-samples.max-age=12h
      -ingester.client.grpc-compression=snappy
      -distributor.ring.prefix=collectors/
      -blocks-storage.backend=s3
      -blocks-storage.s3.bucket-name=
      -blocks-storage.s3.endpoint=
      -blocks-storage.s3.access-key-id=
      -blocks-storage.s3.secret-access-key=
      -store.engine=blocks
      -ingester.lifecycler.interface=eth0
      -ring.prefix=collectors/
      -blocks-storage.tsdb.block-ranges-period=2h
      -blocks-storage.tsdb.dir=/data/tsdb
      -ring.store=consul
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 3048M
      placement:
        constraints: [node.hostname == node1]

  ingester1:
    hostname: ingester1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    image: cortex
    networks:
      - cortex
    ports:
      - "9008:9009"
      - "9098:9095"
    volumes:
      - /srv/certs:/etc/cortex/certs
      - ingester-data:/data
    command:
      -config.file=/etc/cortex/cortex.yaml
      -server.http-tls-cert-path=/etc/cortex/certs/server.cer
      -server.http-tls-key-path=/etc/cortex/certs/server.key
      -target=ingester
      -ring.store=consul
      -consul.hostname=consul:8500
      -distributor.replication-factor=3
      -blocks-storage.backend=s3
      -auth.enabled=true
      -blocks-storage.s3.bucket-name=
      -blocks-storage.s3.endpoint=
      -blocks-storage.s3.access-key-id=
      -blocks-storage.s3.secret-access-key=
      -store.engine=blocks
      -ingester.lifecycler.interface=eth0
      -ring.prefix=collectors/
      -blocks-storage.tsdb.block-ranges-period=2h
      -blocks-storage.tsdb.dir=/data/tsdb
      -blocks-storage.tsdb.retention-period=96h
      -blocks-storage.tsdb.ship-interval=1m
      -distributor.health-check-ingesters=true
      -distributor.shard-by-all-labels=true
      -ingester.heartbeat-period=15s
      -ingester.join-after=0s
      -ingester.max-global-series-per-metric=1500000
      -ingester.max-series-per-metric=1500000
      -ingester.num-tokens=512
      -ingester.unregister-on-shutdown=true
      -ring.heartbeat-timeout=10m
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 35000M
      placement:
        constraints: [node.hostname == node1]

  querier1:
    hostname: querier1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    image: cortex
    networks:
      - cortex
    ports:
      - "9003:9009"
      - "9093:9095"
    volumes:
      - /srv/certs:/etc/cortex/certs
    command:
      -config.file=/etc/cortex/cortex.yaml
      -target=querier
      -blocks-storage.backend=s3
      -server.http-tls-cert-path=/etc/cortex/certs/server.cer
      -server.http-tls-key-path=/etc/cortex/certs/server.key
      -blocks-storage.s3.bucket-name=
      -auth.enabled=true
      -blocks-storage.s3.endpoint=
      -blocks-storage.s3.access-key-id=
      -blocks-storage.s3.secret-access-key=
      -ring.store=consul
      -log.level=debug
      -blocks-storage.bucket-store.sync-dir=/data/tsdb
      -consul.hostname=consul:8500
      -store-gateway.sharding-ring.store=consul
      -store-gateway.sharding-ring.consul.hostname=consul:8500
      -store-gateway.sharding-ring.replication-factor=3
      -store-gateway.sharding-enabled=true
      -distributor.replication-factor=3
      -distributor.shard-by-all-labels=true
      -distributor.health-check-ingesters=true
      -querier.frontend-address=query-frontend:9092
      -store.engine=blocks
      -blocks-storage.bucket-store.ignore-deletion-marks-delay=1h
      -querier.max-concurrent=8
      -querier.query-ingesters-within=13h
      -querier.query-store-after=12h
      -querier.worker-parallelism=4
      -store.max-query-length=768h
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4000M
      placement:
        constraints: [node.hostname == node1]

  store-gateway1:
    hostname: store-gateway1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    image: cortex
    networks:
      - cortex
    ports:
      - "9004:9009"
      - "9094:9095"
    volumes:
      - /srv/certs:/etc/cortex/certs
      - store-gateway-data:/data
    command:
      -config.file=/etc/cortex/cortex.yaml
      -target=store-gateway
      -log.level=debug
      -store-gateway.sharding-enabled=true
      -server.http-tls-cert-path=/etc/cortex/certs/server.cer
      -server.http-tls-key-path=/etc/cortex/certs/server.key
      -store-gateway.sharding-ring.store=consul
      -store-gateway.sharding-ring.consul.hostname=consul:8500
      -store-gateway.sharding-ring.replication-factor=3
      -store-gateway.sharding-strategy=default
      -blocks-storage.backend=s3
      -auth.enabled=true
      -blocks-storage.s3.bucket-name=
      -blocks-storage.s3.endpoint=
      -blocks-storage.s3.access-key-id=
      -blocks-storage.s3.secret-access-key=
      -store-gateway.sharding-ring.wait-stability-min-duration=0
      -blocks-storage.bucket-store.sync-dir=/data/tsdb
      -store.engine=blocks
      -server.grpc.keepalive.ping-without-stream-allowed=true
      -server.grpc.keepalive.min-time-between-pings=10m
      -blocks-storage.bucket-store.ignore-deletion-marks-delay=1h
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4000M
      placement:
        constraints: [node.hostname == node1]

  
  query-frontend1:
    hostname: query-frontend1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    image: cortex
    networks:
      - cortex
    ports:
      - "9002:9009"
      - "9092:9095"
    volumes:
      - /srv/certs:/etc/cortex/certs
    command:
      -config.file=/etc/cortex/cortex.yaml
      -server.http-tls-cert-path=/etc/cortex/certs/server.cer
      -server.http-tls-key-path=/etc/cortex/certs/server.key
      -target=query-frontend
      -api.response-compression-enabled=true
      -querier.cache-results=true
      -auth.enabled=true
      -querier.align-querier-with-step=false
      -querier.split-queries-by-interval=24h
      -store.max-query-length=12000h
      -server.grpc-max-recv-msg-size-bytes=104857600
      -server.grpc.keepalive.min-time-between-pings=10s
      -server.grpc.keepalive.ping-without-stream-allowed=true
      -server.http-write-timeout=1m
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
      placement:
        constraints: [node.hostname == node1]

  
  ruler1:
    image: cortex
    networks:
      - cortex
    hostname: ruler1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    ports:
      - "9001:9009"
      - "9091:9095"
    volumes:
      - /srv/certs:/etc/cortex/certs
    command:
      -config.file=/etc/cortex/cortex.yaml
      -target=ruler
      -api.response-compression-enabled=true
      -server.http-tls-cert-path=/etc/cortex/certs/server.cer
      -server.http-tls-key-path=/etc/cortex/certs/server.key
      -blocks-storage.backend=s3
      -auth.enabled=true
      -blocks-storage.s3.bucket-name=cortex
      -blocks-storage.s3.endpoint=
      -blocks-storage.s3.access-key-id=
      -blocks-storage.s3.secret-access-key=
      -store.engine=blocks
      -blocks-storage.bucket-store.sync-dir=/data/tsdb
      -ring.store=consul
      -consul.hostname=consul:8500
      -distributor.extend-writes=true
      -distributor.health-check-ingesters=true
      -distributor.replication-factor=3
      -distributor.shard-by-all-labels=true
      -experimental.ruler.enable-api=true
      -querier.query-ingesters-within=13h
      -querier.query-store-after=12h
      -ruler-storage.backend=s3
      -ruler-storage.s3.bucket-name=ruler
      -ruler-storage.s3.endpoint=
      -ruler-storage.s3.secret-access-key=
      -ruler-storage.s3.access-key-id=
      -ruler.enable-sharding=true
      -ruler.ring.store=consul
      -ruler.ring.consul.hostname=consul:8500
      -store-gateway.sharding-enabled=true
      -store-gateway.sharding-ring.consul.hostname=consul:8500
      -store-gateway.sharding-ring.replication-factor=3
      -store-gateway.sharding-ring.store=consul
      -ruler.alertmanager-url=https://url/alertmanager
      -store.engine=blocks
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4000M
      placement:
        constraints: [node.hostname == node1]

 

  alertmanager1:
    hostname: alertmanager1
    image: cortex
    networks:
      - cortex
    ports:
      - "9000:9009"
      - "9090:9095"

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - /srv/certs:/etc/cortex/certs
      - alertmanager-data:/data
      - /srv/alertmanager/:/etc/cortex/alertmanager/
    command:
      -config.file=/etc/cortex/cortex.yaml
      -target=alertmanager
      -auth.enabled=true
      -alertmanager-storage.backend=s3
      -server.http-tls-cert-path=/etc/cortex/certs/server.cer
      -server.http-tls-key-path=/etc/cortex/certs/server.key
      -alertmanager-storage.s3.secret-access-key=
      -alertmanager-storage.s3.access-key-id=
      -alertmanager-storage.s3.endpoint=
      -alertmanager-storage.s3.bucket-name=
      -alertmanager.storage.path=/data
      -alertmanager.web.external-url=/alertmanager
      -alertmanager.configs.fallback=/etc/cortex/alertmanager/alertmanager.yml
      -experimental.alertmanager.enable-api=true
      -alertmanager.sharding-enabled=true
      -alertmanager.sharding-ring.store=consul
      -alertmanager.sharding-ring.consul.hostname=consul:8500
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
      placement:
        constraints: [node.hostname == node1]

  
  compactor1:
    hostname: compactor1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    image: cortex
    networks:
      - cortex
    ports:
      - "9006:9009"
      - "9096:9095"
    volumes:
      - /srv/certs:/etc/cortex/certs
      - compactor-data:/data
    command:
      -target=compactor
      -config.file=/etc/cortex/cortex.yaml
      -blocks-storage.backend=s3
      -server.http-tls-cert-path=/etc/cortex/certs/server.cer
      -server.http-tls-key-path=/etc/cortex/certs/server.key
      -blocks-storage.s3.bucket-name=
      -auth.enabled=true
      -blocks-storage.s3.endpoint=
      -blocks-storage.s3.access-key-id=
      -blocks-storage.s3.secret-access-key=
      -compactor.sharding-enabled=true
      -compactor.ring.store=consul
      -compactor.ring.prefix=collectors/
      -compactor.ring.consul.hostname=consul:8500
      -store.engine=blocks
      -compactor.data-dir=/data
      -compactor.block-ranges=2h,12h,24h
      -compactor.blocks-retention-period=0
      -compactor.cleanup-interval=15m
      -compactor.compaction-concurrency=1
      -compactor.compaction-interval=30m
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4048M
      placement:
        constraints: [node.hostname == node1]

networks:
  cortex:
    name: cortex
    driver: overlay
    attachable: true

volumes:
  ingester-data:
  store-gateway-data:
  compactor-data:
  alertmanager-data:`

**Comment by Marcusfve** [comment]
`level=warn ts=2023-02-07T08:19:07.122110325Z caller=logging.go:72 traceID=3908e41cfe906abe msg="GET /prometheus/api/v1/query_range?end=1675378800&query=sum+by%28container%29+%28rate%28container_cpu_usage_seconds_total%7Bcontainer%21%3D%22POD%22%2Cimage%21%3D%22%22%2Cnamespace%3D%22test-1234%22%2Cpod%3D%22audit-service-89768578d-fnbcd%22%7D%5B5m%5D%29%29&start=1675296000&step=3600 (500) 129.383642ms Response: \"{\\\"status\\\":\\\"error\\\",\\\"errorType\\\":\\\"internal\\\",\\\"error\\\":\\\"expanding series: consistency check failed because some blocks were not queried: 01GR9A9WN8S0282B110CFVCA9M\\\"}\" ws: false; X-Scope-Orgid: test1234; uber-trace-id: 3908e41cfe906abe:6e25aadef82778b1:7c867e9e4d0c4e4d:0; "`

This is the full error log message.

**Comment by friedrichg** [comment]
Thanks for the detail.

I am not too familiar with docker swarm, but I think you are limiting memory for store-gateways to 4Gb and cpu to 1. 

1. Setting cpu limits is known to cause latency issues in kubernetes, as well as minimizing resource usage in one node. I would expect the same in docker swarm, I recommend you don't set them and instead you increase priority for ingesters and distributors over the rest (Ingestion is always more important than reading). I am not sure how that is done in docker swarm but I bet it's possible. Only set up limits if you see node issues, but otherwise don't use cpu limits. Memory limits is fine to use though.

2. -compactor.blocks-retention-period=0 means blocks in minio are growing non stop, the more blocks you have in minio the more store-gateways you will need space, memory and cpu to serve those blocks. I don't know if that is what you are currently facing, but this eventually will become a problem. The experience shows that the number of store-gateways grows from the time a new cluster is created till block-retention-period has passed.

3. The memory for store-gateways seems really low. Specially if running same amount of ingesters as store-gateways, which I think is the case. It might be possible the store-gateway memory was ok in the beginning, and as blocks grew, now there is a problem. https://github.com/cortexproject/cortex-jsonnet/blob/main/cortex/store-gateway.libsonnet#L44

4. Yes, enable bucket-index. it should be enabled in querier and store-gateway.
https://github.com/cortexproject/cortex-jsonnet/blob/5e810e9ce28cc0640e810a355509a6536daad402/cortex/tsdb-config.libsonnet#L77-L80

5. Enable index-header-lazy to reduce store-gateway memory usage as well as reduce minio read usage.
https://github.com/cortexproject/cortex-jsonnet/blob/main/cortex/store-gateway.libsonnet#L28-L31

6. You have no cache configure, it's recommended to run memcache or use memcache. Memcache not only reduces response time, but also reduces memory usage during querying.
There is chunks, index and metadata cache, and all three can be used by store-gateways.
https://github.com/cortexproject/cortex-jsonnet/blob/5e810e9ce28cc0640e810a355509a6536daad402/cortex/tsdb-config.libsonnet#L37-L74

8. Use the [cortex-mixin](https://github.com/cortexproject/cortex-jsonnet/tree/main/cortex-mixin) dashboards and alerts. Dashboards, runbook and alerts will help you track and fix problems.

Specially for this case is the Object Storage dashboard which can show you p99 latency and errors from store-gateways to object storage and the Reads dashboard that can show you errors and latency coming from store-gateways.

If you have them configured you can paste a screenshot of both dashboards to help you more.  I think is very hard to fix cortex without its internal metrics only looking at logs.

-----
Less important:

For sharing logs and configuration a github gist can keep the formatting https://gist.github.com/

it's kind of weird that the org_id=asd1234 and X-Scope-Orgid is test-1234. I would expect both to be the same. I think you doctored it a bit to hide the real tenant. That is fine :)
