### ISSUE TITLE
Input problem with Custom Analyzer

### ISSUE THREAD

**Issue by ManFromTheM00n** [cortexproject/cortex#5131]
**Describe the bug**
I am trying to edit an existing cortex analyzer (Urlscan_io_Search_0_1_1) to add a new feature. I want to add to this existing analyzer an extra option for a regex based search through Urlscan's capability to search using URL keyword regex. The issue raises when I use a "\\" character and cortex adds an extra "\\" character.

**To Reproduce**
1. Create or edit an analyzer and use as datatype regexp in Service Interaction File.
2. Use the analyzer and give as an input a regex with "\\" character in. For example "http\\:\\/\\/domain\\.test"
3. Then the cortex will change the regex into "http\\\\:\\\\/\\\\/domain\\\\.test"
**Expected behavior**
In this occasion we will expect to use "\\" character as it is without cortex adding an extra "\\" character".

The same problem rises when running OpenCTI_SearchObservables_2_0 analyzer with regexp option.

**Comment by friedrichg** [comment]
I think you are looking for https://github.com/TheHive-Project/Cortex. (Just a guess!)

**Comment by ManFromTheM00n** [comment]
> I think you are looking for https://github.com/TheHive-Project/Cortex. (Just a guess!)

-___-.  You are right. Ty
