### ISSUE TITLE
Support enabled_tenants and disabled_tenants in store-gateway

### ISSUE THREAD

**Issue by friedrichg** [cortexproject/cortex#5133]
**Is your feature request related to a problem? Please describe.**
enabled_tenants and disabled_tenants in rulers, compactors and alertmanager is a nice feature to run different ruler and compactors and alertmanager for different tenants.
It should be possible to do the same in store-gateway

**Describe the solution you'd like**
It should be possible to define -store-gateway.enabled-tenants and -store-gateway.disabled-tenants to enable specific tenants in the store-gateway cluster

**Describe alternatives you've considered**
None, I think this one is consistent with the rest of the options.

**Additional context**
None

**Comment by johurul000** [comment]
@friedrichg Is it beginner friendly?

**Comment by moki1202** [comment]
@friedrichg Can I work on this?

**Comment by friedrichg** [comment]
@moki1202 yes
@moki1202 sure, go ahead. Another thing you can do as a beginner is to review other PRs and give suggestions that have not been given.

**Comment by moki1202** [comment]
> @moki1202 yes @moki1202 sure, go ahead. Another thing you can do as a beginner is to review other PRs and give suggestions that have not been given.

I would love to! I'll have a look at some of the PRs.
