### ISSUE TITLE
Upgrade cortexto use go 1.20

### ISSUE THREAD

**Issue by alanprot** [cortexproject/cortex#5147]
Go 1.20 was released: https://go.dev/doc/go1.20

**Comment by alvinlin123** [comment]
@mehrdadbn9  there is also build image that need to be upgraded like here: https://github.com/cortexproject/cortex/commit/5347bf4379607d0edc9b275a6171bb043a8b9860

**Comment by mehrdadbn9** [comment]
thanks for your answer 
please assign me
as i understood i should change dockerfile so happy to do it
