### ISSUE TITLE
Error: exceeded chunks limit - no flag to increase limit

### ISSUE THREAD

**Issue by jtweaver** [cortexproject/cortex#5149]
**Describe the bug**
I can't find a way to increase the chunk limit per query. From this comment, it looks like there should be a flag `-store.query-chunk-limit` to increase the limit, but I see no documentation for that flag or really any reference to it anywhere.
https://github.com/cortexproject/cortex/issues/4330#issuecomment-871463177

This is the error I get:
execution: expanding series: error querying tenant_id <the_tenant>: failed to receive series from 192.18.29.156:9095: rpc error: code = Code(422) desc = fetch series for block 01GS9S165XPR46FQZR26GYCFSA: exceeded chunks limit: rpc error: code = Code(422) desc = limit 2000000 violated (got 2000033)

How can we increase that limit?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Environment:**
 - Infrastructure: Kubernetes

**Additional Context**

**Comment by friedrichg** [comment]
that limit got renamed recently https://github.com/cortexproject/cortex/blob/master/CHANGELOG.md#1140-2022-12-02
Which cortex version are you using?

**Comment by jtweaver** [comment]
1.14.0 right now, so yeah that would make sense. Looks like it's changed to `-querier.max-fetched-chunks-per-query`. That seems to work. Thanks.
