### ISSUE TITLE
Unify README.md with /docs/_index.md

### ISSUE THREAD

**Issue by friedrichg** [cortexproject/cortex#5152]
**Describe the bug**
Both files have roughly the same content, makes little sense having this duplication.

**Expected behavior**
Ensure updated content is in only one file.
We can generate/copy from docs/_index.md to README.md

**Comment by ankur12-1610** [comment]
I would like to work on this issue :)

**Comment by dogukanteber** [comment]
Hey @ankur12-1610 

Are you still working on this issue? If not, I would like to open a PR for this
