### ISSUE TITLE
Tests needed for zstd compression

### ISSUE THREAD

**Issue by friedrichg** [cortexproject/cortex#5184]
**Describe the bug**
https://github.com/cortexproject/cortex/pull/5092 added  zstd compression but there are no test cases for it

**Expected behavior**
Test cases similar to https://github.com/cortexproject/cortex/blob/master/pkg/util/grpcencoding/snappy/snappy_test.go
should be created

**Comment by ankur12-1610** [comment]
I love writing tests, can I?

**Comment by alanprot** [comment]
This PR moved the test from snappy to run on all compression options:

https://github.com/cortexproject/cortex/pull/5215
