### ISSUE TITLE
setting -distributor.ingestion-tenant-shard-size to 0 throws error

### ISSUE THREAD

**Issue by sanyamjain22** [cortexproject/cortex#5189]
**Describe the bug**
setting -distributor.ingestion-tenant-shard-size to 0 throws error . According to the documentation setting this flag to 0 should disable the shuffle sharding. However it throws validation error that value can not be 0.

**To Reproduce**

1. Set -distributor.ingestion-tenant-shard-size to 0
2. Deploy distributors

**Expected behavior**
Documentation should be clear.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

**Comment by friedrichg** [comment]
I am familiar with this. I saw it when I started using shuffle sharding for ingesters a long time ago. Ended up setting a bigger than 15 value for all users while configuring bigger shard size for larger users using overrides.

Fixing the docs seems like the easiest to do here. But I am wondering if we should instead fix the limit to do what the docs say. "0 should make all tenants use no sharding by default".

**Comment by dogukanteber** [comment]
I think that is better @friedrichg. I would like to fix this problem if we agree on what you propose.

I reproduced the error in my local system but before working on the issue, I would like to know whether I should fix the docs or fix the code
