### ISSUE TITLE
cardinality_limit is removed without any notice

### ISSUE THREAD

**Issue by sivadeepN** [cortexproject/cortex#5214]
**Describe the bug**
cardinality_limit is removed without any notice. Because of this all the pods crash looped because of failed validation. Also what is the replacement for this config

**To Reproduce**
upgrading cortex from 1.10.0 to 1.14.1 

**Expected behavior**
All deprecated configs should be added clearly in the changeLog
**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

**Comment by jeromeinsf** [comment]
@sivadeepN is the changelog mentioned by Friedrich enough?

**Comment by friedrichg** [comment]
Closing as there is no bug here.
We are also in slack, let us now if you have more issues/questions. https://github.com/cortexproject/cortex#getting-help
