### ISSUE TITLE
Store-Gateway histogram metrics are `NaN`

### ISSUE THREAD

**Issue by harry671003** [cortexproject/cortex#5216]
**Describe the bug**
- Some of the store-gateway histogram metrics are NaN.

```
# HELP cortex_bucket_store_series_data_fetched How many items of a data type in a block were fetched for a single series request.
# TYPE cortex_bucket_store_series_data_fetched summary
cortex_bucket_store_series_data_fetched{component="store-gateway",data_type="chunks",quantile="0.5"} NaN
cortex_bucket_store_series_data_fetched{component="store-gateway",data_type="chunks",quantile="0.95"} NaN
cortex_bucket_store_series_data_fetched{component="store-gateway",data_type="chunks",quantile="0.99"} NaN
cortex_bucket_store_series_data_fetched_sum{component="store-gateway",data_type="chunks"} 1.090387e+06
cortex_bucket_store_series_data_fetched_count{component="store-gateway",data_type="chunks"} 10534
cortex_bucket_store_series_data_fetched{component="store-gateway",data_type="postings",quantile="0.5"} NaN
cortex_bucket_store_series_data_fetched{component="store-gateway",data_type="postings",quantile="0.95"} NaN
cortex_bucket_store_series_data_fetched{component="store-gateway",data_type="postings",quantile="0.99"} NaN
cortex_bucket_store_series_data_fetched_sum{component="store-gateway",data_type="postings"} 7
cortex_bucket_store_series_data_fetched_count{component="store-gateway",data_type="postings"} 10534
cortex_bucket_store_series_data_fetched{component="store-gateway",data_type="series",quantile="0.5"} NaN
cortex_bucket_store_series_data_fetched{component="store-gateway",data_type="series",quantile="0.95"} NaN
cortex_bucket_store_series_data_fetched{component="store-gateway",data_type="series",quantile="0.99"} NaN
cortex_bucket_store_series_data_fetched_sum{component="store-gateway",data_type="series"} 2
cortex_bucket_store_series_data_fetched_count{component="store-gateway",data_type="series"} 10534
```

**To Reproduce**
- port-forward to a store-gateway pod and go to  `/metrics` endpoint.

**Comment by friedrichg** [comment]
These are summaries, not histograms.

https://github.com/cortexproject/cortex/blob/ed36a622550df39af2b75bf249ea29282bdf9f43/pkg/storegateway/bucket_store_metrics.go#L218

And I think this is how it was decided no observation should look like
https://github.com/prometheus/client_golang/issues/85

why is this a problem?

**Comment by yeya24** [comment]
Yeah I think this should is expected. Probably we could think about changing summary metric to histograms as we can't aggregate summary metrics over multiple store gateway instances.

**Comment by harry671003** [comment]
I was confused because I saw the NaNs and thought this was a bug.

I was tryng to gather information about p99 and p50 series fetched per query from store-gateways. We have these metrics in ingesters. `cortex_ingester_queried_series`. Would it be useful to have these histogram metrics?

**Comment by friedrichg** [comment]
We already have the thanos that uses histograms for these, we should fix the cortex code https://github.com/cortexproject/cortex/commit/da2ad99f2c258537701c2b427195029c838612df#r106535583
