### ISSUE TITLE
An error occurred within the plugin when using query-frontend

### ISSUE THREAD

**Issue by SuperMatt** [cortexproject/cortex#5252]
**Describe the bug**
An invalid query performed from Grafana against a Cortex Query-Frotned returns the error "An error occurred within the plugin". When performing this query directly against a Cortex Querier or a Prometheus datasource, a correct error is shown. See the below screenshots. The first is the correct response, the second is the incorrect one:
![Web capture_6-4-2023_81326_grafana yelpcorp com](https://user-images.githubusercontent.com/3635576/230302615-c2caa1c4-16f3-47a6-b13e-c1c44db31925.jpeg)

![Web capture_6-4-2023_81227_grafana yelpcorp com](https://user-images.githubusercontent.com/3635576/230302633-83400d1a-6b5c-4ec2-8f6c-c1b89971db62.jpeg)

**To Reproduce**
1. Start Cortex (v1.14.1 arm) via the helm chart (2.1.0) with the following components, configured with zone awareness across 3 zones
  a. nginx
  b. distributors
  c. ingesters
  d. store gateways (s3 backend)
  e. queriers
  f. query frontend
  g. query schedulers
  h. ruler
  i. compactor
2. Configure Grafana 9.3.6 with a datasource pointing at either the nginx or query frontends
3. Perform a basic broken query like `count by (job) (up})

**Expected behavior**
Expected to see `bad_data: invalid parameter "query": 1:19: parse error: unexpected character: '}' bad_data: 1:19: parse error: unexpected character: '}'`

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Additional Context**
A little bit of testing has shown that the issue only occurs when the Grafana datasource points to a query-frontend, but actually works correctly when pointed straight at a querier.

**Comment by SuperMatt** [comment]
I've just performed a couple of curls against the query-frontend and queriers and there is one difference which stands out, and that is that the query-frontend appears to be adding this header to the response: `Content-Type: text/plain; charset=utf-8`. Below you can see the two curl responses. The first one is from the query-frontend which has the `Content-Type` header, whereas the second one is querier, and it does not have this header.

```
root@cortex-a-nginx-7d9d96f8ff-r4f8b:/# curl "http://cortex-a-query-frontend:8080/prometheus/api/v1/query?query=up)" -H "X-Scope-OrgID: foobar" -v; echo
*   Trying 172.20.254.26:8080...
* Connected to cortex-a-query-frontend (172.20.254.26) port 8080 (#0)
> GET /prometheus/api/v1/query?query=up) HTTP/1.1
> Host: cortex-a-query-frontend:8080
> User-Agent: curl/7.74.0
> Accept: */*
> X-Scope-OrgID: foobar
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Vary: Accept-Encoding
< Date: Thu, 06 Apr 2023 08:03:13 GMT
< Content-Length: 131
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host cortex-a-query-frontend left intact
{"status":"error","errorType":"bad_data","error":"invalid parameter \"query\": 1:4: parse error: unexpected right parenthesis ')'"}


root@cortex-a-nginx-7d9d96f8ff-r4f8b:/# curl "http://cortex-a-querier:8080/prometheus/api/v1/query?query=up)" -H "X-Scope-OrgID: foobar" -v; echo
*   Trying 172.20.225.63:8080...
* Connected to cortex-a-querier (172.20.225.63) port 8080 (#0)
> GET /prometheus/api/v1/query?query=up) HTTP/1.1
> Host: cortex-a-querier:8080
> User-Agent: curl/7.74.0
> Accept: */*
> X-Scope-OrgID: foobar
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Results-Cache-Gen-Number: 
< Vary: Accept-Encoding
< Date: Thu, 06 Apr 2023 08:03:28 GMT
< Content-Length: 131
< 
* Connection #0 to host cortex-a-querier left intact
{"status":"error","errorType":"bad_data","error":"invalid parameter \"query\": 1:4: parse error: unexpected right parenthesis ')'"}
```

**Comment by yeya24** [comment]
Hi @SuperMatt, is this bug reproducible if you use the latest RC?

**Comment by SuperMatt** [comment]
Hi @yeya24 I can confirm that the problem is still there in the latest RC

**Comment by yeya24** [comment]
I am not sure why but I cannot reproduce it locally with the latest version. I am just running querier and query frontend binary locally and this is what I got.

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/25150124/231225469-a0de3dcd-7f51-4172-ac03-32667d108236.png">

**Comment by SuperMatt** [comment]
That's very odd. I'll have to do some testing tomorrow because I cannot think of any good reason why we would have a difference. I wonder if there's something in my config that's causing this.

**Comment by SuperMatt** [comment]
I've managed to do an at home test because I had a spare moment, and I was able to replicate this issue.

I used the Cortex Helm Chart in its current iteration and the following configuration for it:

```
helm install --namespace cortex --set="config.blocks_storage.backend=filesystem" cortex cortex-helm/cortex
```

I then pointed my Grafana instance in the same namespace directly at the frontend and it gave this error.

![image](https://user-images.githubusercontent.com/3635576/231247267-153158f1-b926-44f0-a357-493e9d6a3ebd.png)

This all suggests that there is something that the Cortex Helm Chart might be doing wrong/differently, causing the problem.

The same issue occurs when I upgrade the pods to use the latest rc of cortex itself.

**Comment by yeya24** [comment]
@SuperMatt Thanks, I think I can reproduce this now by enabling caching and splitting.

**Comment by yeya24** [comment]
https://github.com/cortexproject/cortex/pull/5260 This should fix the problem.

**Comment by yeya24** [comment]
@SuperMatt We got our latest image with the new fix. Can you please let us know, if the fix works for you? Thanks!
https://hub.docker.com/layers/cortexproject/cortex/master-67af431/images/sha256-01c6b8e4b71a780060fb80d73c2b88acc13717a5336e0599d15e1babe411019a?context=explore

**Comment by SuperMatt** [comment]
@yeya24 I can see this has already been cherry-picked for 1.15 so you can ignore me. Thanks all for your very fast turn around on this. I'd been seeing this issue for a while, but only recently had the brainspace for it.
