### ISSUE TITLE
"header line too long" from lite/localstack with -dynamodb.use-periodic-tables=true

### ISSUE THREAD

**Issue by meccanorak** [cortexproject/cortex#526]
It seems desirable for LOCAL cortex to use current schemas (ie same as DEV & LIVE) which isn't currently the case 

Currently DEV & LIVE are started with switch
    `-dynamodb.use-periodic-tables=true`
whereas LOCAL doesn't yet have this switch, with downside that LOCAL is unuseful for investigating anything related to schemas actually used by production

In principle this would "just" need above switch added to local/cortex/lite-dep.yaml in service-conf
In practice, if lite is left running like this for a while (?long enough for chunks to be flushed into localstack?)
range queries (possibly others) begin failing with
`QueryPages error: table=cortex_weekly_2482, err=SerializationError: failed decoding JSON RPC response caused by: header line too long`
From brief investigation, error originates within aws-sdk-go during processing of response data from localstack.
Maybe there's some difference between structure of data returned by localstack compared with dynamodb?

**Comment by aaron7** [comment]
> It seems desirable for LOCAL cortex to use current schemas (ie same as DEV & LIVE) which isn't currently the case

Agreed that it makes sense to use periodic tables locally. Feel free to make the change for our local k8s config in our private config repo.

> `QueryPages error: table=cortex_weekly_2482, err=SerializationError: failed decoding JSON RPC response caused by: header line too long`

I've looked into the problem briefly before but I didn't create an issue (sorry, I should have). DynamoDB should limit requests to pages of 1mb in size. http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.Pagination LocalStack should apply the same limit.

Could you try adding logging locally to see what page sizes we see https://github.com/weaveworks/cortex/blob/master/pkg/chunk/aws_storage_client.go#L281. 

We could also try explicitly setting a page size on the request by setting `QueryInput.Limit` to a small value https://github.com/weaveworks/cortex/blob/master/pkg/chunk/aws_storage_client.go#L235 https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/#QueryInput and observe the size of responses and whether pagination is happening with or without the explicit argument.

I added https://github.com/weaveworks/cortex/pull/502 to check that requests were being paginated in production. They are for some queries which suggest pagination is happening in production. You could perhaps query a local (non-cortex) prometheus instance for this metric to observe page sizes in local.

Thanks for looking into this.

**Comment by aaron7** [comment]
Thinking about this further, I'm now unsure whether it is related to pagination as the responses shouldn't be large enough to cause a problem, especially after it has only flushed the first chunks. 

It might be worth looking further at the requests made to localstack first and making sure it's not a problem with the communication between cortex and localstack instead.

**Comment by meccanorak** [comment]
I've experimented with @aaron7  suggestion of setting QueryInput.Limit to 5
No improvement - still fails in same way.

Other lines of investigation in same comment from @aaron7 look interesting ... but I'd need them expanded a bit in order for me to make sense of them

**Comment by gouthamve** [comment]
Closing this as lite doesn't exist anymore.
