### ISSUE TITLE
Deprecate & remove Heap Ballast

### ISSUE THREAD

**Issue by friedrichg** [cortexproject/cortex#5283]
**Is your feature request related to a problem? Please describe.**
Deprecate and later remove the heap ballast introduced in https://github.com/cortexproject/cortex/pull/1489

**Describe the solution you'd like**
Since 1.19 we can use GOMEMLIMIT with GOGC which is a better approach at the problem
See https://tip.golang.org/doc/gc-guide

**Describe alternatives you've considered**
Keeping the option is not ideal, as it has a bad usage of the memory

**Comment by yeya24** [comment]
Let's move this to release 1.17. Unfortunately we didn't get it for 1.16
