### ISSUE TITLE
Support other block storage options as a storage backend for runtime configuration file

### ISSUE THREAD

**Issue by anna-tran** [cortexproject/cortex#5292]
**Is your feature request related to a problem? Please describe.**
Currently Cortex reads the [runtime configuration file](https://cortexmetrics.io/docs/configuration/arguments/#runtime-configuration-file) from filesystem. Cortex should be able to support other storage backends that Cortex can read the configuration file from (e.g. S3) in order to better keep track of versioning and easier access.

This is already supported today for other Cortex configurations like
[blocks storage config](https://github.com/cortexproject/cortex/blob/909a090592b64c4dda5213681a6a7386316a5489/docs/blocks-storage/querier.md#blocks_storage_config).

**Describe the solution you'd like**
Inline the [`storage bucket config`](https://github.com/cortexproject/cortex/blob/master/pkg/storage/bucket/client.go) with the runtime configuration Config as done for other components like [rule store](https://github.com/cortexproject/cortex/blob/1ad8b03edbab2e4f305eee0b4e037fee52aceff4/pkg/ruler/rulestore/config.go#L16).

By default the storage backend will be `Filesystem`, the same as it is today.

**Comment by marianafranco** [comment]
This can be useful for k8s cortex installations with many per-user limits overrides which are unable to use a ConfigMap as the storage solution for runtime configs given its [1 MiB limit](https://kubernetes.io/docs/concepts/configuration/configmap/).

**Comment by marianafranco** [comment]
@anna-tran The idea is to allow something like this, right? 

```
runtime_config:
  # existent field
  [period: <duration> | default = 10s]

  # existent field
  [file: <string> | default = ""]

  [backend: <string> | default = "filesystem"]

  s3: 
      [endpoint: <string> | default = ""]

      [region: <string> | default = ""]

      [bucket_name: <string> | default = ""]
       ...

  filesystem:
      [dir: <string> | default = ""]

   gcs:
       [bucket_name: <string> | default = ""]
       
       [service_account: <string> | default = ""]
```

**Comment by anna-tran** [comment]
@marianafranco Yes, for now we can start with only s3 and filesystem as options for the backend and extend to other storage/cloud services

**Comment by marianafranco** [comment]
Don't we need the `runtime_config.file` since the S3 config don't have a way to specify the file name? 

https://github.com/cortexproject/cortex/blob/3d1315a553672faf6e0a883b443d58dca8b2db36/pkg/storage/bucket/s3/config.go#L60-L72

**Comment by yeya24** [comment]
> Don't we need the runtime_config.file since the S3 config don't have a way to specify the file name?

Yeah I think we can reuse that field for the filename for S3. Just wanna double check, do we have any use case of using dynamic file name? If not, then this should be good enough.

**Comment by alvinlin123** [comment]
Should we start with a proposal PR?

**Comment by anna-tran** [comment]
> do we have any use case of using dynamic file name

I think to keep it simple we’ll require the file name to be specified like we do today.

@alvinlin123 I will start the proposal PR for it today
