### ISSUE TITLE
Make Alert Manager MaxSendMsgSize and MaxRecvMsgSize configurable

### ISSUE THREAD

**Issue by emanlodovice** [cortexproject/cortex#5330]
**Is your feature request related to a problem? Please describe.**
We have a use case where we need to send a response that is much bigger than the current hard coded AM MaxSendMsgSize.
https://github.com/cortexproject/cortex/blob/master/pkg/alertmanager/alertmanager_client.go#L59 

**Describe the solution you'd like**
I see that based on the discussion is https://github.com/cortexproject/cortex/pull/4889 , the maintainers are not totally against the idea of exposing these limits to configuration. It was not added in the PR because there was no need for it at the time. We can make a change similar to this PR to expose the limits.

**Comment by yeya24** [comment]
I am up for the change. Feel free to open a pr for it!
