### ISSUE TITLE
Prometheus rewrite engine DoBatch: InstancesCount <= 0

### ISSUE THREAD

**Issue by babvin** [cortexproject/cortex#5361]
**Describe the bug**
Unable to write data from Prometheus to cortex HA config

Environment: Horizontally scale out example as shown in Getting Started
CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS          PORTS                                                                                      NAMESac6b6b2f8521   cortexproject/cortex:master-6a63df3   "/bin/cortex -config…"   52 minutes ago   Up 52 minutes   80/tcp, 0.0.0.0:9002->9009/tcp, :::9002->9009/tcp                                          cortex2
4f53e7016c66   cortexproject/cortex:master-6a63df3   "/bin/cortex -config…"   52 minutes ago   Up 52 minutes   80/tcp, 0.0.0.0:9001->9009/tcp, :::9001->9009/tcp                                          cortex1
61b945ba9c96   consul                                "docker-entrypoint.s…"   4 hours ago      Up 4 hours      8300-8302/tcp, 8500/tcp, 8301-8302/udp, 8600/tcp, 8600/udp                                 consul

Logs @ Cortex

ts=2023-05-25T13:59:58.731218109Z caller=logging.go:86 level=warn traceID=410f103c0dc8c5fb msg="POST /api/v1/push (500) 879.558µs Response: \"DoBatch: InstancesCount <= 0\\n\" ws: false; Content-Encoding: snappy; Content-Length: 10988; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.43.0; X-Prometheus-Remote-Write-Version: 0.1.0; "
ts=2023-05-25T13:59:58.732513183Z caller=logging.go:86 level=warn traceID=1b3c172653861778 msg="POST /api/prom/push (500) 856.49µs Response: \"DoBatch: InstancesCount <= 0\\n\" ws: false; Content-Encoding: snappy; Content-Length: 10988; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.43.0; X-Prometheus-Remote-Write-Version: 0.1.0; "
ts=2023-05-25T14:00:02.085360381Z caller=logging.go:86 level=warn traceID=5fee9b3ad7c6efe3 msg="POST /api/v1/push (500) 645.709µs Response: \"DoBatch: InstancesCount <= 0\\n\" ws: false; Content-Encoding: snappy; Content-Length: 15081; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.43.0; X-Prometheus-Remote-Write-Version: 0.1.0; "
ts=2023-05-25T14:00:02.085503028Z caller=logging.go:86 level=warn traceID=1a8fff4087a3fe5d msg="POST /api/prom/push (500) 528.859µs Response: \"DoBatch: InstancesCount <= 0\\n\" ws: false; Content-Encoding: snappy; Content-Length: 14729; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.43.0; X-Prometheus-Remote-Write-Version: 0.1.0; "
^C

Logs @ Prometheus
May 25 14:10:22 prometheus prometheus[1406214]: ts=2023-05-25T14:10:22.311Z caller=dedupe.go:112 component=remote level=warn remote_name=c76b0b url=http://10.244.128.91:9002/api/prom/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: DoBatch: InstancesCount <= 0"
May 25 14:10:22 prometheus prometheus[1406214]: ts=2023-05-25T14:10:22.311Z caller=dedupe.go:112 component=remote level=warn remote_name=206bd3 url=http://10.244.128.91:9002/api/v1/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: DoBatch: InstancesCount <= 0"
May 25 14:10:22 prometheus prometheus[1406214]: ts=2023-05-25T14:10:22.312Z caller=dedupe.go:112 component=remote level=warn remote_name=2041f7 url=http://10.244.128.91:9001/api/prom/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: DoBatch: InstancesCount <= 0"
May 25 14:10:22 prometheus prometheus[1406214]: ts=2023-05-25T14:10:22.312Z caller=dedupe.go:112 component=remote level=warn remote_name=377a74 url=http://10.244.128.91:9001/api/v1/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: DoBatch: InstancesCount <= 0"

**Comment by friedrichg** [comment]
it appears the ingester ring is empty. 
Is this a test environment or a production environment? can you share more of your config?
