### ISSUE TITLE
Ingester startup does not fail when memberlist_client service fails to initialize

### ISSUE THREAD

**Issue by danielblando** [cortexproject/cortex#5379]
**Describe the bug**
Using memberlist as ring.

When ingester is starting, it will initialize the ring lifecycler
https://github.com/cortexproject/cortex/blob/220683a13992596db044ea2b38a7eb87de4226fd/pkg/ingester/ingester.go#L640

and start it while starting ingester service
https://github.com/cortexproject/cortex/blob/220683a13992596db044ea2b38a7eb87de4226fd/pkg/ingester/ingester.go#L709

The lifecycler creating and initialization is pretty simple. It will start a kv client (in this case memberlist_client) and will not have any start function.
https://github.com/cortexproject/cortex/blob/220683a13992596db044ea2b38a7eb87de4226fd/pkg/ring/lifecycler.go#L150-L194

The memberlist_client when started by the lifecycler will also start its own service, trying to discover members and join the ring.
https://github.com/cortexproject/cortex/blob/220683a13992596db044ea2b38a7eb87de4226fd/pkg/ring/kv/memberlist/memberlist_client.go#L365

The problem occurs when the memberlist_client start fails. For example, if the dns to discover members is not responding.
https://github.com/cortexproject/cortex/blob/220683a13992596db044ea2b38a7eb87de4226fd/pkg/ring/kv/memberlist/memberlist_client.go#L447

The memberlist_client service will be failing to start on discovering members, but ingester will not be aware of the issue as lifecycler is also not aware.

In this scenario, ingester will wait to lifecycler to start which will be ok with no issue and then continue the startup.
The lifecycler then will try to initRing which will create a new ring as the memberlist never loaded the existent ring.
https://github.com/cortexproject/cortex/blob/220683a13992596db044ea2b38a7eb87de4226fd/pkg/ring/lifecycler.go#L420

That will create basically two rings on the service. The bad ingester will have an empty ring with its own inside in an ACTIVE state. All other ingester and services will not know that fault ingester is running leaving the service with two rings.

Biggest problem is ingester checkReady
https://github.com/cortexproject/cortex/blob/220683a13992596db044ea2b38a7eb87de4226fd/pkg/ingester/ingester.go#L1658

which should be responsible to make sure the ring is health. The check will pass as the local ring for memberlist is ok, without knowing that is not the current state of the service ring.

**To Reproduce**
1. Config cortex to run with memberlist
2. Start Cortex
3. Make sure ingester ring is up and running.
4. Change the membelist config `join_members` to something fault. (eg. wrongDNS.cluster.local) 
5. Delete one ingester, forcing it to restart (or restart ingester service)
6. Confirm the restart ingester will have logs for failing to resolve DNS and it will eventually end with a ring only containing one ingester.  

**Expected behavior**
Ingester should not start in this case and validate the memberlist_client service did not successfully started.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Comment by marianafranco** [comment]
There is a memberlist flag `abort_if_cluster_join_fails` that can be used for this. You need to configure your service to make sure that the abort will happen before the ingester is marked are ready, for example, by setting some `initialDelaySeconds` in the readiness probe.

You can also change the `max_join_retries` so the abort happens faster. The default is 10 retries which I saw taking around 4 minutes to abort.

**Comment by danielblando** [comment]
Nice, thanks @marianafranco 

This seems to work.
