### ISSUE TITLE
Customize error message when hitting limits

### ISSUE THREAD

**Issue by friedrichg** [cortexproject/cortex#5452]
**Is your feature request related to a problem? Please describe.**

Prometheus/Remote write agents that get throttled will get a typical error message like this in the logs

```
server returned HTTP status 400 Bad Request: user=xxx: per-user series limit of 150000 exceeded, please contact administrator to raise it (local limit: 0 global limit: 150000 actual local limit: 30000)
```

**Describe the solution you'd like**
It should be possible to customize error messages for limits or other problems

Ideally we should make the part "please contact administrator to raise it" customizable. So admin can provide more exact info on where to get help.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by friedrichg** [comment]
https://github.com/cortexproject/cortex/blob/2c37922134b671dcf46f030da29a3f7e2969d62a/pkg/ingester/limiter.go#L134

**Comment by kumanik** [comment]
Hi, I would love to give this issue a go.
