### ISSUE TITLE
Metrics for tsdb startup time

### ISSUE THREAD

**Issue by damnever** [cortexproject/cortex#5471]
**Is your feature request related to a problem? Please describe.**
Add some metrics to show the tsdb startup time.

**Describe the solution you'd like**
We can reuse the tsdb level metrics, such as `prometheus_tsdb_data_replay_duration_seconds` and `prometheus_tsdb_snapshot_replay_error_total`. Alternatively, we can also introduce new metrics at the cortex level specific to each tenant.

**Comment by yeya24** [comment]
I like this. I guess it is fine to make it per tenant since we have other per tenant metrics in ingester anyway

**Comment by damnever** [comment]
However, there is already a metric called `cortex_ingester_tsdb_wal_replay_duration_seconds` https://github.com/cortexproject/cortex/blob/634df354b05c5a130fa21b76bb30f7ea9933b8af/pkg/ingester/ingester.go#L590-L594

**Comment by damnever** [comment]
Perhaps we should deprecate 'cortex_ingester_tsdb_wal_replay_duration_seconds' and replace it with [`cortex_ingester_tsdb_data_replay_duration_seconds `](https://github.com/cortexproject/cortex/pull/5477). Since I personally do not find the percentile metric useful for identifying slow users when considering related context information such as the number of series the user has.

**Comment by yeya24** [comment]
I think I am ok to align with TSDB metrics. Thoughts? @friedrichg @alanprot @alvinlin123 ?
