### ISSUE TITLE
Replace Hashicorp libraries

### ISSUE THREAD

**Issue by friedrichg** [cortexproject/cortex#5523]
**Is your feature request related to a problem? Please describe.**
A number of hashicorp libraries have gone BSL, we need to identify them and fork them. 

**Describe the solution you'd like**
A PR that replaces these libraries with cortexproject libraries.
Don't see any other easy way to get out of trouble.

**Additional context**
https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license

**Comment by alanprot** [comment]
I dont think we need to do anything as per: https://discuss.hashicorp.com/t/hashicorp-projects-changing-license-to-business-source-license-v1-1/57106

**Comment by friedrichg** [comment]
```
github.com/hashicorp/consul/api MPL
github.com/hashicorp/consul/sdk MPL
github.com/hashicorp/cronexpr Apache
github.com/hashicorp/errwrap MPL
github.com/hashicorp/go-cleanhttp MPL
github.com/hashicorp/go-hclog MIT
github.com/hashicorp/go-immutable-radix MIT
github.com/hashicorp/go-msgpack MIT
github.com/hashicorp/go-multierror MPL
github.com/hashicorp/go-retryablehttp MPL
github.com/hashicorp/go-rootcerts MPL
github.com/hashicorp/go-sockaddr MPL
github.com/hashicorp/go-syslog MPL
github.com/hashicorp/go-uuid MPL
github.com/hashicorp/go-version MPL
github.com/hashicorp/golang-lru MPL
github.com/hashicorp/golang-lru/v2 MPL
github.com/hashicorp/hcl MPL
github.com/hashicorp/logutils MPL
github.com/hashicorp/mdns MIT
github.com/hashicorp/nomad/api MPL
github.com/hashicorp/serf MPL
```
You are right @alanprot ! 🙏
