### ISSUE TITLE
cortex How to set data deletion time for different tenant

### ISSUE THREAD

**Issue by liangrui1988** [cortexproject/cortex#5529]
example prometheus
--storage.tsdb.path=/data1/prome_data/hdfs --storage.tsdb.retention.time 30d 
--storage.tsdb.path=/data2/prome_data/yarn --storage.tsdb.retention.time 20d 

How do I set up the above migration to cortex?
I've looked through a lot of documentation and I can't find anything about it

**Comment by yeya24** [comment]
Cortex uses runtime config to set per tenant configurations.
Cortex block storage retention is performed by compactor to delete blocks on object storage. You can set `compactor_blocks_retention_period` in runtime config to set the retention.

**Comment by liangrui1988** [comment]
![211E1B3304E7842726242EC56E708403](https://github.com/cortexproject/cortex/assets/7435076/c1357d30-71cb-4437-94a8-e4c898615e3b)

Why do I set 5d and 3d data retention time respectively?
But it looks like it only retained 10 hours of data?
How do I set it up correctly?

my config
![image](https://github.com/cortexproject/cortex/assets/7435076/5ce94daf-aa4f-45da-abcd-c66aeaef8ef3)

**Comment by liangrui1988** [comment]
![image](https://github.com/cortexproject/cortex/assets/7435076/c5ad2b8b-569a-4dd4-b73d-904ac5602898)
And the old data hasn't been cleaned up

**Comment by liangrui1988** [comment]
> ![image](https://user-images.githubusercontent.com/7435076/264954090-c5ad2b8b-569a-4dd4-b73d-904ac5602898.png) And the old data hasn't been cleaned up

-blocks-storage.bucket-store.bucket-index.enabled=true
The data in each ingester query is different because this configuration is not enabled, but when I delete the data, the range still does not match the compactor_blocks_retention_period I configured. Why is this so surprising?

![image](https://github.com/cortexproject/cortex/assets/7435076/b2812a9e-df61-45ee-92f6-8e44c54519c5)
vs -blocks-storage.bucket-store.bucket-index.enabled=true
![image](https://github.com/cortexproject/cortex/assets/7435076/edda4c46-57e2-4865-8c3d-078e1ca424b5)
