### ISSUE TITLE
 stop  prometheus on grafna show value error

### ISSUE THREAD

**Issue by liangrui1988** [cortexproject/cortex#5530]
**Is your feature request related to a problem? Please describe.**
grafana query http://cortex:9009/prometheus, when prometheus stop ，grafna The last monitoring value is displayed unchanged？

**Describe the solution you'd like**
The grafna monitor value should be empty instead of leaving the last value unchanged

**Describe alternatives you've considered**
It is easy to misunderstand the monitoring value

**Additional context**
example
![image](https://github.com/cortexproject/cortex/assets/7435076/af0c6752-6131-401f-8479-48348a95adcf)
![image](https://github.com/cortexproject/cortex/assets/7435076/d1271315-198d-4a57-a1c4-efc35df16de8)

**Comment by yeya24** [comment]
This doesn't seem a Cortex issue. It is how Grafana displays data I believe.
If you wait for longer time, you should be able to see the data is missing from Grafana.

**Comment by yeya24** [comment]
You should change your query to use `xxx[10m]` to observe the raw samples value, rather than using range query. Range query sometimes might be confusing because of step.
