### ISSUE TITLE
Where is it enabled  EnableCompactions ?

### ISSUE THREAD

**Issue by liangrui1988** [cortexproject/cortex#5576]
**Describe the bug**
not EnableCompactions enables auto compactions.

**To Reproduce**
grep cortex log  print Compactions disabled"

```
grep 'Compactions disabled' stderr.log*
stderr.log:level=info ts=2023-09-25T02:09:07.880473898Z caller=db.go:1719 org_id=celeborn_metrics msg="Compactions disabled"
stderr.log:level=info ts=2023-09-25T02:09:08.001138229Z caller=db.go:1719 org_id=hdfs_testclsuter msg="Compactions disabled"
stderr.log:level=info ts=2023-09-25T02:09:08.110673415Z caller=db.go:1719 org_id=kubesphere_metrics_test msg="Compactions disabled"
stderr.log:level=info ts=2023-09-25T02:09:08.320052594Z caller=db.go:1719 org_id=yarn_app_run msg="Compactions disabled"
stderr.log:level=info ts=2023-09-25T02:09:08.446121708Z caller=db.go:1719 org_id=fake msg="Compactions disabled"
stderr.log:level=info ts=2023-09-25T02:09:08.662520104Z caller=db.go:1719 org_id=hdfs_fsimage msg="Compactions disabled"
stderr.log:level=info ts=2023-09-25T02:09:08.731827834Z caller=db.go:1719 org_id=yarn_app_finish msg="Compactions disabled"
```

**Expected behavior**
How EnableCompactions enables auto compactions.?

**Environment:**
bare-metal

**Additional Context**
The index cannot be created because compactions cannot be enabled
![image](https://github.com/cortexproject/cortex/assets/7435076/cd3df61b-93e0-4121-b03d-8a4fc77c2357)

Problems caused
#5574

**Comment by yeya24** [comment]
I don't think it is the same issue. This is saying compaction is disabled in ingester.
What you need is to enable compactor deployment.
I will close this issue
