### ISSUE TITLE
cortex query timeout when one cortex query-frontend instance down

### ISSUE THREAD

**Issue by wolf666666** [cortexproject/cortex#5610]
**Describe the bug**
the cortex services(1.15.3) are deployed as microservices, we have two cortex query-frontend and some queriers.
the querier refer query-frontend with config: -querier.frontend-address=<dns_name>:9999, this dns_name binds two IP address of the query-frontend. when one of query-frontend server down, the metric queries will timeout.

if i config the item: -querier.frontend-address=<dns_name>, if dns_name is a proxy ip, and the proxy route to the two query frontends, the metircss query will also failed.

**To Reproduce**
1. start two cortex query frontend instances
2. start four cortex querier instances with config -querier.frontend-address=<dns_name>:port, dns_name binding two ip address of query frontends, 
3.   execute query

**Expected behavior**
expect that the query frontend and querier HA with microservcie mode.

**Comment by yeya24** [comment]
I don't know if it is a bug. It looks like expected behavior. If the query frontend that is currently handling the query is down, then there is no retry mechanism built in for that, as query frontend is the entrypoint.

In this case, it relies on some proxy/gateway or client side application to retry.

**Comment by wolf666666** [comment]
> I don't know if it is a bug. It looks like expected behavior. If the query frontend that is currently handling the query is down, then there is no retry mechanism built in for that, as query frontend is the entrypoint.
> 
> In this case, it relies on some proxy/gateway or client side application to retry.

What is the query queue mechanism of the query frontend and querier?  the querier will pick the query task from the query frontend, does the queryfrontend share the task queue?  when the querier finish one query task, how does the querier know which query frontend to return the query result? if i add a proxy betweed the querier an query frontend, does the querier still can send the query result back the corrent query frontend?

**Comment by friedrichg** [comment]
>What is the query queue mechanism of the query frontend and querier? the querier will pick the query task from the query frontend, does the queryfrontend share the task queue? when the querier finish one query task, how does the querier know which query frontend to return the query result? if i add a proxy betweed the querier an query frontend, does the querier still can send the query result back the corrent query frontend?

Like @yeya24 suggested, whatever ip you put behind dns should always respond, that is standard in all http services. People tend to use load balancers/proxy for that reason, but I don't think you should in this case.
queriers act as workers to query-frontend. If the result is ready in querier, they won't be able to send it back, they will not change the query-frontend that sent it.
I think you should just make sure your query-frontends don't crash. They tend to oom if they don't have enough memory, but that's about the only problem I see can happen to query-frontends. Or do you see anything different?

Note that you can also add [query-scheduler](https://cortexmetrics.io/docs/operations/scaling-query-frontend/) to the mix, to be able to scale up query-frontend better.
But that won't change the fact that you need your query-frontends to be up and not crashing.

**Comment by wolf666666** [comment]
> > What is the query queue mechanism of the query frontend and querier? the querier will pick the query task from the query frontend, does the queryfrontend share the task queue? when the querier finish one query task, how does the querier know which query frontend to return the query result? if i add a proxy betweed the querier an query frontend, does the querier still can send the query result back the corrent query frontend?
> 
> Like @yeya24 suggested, whatever ip you put behind dns should always respond, that is standard in all http services. People tend to use load balancers/proxy for that reason, but I don't think you should in this case. queriers act as workers to query-frontend. If the result is ready in querier, they won't be able to send it back, they will not change the query-frontend that sent it. I think you should just make sure your query-frontends don't crash. They tend to oom if they don't have enough memory, but that's about the only problem I see can happen to query-frontends. Or do you see anything different?
> 
> Note that you can also add [query-scheduler](https://cortexmetrics.io/docs/operations/scaling-query-frontend/) to the mix, to be able to scale up query-frontend better. But that won't change the fact that you need your query-frontends to be up and not crashing.

The issue i met is that the query-frontend server crashed when upgrade, in this case, even i have two query-frontend server, they cortex services are still unaviable, the metric query will be timeout.
So i try to add envoy proxy between querier and query-frontend, the config is -querier.frontend-address=<envoy dns name>, but it's not work, the querier can not connect to query-frontend with envoy proxy.
 So i'd like to know whether the querier support proxy here: -querier.frontend-address=<proxy> ?

**Comment by yeya24** [comment]
I never try putting a proxy between the two services but I think it doesn't work.

Every querier already maintains a connection to every query frontend instance and tries to pull request from the query frontned queue. So the envoy proxy between the two services is kind of useless here.

The problem is that one request is processed in only one query frontend so if the frontend is down request will fail. You need to duplicate the requests to multiple query frontend to make HA per request.

**Comment by wolf666666** [comment]
Thanks so much, I got it. 
i will close the ticket
