### ISSUE TITLE
Query limits are not applied properly since the prometheus upgrade

### ISSUE THREAD

**Issue by rajagopalanand** [cortexproject/cortex#5620]
PR https://github.com/cortexproject/cortex/pull/5593 introduced changes in how context is passed. Context is now passed to the `select` method. Previously, context was stored in querier and the query limiter that was stored in the context could be shared across multiple `select` method calls. Now, since the query limiter is newly constructed in `setupFromCtx` on every `select` function call, the limits are not being applied correctly and can potentially result in out of memory errors. The limit is now applied per `select` call instead of per query which would allow queries that result in multiple `select` calls to use significantly higher memory

**Comment by yeya24** [comment]
Resolving this
