### ISSUE TITLE
Improve CreateRuleGroup for tenant with no RulerMaxRuleGroupsPerTenant limit

### ISSUE THREAD

**Issue by emanlodovice** [cortexproject/cortex#5646]
**Describe the bug**
The ruler `CreateRuleGroup` api still lists all rule groups under the tenant even if the `RulerMaxRuleGroupsPerTenant` for the tenant is 0. For huge workspaces with no limit set this results to unnecessary latency.
https://github.com/cortexproject/cortex/blob/master/pkg/ruler/api.go#L530

**To Reproduce**
1. Create a 3 thousand rule groups under a workspace
2. Notice that the latency of the create calls increases even if the workspace has no set limit on the number of rule groups.

**Expected behavior**
`CreateRuleGroup` should skip listing all rule groups if `RulerMaxRuleGroupsPerTenant` is not set.

**Additional Context**

**Comment by emanlodovice** [comment]
I am planning on working on this.

**Comment by yeya24** [comment]
@emanlodovice Assigned to you
