### ISSUE TITLE
Pushing to docker.io is failing with resource is denied

### ISSUE THREAD

**Issue by friedrichg** [cortexproject/cortex#5654]
**Describe the bug**
```
The push refers to repository [docker.io/cortexproject/thanosconvert-linux]
7cd186aff576: Preparing
09df970fa2dc: Preparing
36b50b131297: Preparing
denied: requested access to the resource is denied
```

**To Reproduce**

https://github.com/cortexproject/cortex/actions/runs/6853441493/job/18654506731

**Expected behavior**
It should push normally

**Comment by friedrichg** [comment]
Tried updating the password but that is not the problem. The problem is we have a few private locked repositories in cortexproject
![Screenshot 2023-11-14 at 9 37 33 AM](https://github.com/cortexproject/cortex/assets/1517449/3b80e854-a418-4e49-bb4d-7e0bbeffe3d7)

Are we ok making these repositories public to fix ci/cd? @alanprot @yeya24 @alvinlin123 ?

I can see we need these private if we are fixing a vulnerability and we don't want to publish it yet. So this should be temporary until we get docker team back in cortexproject (if we get it)

**Comment by alvinlin123** [comment]
First of all, I don't have a problem to make them public. But it seems like they are just some repo for linux flavour of things which we really shouldn't need. So I would also recommend to not push to those private repo anymore. 

By the way I got the following e-mail before 

```
Hello cortexproject!
We were unable to process a payment on your account for invoice #INV-XXXXX that was due on November 08, 2023 - the credit card was declined for an unknown reason.
We appreciate you working with Docker on this and look forward to resolving the matter with you quickly.
```

There were never a credit card added to the org, and Cortex was in [DockerHub's Open Source Sponsor Program](https://www.docker.com/community/open-source/application/). I am not sure what changed. Maybe we need to apply again?

**Comment by alvinlin123** [comment]
Ok I just applied to DockerHub's OSS sponsorship program again, let's see what happens next.

**Comment by alvinlin123** [comment]
alright we are back in the game again 

>>Hi Alvin Lin,
Congratulations! Your project has been approved for the Docker-Sponsored Open Source program. A Docker Team subscription will be allocated to the project organization Docker ID specified in your application within the next 3 weeks. In addition to a Team subscription, you now have:
free autobuilds
rate-limit removal for all users pulling public images from your project namespace
special badging on Docker Hub (this will be visible within two weeks)
If you haven’t already, please take the time to update your project’s Hub pages to include a detailed project description, links to your project source code, as well as contributing guidelines, and a link to your organization’s website. Projects lacking this information may not receive the Docker Sponsored Open Source badging for their images on Docker Hub.
Membership in the Docker-Sponsored Open Source (DSOS) program is valid for one year. You will receive a reminder email from us when it is time to renew your membership.
We are thrilled to have you as an open-source partner. If you have any questions regarding the open source program please contact [opensource@docker.com](mailto:opensource@docker.com) and include the name of your project in the subject line. If you have questions regarding technical support please contact [support@docker.com](mailto:support@docker.com).
Thank you!

**Comment by friedrichg** [comment]
It is still failing 
https://github.com/cortexproject/cortex/actions/runs/6872359270/job/18701488105

I don't think we are still allowed to have private repos in dockerhub :( 

![Screenshot 2023-11-15 at 11 48 50 AM](https://github.com/cortexproject/cortex/assets/1517449/289d6d7e-5c66-4037-b734-9c1d13561807)

It says we are using 3 out 0

**Comment by friedrichg** [comment]
Made those 3 repositories public too. We can later have a discussion if we actually need those repos in the first place like alvin mentioned

**Comment by alvinlin123** [comment]
> I don't think we are still allowed to have private repos in dockerhub :(

I agree with the sad face

**Comment by alvinlin123** [comment]
Alright yea, no private repo for OSS project  ... which make sense I guess.

It's documented in https://www.docker.com/developers/free-team-faq/ under the question `What’s the difference between the (paid) Docker Team plan and the Docker Free Team plan?`
