### ISSUE TITLE
1.16.0 Store Gateway Query stats - ability to disable

### ISSUE THREAD

**Issue by philiptrovato** [cortexproject/cortex#5721]
**Describe the bug**
New Store Gateway Query stats are pretty cool, but verbose and generate an excessive amounts of logs. No current flags to disable from what I can tell, must be turned off by setting log level to "warn".

Querier: Log query stats when querying store gateway. https://github.com/cortexproject/cortex/pull/5376

**To Reproduce**
1. Run Cortex v1.16.0 at info log level
2. Perform query or ruler operations which hit the SGW

**Expected behavior**
Expected the new SGW query stats to follow the flag "query_stats_enabled"
Or have its own flag to disable.
Or have the new SGW query stats set at debug level instead of info.

**Comment by yeya24** [comment]
That's a good call.
`query_stats_enabled` is a flag used in QFE only. I think what I am gonna do is to add a new flag for store gateway stats log.

**Comment by yeya24** [comment]
Sorry for the lag. I just opened a pr to fix this problem. https://github.com/cortexproject/cortex/pull/5749
