### ISSUE TITLE
CNCF TOC follow up on project health

### ISSUE THREAD

**Issue by rochaporto** [cortexproject/cortex#5728]
Hi.

Following up on an open issue with the CNCF TOC regarding the health of the Cortex project:
https://github.com/cncf/toc/issues/899

The TOC would like to collect information on a few items to reach a conclusion in that issue.

1. Roadmap and planning for the next 6 months

There is a recent release with significant features added:
https://github.com/cortexproject/cortex/blob/master/CHANGELOG.md

Could you link to a roadmap file, we might have missed it. And summarize any additional plans for the next 6 months: major goals for the project, major features, work on adoption and documentation updates and any other similar items.

2. Update on the project health

The TOC issue linked above raised concerns regarding project maintainers. Is there an update to the [MAINTAINERS.md](https://github.com/cortexproject/cortex/blob/master/MAINTAINERS) file since the last one 2 years ago? And any other relevant update to what was given in that ticket.

Also please add any item where you think the CNCF could be useful to the project.

3. Longevity and project maturity

Regarding project adoption, any additional information to what is in the ADOPTERS.md file you would like to add?

Do you think the project meets the criteria for graduation, and if not which items need to be worked on?
https://github.com/cncf/toc/blob/main/process/graduation_criteria.md#graduation-stage

Many thanks for the reply.

We would like to close the ticket in the CNCF TOC repo, if possible, by the end of January 2024.

**Comment by rochaporto** [comment]
@friedrichg do you have an update for this request?

**Comment by friedrichg** [comment]
@rochaporto 

1.
I have a draft for the roadmap on https://github.com/orgs/cortexproject/projects/1 . I got the feedback from other maintainer that it was nice. We still have to get feedback from the community.

2.
We have many new contributors, new adopters, but not yet new maintainers.

3.
The ADOPTERS.md file needs some cleaning up. I will try to finish that soon.
I think we do fulfil already graduation part. I will check that too

**Comment by rochaporto** [comment]
Thanks @friedrichg .

I see the ADOPTERS.md file has been updated, is there any other update for the roadmap or maintainers?

Thanks again.

**Comment by friedrichg** [comment]
Sorry, I forgot to update you. The initial roadmap is there in the link provided, maintainers agreed to use it. We just deliver one of the features we had on the roadmap (OTLP ingestion). We are slowly adding more features to the roadmap too

Regarding maintainers, we have folks interested in becoming maintainers. @harry671003 is one (sorry for pinging) . We would like to see constant contributions from these folks before moving forward. it's what the governance requires.

I will keep you updated moving forward.

**Comment by rochaporto** [comment]
Thanks @friedrichg , this is great news.

Should we organize a quick call to wrap up this issue? I think we have enough now, @alolita would join in as well.

**Comment by friedrichg** [comment]
@rochaporto of course, I can do it any day next week. Invite also other mantainers @yeya24 @alanprot @alvinlin123

**Comment by alolita** [comment]
Sounds good @friedrichg Lets coordinate a time on Slack - w @rochaporto

**Comment by friedrichg** [comment]
After our meeting I understood that we provided everything that was required for now. Including 
- Roadmap
- Maintainers update
- Adopters update.

And we will have a meeting again in 6 months. I will close this ticket

**Comment by rochaporto** [comment]
Adding here for information the same summary as in the ticket from the TOC repo.

Following the evaluation of the project, the TOC has seen progress in multiple areas:
* Roadmap: established and now being kept up to date
* Maintainers: list has been updated with maintainers from two different organizations
* Adopters: list updated showing multiple end users relying on the project in production

The TOC has the following recommendations for the project moving forward:
* Improve community meetings, either following the current defined cadence of 2 weeks or updating the cadence to what is feasible and reflecting that in the repos
* Reach out to TAG-ContributorStrategy for recommendations on how to get more contributors potentially becoming maintainers over time
* Perform an early check for graduation to identify other areas where the project could be improved

TAG-Observability will continue supporting the project, and will organize quarterly checks to identify areas where the TOC can further help with all the tasks above.
