### ISSUE TITLE
Track sample validation errors with synthetic metrics

### ISSUE THREAD

**Issue by awh** [cortexproject/cortex#577]
Samples can be rejected for various reasons:

* Timestamp too old
* Out of order timestamps
* Repeated timestamps
* Invalid labels or metric names
* Too many series
* ...

Our approach to these is rather ad-hoc at the moment - some are silently dropped, some return errors, and some cause (voluminous) logging. Instead we could record them as a set of synthetic metrics in cortex itself on a per-instance basis under an appropriate namespace (e.g. `weaveworks_cortex_timestamp_too_old_count`) so that they're a) visible to those who're sending them to us and b) available for the generation of alerts or notifications.

**Comment by bboreham** [comment]
Note that many of these errors come from Weave Cloud's own instance of Prometheus sending to Cortex, so we might want to drill in there before bugging customers.

**Comment by bboreham** [comment]
In discussion we noted that the sending Prometheus has a metric `prometheus_remote_storage_failed_samples_total`, and many of the errors will appear in the logs there.

Also, while I'm here, I'll note that creating synthetic metrics is a lot easier from the distributor (where these checks recently moved) than it was in the ingester.

**Comment by leth** [comment]
In case it's of interest, the distributor counts dropped samples in the `cortex_discarded_samples_total` metric

**Comment by bboreham** [comment]
Yeah, but not per-instance.

**Comment by tomwilkie** [comment]
I think this has been fixed recently as part of #890 and others.
