### ISSUE TITLE
Flaky TestRulerKeepFiring integration test

### ISSUE THREAD

**Issue by yeya24** [cortexproject/cortex#5853]
**Describe the bug**
Flaky test run https://github.com/cortexproject/cortex/actions/runs/8619846095/job/23625587487.

Error message:

```
    ruler_test.go:1135: 
        	Error Trace:	/home/runner/work/cortex/cortex/integration/ruler_test.go:1135
        	Error:      	Should NOT be empty, but was <nil>
        	Test:       	TestRulerKeepFiring
```

**Expected behavior**
Test should pass.

**Comment by mustafain117** [comment]
Another failure: https://github.com/cortexproject/cortex/actions/runs/8758051411/job/24038143808

Trying to reproduce locally
