### ISSUE TITLE
Building time increased 60s because of node

### ISSUE THREAD

**Issue by friedrichg** [cortexproject/cortex#5877]
**Describe the bug**
Nodesource is punishing us with 60s more build time
```
 => [3/9] RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -                      48.8s
 => => #                           SCRIPT DEPRECATION WARNING
 => => # ================================================================================
 => => # ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
 => => # ================================================================================
 => => # TO AVOID THIS WAIT MIGRATE THE SCRIPT
 => => # Continuing in 60 seconds (press Ctrl-C to abort) ...
```
**To Reproduce**
1. Run make
2. see the waiting time in the logs

**Expected behavior**
There should be no waiting time. We should use something else

**Additional Context**
The bug is on https://github.com/cortexproject/cortex/blob/12a60a4f3713ab1b94b64acb8492aa88ea2e2bb3/build-image/Dockerfile#L6

**Comment by yeya24** [comment]
Let's update build image script to use Node 18 instead.

**Comment by yeya24** [comment]
Help wanted.

**Comment by Kramer0x0** [comment]
I can pick this up if you want to assign to me.

**Comment by yeya24** [comment]
Let's resolve it since #5906 already merged
