### ISSUE TITLE
ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".

### ISSUE THREAD

**Issue by KrisBuytaert** [cortexproject/cortex#5897]
**Describe the bug**
Since the upgrade of our (dev) cluster from 1.14 to 1.16 the 
ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".   
started appearing frequently (multiple times per hour). 
The cluster still seems to work.

After reading the comments and suggestions in https://github.com/cortexproject/cortex/issues/5803  I have added 
the snippet to change the ingester_client config to gzip.

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: gzip

My metrics indeed show a significant change in bandwidth usage, however the errors have persisted after this change.

[root@cortex01.o11ydev.o11y.eu ~]# yum info cortex
Last metadata expiration check: 0:15:12 ago on Thu 25 Apr 2024 01:58:47 PM CEST.
Installed Packages
Name         : cortex
Version      : 1.16.0
Release      : 1
Architecture : x86_64
Size         : 67 M
Source       : cortex-1.16.0-1.src.rpm
Repository   : @System
From repo    : upstream
Summary      : no description given
URL          : https://github.com/cortexproject/cortex
License      : Apache 2.0
Description  : no description given

**Comment by friedrichg** [comment]
ideally you should not skip versions during upgrades, Can you provide the full error log message?

**Comment by KrisBuytaert** [comment]
Apr 25 04:20:03 cortex01 cortex[147661]: 2024/04/25 04:20:03 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
Apr 25 04:20:04 cortex01 cortex[147707]: 2024/04/25 04:20:04 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
Apr 25 04:20:04 cortex01 cortex[147707]: 2024/04/25 04:20:04 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".

There are no details about which line and the pids refer to both the distributor and the querier

**Comment by KrisBuytaert** [comment]
I downgraded the cluster to 1.15 .. and after an hour+ of testing there were no errors. 
In a 1.16 cluster the errors start happening within the first 10 minutes already

**Comment by yeya24** [comment]
Hi @KrisBuytaert,

> With debugging enabled , no mor details regarding the line nr were visible , this is a snippet from the querier log..

Is it also happening to other components as well? Do you use memberlist? I am curious if we see the same error log in query frontend log

**Comment by KrisBuytaert** [comment]
@yeya24  these errors occured in both the querier and the distributor ,  and from what I noticed not in the  query-frontend I`m not using memberlist

**Comment by KrisBuytaert** [comment]
FWIW I've upgraded to 1.17 and no change .. the errors are still there ..

**Comment by yeya24** [comment]
Hi @KrisBuytaert, thanks for sharing your configuration. I think the issue is etcd related and I do find this from etcd repo https://github.com/etcd-io/etcd/issues/15719.

Cortex enables `PermitWithoutStream` option on the client side [here](https://github.com/cortexproject/cortex/blob/master/pkg/ring/kv/etcd/etcd.go#L105). However, etcd server doesn't have a way to turn on it at server side. I am not sure why this problem only occures after 1.15.0 release. It might be a etcd client library version upgrade.

This error matches the behavior mentioned in the gRPC doc [here](https://pkg.go.dev/google.golang.org/grpc/keepalive#:~:text=//%20If%20true%2C%20server%20allows%20keepalive%20pings%20even%20when%20there%20are%20no%20active%0A%09//%20streams(RPCs).%20If%20false%2C%20and%20client%20sends%20ping%20when%20there%20are%20no%20active%0A%09//%20streams%2C%20server%20will%20send%20GOAWAY%20and%20close%20the%20connection.%0A%09PermitWithoutStream%20bool%20//%20false%20by%20default).

But overall, this error happens when Cortex client sends keepalive pings to etcd server. Ideally it shouldn't impact the normal Ring functionalities like data loss. As mentioned in the code comment,

```
		// Configure the keepalive to make sure that the client reconnects
		// to the etcd service endpoint(s) in case the current connection is
		// dead (ie. the node where etcd is running is dead or a network
		// partition occurs).
```

**Comment by KrisBuytaert** [comment]
@yeya24  thank you for this update !     We just moved away from consul to etcd  because of their license change , not many options left ..  but given that as you mention this is about the connection to etcd , that also means there is no data loss happening ..

We're on etcd-3.5.12-1  

Do I understand correctly that even if cortex were to implement the client config  that wouldn't help yet untill etcd also exposes the feature ? 

So for now the best approach probably is to ignore the error log ?

**Comment by yeya24** [comment]
I guess we can disable this option on client side to mitigate the error log.

It shouldn't cause much negative impact since it is just keep alive. And keep alive ping from client are still sent when there is an active connection

**Comment by yeya24** [comment]
After a bit more investigation I think the cause is https://github.com/grpc/grpc-go/pull/5935, which is added in grpc-go v1.54.0 release. Now we are at v1.63.2 so it is unlikely to downgrade that.

**Comment by yeya24** [comment]
@KrisBuytaert Would it be possible for you to change this value to false and rebuild a new image and test?
https://github.com/cortexproject/cortex/blob/master/pkg/ring/kv/etcd/etcd.go#L105

I am unable to reproduce this error log locally in a test case and I am unsure if this change could mitigate the issue 100%. If you could test it out it would be great.

**Comment by KrisBuytaert** [comment]
@yeya24  so I build the binary and launched it about 24 hours ago ...   my logs show no more CALM errors ... 
So I guess that change most probably fixes the problem

**Comment by yeya24** [comment]
Great to see it helps. Feel free to open a PR for it. Or anyone from the community can pick it up.

AC:
- Expose this configuration as a flag https://github.com/cortexproject/cortex/blob/master/pkg/ring/kv/etcd/etcd.go#L105
