### ISSUE TITLE
List rules API not honoring exclude_alerts flag

### ISSUE THREAD

**Issue by sirianni** [cortexproject/cortex#5989]
**Describe the bug**
I am consuming the Cortex API implicitly via Amazon Managed Prometheus (AMP).  

When I hit `/api/v1/rules?exclude_alerts=true` I still get the list of active `alerts[]` array in the response.

According to the [prometheus docs](https://prometheus.io/docs/prometheus/latest/querying/api/#rules), the `exclude_alerts` should omit this element.

**Environment:**
Amazon Managed Prometheus

**Comment by yeya24** [comment]
Hi @rajagopalanand @rapphil, can you help take a look?

**Comment by rajagopalanand** [comment]
This is a bug in Cortex that needs to get fixed

**Comment by rapphil** [comment]
@yeya24 can you assign this issue to me?
