### ISSUE TITLE
Why is there no downsampling function? Where do I start if I want to add downsampling?

### ISSUE THREAD

**Issue by lu-xiansheng** [cortexproject/cortex#6006]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yeya24** [comment]
Downsampling is on our roadmap.

If you want to try downsampling in Cortex, you can just port Thanos downsampling to Cortex and do some tweak. It should work out of the box.

**Comment by yeya24** [comment]
Let's close this issue and convert the discussion to the main issue https://github.com/cortexproject/cortex/issues/4322
