### ISSUE TITLE
Time-out DynamoDB chunk requests faster

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#602]
I see occasional `DynamoDB.BatchGetItemPage` requests that take tens of seconds, where the typical time is under 100ms:

![image](https://user-images.githubusercontent.com/8125524/32993456-428256ec-cd50-11e7-8c08-d79c5860aeb6.png)

suggest putting a timeout like 2 seconds on these so they will go round the retry loop and hopefully have better luck.

I think this can be done via `ResponseHeaderTimeout` on the `Transport`

**Comment by alvinlin123** [comment]
As chunk store is deprecated, I think we should close this issue. Please feel free to re-open if needed.
