### ISSUE TITLE
Add support to the `Info` field in the body of query API responses

### ISSUE THREAD

**Issue by rapphil** [cortexproject/cortex#6117]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

Starting with Prometheus 2.54.0, the response body of query APIs will have a `info` field that is used to store potential query issues, that may or may not be a false positive. To maintain Prometheus compatibility, we should support to this field in cortex as well.

## References

https://github.com/prometheus/prometheus/pull/14327
https://github.com/prometheus/prometheus/pull/14429/

**Comment by SungJin1212** [comment]
@rapphil 
Could you please assign me?
