### ISSUE TITLE
Make distributors/ingesters aware of availability zones

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#612]
Suppose your replication-factor is about the same as the number of AZs.  You'd prefer that replicas for any particular write were spread across all the AZs.

I have no idea how hard this is.

**Comment by tomwilkie** [comment]
Cassandra does this with topology-aware snitches[1] and replication strategies[2]

[1] https://docs.datastax.com/en/cassandra/2.1/cassandra/architecture/architectureSnitchesAbout_c.html
[2] https://docs.datastax.com/en/cassandra/2.1/cassandra/architecture/architectureDataDistributeReplication_c.html

**Comment by weeco** [comment]
I believe Kafka's approach is similarly to Cassandra's. They attach a Rack ID on each broker pod (which would be the identifier for a AV Zone): https://issues.apache.org/jira/browse/KAFKA-1215

**Comment by khaines** [comment]
going to revive this issue and do some investigating
