### ISSUE TITLE
Record rule is not working

### ISSUE THREAD

**Issue by mannam0152** [cortexproject/cortex#6174]
**Describe the bug**
I am trying to create record rules for cortex metrics using /rules api and able to create the record successfully with below payload
{
    "name": "record_definition",
    "rules": [{
        "record": "critical_alert",
        "expr": "avg(system_cpu_utilization)"
    }]
}
Also i can get the record created using get api. But while i am trying to execute the record by using record name "critical_alert" as query in cortex but it's giving the empty data. But if i execute the EXPR separately in the same query tab i am getting the data as expected. Could you guys please help me in resolving the issue

**To Reproduce**
1. Create a record rule using rules api
2. Query the data by record name using range or metric api(empty result)

**Expected behavior**
It should give the data how the expr has ran individually

**Environment:**
local system with java config to cortex api

**Additional Context**

**Comment by CharlieTLe** [comment]
Resolved in our Slack channel: https://cloud-native.slack.com/archives/CCYDASBLP/p1724239670064419
