### ISSUE TITLE
Support peakSamples in query frontend response

### ISSUE THREAD

**Issue by yeya24** [cortexproject/cortex#6181]
**Is your feature request related to a problem? Please describe.**
`peakSamples` field was supported in Prometheus query response long time ago https://github.com/prometheus/prometheus/pull/10369/files#diff-9e1a49d3ecc79eae504d539895c7621d3f45eef192ddd6192d8b304ffa591864R111.

However, it is not supported yet at Cortex. https://github.com/cortexproject/cortex/blob/master/pkg/querier/tripperware/query.proto#L41

We only have `totalQueryableSamples` and `totalQueryableSamplesPerStep`.

**Describe the solution you'd like**
Modify the query frontend protobuf and add the field. Also implement the merge logic accordingly.

**Comment by SungJin1212** [comment]
@yeya24 
Could you assign to me?

**Comment by yeya24** [comment]
Here you go.

**Comment by SungJin1212** [comment]
@yeya24 
I think the _peakSamples_ should be the largest one among the query responses in the merging process. Because the _peakSample_ is the maximum samples kept in memory during the query process.. What do you think of it?

**Comment by yeya24** [comment]
Sounds reasonable to aggregate using max not sum.

**Comment by SungJin1212** [comment]
@yeya24 
I have made the pr! (https://github.com/cortexproject/cortex/pull/6188)
