### ISSUE TITLE
Add exemplars coverage in OTLP integration test

### ISSUE THREAD

**Issue by yeya24** [cortexproject/cortex#6235]
**Is your feature request related to a problem? Please describe.**

The existing OTLP push integration test covers the ingestion of both series and histograms. However, we didn't cover exemplar data type.
https://github.com/cortexproject/cortex/blob/master/integration/otlp_test.go 

**Describe the solution you'd like**

Ingest exemplars data in the integration test and make sure the exemplars can be ingested successfully via OTLP endpoint.

**Comment by SungJin1212** [comment]
@yeya24 
Please assign me!
