### ISSUE TITLE
RPC error message on overload is overly talkative and hard to understand

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#636]
I got this message, visible in Grafana:

> QueryPage error: terminated after 20 retries for table prod_chunks_weekly_2503, last error ProvisionedThroughputExceededException: The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API. status code: 400, request id: RM74KP9TT0DCD0H7C7CUNP39HVVV4KQNSO5AEMVJF66Q9ASUAAJG

This leaks details of the underlying infrastructure, and is basically meaningless to someone who doesn't work on Cortex.

Instead, it could say something like "your query is too hard, or the system is overloaded, or badly configured".
We should log that error but not show it to the end-user.

**Comment by palash25** [comment]
> We should log that error but not show it to the end-user.

@bboreham hi I would like to work on this. I just had one question.

> We should log that error but not show it to the end-user.

do you mean that logging the original overcomplicated error message and returning the simplified error message or just logging the new error message and not returning it?
