### ISSUE TITLE
Emit metric for labelsSizeBytes

### ISSUE THREAD

**Issue by anna-tran** [cortexproject/cortex#6372]
**Is your feature request related to a problem? Please describe.**
Cortex provides a `MaxLabelsSizeBytes` limit for the max combined size in bytes of all labels and label values for a given metric name, but does not emit the metric this is compared to. Exposing such a metric would help users to know how close they are to hitting the limit in case they intend to add more labels to a metric name.

**Describe the solution you'd like**
Expose the [`labelSizeBytes`](https://github.com/cortexproject/cortex/blob/24efa2bc291c92e95baa307a69563e43fc2afd6c/pkg/util/validation/validate.go#L239) as a native histogram metric that tenants can monitor.

**Comment by danielblando** [comment]
I like the proposal to add a metric for labelSizeBytes and allowing tenants to monitor it.

My only concern is how much it would be useful to track the exact metricName which the high labelSize is coming from. 
Would you add a label for tenant and metricName? Having a metricName label even with native histogram can create a lot of data, no?

**Comment by anna-tran** [comment]
I think we could just add the tenant but not the metric name. If the tenant exceeds the label size limit the error returned will include the entire label set so the tenant should be able to deduce the metric name from there.
