### ISSUE TITLE
Add a slogAdapter converting go-kit/log to slog

### ISSUE THREAD

**Issue by SungJin1212** [cortexproject/cortex#6402]
The Prometheus v3.0.0 uses a `slog` instead of the `go-kit/log`. In other words, the passed log parameter is changed to `slog`.
To upgrade Prometheus v3.0.0, we should pass `slog` instead of `go-kit/log`.

So, it might be good to implement a `slogAdapter` which converts `go-kit/log` to `slog`.

**Comment by yeya24** [comment]
FYI we should need to update the common library to support slog there. https://github.com/cortexproject/weaveworks-common/tree/master/logging

We can try the adapter approach https://github.com/tjhop/slog-gokit first and see if it is good enough.

**Comment by CharlieTLe** [comment]
Might be a good opportunity to see if we can use OpenTelemetry-go for logging here as the api and use slog as the sdk. Benefits include standardization of logging and exemplar support with traces.
