### ISSUE TITLE
Include metric name in max series per metric limit exceeded error

### ISSUE THREAD

**Issue by eeldaly** [cortexproject/cortex#6416]
**Is your feature request related to a problem? Please describe.**
When receiving an errMaxSeriesPerMetricLimitExceeded error, the metric name is not displayed.

**Describe the solution you'd like**
Include the metric name in the error message.

**Additional context**
When a user hits the max-series per metric name limit, they should know which metric caused the limit to be reached so that they can reduce their active series for that limit or increase the limit.

**Comment by yeya24** [comment]
Thanks! Proposal makes sense to me.
https://github.com/cortexproject/cortex/blob/cdf947110d38cef77fd96e74a126e420903eed24/pkg/ingester/limiter.go#L132

We have both `formatMaxSeriesPerMetricError` and `formatMaxMetadataPerMetricError`. We should include metric name to both error messages
