### ISSUE TITLE
Include response series count in query stats log

### ISSUE THREAD

**Issue by yeya24** [cortexproject/cortex#6421]
**Is your feature request related to a problem? Please describe.**
There is a query stats log in Query Frontend which is useful to gather query insights and debug. https://github.com/cortexproject/cortex/blob/master/pkg/frontend/transport/handler.go#L375

What is missing now is the number of series in the response. It would be good to include this info for query insights purpose.

We can start this for instant query and range queries.

**Describe the solution you'd like**
We encode query response to JSON here https://github.com/cortexproject/cortex/blob/master/pkg/querier/tripperware/roundtrip.go#L214.

We can try to extract the series count here and pass down using querier stats.

**Comment by SungJin1212** [comment]
It looks nice, can I take it?

**Comment by yeya24** [comment]
Yes you can go ahead
