### ISSUE TITLE
Get the log_messages counter to work properly

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#666]
There is supposed to be a metric exposed called `log_messages` so you can alert on too many errors, warnings, etc.  But it doesn't work.  [UPDATE: I think right now it is giving all zeros]

If there is [another library](https://github.com/weaveworks/promrus/blob/0599d76/promrus.go#L20) in your program trying to use a counter named `log_messages`, it's unpredictable which one wins.

Maybe some kind of namespacing in the name should be added, but from the Prometheus docs it seems that the `AlreadyRegisteredError` is designed for the case above.

**Comment by bboreham** [comment]
Right now it looks more like we don't set up `logrus` so any logging that goes that way from `weaveworks/common` or the like is not getting counted and not affected by `-log-level`

**Comment by bboreham** [comment]
The only path I can see that goes via promrus is `weaveworks/common/ServerLoggingInterceptor` - if that took a logger as a parameter we'd be set.

**Comment by saurav-malani** [comment]
I tried running the program and curled the metrics, and I am getting non-zero numbers. So, I think this is no longer an issue.

**Comment by bboreham** [comment]
Thanks for looking into this @saurav-malani.

I poked around a bit further and came to the conclusion the reason it's not an issue right now is the [version of `promrus`](https://github.com/cortexproject/cortex/blob/6ba9315e24bb169cea7a9938855fcca1a1da09e2/vendor/github.com/weaveworks/promrus/promrus.go#L20) that Cortex is vendoring has the metric `log_messages` whereas [Cortex' own code](https://github.com/cortexproject/cortex/blob/a5ecafc0782b4c480c3902f228e3409a647d82cb/pkg/util/log.go#L23) is using `log_messages_total`.  So the names don't clash and we don't get the issue.

If we updated vendor to the current `promrus` it quite likely would be a problem again.

**Comment by gouthamve** [comment]
We don't have this metric anymore. Closing :)

**Comment by bboreham** [comment]
We do.
