### ISSUE TITLE
Ruler scheduler can have gaps when overloaded and rules are updated

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#680]
After running an evaluation, it [reschedules](https://github.com/weaveworks/cortex/blob/master/pkg/ruler/scheduler.go#L73) that item to 15 seconds after it was supposed to run last time. If we are running a bit slow, and it's already more 15 seconds after it was supposed to run last time, it will go into the queue at an overdue time.

When we receive a rules update, we [add it in](https://github.com/weaveworks/cortex/blob/master/pkg/ruler/scheduler.go#L200) to run 'now'. If the ruler has been overloaded for a while, 'now' will be a long time after the head of the queue, perhaps hours.

The simple mitigation is to add enough workers so it isn't overloaded.  But I think it could floor the due time of everything in the queue to be 'now' at worst, then we wouldn't get gaps in execution.

**Comment by gouthamve** [comment]
this is most likely fixed by the change to upstream Prometheus based scalable ruler. You can scale out now if your rules can't be evaluated in time.
