### ISSUE TITLE
tablemanager has lots of command-line flags that don't apply

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#696]
As @juliusv [noted](https://github.com/weaveworks/cortex/pull/693#discussion_r167129101):

The `ingester.Config` adds 24 flags, while we use only one of them in the table manager. That can be confusing. Maybe it's worth it to separate the max chunk age flag out somehow?

Also lots of flags for S3, etc., don't apply.

**Comment by tomwilkie** [comment]
Now we have a single binary, which has all the flags.  Not exactly great, but it is what it is, and needs to be this way. 

We have config files too now, which makes this whole situation easier.
