### ISSUE TITLE
Documentation - Where, how etc?

### ISSUE THREAD

**Issue by bcotton** [cortexproject/cortex#704]
In the process of running Cortex we've had to learn many things about this system. Some of this we've documented internally for our own team and would rather push this back.

Couple of questions:
1. Do you have any (even outdated) design docs you can share
2. Where would you like documentation? Wiki, docs/ directory, something else?

**Comment by jml** [comment]
Thanks! `docs/` directory please. reStructuredText or Markdown.

[Original design doc](https://docs.google.com/document/d/1C7yhMnb1x2sfeoe45f4mnnKConvroWhJ8KQZwIHJOuw/edit#heading=h.nimsq29kl184)

There are some blog posts on the [Weaveworks blog](https://www.weave.works/blog/) that might count as documentation, depending on who you ask.

Might be other docs out there.

**Comment by gouthamve** [comment]
We're documenting stuff in https://github.com/cortexproject/cortex/tree/master/docs now :)
