### ISSUE TITLE
Add example alerts

### ISSUE THREAD

**Issue by csmarchbanks** [cortexproject/cortex#748]
In order to help new users run cortex we should provide some sample dashboards/alert-manager configurations, similar to the k8s configuration examples.

FreshTracks is open to sharing our configuration once it is fleshed out a bit more.

**Comment by tomwilkie** [comment]
+1 we've got some alerts we can share too.  I'd also be keen to share out ksonnet config for running Cortex, its pretty cool.

**Comment by csmarchbanks** [comment]
@tomwilkie I would love to see that ksonnet config! I just started working on moving some of our configs over to ksonnet as well, so that would be awesome.

**Comment by cboggs** [comment]
@tomwilkie, any chance you could throw your ksonnet config(s) on a branch here? Or is it a bit too specific to your environment for that?
