### ISSUE TITLE
Tidy up 'ring' admin page

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#759]
Distributors answer an http call to `/ring` with an html page showing current status of all ingesters and all tokens.  I find I quite often want the status and have never needed the tokens, which form 99.5% of the bulk of the page.

exerpt:
```
tokens: <
  token: 4287485801
  ingester: "ingester-5cd48d4477-p22fk"
>
tokens: <
  token: 4288738658
  ingester: "ingester-5cd48d4477-j7bhg"
>
```

Each token could go on one line; we could have a button on the page to request the full detail.

**Comment by ankit1ank** [comment]
What details would this new button show? Would all the tokens still be printed on the same page as they are now?

**Comment by bboreham** [comment]
The page would show just the ingesters table by default, then if you press the button you get to see the tokens like on the current page.
