### ISSUE TITLE
RFC: Tools to block and/or drop data which is bad

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#771]
Suppose a user suddenly starts sending thousands of samples where the labels change each time: the ingester will create new series for each of them and quickly grow in memory. (cf #665)

Many installations of Cortex will have an upstream component to validate users, so we perhaps don't need to block inside Cortex, but we may want to have a button to erase all series from the flush queue for a particular user.

**Comment by bboreham** [comment]
Another variant: drop all series for a particular metric as they arrive, because it has been observed to be very high-cardinality.

**Comment by gouthamve** [comment]
I think this is fixed with the `-ingester.min-chunk-length`

**Comment by bboreham** [comment]
Some aspects are improved, but this feature is to block before the data gets into ingesters.

**Comment by gouthamve** [comment]
Closing this in favour of #1507
