### ISSUE TITLE
Ingester flushes queued chunks while sending to another ingester

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#775]
If the transfer succeeds then the same data is going to be flushed again by the new ingester.

If the transfer fails then the ingester will attempt to flush everything, so maybe it's a benefit that we kept on flushing regardless, but I think it would be better to optimise the happy path.

**Comment by gouthamve** [comment]
This is much less of an issue when using the WAL (statefulset) because there is no handover.

**Comment by alanprot** [comment]
Chunks storage was removed.
