### ISSUE TITLE
Support reverse proxy in admin http pages

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#778]
The `/ring` page (maybe others too) does a redirect which will break if you put it behind a reverse proxy that changes the path.

Prometheus has a `--web.external-url` option to address this.

**Comment by pstibrany** [comment]
What places need to be fixed, apart from /ring? Perhaps we can do it without --web.external-url ? (By using relative paths everywhere)

**Comment by bboreham** [comment]
I don't know, nor did I ever understand what the "PRG pattern" is that needed the redirect.

**Comment by pstibrany** [comment]
> I don't know, nor did I ever understand what the "PRG pattern" is that needed the redirect.

PRG is used to make REFRESH in the browser work correctly after POST request. Without this, refreshing the page would do another POST and browser would ask the user if he really wants to do the refresh, which is annoying. With redirect to GET, refreshing the page simply repeats the GET.

I don't quite see how it is relevant to cross-site request forgery (CSRF) attack though.

**Comment by gouthamve** [comment]
We looked at this in our bug scrub and decided that it was closed by #1896

**Comment by pracucci** [comment]
Closed by #1896
