### ISSUE TITLE
Use newest upstream Alertmanager packages with memberlist support

### ISSUE THREAD

**Issue by juliusv** [cortexproject/cortex#793]
Upstream Alertmanager has undergone major changes with regards to how it syncs notification state between cluster replicas. Instead of https://github.com/weaveworks/mesh, it now uses https://github.com/hashicorp/memberlist. We should update Cortex to work with the upstream changes so that we are not blocked to pick up other relevant upstream features.

**Comment by bboreham** [comment]
I believe there was a blocker in that we currently force down an updated list of peers, and memberlist doesn't let us do that.  But I can't find the details right now.

**Comment by juliusv** [comment]
@bboreham That is correct. Or at least Alertmanager's abstraction of memberlist in https://github.com/prometheus/alertmanager/blob/master/cluster/cluster.go didn't allow for that last time I checked.

**Comment by bboreham** [comment]
To update on this, I have managed to compile and run Cortex with recent upstream Alertmanager code; now I am figuring out how to test it.
