### ISSUE TITLE
Data from the future causes chunk age metric to go crazy

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#822]
because of [this line](https://github.com/weaveworks/cortex/blob/master/pkg/ingester/ingester_flush.go#L228):

```
		i.chunkAge.Observe(model.Now().Sub(chunkDesc.FirstTime).Seconds())
```

It's always wrong to compare "our" idea of `Now` with "theirs".

Not that I have a better idea right now.

**Comment by bboreham** [comment]
Indeed the problem is overflow, but I stand by my position that the two quantities there are in different dimensions.  If we recorded our idea of Now when the first sample arrived, we could subtract our Now later.

**Comment by gouthamve** [comment]
We should also look for other places where having data in the future causes issues. This is a bug nevertheless.

**Comment by alanprot** [comment]
Chunks storage was removed.
