### ISSUE TITLE
Docker image no longer updated?

### ISSUE THREAD

**Issue by icco** [cortexproject/cortex#829]
It looks like https://hub.docker.com/r/weaveworks/cortex/ hasn't been pushed to in over a year. Is there a different place to get a cortex docker image now?

**Comment by bboreham** [comment]
Re-opening because, while the answer is that we moved Cortex images to quay.io, this answer isn't obvious from DockerHub or the project README.

**Comment by tomwilkie** [comment]
Yeah do it.

**Comment by bboreham** [comment]
Gone. We should still have something in the docs like "If you want to run from prebuilt images..."

**Comment by berlincount** [comment]
The quay.io images are not tagged with `:latest`, so the `kubectl` command for `minikube` doesn't work out of the box, either :-/

**Comment by bboreham** [comment]
@berlincount that line in the README is under one telling you to run `make`, which will give you `:latest` images.

Maybe we need a line saying to copy them onto your minikube VM ?

**Comment by berlincount** [comment]
well, having `quay.io` involved doesn't make it easier :-D

**Comment by gouthamve** [comment]
I think we releases this is fixed. And we're pushing via CI to https://hub.docker.com/r/cortexproject/cortex/
