### ISSUE TITLE
Overwhelmed ingesters report unhealthy

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#851]
When we get spikes in reads / writes, the ingesters are failing to healthcheck quickly enough and get marked as unhealthy.  This isn't necessarily the end of the world as it stops writes to the ingester, reduceding load.  But it does hamper rollouts of updated ingesters (normally to increase CPU limits), as roll outs require that all ingesters are healthy.

Ideas:
- [ ] use a more sophisticated error detector on the ingester to decide if they are healthy?
- [ ] find a lower-resource way of health checking (UDP heartbeats?)
- [ ] add a 'global' per ingester rate limit on queries and writes

**Comment by bboreham** [comment]
* [ ] add a global override to force a 'ready' report so rollouts can proceed

**Comment by gouthamve** [comment]
After more investigation, the ingesters were not overloaded but the consuls were and they were failing CAS-ing. We've since fixed that and haven't seen this issue again.
