### ISSUE TITLE
github.com/gogo/protobuf/protoc-gen-gogoslick installed with go get

### ISSUE THREAD

**Issue by lelenanam** [cortexproject/cortex#893]
https://github.com/weaveworks/cortex/blob/c1193e4ae27553608dc13f398607f72b21c39a05/build-image/Dockerfile#L19
This means that it always install a version from master which is different from the version of `github.com/gogo/protobuf` library in vendor.
This might lead to uncompilable code, for example like #892

**Comment by gouthamve** [comment]
Fixed in master.
