### ISSUE TITLE
Too much logging because of maintenance messages

### ISSUE THREAD

**Issue by lelenanam** [cortexproject/cortex#900]
The "maintenance" messages for nflog are showing up at INFO level:
`cortex/alertmanager, 107 info log lines/sec`:

```
level=info ts=2018-07-25T06:41:56.829037128Z caller=nflog.go:293 user=11932 component=nflog msg="Running maintenance"
level=info ts=2018-07-25T06:41:56.829033576Z caller=silence.go:269 user=11932 component=silences msg="Running maintenance"
level=info ts=2018-07-25T06:41:56.829968541Z caller=silence.go:271 user=11932 component=silences msg="Maintenance done" duration=939.319µs size=0
level=info ts=2018-07-25T06:41:56.830009699Z caller=nflog.go:295 user=11932 component=nflog msg="Maintenance done" duration=981.364µs size=276
```

There is a PR to change log level to `DEBUG`: https://github.com/prometheus/alertmanager/pull/1347
Updating `alertmanager` in Cortex would move the log messages from `info` to `debug`.

**Comment by bricef** [comment]
Of note is that according to @bboreham these logs are from a vendored library.

**Comment by bboreham** [comment]
The PR that @lelenanam mentions was merged after the move to memberlist; we have an issue for that https://github.com/weaveworks/cortex/issues/793, which has its own difficulties.
