### ISSUE TITLE
Implement LabelValues() on the chunk store

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#915]
So we can do label queries going back in time

**Comment by tomwilkie** [comment]
Challenge will be the index needs a metric name, and the queries for label names don't include one.

**Comment by bboreham** [comment]
I've been thinking about storing metadata, e.g. all metric names, label names and cardinality counts, stored per instance per day.  Then you can also use this information to inform choice of index.

Could be a few MB per instance; might be more effort than it's worth.

**Comment by bboreham** [comment]
This change to the API would make the feature more useful: https://github.com/prometheus/prometheus/issues/6865
