### ISSUE TITLE
Query across multiple users / tenants / instances

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#923]
As an administrator, I would like to query metrics that exist in multiple tenants.  For example  `prometheus_remote_storage_shards` - I'd like to see what the typical range is, look for outliers.

Previously discussed at #849 but that refers more to metrics generated inside Cortex.

I see two practical considerations: authorisation to access data from other users/instances, and performance.

Other notes from previous conversations:
 * the tentant ID could be exposed as a label…
 * suspect the locking strategy inside ingesters might need care
 * there is no list of users anywhere - you could use all the users with chunks in the ingesters, but that could miss people who haven’t sent anything in ~15mins
   * for many admin purposes, “active users” is fine.

Also related: #577

**Comment by gouthamve** [comment]
People asked for this several times including at promcon 2019

**Comment by lukipro** [comment]
Are the any plans to add support for a way to query all tenants at once?

We could supposedly have a dedicated header to do just that:
**"X-Scope-Administrator": "true"**.

Or perhaps a reserved value of the current one like:
**"X-Scope-OrdId": "administrator"**

**Comment by Andrewpk** [comment]
This would be awesome

**Comment by till** [comment]
What about `X-Scope-OrgId: tenant1,tenant2,tenant3`?

We'd also like to be able to query across multiple.

**Comment by gotjosh** [comment]
Following.

**Comment by simonxmh** [comment]
Are there any updates on this?

**Comment by AllenzhLi** [comment]
Fllowing.

**Comment by pracucci** [comment]
> Fllowing.

@AllenzhLi Quick suggestion. Each GitHub issue page as a "subscribe" button to subscribe to notifications. That's the best way to "follow" an issue.

**Comment by AllenzhLi** [comment]
In addition tenant metric data, tenant ruler and alertmanager configs also need to be considered.
As an administrator, I want to watch every thing in che system.

**Comment by wangzhao765** [comment]
Is there any update for this issue and this pull-request?  https://github.com/cortexproject/cortex/pull/3250

**Comment by pracucci** [comment]
> Is there any update for this issue and this pull-request? #3250

PR #3250 is an in progress work but I would say we're at a good stage.
