### ISSUE TITLE
Ingester specific metrics are reported by table-manager

### ISSUE THREAD

**Issue by csmarchbanks** [cortexproject/cortex#932]
There are ingester specific metrics such as `cortex_ingester_ingested_samples_total` being reported by the table manager now. This is due to the table manager instantiating an `ingester.Config` which will register all of the ingester prometheus metrics.

Caused by: https://github.com/weaveworks/cortex/pull/930

**Comment by tomwilkie** [comment]
Sorry @csmarchbanks! Is this causing you problems? 

We can probably refactor the code to remove this, however I’m sure there are other occurances of the same thing. Happens with flags too.

**Comment by tomwilkie** [comment]
Now we're doing a single binary, all services export all the same metrics.  Perhaps not a great thing, but I suspect the number of people running the microservice arch are limited and I don't see there being anything obvious we can do about this.
