### ISSUE TITLE
Series index: don't rely so heavily on NOSQL to dedupe writes.

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#957]
The series store will write the index entries (metric:label -> series) for every chunk, and rely on the underlying store to dedupe these.  We could keep a cache of the most recently written entries and not bother writing ones we already know exist, removing some write load on the database.

For an ingester with ~1m series, an average chunk size of 6hs, and 10 labels per chunks, we're writing ~500 entries / sec.  A cache of 10m entries would potentially reduce this to ~entries / sec.

**Comment by bboreham** [comment]
Somewhat related to #607
