### ISSUE TITLE
Smarter scheduling of big and small queries

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#968]
Queries could be smarter about how many queries they take on.  The problem is limiting concurrency introduces unneeded latency for small queries, whilst higher limits increase the chance of OOMing a querier when multiple big queries hit it.

Idea: Could estimate "cost" of queries (#timeseries * duration) and have a budget for number of queries they handle simultaneously.

**Comment by alvinlin123** [comment]
100% agree. 

But, given the size of the issue backlog, I would close this issue for now as it's too general. Proposals for smarter scheduling welcome!
