### ISSUE TITLE
Two ingesters started to hand over to the same target

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#974]
Observed in the logs of two containers; one also mentioned in issue #973.
```
ingester-85b85799cc-dmh2r: level=info ts=2018-08-30T16:59:50.946449637Z caller=transfer.go:194 msg="sending chunks" to_ingester=10.244.229.56:9095 
ingester-7575679fd5-4dpsp: level=info ts=2018-08-30T16:59:53.065834618Z caller=transfer.go:194 msg="sending chunks" to_ingester=10.244.229.56:9095 
```

Since they're three seconds apart, is this a bug, or just some fancy footwork?

we should log more info so we can figure out what `10.244.229.56:9095` refers to in logs.

**Comment by tomwilkie** [comment]
Did the first of these ingesters have no tokens?  What version of the code were you running?

If the first transfer had no tokens and you're running with #955, this isn't so bad.

**Comment by bboreham** [comment]
The entire log of the first one is in #973.

Pretty sure it was the latest code.  Neither pod still existed by the time I came to look at them.
