### ISSUE TITLE
Investigate caching strategies

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#976]
We currently have a bunch of caches and eviction strategies:
1. in-process index cache, 15 min expiration, FIFO eviction
2. in-process chunk cache, "collision" based eviction
3. external chunk cache, memcache LRU? 

@jtlisi suggested offline this probably wasn't optimal; we should investigate literature for best approach to tiered caching.  I seem to recall some discussion of LFU (least frequently used) being a good option for the in-process tier. 

Also, now the in-process chunk cache keeps the index on heap, we can probably do something more sophisticated and completely get rid of the hash.  Perhaps we make the FIFO cache a LFU cache, and then use that as the index for the chunk cache, nicely unifying them all?

**Comment by tomwilkie** [comment]
Related to #611 as well.

**Comment by tomwilkie** [comment]
Interesting: https://memcached.org/blog/modern-lru/

> Even if hot items don’t always “bump” in the LRU, fetching hundreds of items in one go are likely to bump at least a few of them (or potentially all, if a user is returning from a snack break). This can cause spikes in mutex contention, uneven latency, and excess CPU usage on the server.

**Comment by bboreham** [comment]
I guess the general point to think about caching is evergreen, but do we want to keep this issue open?

**Comment by alvinlin123** [comment]
I think there is little value to keep this issue open, so I will close it for now. Proposal for new caching strategies welcome though.
