### ISSUE TITLE
How should we handle traffic from HA pairs of Prometheus?

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#990]
We should be advising people to run their Prometheus instance in HA, so they don't loose data if the machine Prometheus is running on fails.  However, in a nieve setup, this will lead to a high percentage of out-of-order samples.  The questions is: what to do about this?

Simpilest thing would be to ask for external labels (`replica: 0`, `replica: 1` etc) but this doesn't help at query time.  Can we do something better?  Also, can we come up with a way to solve this on ingestion so we don't have to store everything twice?

We should look at the heuristics thanos use.

**Comment by tomwilkie** [comment]
Enumerating the solutions I can think of, in order of the retrival/write/read pipeline:

1. We could stick to our guns around single source of truth, and provide a better failover solution at the client side.

   This would look a bit like Vulcan's sharded scraping, and would move Cortex away from using Prometheus as the client's agent.  We could have a gossip'd DHT cluster of agents, each scraping 1/Nth of the targets.  When one scraper fails, we could detect the fairly quickly via gossip & something like a phi-accrual failure detector (ala Cassandra) and fail the scraping over to the other scrapers.  Partitions would results in two sets of samples being sent and deduped on the Cortex side (see #3).

   Pros:
   - only one set of sample sent under normal conditions
   - quick failover
   - single source of truth won't make query performance worse

   Cons:
   - complexity
   - moves away from Prometheus as the client, no more client side rule or alert evalutation
   - probably need a solution to #3 consistency issues under partitions

2. As #1, but get rid of any gossip/DHT and recommend a single agent per host.

   Pros:
   - Simpler 
   - Failure modes easy to understand: if a host fails, no more metrics from the jobs on that host.

   Cons:
   - Pain to deploy?

3. Send both HA pairs, with the same external labels, and rely on ordering guarantees to remove duplicates.

   This would work reasonably well; if one of the pair fails the other would instantly "take over" and start having samples accepted.  The downside is twice as much traffic coming through and the errors Prometheus would see on writes.   We might be able to detect and suppress these if we nominate a specific label to identify each replica, don't include said label in the series labels, but track the most recently written label with some timeout - ie, we accept writes from replica "A", ignoring all others, until we haven't seen a write for ~1m, then we accept what ever shard gets to us first, replica "B" etc.  Then When we reject writes from the other shard then it won't be a error.

   Consistency might be tricky, it would be possible for replicas to race and have A write the first two copies and replica B write the third.  This would mean B would keep failing (due to retires and never reaching quorum), but would be accepted on a single shard and lead to two duplicate streams on query.  We could detect this with special error messages and "roll back" the write on the third replica, but its getting complicated..

   Pros:
   - Prometheus as the agent, simpler for users.
   - No extra copies of the data written, query performance not impacted.
  
   Cons:
   - Dealing with the consistency issue will be hard.
   - Twice as much network traffic

4. Write both shards of data and use a Thanos style heuristic to switch streams on query

   Pretty self-explanatory.

   Pros:
   - Probably the simpliest change for us.

   Cons:
   - Twice as much data written.
   - Queries get twice as expensive.

**Comment by tomwilkie** [comment]
5. Send both HA pairs, with a common external label `__cluster__` and different values `__shard__`.  

When we receive a sample, lookup `userid/<__cluster__'s value>` in consul.  If value of that == `__shard__`, accept the write.  Otherwise, reject.  If key doesn't exist, accept write and set key.  If key is older than some timeout, accept write and overwrite key.

Would need to use watches & caching to prevent excessive read load, and rate limit, jitter & stagger writes to reduce write load.

**Comment by shaoxt** [comment]
Like  proposal 3.  It will be a quick win to resolve this issue.

**Comment by shaoxt** [comment]
Can we have an implementation for proposal 3 in short term?

**Comment by tomwilkie** [comment]
Fixed in #1226
